{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(jivoDisplayDefineText:forElement:) "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoDisplay"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"defineText"},{"kind":"text","text":" "},{"text":"sdk","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forElement"},{"text":" ","kind":"text"},{"text":"element","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","text":"JVDisplayElement"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"text":" ","type":"text"},{"text":"Reference to JivoSDK","type":"text"}]}],"name":"sdk"},{"name":"forElement","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"text":"Element for which you provide your custom setting, or nil to use the default one","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Called to customize captions and texts for some elements"}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"DEPRECATED"},{"type":"text","text":" "},{"text":"Please use Jivo.display.define(text:forElement:) instead","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(definetext:forelement:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(definetext:forelement:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate"]]},"kind":"symbol","metadata":{"role":"symbol","title":"jivoDisplay(defineText:forElement:)","navigatorTitle":[{"kind":"identifier","text":"jivoDisplayDefineText:forElement:"}],"required":true,"modules":[{"name":"JivoSDK"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"defineText"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"kind":"text","text":", "},{"text":"forElement","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"c:@M@JivoSDK@objc(pl)JVDisplayDelegate(im)jivoDisplayDefineText:forElement:","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineText:forElement:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","title":"Jivo","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"type":"topic","abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","kind":"symbol","role":"collection","type":"topic","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate":{"abstract":[{"type":"text","text":"Interface to control displaying lifecycle,"},{"type":"text","text":" "},{"type":"text","text":"relates to "},{"type":"codeVoice","code":"Jivo.display"},{"type":"text","text":" namespace"}],"type":"topic","url":"\/documentation\/jivosdk\/jvdisplaydelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayDelegate"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate","role":"symbol","title":"JVDisplayDelegate","navigatorTitle":[{"kind":"identifier","text":"JVDisplayDelegate"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(defineText:forElement:)":{"role":"symbol","type":"topic","title":"jivoDisplay(defineText:forElement:)","navigatorTitle":[{"text":"jivoDisplayDefineText:forElement:","kind":"identifier"}],"required":true,"kind":"symbol","url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(definetext:forelement:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineText:forElement:)","abstract":[{"text":"DEPRECATED","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Please use Jivo.display.define(text:forElement:) instead"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoDisplay"},{"text":"(","kind":"text"},{"text":"defineText","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forElement"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","text":"JVDisplayElement","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"abstract":[{"type":"text","text":"UI elements available for customization"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDisplayElement"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","type":"topic","url":"\/documentation\/jivosdk\/jvdisplayelement","title":"JVDisplayElement","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"jivoDisplayDefineText:forElement:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"jivoDisplayDefineText:forElement:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"jivoDisplayDefineText:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":" *) ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":" "},{"text":"forElement:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","text":"JVDisplayElement","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"},{"kind":"text","text":") "},{"kind":"internalParam","text":"element"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"op":"replace","value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"value":"JVDisplayDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/fragments","value":[{"text":"JVDisplayDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(defineText:forElement:)\/title","value":"jivoDisplayDefineText:forElement:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"jivoDisplayDefineText:forElement:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(defineText:forElement:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","value":"JVDisplayElement"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments","op":"replace","value":[{"text":"JVDisplayElement","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}