{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(diddisappear:)"]},{"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(diddisappear:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(jivoDisplayDidDisappear:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"didDisappear","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sdk"},{"text":": ","kind":"text"},{"text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(didDisappear:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Instance Method","required":true,"symbolKind":"method","title":"jivoDisplay(didDisappear:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoDisplay"},{"text":"(","kind":"text"},{"text":"didDisappear","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"jivoDisplayDidDisappear:","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(pl)JVDisplayDelegate(im)jivoDisplayDidDisappear:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate"]]},"abstract":[{"type":"text","text":"Called after the SDK is closed"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(didDisappear:)":{"type":"topic","title":"jivoDisplay(didDisappear:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(didDisappear:)","required":true,"role":"symbol","navigatorTitle":[{"text":"jivoDisplayDidDisappear:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"didDisappear","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":")","kind":"text"}],"url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(diddisappear:)","abstract":[{"text":"Called after the SDK is closed","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate":{"type":"topic","title":"JVDisplayDelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDisplayDelegate"}],"role":"symbol","url":"\/documentation\/jivosdk\/jvdisplaydelegate","navigatorTitle":[{"kind":"identifier","text":"JVDisplayDelegate"}],"abstract":[{"text":"Interface to control displaying lifecycle,","type":"text"},{"type":"text","text":" "},{"text":"relates to ","type":"text"},{"type":"codeVoice","code":"Jivo.display"},{"type":"text","text":" namespace"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","title":"Jivo","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivo","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","navigatorTitle":[{"kind":"identifier","text":"Jivo"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","abstract":[],"url":"\/documentation\/jivosdk","title":"JivoSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"jivoDisplayDidDisappear:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"jivoDisplayDidDisappear:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"jivoDisplayDidDisappear:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sdk"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(didDisappear:)\/title","value":"jivoDisplayDidDisappear:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(didDisappear:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jivoDisplayDidDisappear:"}]},{"value":"JVDisplayDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/title"},{"value":[{"kind":"identifier","text":"JVDisplayDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}],"op":"replace"}]}]}