{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(jivoDisplayDefineColor:forElement:) "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"defineColor"},{"text":" ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier","text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forElement"},{"text":" ","kind":"text"},{"text":"element","kind":"internalParam"},{"kind":"text","text":": "},{"text":"JVDisplayElement","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":") -> ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"parameters":[{"name":"sdk","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Reference to JivoSDK"}]}]},{"name":"forElement","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Element for which you provide your custom setting, or nil to use the default one"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Called to customize colors for some elements"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(definecolor:forelement:)"]},{"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(definecolor:forelement:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate"]]},"abstract":[{"type":"text","text":"DEPRECATED"},{"type":"text","text":" "},{"type":"text","text":"Please use Jivo.display.define(color:forElement:) instead"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineColor:forElement:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"jivoDisplay(defineColor:forElement:)","required":true,"navigatorTitle":[{"text":"jivoDisplayDefineColor:forElement:","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(pl)JVDisplayDelegate(im)jivoDisplayDefineColor:forElement:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoDisplay"},{"kind":"text","text":"("},{"kind":"externalParam","text":"defineColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forElement","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JVDisplayElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate":{"kind":"symbol","title":"JVDisplayDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayDelegate"}],"url":"\/documentation\/jivosdk\/jvdisplaydelegate","navigatorTitle":[{"text":"JVDisplayDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate","abstract":[{"type":"text","text":"Interface to control displaying lifecycle,"},{"text":" ","type":"text"},{"type":"text","text":"relates to "},{"code":"Jivo.display","type":"codeVoice"},{"type":"text","text":" namespace"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"kind":"symbol","title":"JVDisplayElement","role":"symbol","navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","type":"topic","url":"\/documentation\/jivosdk\/jvdisplayelement","abstract":[{"type":"text","text":"UI elements available for customization"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVDisplayElement","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(defineColor:forElement:)":{"kind":"symbol","title":"jivoDisplay(defineColor:forElement:)","required":true,"abstract":[{"text":"DEPRECATED","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Please use Jivo.display.define(color:forElement:) instead"}],"url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(definecolor:forelement:)","role":"symbol","navigatorTitle":[{"text":"jivoDisplayDefineColor:forElement:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineColor:forElement:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"defineColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","text":"Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","text":"JVDisplayElement"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?","kind":"text"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"type":"topic","title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","url":"\/documentation\/jivosdk\/jivo","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"title":"Jivo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"jivoDisplayDefineColor:forElement:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jivoDisplayDefineColor:forElement:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"jivoDisplayDefineColor:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","text":"Jivo"},{"text":" *) ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"forElement:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","text":"JVDisplayElement"},{"kind":"text","text":") "},{"kind":"internalParam","text":"element"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/title","value":"JVDisplayDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/fragments","value":[{"kind":"identifier","text":"JVDisplayDelegate"}]},{"value":"JVDisplayElement","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","op":"replace"},{"value":[{"text":"JVDisplayElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(defineColor:forElement:)\/title","value":"jivoDisplayDefineColor:forElement:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(defineColor:forElement:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoDisplayDefineColor:forElement:"}]},{"value":"Jivo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}]}]}]}