{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(asksToAppear:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(jivoDisplayAsksToAppear:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"kind":"text","text":"("},{"text":"asksToAppear","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(askstoappear:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(askstoappear:)"]}],"metadata":{"title":"jivoDisplay(asksToAppear:)","required":true,"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"jivoDisplay","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"asksToAppear"},{"kind":"text","text":": "},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":")"}],"modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(pl)JVDisplayDelegate(im)jivoDisplayAsksToAppear:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"jivoDisplayAsksToAppear:"}],"roleHeading":"Instance Method"},"sections":[],"abstract":[{"text":"Called when SDK needs to display chat UI on screen","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","url":"\/documentation\/jivosdk","kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(asksToAppear:)":{"type":"topic","required":true,"abstract":[{"text":"Called when SDK needs to display chat UI on screen","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoDisplay"},{"text":"(","kind":"text"},{"text":"asksToAppear","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":")"}],"url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(askstoappear:)","role":"symbol","title":"jivoDisplay(asksToAppear:)","navigatorTitle":[{"text":"jivoDisplayAsksToAppear:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(asksToAppear:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate":{"kind":"symbol","title":"JVDisplayDelegate","abstract":[{"type":"text","text":"Interface to control displaying lifecycle,"},{"type":"text","text":" "},{"text":"relates to ","type":"text"},{"code":"Jivo.display","type":"codeVoice"},{"text":" namespace","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVDisplayDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDisplayDelegate"}],"type":"topic","url":"\/documentation\/jivosdk\/jvdisplaydelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"topic","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}],"kind":"symbol","role":"symbol","title":"Jivo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"jivoDisplayAsksToAppear:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jivoDisplayAsksToAppear:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"jivoDisplayAsksToAppear:"},{"kind":"text","text":"("},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sdk"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(asksToAppear:)\/title","value":"jivoDisplayAsksToAppear:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"jivoDisplayAsksToAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(asksToAppear:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/title","op":"replace","value":"JVDisplayDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/fragments","value":[{"kind":"identifier","text":"JVDisplayDelegate"}]},{"value":"Jivo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]}]}]}