{"metadata":{"role":"symbol","symbolKind":"method","title":"jivoDisplay(defineImage:forElement:)","externalID":"c:@M@JivoSDK@objc(pl)JVDisplayDelegate(im)jivoDisplayDefineImage:forElement:","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"jivoDisplayDefineImage:forElement:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"defineImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(defineimage:forelement:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(defineimage:forelement:)"]}],"abstract":[{"type":"text","text":"DEPRECATED"},{"text":" ","type":"text"},{"text":"Please use Jivo.display.define(image:forElement:) instead","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineImage:forElement:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(jivoDisplayDefineImage:forElement:) ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"kind":"text","text":"("},{"text":"defineImage","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sdk"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","text":"Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forElement"},{"kind":"text","text":" "},{"text":"element","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","text":"JVDisplayElement"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"text":" ","type":"text"},{"type":"text","text":"Reference to JivoSDK"}]}],"name":"sdk"},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"text":"Element for which you provide your custom setting, or nil to use the default one","type":"text"}]}],"name":"forElement"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Called to customize icons for some elements"}]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(defineImage:forElement:)":{"role":"symbol","url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(defineimage:forelement:)","navigatorTitle":[{"kind":"identifier","text":"jivoDisplayDefineImage:forElement:"}],"abstract":[{"type":"text","text":"DEPRECATED"},{"type":"text","text":" "},{"text":"Please use Jivo.display.define(image:forElement:) instead","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"jivoDisplay","kind":"identifier"},{"kind":"text","text":"("},{"text":"defineImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","text":"Jivo"},{"text":", ","kind":"text"},{"text":"forElement","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","kind":"typeIdentifier","text":"JVDisplayElement"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineImage:forElement:)","title":"jivoDisplay(defineImage:forElement:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","title":"JivoSDK","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate","abstract":[{"type":"text","text":"Interface to control displaying lifecycle,"},{"type":"text","text":" "},{"text":"relates to ","type":"text"},{"type":"codeVoice","code":"Jivo.display"},{"type":"text","text":" namespace"}],"url":"\/documentation\/jivosdk\/jvdisplaydelegate","kind":"symbol","role":"symbol","title":"JVDisplayDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVDisplayDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"JVDisplayDelegate","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"url":"\/documentation\/jivosdk\/jvdisplayelement","kind":"symbol","title":"JVDisplayElement","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDisplayElement","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDisplayElement"}],"abstract":[{"type":"text","text":"UI elements available for customization"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"kind":"symbol","url":"\/documentation\/jivosdk\/jivo","title":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"jivoDisplayDefineImage:forElement:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"jivoDisplayDefineImage:forElement:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"jivoDisplayDefineImage:"},{"text":"(","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sdk"},{"text":" ","kind":"text"},{"text":"forElement:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","text":"JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"kind":"text","text":") "},{"kind":"internalParam","text":"element"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(defineImage:forElement:)\/title","value":"jivoDisplayDefineImage:forElement:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoDisplayDefineImage:forElement:"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(defineImage:forElement:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/title","value":"JVDisplayDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/fragments","op":"replace","value":[{"text":"JVDisplayDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","value":"JVDisplayElement","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments","value":[{"text":"JVDisplayElement","kind":"identifier"}]},{"op":"replace","value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"op":"replace","value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}