{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(jivoDisplayWillAppear:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"willAppear"},{"text":" ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(willappear:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(willappear:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"text":"(","kind":"text"},{"text":"willAppear","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","text":"Jivo"},{"kind":"text","text":")"}],"externalID":"c:@M@JivoSDK@objc(pl)JVDisplayDelegate(im)jivoDisplayWillAppear:","roleHeading":"Instance Method","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"jivoDisplayWillAppear:"}],"required":true,"symbolKind":"method","title":"jivoDisplay(willAppear:)","role":"symbol"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(willAppear:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Called before opening the SDK","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"topic","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}],"kind":"symbol","role":"symbol","title":"Jivo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate":{"kind":"symbol","title":"JVDisplayDelegate","abstract":[{"type":"text","text":"Interface to control displaying lifecycle,"},{"type":"text","text":" "},{"text":"relates to ","type":"text"},{"code":"Jivo.display","type":"codeVoice"},{"text":" namespace","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVDisplayDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDisplayDelegate"}],"type":"topic","url":"\/documentation\/jivosdk\/jvdisplaydelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(willAppear:)":{"url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(willappear:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoDisplay","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"willAppear"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"jivoDisplay(willAppear:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(willAppear:)","abstract":[{"text":"Called before opening the SDK","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"jivoDisplayWillAppear:","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","url":"\/documentation\/jivosdk","kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"jivoDisplayWillAppear:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jivoDisplayWillAppear:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"jivoDisplayWillAppear:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","text":"Jivo"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sdk"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/title","op":"replace","value":"JVDisplayDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/fragments","value":[{"text":"JVDisplayDelegate","kind":"identifier"}]},{"op":"replace","value":"jivoDisplayWillAppear:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(willAppear:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(willAppear:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"jivoDisplayWillAppear:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}