{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate"]]},"metadata":{"externalID":"c:@M@JivoSDK@objc(pl)JVDisplayDelegate(im)jivoDisplayCustomizeHeader:navigationBar:navigationItem:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"jivoDisplayCustomizeHeader:navigationBar:navigationItem:","kind":"identifier"}],"title":"jivoDisplay(customizeHeader:navigationBar:navigationItem:)","role":"symbol","modules":[{"name":"JivoSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customizeHeader"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"text":", ","kind":"text"},{"text":"navigationBar","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationBar","kind":"typeIdentifier","text":"UINavigationBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"navigationItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem","text":"UINavigationItem"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(jivoDisplayCustomizeHeader:navigationBar:navigationItem:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"customizeHeader"},{"kind":"text","text":" "},{"text":"sdk","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"navigationBar"},{"kind":"text","text":": "},{"text":"UINavigationBar","preciseIdentifier":"c:objc(cs)UINavigationBar","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"navigationItem","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationItem","text":"UINavigationItem","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"text":"Reference to JivoSDK","type":"text"}]}],"name":"sdk"},{"name":"navigationBar","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Navigation Bar of Navigation Controller","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Navigation Item of JivoSDK screen","type":"text"}]}],"name":"navigationItem"}],"kind":"parameters"}],"sections":[],"abstract":[{"text":"Called to customize Header Bar appearance","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(customizeHeader:navigationBar:navigationItem:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(customizeheader:navigationbar:navigationitem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(customizeheader:navigationbar:navigationitem:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol","url":"\/documentation\/jivosdk","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(customizeHeader:navigationBar:navigationItem:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"customizeHeader"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"navigationBar"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationBar","text":"UINavigationBar","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"navigationItem"},{"text":": ","kind":"text"},{"text":"UINavigationItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"jivoDisplayCustomizeHeader:navigationBar:navigationItem:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(customizeheader:navigationbar:navigationitem:)","title":"jivoDisplay(customizeHeader:navigationBar:navigationItem:)","type":"topic","abstract":[{"type":"text","text":"Called to customize Header Bar appearance"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(customizeHeader:navigationBar:navigationItem:)","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayDelegate"}],"kind":"symbol","title":"JVDisplayDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDisplayDelegate"}],"abstract":[{"type":"text","text":"Interface to control displaying lifecycle,"},{"type":"text","text":" "},{"type":"text","text":"relates to "},{"type":"codeVoice","code":"Jivo.display"},{"type":"text","text":" namespace"}],"url":"\/documentation\/jivosdk\/jvdisplaydelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"role":"symbol","abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","title":"Jivo","url":"\/documentation\/jivosdk\/jivo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Jivo"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"jivoDisplayCustomizeHeader:navigationBar:navigationItem:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"jivoDisplayCustomizeHeader:navigationBar:navigationItem:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"jivoDisplayCustomizeHeader:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier","text":"Jivo"},{"text":" *) ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"navigationBar:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UINavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationBar"},{"kind":"text","text":" *) "},{"text":"navigationBar","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"navigationItem:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem","text":"UINavigationItem"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"navigationItem"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(customizeHeader:navigationBar:navigationItem:)\/title","value":"jivoDisplayCustomizeHeader:navigationBar:navigationItem:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(customizeHeader:navigationBar:navigationItem:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"jivoDisplayCustomizeHeader:navigationBar:navigationItem:","kind":"identifier"}]},{"op":"replace","value":"JVDisplayDelegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/fragments","value":[{"kind":"identifier","text":"JVDisplayDelegate"}],"op":"replace"},{"value":"Jivo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"}]}]}