{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(setPermissionAskingAt:handler:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPermissionAsking","kind":"identifier"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"kind":"text","text":" "},{"text":"moment","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingMoment","text":"JivoSDKNotificationsPermissionAskingMoment"},{"text":", ","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingHandler","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler","text":"JivoSDKNotificationsPermissionAskingHandler"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdknotifications\/setpermissionasking(at:handler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdknotifications\/setpermissionasking(at:handler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","title":"setPermissionAsking(at:handler:)","navigatorTitle":[{"kind":"identifier","text":"setPermissionAskingAt:handler:"}],"symbolKind":"method","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications(im)setPermissionAskingAt:handler:","platforms":[],"modules":[{"name":"JivoSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPermissionAsking"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingMoment","text":"JivoSDKNotificationsPermissionAskingMoment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKNotificationsPermissionAskingHandler","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingHandler"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPermissionAsking(at:handler:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/setPermissionAsking(at:handler:)":{"role":"symbol","title":"setPermissionAsking(at:handler:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPermissionAsking(at:handler:)","navigatorTitle":[{"kind":"identifier","text":"setPermissionAskingAt:handler:"}],"url":"\/documentation\/jivosdk\/jivosdknotifications\/setpermissionasking(at:handler:)","kind":"symbol","type":"topic","abstract":[],"deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPermissionAsking"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingMoment","text":"JivoSDKNotificationsPermissionAskingMoment"},{"kind":"text","text":", "},{"text":"handler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"JivoSDKNotificationsPermissionAskingHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingHandler"},{"text":")","kind":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"kind":"symbol","title":"JivoSDK","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingHandler":{"abstract":[],"type":"topic","deprecated":true,"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKNotificationsPermissionAskingHandler","kind":"identifier"}],"role":"symbol","title":"JivoSDKNotificationsPermissionAskingHandler","navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingHandler","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications":{"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKNotifications","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdknotifications","kind":"symbol","navigatorTitle":[{"text":"JivoSDKNotifications","kind":"identifier"}],"deprecated":true,"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications","title":"JivoSDKNotifications"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMoment"}],"role":"symbol","deprecated":true,"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMoment"}],"title":"JivoSDKNotificationsPermissionAskingMoment","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"setPermissionAskingAt:handler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setPermissionAskingAt:handler:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"setPermissionAskingAt:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingMoment","text":"JivoSDKNotificationsPermissionAskingMoment","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"moment","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"handler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingHandler","text":"JivoSDKNotificationsPermissionAskingHandler"},{"kind":"text","text":") "},{"kind":"internalParam","text":"handler"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1setPermissionAsking(at:handler:)\/title","op":"replace","value":"setPermissionAskingAt:handler:"},{"value":[{"text":"- ","kind":"text"},{"text":"setPermissionAskingAt:handler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1setPermissionAsking(at:handler:)\/fragments"},{"op":"replace","value":"JivoSDKNotificationsPermissionAskingHandler","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler\/fragments","value":[{"text":"JivoSDKNotificationsPermissionAskingHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/title","value":"JivoSDKNotifications"},{"op":"replace","value":[{"text":"JivoSDKNotifications","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment\/title","op":"replace","value":"JivoSDKNotificationsPermissionAskingMoment"},{"value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMoment"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment\/fragments"}]}]}