{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/delegate"},"metadata":{"role":"symbol","platforms":[],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI(py)delegate","roleHeading":"Instance Property","symbolKind":"property","title":"delegate","modules":[{"name":"JivoSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKChattingUIDelegate","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JivoSDKChattingUIDelegate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/delegate"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(delegate) ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate","kind":"typeIdentifier","text":"JivoSDKChattingUIDelegate","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JivoSDKChattingUIDelegate"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI","url":"\/documentation\/jivosdk\/jivosdkchattingui","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingUI","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingUI"}],"abstract":[],"deprecated":true,"title":"JivoSDKChattingUI"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/delegate":{"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/delegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(pl)JivoSDKChattingUIDelegate","kind":"typeIdentifier","text":"JivoSDKChattingUIDelegate"},{"kind":"text","text":"?"}],"abstract":[],"title":"delegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","type":"topic","role":"collection","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUIDelegate":{"role":"symbol","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdkchattinguidelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKChattingUIDelegate"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingUIDelegate"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate","title":"JivoSDKChattingUIDelegate","deprecated":true}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"delegate"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@JivoSDK@objc(pl)JivoSDKChattingUIDelegate","text":"id<JivoSDKChattingUIDelegate>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/title","value":"JivoSDKChattingUI","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/fragments","value":[{"text":"JivoSDKChattingUI","kind":"identifier"}]},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1delegate\/title"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1delegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate\/title","value":"JivoSDKChattingUIDelegate"},{"value":[{"text":"JivoSDKChattingUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}