{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/isdisplaying"]},{"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/isdisplaying"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(isDisplaying) ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDisplaying"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/isDisplaying","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI(py)isDisplaying","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isDisplaying","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":[],"symbolKind":"property","title":"isDisplaying","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"isDisplaying"}],"role":"symbol","modules":[{"name":"JivoSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/isDisplaying":{"kind":"symbol","deprecated":true,"abstract":[],"title":"isDisplaying","url":"\/documentation\/jivosdk\/jivosdkchattingui\/isdisplaying","navigatorTitle":[{"text":"isDisplaying","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDisplaying","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/isDisplaying","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","url":"\/documentation\/jivosdk","kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKChattingUI","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingUI"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI","deprecated":true,"role":"symbol","abstract":[],"title":"JivoSDKChattingUI","url":"\/documentation\/jivosdk\/jivosdkchattingui"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isDisplaying","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"isDisplaying"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"text":"isDisplaying","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"isDisplaying","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1isDisplaying\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1isDisplaying\/fragments","value":[{"kind":"identifier","text":"isDisplaying"}],"op":"replace"},{"value":"JivoSDKChattingUI","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"JivoSDKChattingUI"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/fragments"}]}]}