{"abstract":[{"type":"text","text":"DEPRECATED"},{"text":" ","type":"text"},{"type":"text","text":"Please use Jivo.display.define(color:forElement:) instead"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"defineColor","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sdk"},{"text":": ","kind":"text"},{"text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forElement"},{"kind":"text","text":" "},{"kind":"internalParam","text":"element"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVDisplayElement","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"sdk","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Reference to JivoSDK"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Element for which you provide your custom setting, or nil to use the default one"}]}],"name":"forElement"}],"kind":"parameters"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Called to customize colors for some elements","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineColor:forElement:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"]]},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"text":"jivoDisplayDefineColor:forElement:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"kind":"text","text":"("},{"text":"defineColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","text":"Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forElement"},{"kind":"text","text":": "},{"text":"JVDisplayElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"kind":"text","text":") -> "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","platforms":[],"title":"jivoDisplay(defineColor:forElement:)","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI(im)jivoDisplayDefineColor:forElement:"},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(definecolor:forelement:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(definecolor:forelement:)"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JivoSDKChattingUI","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI","role":"symbol","abstract":[],"url":"\/documentation\/jivosdk\/jivosdkchattingui","navigatorTitle":[{"text":"JivoSDKChattingUI","kind":"identifier"}],"kind":"symbol","title":"JivoSDKChattingUI","deprecated":true,"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/jivoDisplay(defineColor:forElement:)":{"abstract":[{"text":"DEPRECATED","type":"text"},{"type":"text","text":" "},{"text":"Please use Jivo.display.define(color:forElement:) instead","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"jivoDisplayDefineColor:forElement:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"defineColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","text":"Jivo"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forElement"},{"kind":"text","text":": "},{"text":"JVDisplayElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineColor:forElement:)","url":"\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(definecolor:forelement:)","role":"symbol","deprecated":true,"kind":"symbol","title":"jivoDisplay(defineColor:forElement:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"role":"symbol","abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","title":"Jivo","url":"\/documentation\/jivosdk\/jivo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Jivo"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol","url":"\/documentation\/jivosdk","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"abstract":[{"text":"UI elements available for customization","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDisplayElement","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","role":"symbol","navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}],"title":"JVDisplayElement","type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jvdisplayelement"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"jivoDisplayDefineColor:forElement:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"jivoDisplayDefineColor:forElement:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"jivoDisplayDefineColor:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"kind":"text","text":" *) "},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":" "},{"text":"forElement:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"JVDisplayElement","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"kind":"text","text":") "},{"text":"element","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/title","value":"JivoSDKChattingUI"},{"op":"replace","value":[{"text":"JivoSDKChattingUI","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(defineColor:forElement:)\/title","op":"replace","value":"jivoDisplayDefineColor:forElement:"},{"value":[{"text":"- ","kind":"text"},{"text":"jivoDisplayDefineColor:forElement:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(defineColor:forElement:)\/fragments"},{"value":"Jivo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","op":"replace","value":"JVDisplayElement"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVDisplayElement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}