{"metadata":{"navigatorTitle":[{"text":"jivoDisplayDefineImage:forElement:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","platforms":[],"role":"symbol","modules":[{"name":"JivoSDK"}],"title":"jivoDisplay(defineImage:forElement:)","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI(im)jivoDisplayDefineImage:forElement:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"text":"(","kind":"text"},{"text":"defineImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","text":"Jivo"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forElement"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","text":"JVDisplayElement","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?","kind":"text"}]},"variants":[{"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(defineimage:forelement:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(defineimage:forelement:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"text":"(","kind":"text"},{"text":"defineImage","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"kind":"text","text":", "},{"text":"forElement","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"element","kind":"internalParam"},{"kind":"text","text":": "},{"text":"JVDisplayElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Reference to JivoSDK","type":"text"}]}],"name":"sdk"},{"name":"forElement","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Element for which you provide your custom setting, or nil to use the default one"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Called to customize icons for some elements"}]}],"kind":"content"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineImage:forElement:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"]]},"abstract":[{"type":"text","text":"DEPRECATED"},{"text":" ","type":"text"},{"text":"Please use Jivo.display.define(image:forElement:) instead","type":"text"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"abstract":[],"url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"role":"symbol","title":"Jivo","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"symbol","navigatorTitle":[{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"url":"\/documentation\/jivosdk\/jvdisplayelement","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","abstract":[{"type":"text","text":"UI elements available for customization"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayElement"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayElement"}],"title":"JVDisplayElement"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/jivoDisplay(defineImage:forElement:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineImage:forElement:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"kind":"text","text":"("},{"kind":"externalParam","text":"defineImage"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":", ","kind":"text"},{"text":"forElement","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"jivoDisplayDefineImage:forElement:"}],"abstract":[{"text":"DEPRECATED","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Please use Jivo.display.define(image:forElement:) instead"}],"title":"jivoDisplay(defineImage:forElement:)","role":"symbol","deprecated":true,"url":"\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(defineimage:forelement:)","kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI":{"abstract":[],"title":"JivoSDKChattingUI","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingUI","kind":"identifier"}],"deprecated":true,"navigatorTitle":[{"text":"JivoSDKChattingUI","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI","url":"\/documentation\/jivosdk\/jivosdkchattingui","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"jivoDisplayDefineImage:forElement:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"jivoDisplayDefineImage:forElement:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"jivoDisplayDefineImage:"},{"kind":"text","text":"("},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sdk"},{"text":" ","kind":"text"},{"text":"forElement:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JVDisplayElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"element"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"Jivo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"value":"JVDisplayElement","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","op":"replace"},{"value":[{"text":"JVDisplayElement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(defineImage:forElement:)\/title","value":"jivoDisplayDefineImage:forElement:"},{"value":[{"kind":"text","text":"- "},{"text":"jivoDisplayDefineImage:forElement:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(defineImage:forElement:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/title","op":"replace","value":"JivoSDKChattingUI"},{"value":[{"kind":"identifier","text":"JivoSDKChattingUI"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/fragments","op":"replace"}]}]}