{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(willAppear:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Called before opening the SDK"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoDisplay"},{"kind":"text","text":"("},{"text":"willAppear","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI(im)jivoDisplayWillAppear:","platforms":[],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"jivoDisplayWillAppear:"}],"modules":[{"name":"JivoSDK"}],"role":"symbol","title":"jivoDisplay(willAppear:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"willAppear","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(willappear:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(willappear:)"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI":{"title":"JivoSDKChattingUI","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingUI","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"deprecated":true,"navigatorTitle":[{"text":"JivoSDKChattingUI","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivo","role":"symbol","title":"Jivo","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/jivoDisplay(willAppear:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(willAppear:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"kind":"text","text":"("},{"text":"willAppear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Called before opening the SDK"}],"deprecated":true,"navigatorTitle":[{"text":"jivoDisplayWillAppear:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(willappear:)","role":"symbol","title":"jivoDisplay(willAppear:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"jivoDisplayWillAppear:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoDisplayWillAppear:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"jivoDisplayWillAppear:"},{"text":"(","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":" *) ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"JivoSDKChattingUI","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/title"},{"op":"replace","value":[{"kind":"identifier","text":"JivoSDKChattingUI"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/fragments"},{"op":"replace","value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"value":[{"text":"Jivo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"value":"jivoDisplayWillAppear:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(willAppear:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(willAppear:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"jivoDisplayWillAppear:","kind":"identifier"}]}]}]}