{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:config:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(placeWithin:withConfig:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"place"},{"text":"(","kind":"text"},{"text":"within","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"navigationController"},{"text":": ","kind":"text"},{"text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig","kind":"typeIdentifier","text":"JivoSDKChattingConfig"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/place(within:config:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/place(within:config:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"place(within:config:)","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI(im)placeWithin:withConfig:","symbolKind":"method","navigatorTitle":[{"text":"placeWithin:withConfig:","kind":"identifier"}],"platforms":[],"modules":[{"name":"JivoSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"place"},{"text":"(","kind":"text"},{"text":"within","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig","text":"JivoSDKChattingConfig","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"kind":"symbol","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingConfig":{"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdkchattingconfig","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig","role":"symbol","navigatorTitle":[{"text":"JivoSDKChattingConfig","kind":"identifier"}],"abstract":[],"type":"topic","title":"JivoSDKChattingConfig","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKChattingConfig"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/place(within:config:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:config:)","title":"place(within:config:)","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"place","kind":"identifier"},{"kind":"text","text":"("},{"text":"within","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"text":", ","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig","text":"JivoSDKChattingConfig","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/place(within:config:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"placeWithin:withConfig:"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI":{"title":"JivoSDKChattingUI","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingUI","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"deprecated":true,"navigatorTitle":[{"text":"JivoSDKChattingUI","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"placeWithin:withConfig:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"placeWithin:withConfig:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"placeWithin:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"navigationController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withConfig:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig","text":"JivoSDKChattingConfig","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"config"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig\/title","op":"replace","value":"JivoSDKChattingConfig"},{"op":"replace","value":[{"text":"JivoSDKChattingConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig\/fragments"},{"value":"placeWithin:withConfig:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:config:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:config:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"placeWithin:withConfig:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/title","value":"JivoSDKChattingUI","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingUI"}],"op":"replace"}]}]}