{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(placeWithin:closeButton:withConfig:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"place","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"within"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"navigationController"},{"kind":"text","text":": "},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton","text":"JivoSDKChattingCloseButton"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"text":"JivoSDKChattingConfig","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"place(within:closeButton:config:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"place","kind":"identifier"},{"kind":"text","text":"("},{"text":"within","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closeButton"},{"text":": ","kind":"text"},{"text":"JivoSDKChattingCloseButton","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"text":"JivoSDKChattingConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"placeWithin:closeButton:withConfig:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI(im)placeWithin:closeButton:withConfig:","role":"symbol","platforms":[],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:closeButton:config:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/place(within:closebutton:config:)"]},{"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/place(within:closebutton:config:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingConfig":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JivoSDKChattingConfig","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingConfig"}],"type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattingconfig","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig","title":"JivoSDKChattingConfig","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","type":"topic","role":"collection","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI","url":"\/documentation\/jivosdk\/jivosdkchattingui","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingUI","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingUI"}],"abstract":[],"deprecated":true,"title":"JivoSDKChattingUI"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKChattingCloseButton"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingCloseButton"}],"type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton","title":"JivoSDKChattingCloseButton","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/place(within:closeButton:config:)":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"place","kind":"identifier"},{"kind":"text","text":"("},{"text":"within","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"},{"text":", ","kind":"text"},{"text":"closeButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"JivoSDKChattingCloseButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"text":"JivoSDKChattingConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"placeWithin:closeButton:withConfig:"}],"type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattingui\/place(within:closebutton:config:)","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:closeButton:config:)","title":"place(within:closeButton:config:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"placeWithin:closeButton:withConfig:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"placeWithin:closeButton:withConfig:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"placeWithin:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"navigationController"},{"text":" ","kind":"text"},{"text":"closeButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton","text":"JivoSDKChattingCloseButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton"},{"kind":"text","text":") "},{"kind":"internalParam","text":"closeButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"withConfig:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig","text":"JivoSDKChattingConfig","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"config","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig\/title","value":"JivoSDKChattingConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingConfig"}]},{"op":"replace","value":"JivoSDKChattingUI","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingUI"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton\/title","op":"replace","value":"JivoSDKChattingCloseButton"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton\/fragments","op":"replace","value":[{"text":"JivoSDKChattingCloseButton","kind":"identifier"}]},{"value":"placeWithin:closeButton:withConfig:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:closeButton:config:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"placeWithin:closeButton:withConfig:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:closeButton:config:)\/fragments"}]}]}