{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:closeButton:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(placeWithin:closeButton:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"place","kind":"identifier"},{"text":"(","kind":"text"},{"text":"within","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"navigationController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"text":", ","kind":"text"},{"text":"closeButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKChattingCloseButton","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"]]},"metadata":{"title":"place(within:closeButton:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"place","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"within"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closeButton"},{"text":": ","kind":"text"},{"text":"JivoSDKChattingCloseButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton"},{"kind":"text","text":")"}],"platforms":[],"navigatorTitle":[{"kind":"identifier","text":"placeWithin:closeButton:"}],"role":"symbol","modules":[{"name":"JivoSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI(im)placeWithin:closeButton:","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/place(within:closebutton:)"]},{"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/place(within:closebutton:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI":{"type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattingui","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingUI","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"JivoSDKChattingUI","kind":"identifier"}],"kind":"symbol","deprecated":true,"role":"symbol","title":"JivoSDKChattingUI"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton","url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton","abstract":[],"title":"JivoSDKChattingCloseButton","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKChattingCloseButton"}],"navigatorTitle":[{"text":"JivoSDKChattingCloseButton","kind":"identifier"}],"deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/place(within:closeButton:)":{"title":"place(within:closeButton:)","role":"symbol","abstract":[],"deprecated":true,"url":"\/documentation\/jivosdk\/jivosdkchattingui\/place(within:closebutton:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"place","kind":"identifier"},{"text":"(","kind":"text"},{"text":"within","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closeButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton","text":"JivoSDKChattingCloseButton"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:closeButton:)","navigatorTitle":[{"text":"placeWithin:closeButton:","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","title":"JivoSDK","abstract":[],"url":"\/documentation\/jivosdk","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"placeWithin:closeButton:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"placeWithin:closeButton:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"placeWithin:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"navigationController"},{"text":" ","kind":"text"},{"kind":"identifier","text":"closeButton:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"JivoSDKChattingCloseButton","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton"},{"kind":"text","text":") "},{"text":"closeButton","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"JivoSDKChattingUI","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/title"},{"op":"replace","value":[{"text":"JivoSDKChattingUI","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/fragments"},{"op":"replace","value":"JivoSDKChattingCloseButton","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton\/fragments","value":[{"text":"JivoSDKChattingCloseButton","kind":"identifier"}]},{"op":"replace","value":"placeWithin:closeButton:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:closeButton:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"placeWithin:closeButton:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:closeButton:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}