{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/push(into:config:)"},"metadata":{"modules":[{"name":"JivoSDK"}],"title":"push(into:config:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"push","kind":"identifier"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig","text":"JivoSDKChattingConfig","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":[],"navigatorTitle":[{"kind":"identifier","text":"pushInto:withConfig:"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI(im)pushInto:withConfig:"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/push(into:config:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingui\/push(into:config:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(pushInto:withConfig:) "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"push","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"text":"navigationController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKChattingConfig","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingConfig":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKChattingConfig"}],"role":"symbol","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdkchattingconfig","deprecated":true,"title":"JivoSDKChattingConfig","abstract":[],"navigatorTitle":[{"text":"JivoSDKChattingConfig","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"type":"topic","title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKChattingUI","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattingui","title":"JivoSDKChattingUI","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingUI"}],"kind":"symbol","role":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/push(into:config:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/push(into:config:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"push"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"text":", ","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JivoSDKChattingConfig","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig"},{"kind":"text","text":")"}],"title":"push(into:config:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/jivosdk\/jivosdkchattingui\/push(into:config:)","deprecated":true,"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"pushInto:withConfig:"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pushInto:withConfig:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pushInto:withConfig:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"pushInto:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"},{"kind":"text","text":" *) "},{"text":"navigationController","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"withConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig","text":"JivoSDKChattingConfig","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"config"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig\/title","value":"JivoSDKChattingConfig","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingConfig"}]},{"value":"JivoSDKChattingUI","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/fragments","op":"replace","value":[{"kind":"identifier","text":"JivoSDKChattingUI"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1push(into:config:)\/title","value":"pushInto:withConfig:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1push(into:config:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pushInto:withConfig:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}