{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Caption for “Pick a Document” action in Attach Menu,","type":"text"},{"type":"text","text":" "},{"text":"customizable: text","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachFile","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","role":"symbol","modules":[{"name":"JivoSDK"}],"title":"JVDisplayElement.attachFile","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachFile","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayElementAttachFile"}],"externalID":"c:@M@JivoSDK@E@JVDisplayElement@JVDisplayElementAttachFile","symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplayelement\/attachfile"]},{"paths":["\/documentation\/jivosdk\/jvdisplayelement\/attachfile"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/attachFile","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"title":"JVDisplayElement","kind":"symbol","abstract":[{"text":"UI elements available for customization","type":"text"}],"url":"\/documentation\/jivosdk\/jvdisplayelement","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JVDisplayElement","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayElement"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","kind":"symbol","abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/attachFile":{"url":"\/documentation\/jivosdk\/jvdisplayelement\/attachfile","kind":"symbol","role":"symbol","title":"JVDisplayElement.attachFile","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"attachFile","kind":"identifier"}],"abstract":[{"type":"text","text":"Caption for “Pick a Document” action in Attach Menu,"},{"text":" ","type":"text"},{"type":"text","text":"customizable: text"}],"navigatorTitle":[{"text":"JVDisplayElementAttachFile","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/attachFile","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"JVDisplayElementAttachFile"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JVDisplayElementAttachFile","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"JVDisplayElementAttachFile","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","value":"JVDisplayElement"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments","op":"replace","value":[{"text":"JVDisplayElement","kind":"identifier"}]},{"value":"JVDisplayElementAttachFile","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1attachFile\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1attachFile\/fragments","value":[{"text":"JVDisplayElementAttachFile","kind":"identifier"}]}]}]}