{"metadata":{"symbolKind":"case","externalID":"c:@M@JivoSDK@E@JVDisplayElement@JVDisplayElementHeaderSubtitle","role":"symbol","title":"JVDisplayElement.headerSubtitle","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"headerSubtitle","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"text":"JVDisplayElementHeaderSubtitle","kind":"identifier"}],"roleHeading":"Case"},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/headerSubtitle","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"headerSubtitle","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"]]},"kind":"symbol","abstract":[{"text":"Second line in Header Bar,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"customizable: text, color"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvdisplayelement\/headersubtitle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvdisplayelement\/headersubtitle"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/headerSubtitle":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerSubtitle"}],"abstract":[{"type":"text","text":"Second line in Header Bar,"},{"type":"text","text":" "},{"type":"text","text":"customizable: text, color"}],"type":"topic","title":"JVDisplayElement.headerSubtitle","kind":"symbol","url":"\/documentation\/jivosdk\/jvdisplayelement\/headersubtitle","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/headerSubtitle","navigatorTitle":[{"kind":"identifier","text":"JVDisplayElementHeaderSubtitle"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayElement"}],"url":"\/documentation\/jivosdk\/jvdisplayelement","title":"JVDisplayElement","navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"UI elements available for customization"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"JVDisplayElementHeaderSubtitle","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JVDisplayElementHeaderSubtitle"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"JVDisplayElementHeaderSubtitle","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1headerSubtitle\/title","value":"JVDisplayElementHeaderSubtitle"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1headerSubtitle\/fragments","value":[{"text":"JVDisplayElementHeaderSubtitle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","value":"JVDisplayElement","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"JVDisplayElement"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments"}]}]}