{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplayelement\/messagehello"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplayelement\/messagehello"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"]]},"metadata":{"title":"JVDisplayElement.messageHello","role":"symbol","externalID":"c:@M@JivoSDK@E@JVDisplayElement@JVDisplayElementMessageHello","navigatorTitle":[{"kind":"identifier","text":"JVDisplayElementMessageHello"}],"roleHeading":"Case","modules":[{"name":"JivoSDK"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageHello"}]},"kind":"symbol","abstract":[{"text":"Textual content of Hello Message in chat,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"customizable: text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageHello"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/messageHello"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVDisplayElement","kind":"identifier"}],"title":"JVDisplayElement","navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayelement","kind":"symbol","abstract":[{"text":"UI elements available for customization","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/messageHello":{"url":"\/documentation\/jivosdk\/jvdisplayelement\/messagehello","kind":"symbol","title":"JVDisplayElement.messageHello","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDisplayElementMessageHello"}],"abstract":[{"text":"Textual content of Hello Message in chat,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"customizable: text"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"messageHello","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/messageHello"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"JVDisplayElementMessageHello"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"JVDisplayElementMessageHello"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"JVDisplayElementMessageHello"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","value":"JVDisplayElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments","value":[{"text":"JVDisplayElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1messageHello\/title","value":"JVDisplayElementMessageHello","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1messageHello\/fragments","op":"replace","value":[{"text":"JVDisplayElementMessageHello","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}