{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"]]},"abstract":[{"type":"text","text":"Textual content of Offline Message in chat,"},{"type":"text","text":" "},{"type":"text","text":"customizable: text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageOffline","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplayelement\/messageoffline"]},{"paths":["\/documentation\/jivosdk\/jvdisplayelement\/messageoffline"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/messageOffline","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@JivoSDK@E@JVDisplayElement@JVDisplayElementMessageOffline","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"JVDisplayElementMessageOffline"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"messageOffline","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"title":"JVDisplayElement.messageOffline"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","kind":"symbol","abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"title":"JVDisplayElement","kind":"symbol","abstract":[{"text":"UI elements available for customization","type":"text"}],"url":"\/documentation\/jivosdk\/jvdisplayelement","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JVDisplayElement","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayElement"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/messageOffline":{"role":"symbol","navigatorTitle":[{"text":"JVDisplayElementMessageOffline","kind":"identifier"}],"type":"topic","title":"JVDisplayElement.messageOffline","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageOffline","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayelement\/messageoffline","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/messageOffline","abstract":[{"text":"Textual content of Offline Message in chat,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"customizable: text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"JVDisplayElementMessageOffline","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JVDisplayElementMessageOffline"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"JVDisplayElementMessageOffline","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","value":"JVDisplayElement"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments","value":[{"kind":"identifier","text":"JVDisplayElement"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1messageOffline\/title","value":"JVDisplayElementMessageOffline","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1messageOffline\/fragments","value":[{"text":"JVDisplayElementMessageOffline","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}