{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormCommentPlaceholder"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rateFormCommentPlaceholder"}],"modules":[{"name":"JivoSDK"}],"roleHeading":"Case","navigatorTitle":[{"text":"JVDisplayElementRateFormCommentPlaceholder","kind":"identifier"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@JivoSDK@E@JVDisplayElement@JVDisplayElementRateFormCommentPlaceholder","title":"JVDisplayElement.rateFormCommentPlaceholder"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"Placeholder for Comment Field within Rate Form","type":"text"},{"type":"text","text":" "},{"type":"text","text":"customizable: text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"rateFormCommentPlaceholder","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplayelement\/rateformcommentplaceholder"]},{"paths":["\/documentation\/jivosdk\/jvdisplayelement\/rateformcommentplaceholder"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","type":"topic","url":"\/documentation\/jivosdk","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","kind":"symbol","abstract":[{"type":"text","text":"UI elements available for customization"}],"title":"JVDisplayElement","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVDisplayElement","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayelement","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/rateFormCommentPlaceholder":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Placeholder for Comment Field within Rate Form"},{"type":"text","text":" "},{"type":"text","text":"customizable: text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormCommentPlaceholder","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rateFormCommentPlaceholder"}],"navigatorTitle":[{"text":"JVDisplayElementRateFormCommentPlaceholder","kind":"identifier"}],"role":"symbol","title":"JVDisplayElement.rateFormCommentPlaceholder","url":"\/documentation\/jivosdk\/jvdisplayelement\/rateformcommentplaceholder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"JVDisplayElementRateFormCommentPlaceholder","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JVDisplayElementRateFormCommentPlaceholder"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"JVDisplayElementRateFormCommentPlaceholder","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","value":"JVDisplayElement","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments","op":"replace","value":[{"text":"JVDisplayElement","kind":"identifier"}]},{"op":"replace","value":"JVDisplayElementRateFormCommentPlaceholder","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormCommentPlaceholder\/title"},{"op":"replace","value":[{"text":"JVDisplayElementRateFormCommentPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormCommentPlaceholder\/fragments"}]}]}