{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormPreSubmitTitle"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplayelement\/rateformpresubmittitle"]},{"paths":["\/documentation\/jivosdk\/jvdisplayelement\/rateformpresubmittitle"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"rateFormPreSubmitTitle","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"roleHeading":"Case","title":"JVDisplayElement.rateFormPreSubmitTitle","role":"symbol","externalID":"c:@M@JivoSDK@E@JVDisplayElement@JVDisplayElementRateFormPreSubmitTitle","navigatorTitle":[{"text":"JVDisplayElementRateFormPreSubmitTitle","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rateFormPreSubmitTitle","kind":"identifier"}]},"abstract":[{"type":"text","text":"Title for Rate Form"},{"type":"text","text":" "},{"type":"text","text":"customizable: text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","url":"\/documentation\/jivosdk","kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/rateFormPreSubmitTitle":{"navigatorTitle":[{"text":"JVDisplayElementRateFormPreSubmitTitle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormPreSubmitTitle","title":"JVDisplayElement.rateFormPreSubmitTitle","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvdisplayelement\/rateformpresubmittitle","abstract":[{"text":"Title for Rate Form","type":"text"},{"type":"text","text":" "},{"type":"text","text":"customizable: text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"rateFormPreSubmitTitle","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"title":"JVDisplayElement","url":"\/documentation\/jivosdk\/jvdisplayelement","navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"UI elements available for customization"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDisplayElement"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"JVDisplayElementRateFormPreSubmitTitle","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JVDisplayElementRateFormPreSubmitTitle","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"JVDisplayElementRateFormPreSubmitTitle","kind":"identifier"}]}]}},{"value":"JVDisplayElementRateFormPreSubmitTitle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormPreSubmitTitle\/title"},{"value":[{"text":"JVDisplayElementRateFormPreSubmitTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormPreSubmitTitle\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","op":"replace","value":"JVDisplayElement"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments","value":[{"text":"JVDisplayElement","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}