{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplayelement\/rateformpostsubmittitle"]},{"paths":["\/documentation\/jivosdk\/jvdisplayelement\/rateformpostsubmittitle"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"JVDisplayElementRateFormPostSubmitTitle","kind":"identifier"}],"title":"JVDisplayElement.rateFormPostSubmitTitle","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@JivoSDK@E@JVDisplayElement@JVDisplayElementRateFormPostSubmitTitle","role":"symbol","modules":[{"name":"JivoSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rateFormPostSubmitTitle"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rateFormPostSubmitTitle"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"Caption for Finish Button within Rate Form","type":"text"},{"text":" ","type":"text"},{"text":"customizable: text","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormPostSubmitTitle","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","type":"topic","role":"collection","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/rateFormPostSubmitTitle":{"abstract":[{"text":"Caption for Finish Button within Rate Form","type":"text"},{"type":"text","text":" "},{"text":"customizable: text","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateFormPostSubmitTitle"}],"role":"symbol","title":"JVDisplayElement.rateFormPostSubmitTitle","url":"\/documentation\/jivosdk\/jvdisplayelement\/rateformpostsubmittitle","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormPostSubmitTitle","navigatorTitle":[{"kind":"identifier","text":"JVDisplayElementRateFormPostSubmitTitle"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"url":"\/documentation\/jivosdk\/jvdisplayelement","role":"symbol","title":"JVDisplayElement","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayElement"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayElement"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","kind":"symbol","type":"topic","abstract":[{"text":"UI elements available for customization","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"JVDisplayElementRateFormPostSubmitTitle","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"JVDisplayElementRateFormPostSubmitTitle","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"JVDisplayElementRateFormPostSubmitTitle"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"JVDisplayElementRateFormPostSubmitTitle","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormPostSubmitTitle\/title","op":"replace"},{"value":[{"text":"JVDisplayElementRateFormPostSubmitTitle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormPostSubmitTitle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","value":"JVDisplayElement"},{"value":[{"kind":"identifier","text":"JVDisplayElement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments"}]}]}