{"kind":"symbol","variants":[{"paths":["\/documentation\/jivosdk\/jvdisplayelement\/replyplaceholder"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplayelement\/replyplaceholder"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"replyPlaceholder"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"]]},"abstract":[{"text":"Placeholder for replying area,","type":"text"},{"text":" ","type":"text"},{"text":"customizable: text","type":"text"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"replyPlaceholder"}],"symbolKind":"case","title":"JVDisplayElement.replyPlaceholder","roleHeading":"Case","externalID":"c:@M@JivoSDK@E@JVDisplayElement@JVDisplayElementReplyPlaceholder","navigatorTitle":[{"kind":"identifier","text":"JVDisplayElementReplyPlaceholder"}],"modules":[{"name":"JivoSDK"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/replyPlaceholder"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","type":"topic","kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"abstract":[{"type":"text","text":"UI elements available for customization"}],"url":"\/documentation\/jivosdk\/jvdisplayelement","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVDisplayElement","kind":"identifier"}],"navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}],"title":"JVDisplayElement","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/replyPlaceholder":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/replyPlaceholder","title":"JVDisplayElement.replyPlaceholder","kind":"symbol","navigatorTitle":[{"text":"JVDisplayElementReplyPlaceholder","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"replyPlaceholder","kind":"identifier"}],"abstract":[{"type":"text","text":"Placeholder for replying area,"},{"text":" ","type":"text"},{"type":"text","text":"customizable: text"}],"role":"symbol","url":"\/documentation\/jivosdk\/jvdisplayelement\/replyplaceholder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"JVDisplayElementReplyPlaceholder","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"JVDisplayElementReplyPlaceholder"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"JVDisplayElementReplyPlaceholder"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"JVDisplayElement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title"},{"value":[{"text":"JVDisplayElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1replyPlaceholder\/title","op":"replace","value":"JVDisplayElementReplyPlaceholder"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1replyPlaceholder\/fragments","op":"replace","value":[{"text":"JVDisplayElementReplyPlaceholder","kind":"identifier"}]}]}]}