{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"]]},"sections":[],"abstract":[{"type":"text","text":"Text to prefill the replying area,"},{"text":" ","type":"text"},{"text":"customizable: text","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplayelement\/replyprefill"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplayelement\/replyprefill"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"replyPrefill","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"replyPrefill"}],"modules":[{"name":"JivoSDK"}],"symbolKind":"case","navigatorTitle":[{"text":"JVDisplayElementReplyPrefill","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@JivoSDK@E@JVDisplayElement@JVDisplayElementReplyPrefill","title":"JVDisplayElement.replyPrefill"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/replyPrefill","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/replyPrefill":{"role":"symbol","navigatorTitle":[{"text":"JVDisplayElementReplyPrefill","kind":"identifier"}],"title":"JVDisplayElement.replyPrefill","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/replyPrefill","url":"\/documentation\/jivosdk\/jvdisplayelement\/replyprefill","abstract":[{"type":"text","text":"Text to prefill the replying area,"},{"type":"text","text":" "},{"type":"text","text":"customizable: text"}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replyPrefill","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/jivosdk","type":"topic","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVDisplayElement","kind":"identifier"}],"navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}],"title":"JVDisplayElement","kind":"symbol","abstract":[{"text":"UI elements available for customization","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","url":"\/documentation\/jivosdk\/jvdisplayelement"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"JVDisplayElementReplyPrefill","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JVDisplayElementReplyPrefill"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"JVDisplayElementReplyPrefill"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"JVDisplayElementReplyPrefill","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1replyPrefill\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1replyPrefill\/fragments","value":[{"kind":"identifier","text":"JVDisplayElementReplyPrefill"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","value":"JVDisplayElement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments","value":[{"kind":"identifier","text":"JVDisplayElement"}]}]}]}