{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/Equatable-Implementations","interfaceLanguage":"swift"},"kind":"article","variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationscategory\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"API Collection","modules":[{"name":"JivoSDK"}],"role":"collectionGroup","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"generated":true,"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/!=(_:_:)"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory","kind":"symbol","title":"JVNotificationsCategory","url":"\/documentation\/jivosdk\/jvnotificationscategory","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsCategory"}],"abstract":[{"type":"text","text":"Event category of notification"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsCategory"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory/!=(_:_:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/!=(_:_:)","url":"\/documentation\/jivosdk\/jvnotificationscategory\/!=(_:_:)","abstract":[],"kind":"symbol","title":"!=(_:_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"JVNotificationsCategory","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/fragments","value":[{"text":"JVNotificationsCategory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/navigatorTitle","value":[{"text":"JVNotificationsCategory","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}