{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"metadata":{"externalID":"s:7JivoSDK23JVNotificationsCategoryO8rawValueACSgSi_tcfc","title":"init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"modules":[{"name":"JivoSDK"}],"roleHeading":"Initializer","symbolKind":"init"},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/init(rawValue:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationscategory\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory/init(rawValue:)":{"abstract":[],"role":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscategory\/init(rawvalue:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/init(rawValue:)","title":"init(rawValue:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory":{"abstract":[{"type":"text","text":"Event category of notification"}],"title":"JVNotificationsCategory","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory","url":"\/documentation\/jivosdk\/jvnotificationscategory","kind":"symbol","type":"topic","navigatorTitle":[{"text":"JVNotificationsCategory","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JVNotificationsCategory","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","role":"collection","url":"\/documentation\/jivosdk","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/title","value":"JVNotificationsCategory"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/fragments","op":"replace","value":[{"text":"JVNotificationsCategory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/navigatorTitle","value":[{"kind":"identifier","text":"JVNotificationsCategory"}]}]}]}