{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory"]]},"metadata":{"roleHeading":"API Collection","title":"RawRepresentable Implementations","modules":[{"name":"JivoSDK"}],"role":"collectionGroup"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/RawRepresentable-Implementations"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/hashValue"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/hash(into:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationscategory\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory":{"url":"\/documentation\/jivosdk\/jvnotificationscategory","abstract":[{"type":"text","text":"Event category of notification"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory","role":"symbol","title":"JVNotificationsCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsCategory"}],"navigatorTitle":[{"kind":"identifier","text":"JVNotificationsCategory"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory/hashValue":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/hashValue","type":"topic","abstract":[],"url":"\/documentation\/jivosdk\/jvnotificationscategory\/hashvalue","role":"symbol","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"title":"hashValue","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory/hash(into:)":{"title":"hash(into:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"url":"\/documentation\/jivosdk\/jvnotificationscategory\/hash(into:)","type":"topic","kind":"symbol","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","role":"collection","abstract":[],"url":"\/documentation\/jivosdk","title":"JivoSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/title","value":"JVNotificationsCategory"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/fragments","value":[{"text":"JVNotificationsCategory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/navigatorTitle","value":[{"text":"JVNotificationsCategory","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}