{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/dismiss","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplayclosebutton\/dismiss"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplayclosebutton\/dismiss"]}],"metadata":{"roleHeading":"Case","symbolKind":"case","modules":[{"name":"JivoSDK"}],"role":"symbol","externalID":"c:@M@JivoSDK@E@JVDisplayCloseButton@JVDisplayCloseButtonDismiss","navigatorTitle":[{"kind":"identifier","text":"JVDisplayCloseButtonDismiss"}],"title":"JVDisplayCloseButton.dismiss","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"dismiss","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"abstract":[{"text":"Cross symbol, like “X”","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDisplayCloseButton"}],"abstract":[{"text":"Close Button look","type":"text"}],"title":"JVDisplayCloseButton","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton","type":"topic","navigatorTitle":[{"text":"JVDisplayCloseButton","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayclosebutton","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","type":"topic","role":"collection","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton/dismiss":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/dismiss","kind":"symbol","navigatorTitle":[{"text":"JVDisplayCloseButtonDismiss","kind":"identifier"}],"role":"symbol","title":"JVDisplayCloseButton.dismiss","abstract":[{"text":"Cross symbol, like “X”","type":"text"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"dismiss","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayclosebutton\/dismiss"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"JVDisplayCloseButtonDismiss","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"JVDisplayCloseButtonDismiss","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"JVDisplayCloseButtonDismiss","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"JVDisplayCloseButton","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton\/fragments","value":[{"text":"JVDisplayCloseButton","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton~1dismiss\/title","value":"JVDisplayCloseButtonDismiss"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton~1dismiss\/fragments","value":[{"text":"JVDisplayCloseButtonDismiss","kind":"identifier"}],"op":"replace"}]}]}