{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/omit"},"abstract":[{"text":"No symbol","type":"text"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvdisplayclosebutton\/omit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplayclosebutton\/omit"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"omit"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton"]]},"sections":[],"metadata":{"externalID":"c:@M@JivoSDK@E@JVDisplayCloseButton@JVDisplayCloseButtonOmit","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"omit","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"JVDisplayCloseButton.omit","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"text":"JVDisplayCloseButtonOmit","kind":"identifier"}]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton":{"role":"symbol","url":"\/documentation\/jivosdk\/jvdisplayclosebutton","type":"topic","abstract":[{"text":"Close Button look","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JVDisplayCloseButton","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton","title":"JVDisplayCloseButton","navigatorTitle":[{"kind":"identifier","text":"JVDisplayCloseButton"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton/omit":{"abstract":[{"text":"No symbol","type":"text"}],"kind":"symbol","title":"JVDisplayCloseButton.omit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"omit","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/jivosdk\/jvdisplayclosebutton\/omit","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/omit","navigatorTitle":[{"text":"JVDisplayCloseButtonOmit","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"JVDisplayCloseButtonOmit","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"JVDisplayCloseButtonOmit","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"JVDisplayCloseButtonOmit","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"JVDisplayCloseButton","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton\/fragments","value":[{"text":"JVDisplayCloseButton","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton~1omit\/title","value":"JVDisplayCloseButtonOmit"},{"value":[{"kind":"identifier","text":"JVDisplayCloseButtonOmit"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton~1omit\/fragments"}]}]}