{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/asia","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asia","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/jivosdk\/jvsessionserver\/asia"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvsessionserver\/asia"]}],"metadata":{"externalID":"c:@M@JivoSDK@E@JVSessionServer@JVSessionServerAsia","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"asia","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"JVSessionServerAsia"}],"modules":[{"name":"JivoSDK"}],"title":"JVSessionServer.asia"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer/asia":{"url":"\/documentation\/jivosdk\/jvsessionserver\/asia","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"asia"}],"navigatorTitle":[{"text":"JVSessionServerAsia","kind":"identifier"}],"title":"JVSessionServer.asia","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/asia","abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvsessionserver","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer","abstract":[{"type":"text","text":"Primary Jivo servers, by geographical region"}],"title":"JVSessionServer","navigatorTitle":[{"kind":"identifier","text":"JVSessionServer"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVSessionServer"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"JVSessionServerAsia"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"JVSessionServerAsia","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"JVSessionServerAsia","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"JVSessionServerAsia","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer~1asia\/title"},{"value":[{"text":"JVSessionServerAsia","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer~1asia\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer\/title","value":"JVSessionServer","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"JVSessionServer"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer\/fragments"}]}]}