{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvsessionserver\/auto"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvsessionserver\/auto"]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/auto","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@JivoSDK@E@JVSessionServer@JVSessionServerAuto","navigatorTitle":[{"text":"JVSessionServerAuto","kind":"identifier"}],"symbolKind":"case","role":"symbol","modules":[{"name":"JivoSDK"}],"title":"JVSessionServer.auto","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"auto","kind":"identifier"}],"roleHeading":"Case"},"sections":[],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer/auto":{"kind":"symbol","title":"JVSessionServer.auto","role":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvsessionserver\/auto","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"auto","kind":"identifier"}],"navigatorTitle":[{"text":"JVSessionServerAuto","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/auto"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer":{"abstract":[{"type":"text","text":"Primary Jivo servers, by geographical region"}],"title":"JVSessionServer","url":"\/documentation\/jivosdk\/jvsessionserver","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVSessionServer","kind":"identifier"}],"navigatorTitle":[{"text":"JVSessionServer","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","abstract":[],"title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"JVSessionServerAuto","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"JVSessionServerAuto","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"JVSessionServerAuto","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer~1auto\/title","value":"JVSessionServerAuto"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer~1auto\/fragments","op":"replace","value":[{"text":"JVSessionServerAuto","kind":"identifier"}]},{"value":"JVSessionServer","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer\/fragments","value":[{"kind":"identifier","text":"JVSessionServer"}]}]}]}