{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chattingUI"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI","kind":"typeIdentifier","text":"JivoSDKChattingUI"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdk\/chattingui-c.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdk\/chattingui-c.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/chattingUI-c.property","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","platforms":[],"role":"symbol","externalID":"c:@M@JivoSDK@objc(cs)JivoSDK(py)chattingUI","modules":[{"name":"JivoSDK"}],"symbolKind":"property","title":"chattingUI","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"chattingUI"},{"kind":"text","text":": "},{"text":"JivoSDKChattingUI","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI"}],"navigatorTitle":[{"text":"chattingUI","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI":{"abstract":[],"role":"symbol","title":"JivoSDKChattingUI","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingUI","kind":"identifier"}],"deprecated":true,"type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattingui","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingUI"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/chattingUI-c.property":{"role":"symbol","type":"topic","kind":"symbol","title":"chattingUI","url":"\/documentation\/jivosdk\/jivosdk\/chattingui-c.property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chattingUI","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKChattingUI","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/chattingUI-c.property","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"chattingUI"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","abstract":[],"url":"\/documentation\/jivosdk","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"type":"topic","role":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","title":"JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdk","navigatorTitle":[{"text":"JivoSDK","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDK"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"chattingUI","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"chattingUI","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI","kind":"typeIdentifier","text":"JivoSDKChattingUI","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI"},{"kind":"text","text":" * "},{"text":"chattingUI","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/title","value":"JivoSDKChattingUI","op":"replace"},{"value":[{"text":"JivoSDKChattingUI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/fragments"},{"value":"chattingUI","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1chattingUI-c.property\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1chattingUI-c.property\/fragments","value":[{"text":"chattingUI","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title","value":"JivoSDK","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments","value":[{"text":"JivoSDK","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}