{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/debugging-swift.type.property","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdk\/debugging-swift.type.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdk\/debugging-swift.type.property"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"debugging","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKDebugging","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"platforms":[],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDK(cpy)debugging","title":"debugging","roleHeading":"Type Property","modules":[{"name":"JivoSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugging"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging","text":"JivoSDKDebugging","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"debugging","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"]]},"kind":"symbol","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","navigatorTitle":[{"text":"JivoSDK","kind":"identifier"}],"role":"symbol","deprecated":true,"url":"\/documentation\/jivosdk\/jivosdk","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDK"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","title":"JivoSDK","abstract":[],"url":"\/documentation\/jivosdk","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/debugging-swift.type.property":{"type":"topic","title":"debugging","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"debugging"}],"deprecated":true,"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/debugging-swift.type.property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"debugging","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging","text":"JivoSDKDebugging","kind":"typeIdentifier"}],"url":"\/documentation\/jivosdk\/jivosdk\/debugging-swift.type.property","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebugging":{"navigatorTitle":[{"kind":"identifier","text":"JivoSDKDebugging"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging","url":"\/documentation\/jivosdk\/jivosdkdebugging","abstract":[],"role":"symbol","title":"JivoSDKDebugging","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKDebugging"}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"debugging"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"debugging"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"JivoSDKDebugging","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging"},{"kind":"text","text":" * "},{"text":"debugging","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title","op":"replace","value":"JivoSDK"},{"op":"replace","value":[{"kind":"identifier","text":"JivoSDK"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1debugging-swift.type.property\/title","value":"debugging"},{"value":[{"kind":"identifier","text":"debugging"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1debugging-swift.type.property\/fragments"},{"value":"JivoSDKDebugging","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging\/fragments","value":[{"kind":"identifier","text":"JivoSDKDebugging"}]}]}]}