{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notifications"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications","kind":"typeIdentifier","text":"JivoSDKNotifications"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdk\/notifications-c.type.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdk\/notifications-c.type.property"]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/notifications-c.type.property","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDK(cpy)notifications","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifications","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications","text":"JivoSDKNotifications","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"notifications","kind":"identifier"}],"platforms":[],"roleHeading":"Type Property","title":"notifications"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/notifications-c.type.property":{"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdk\/notifications-c.type.property","navigatorTitle":[{"kind":"identifier","text":"notifications"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/notifications-c.type.property","title":"notifications","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifications"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications","text":"JivoSDKNotifications","kind":"typeIdentifier"}],"deprecated":true,"abstract":[],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","abstract":[],"url":"\/documentation\/jivosdk","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"type":"topic","role":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","title":"JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdk","navigatorTitle":[{"text":"JivoSDK","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDK"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications":{"title":"JivoSDKNotifications","url":"\/documentation\/jivosdk\/jivosdknotifications","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotifications"}],"kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKNotifications"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"notifications"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"notifications","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications","kind":"typeIdentifier","text":"JivoSDKNotifications"},{"text":" * ","kind":"text"},{"text":"notifications","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1notifications-c.type.property\/title","value":"notifications"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1notifications-c.type.property\/fragments","op":"replace","value":[{"kind":"identifier","text":"notifications"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title","value":"JivoSDK","op":"replace"},{"value":[{"text":"JivoSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/title","value":"JivoSDKNotifications","op":"replace"},{"value":[{"text":"JivoSDKNotifications","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/fragments"}]}]}