{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notifications"},{"text":": ","kind":"text"},{"text":"JivoSDKNotifications","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/notifications-swift.type.property","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/jivosdk\/jivosdk\/notifications-swift.type.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdk\/notifications-swift.type.property"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"]]},"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Type Property","modules":[{"name":"JivoSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"notifications","kind":"identifier"},{"kind":"text","text":": "},{"text":"JivoSDKNotifications","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications"}],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDK(cpy)notifications","title":"notifications","platforms":[],"navigatorTitle":[{"kind":"identifier","text":"notifications"}]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"type":"topic","title":"JivoSDK","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDK"}],"kind":"symbol","navigatorTitle":[{"text":"JivoSDK","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","url":"\/documentation\/jivosdk\/jivosdk","role":"symbol","deprecated":true,"abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/notifications-swift.type.property":{"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/notifications-swift.type.property","url":"\/documentation\/jivosdk\/jivosdk\/notifications-swift.type.property","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"notifications","kind":"identifier"},{"kind":"text","text":": "},{"text":"JivoSDKNotifications","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications","kind":"typeIdentifier"}],"title":"notifications","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"notifications"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications":{"title":"JivoSDKNotifications","url":"\/documentation\/jivosdk\/jivosdknotifications","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKNotifications"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications","navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotifications"}],"deprecated":true,"abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","value":"notifications","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"notifications"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"JivoSDKNotifications","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"notifications"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"JivoSDK","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments","value":[{"text":"JivoSDK","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1notifications-swift.type.property\/title","value":"notifications","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1notifications-swift.type.property\/fragments","value":[{"text":"notifications","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/title","value":"JivoSDKNotifications"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/fragments","value":[{"text":"JivoSDKNotifications","kind":"identifier"}]}]}]}