{"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession","kind":"typeIdentifier","text":"JivoSDKSession"}],"platforms":[],"modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDK(py)session","navigatorTitle":[{"kind":"identifier","text":"session"}],"role":"symbol","title":"session","roleHeading":"Instance Property","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/session-c.property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdk\/session-c.property"]},{"paths":["\/documentation\/jivosdk\/jivosdk\/session-c.property"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JivoSDKSession","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession"}]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"type":"topic","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JivoSDK","kind":"identifier"}],"navigatorTitle":[{"text":"JivoSDK","kind":"identifier"}],"kind":"symbol","deprecated":true,"url":"\/documentation\/jivosdk\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JivoSDKSession","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdksession","abstract":[],"deprecated":true,"kind":"symbol","navigatorTitle":[{"text":"JivoSDKSession","kind":"identifier"}],"title":"JivoSDKSession","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/session-c.property":{"type":"topic","kind":"symbol","role":"symbol","deprecated":true,"title":"session","url":"\/documentation\/jivosdk\/jivosdk\/session-c.property","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/session-c.property","navigatorTitle":[{"text":"session","kind":"identifier"}],"abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession","text":"JivoSDKSession","kind":"typeIdentifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"kind":"symbol","title":"JivoSDK","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"session","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"session","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"JivoSDKSession","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession"},{"kind":"text","text":" * "},{"text":"session","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title","op":"replace","value":"JivoSDK"},{"op":"replace","value":[{"text":"JivoSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments"},{"value":"JivoSDKSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/title"},{"value":[{"text":"JivoSDKSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1session-c.property\/title","value":"session"},{"value":[{"text":"session","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1session-c.property\/fragments","op":"replace"}]}]}