{"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"session"}],"modules":[{"name":"JivoSDK"}],"platforms":[],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDK(cpy)session","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"session","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession","text":"JivoSDKSession"}],"roleHeading":"Type Property","title":"session"},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/session-swift.type.property","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"]]},"variants":[{"paths":["\/documentation\/jivosdk\/jivosdk\/session-swift.type.property"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdk\/session-swift.type.property"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","text":"JivoSDKSession","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"type":"topic","title":"JivoSDK","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDK"}],"kind":"symbol","navigatorTitle":[{"text":"JivoSDK","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","url":"\/documentation\/jivosdk\/jivosdk","role":"symbol","deprecated":true,"abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession":{"navigatorTitle":[{"text":"JivoSDKSession","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdksession","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKSession","kind":"identifier"}],"title":"JivoSDKSession","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","deprecated":true,"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/session-swift.type.property":{"kind":"symbol","role":"symbol","type":"topic","deprecated":true,"navigatorTitle":[{"text":"session","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdk\/session-swift.type.property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"kind":"text","text":": "},{"text":"JivoSDKSession","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/session-swift.type.property","title":"session"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"session"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"session","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession","text":"JivoSDKSession"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"session"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title","value":"JivoSDK","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments","value":[{"kind":"identifier","text":"JivoSDK"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/title","value":"JivoSDKSession","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/fragments","value":[{"text":"JivoSDKSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1session-swift.type.property\/title","op":"replace","value":"session"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1session-swift.type.property\/fragments","value":[{"text":"session","kind":"identifier"}],"op":"replace"}]}]}