{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus"]]},"variants":[{"paths":["\/documentation\/jivosdk\/jvdebuggingarchivestatus\/failedpreparing"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdebuggingarchivestatus\/failedpreparing"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/failedPreparing"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedPreparing","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"case","title":"JVDebuggingArchiveStatus.failedPreparing","roleHeading":"Case","externalID":"c:@M@JivoSDK@E@JVDebuggingArchiveStatus@JVDebuggingArchiveStatusFailedPreparing","modules":[{"name":"JivoSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedPreparing","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDebuggingArchiveStatusFailedPreparing"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"text":"Failed archiving","type":"text"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus/failedPreparing":{"navigatorTitle":[{"text":"JVDebuggingArchiveStatusFailedPreparing","kind":"identifier"}],"title":"JVDebuggingArchiveStatus.failedPreparing","abstract":[{"type":"text","text":"Failed archiving"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/failedPreparing","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedPreparing"}],"kind":"symbol","role":"symbol","url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus\/failedpreparing"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","type":"topic","kind":"symbol","abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus":{"title":"JVDebuggingArchiveStatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVDebuggingArchiveStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Determines how logs archiving operation was completed"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus","url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus","navigatorTitle":[{"text":"JVDebuggingArchiveStatus","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"JVDebuggingArchiveStatusFailedPreparing"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"JVDebuggingArchiveStatusFailedPreparing","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"JVDebuggingArchiveStatusFailedPreparing","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"JVDebuggingArchiveStatusFailedPreparing","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus~1failedPreparing\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus~1failedPreparing\/fragments","op":"replace","value":[{"text":"JVDebuggingArchiveStatusFailedPreparing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus\/title","value":"JVDebuggingArchiveStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus\/fragments","value":[{"kind":"identifier","text":"JVDebuggingArchiveStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}