{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus"]]},"abstract":[{"type":"text","text":"Failed accessing"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/failedAccessing"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdebuggingarchivestatus\/failedaccessing"]},{"paths":["\/documentation\/jivosdk\/jvdebuggingarchivestatus\/failedaccessing"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@JivoSDK@E@JVDebuggingArchiveStatus@JVDebuggingArchiveStatusFailedAccessing","symbolKind":"case","roleHeading":"Case","title":"JVDebuggingArchiveStatus.failedAccessing","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"JVDebuggingArchiveStatusFailedAccessing"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failedAccessing","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedAccessing"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus/failedAccessing":{"title":"JVDebuggingArchiveStatus.failedAccessing","url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus\/failedaccessing","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/failedAccessing","abstract":[{"type":"text","text":"Failed accessing"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedAccessing"}],"navigatorTitle":[{"text":"JVDebuggingArchiveStatusFailedAccessing","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","type":"topic","kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus","kind":"symbol","type":"topic","title":"JVDebuggingArchiveStatus","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JVDebuggingArchiveStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Determines how logs archiving operation was completed"}],"navigatorTitle":[{"text":"JVDebuggingArchiveStatus","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"JVDebuggingArchiveStatusFailedAccessing","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"JVDebuggingArchiveStatusFailedAccessing","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"JVDebuggingArchiveStatusFailedAccessing","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"JVDebuggingArchiveStatusFailedAccessing","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus~1failedAccessing\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus~1failedAccessing\/fragments","value":[{"text":"JVDebuggingArchiveStatusFailedAccessing","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus\/title","value":"JVDebuggingArchiveStatus"},{"op":"replace","value":[{"text":"JVDebuggingArchiveStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus\/fragments"}]}]}