{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"JVDebuggingArchiveStatus.success","externalID":"c:@M@JivoSDK@E@JVDebuggingArchiveStatus@JVDebuggingArchiveStatusSuccess","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDebuggingArchiveStatusSuccess"}],"roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"modules":[{"name":"JivoSDK"}]},"abstract":[{"text":"Archive is ready","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/success","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdebuggingarchivestatus\/success"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdebuggingarchivestatus\/success"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus":{"kind":"symbol","role":"symbol","url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingArchiveStatus","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVDebuggingArchiveStatus"}],"title":"JVDebuggingArchiveStatus","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus","abstract":[{"type":"text","text":"Determines how logs archiving operation was completed"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus/success":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"}],"navigatorTitle":[{"text":"JVDebuggingArchiveStatusSuccess","kind":"identifier"}],"type":"topic","url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus\/success","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/success","kind":"symbol","title":"JVDebuggingArchiveStatus.success","abstract":[{"type":"text","text":"Archive is ready"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"JVDebuggingArchiveStatusSuccess"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JVDebuggingArchiveStatusSuccess"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"JVDebuggingArchiveStatusSuccess","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus\/title","value":"JVDebuggingArchiveStatus","op":"replace"},{"value":[{"kind":"identifier","text":"JVDebuggingArchiveStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus~1success\/title","value":"JVDebuggingArchiveStatusSuccess"},{"value":[{"kind":"identifier","text":"JVDebuggingArchiveStatusSuccess"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus~1success\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}