{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(jivoAppBannerPresentation:target:event:notification:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoApp"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bannerPresentation"},{"text":" ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"kind":"text","text":", "},{"text":"target","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","text":"JVNotificationsTarget","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget"},{"text":", ","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVNotificationsEvent","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"notification"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UNNotificationPresentationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"sdk","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Reference to JivoSDK"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A target the notification is intended for"}]}],"name":"target"},{"name":"notification","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"An original incoming notification","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Presentation Options to be applied for notification"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"required":true,"modules":[{"name":"JivoSDK"}],"platforms":[],"title":"jivoApp(bannerPresentation:target:event:notification:)","role":"symbol","externalID":"c:@M@JivoSDK@objc(pl)JVAppBannerPresentingDelegate(im)jivoAppBannerPresentation:target:event:notification:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoApp","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bannerPresentation"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":", ","kind":"text"},{"text":"target","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget","kind":"typeIdentifier","text":"JVNotificationsTarget"},{"kind":"text","text":", "},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsEvent","kind":"typeIdentifier","text":"JVNotificationsEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"jivoAppBannerPresentation:target:event:notification:"}]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate\/jivoApp(bannerPresentation:target:event:notification:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate"]]},"abstract":[{"type":"text","text":"Here you can determine UNNotificationPresentationOptions"},{"text":" ","type":"text"},{"text":"to be applied for foreground notifications","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jvappbannerpresentingdelegate\/jivoapp(bannerpresentation:target:event:notification:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvappbannerpresentingdelegate\/jivoapp(bannerpresentation:target:event:notification:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget":{"abstract":[{"text":"Target subsystem of Push Notification","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsTarget"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"JVNotificationsTarget","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","title":"JVNotificationsTarget","url":"\/documentation\/jivosdk\/jvnotificationstarget"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppBannerPresentingDelegate/jivoApp(bannerPresentation:target:event:notification:)":{"kind":"symbol","url":"\/documentation\/jivosdk\/jvappbannerpresentingdelegate\/jivoapp(bannerpresentation:target:event:notification:)","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate\/jivoApp(bannerPresentation:target:event:notification:)","role":"symbol","deprecated":true,"abstract":[{"text":"Here you can determine UNNotificationPresentationOptions","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to be applied for foreground notifications"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"jivoAppBannerPresentation:target:event:notification:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoApp","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bannerPresentation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"target"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JVNotificationsTarget","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget"},{"text":", ","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVNotificationsEvent","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsEvent"},{"kind":"text","text":", "},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotification","kind":"typeIdentifier","text":"UNNotification"},{"kind":"text","text":") -> "},{"text":"UNNotificationPresentationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"}],"title":"jivoApp(bannerPresentation:target:event:notification:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","type":"topic","kind":"symbol","abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVNotificationsEvent","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsEvent"}],"abstract":[{"type":"text","text":"Event category of notification"}],"url":"\/documentation\/jivosdk\/jvnotificationsevent","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","title":"JVNotificationsEvent","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"role":"symbol","type":"topic","title":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivo","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppBannerPresentingDelegate":{"title":"JVAppBannerPresentingDelegate","url":"\/documentation\/jivosdk\/jvappbannerpresentingdelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate","role":"symbol","deprecated":true,"abstract":[{"text":"Determines a way incoming notifications gets displayed","type":"text"}],"navigatorTitle":[{"text":"JVAppBannerPresentingDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"JVAppBannerPresentingDelegate","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"jivoAppBannerPresentation:target:event:notification:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"jivoAppBannerPresentation:target:event:notification:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions"},{"text":") ","kind":"text"},{"kind":"identifier","text":"jivoAppBannerPresentation:"},{"kind":"text","text":"("},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sdk"},{"kind":"text","text":" "},{"kind":"identifier","text":"target:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","text":"JVNotificationsTarget","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"target"},{"text":" ","kind":"text"},{"text":"event:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","text":"JVNotificationsEvent","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsEvent"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"event"},{"text":" ","kind":"text"},{"text":"notification:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"notification"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"JVNotificationsTarget","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVNotificationsTarget"}]},{"op":"replace","value":"jivoAppBannerPresentation:target:event:notification:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate~1jivoApp(bannerPresentation:target:event:notification:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate~1jivoApp(bannerPresentation:target:event:notification:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"jivoAppBannerPresentation:target:event:notification:","kind":"identifier"}]},{"op":"replace","value":"JVNotificationsEvent","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/fragments","value":[{"kind":"identifier","text":"JVNotificationsEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"value":[{"text":"Jivo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/title","value":"JVAppBannerPresentingDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/fragments","value":[{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}