{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate"]]},"abstract":[{"text":"Here you can determine UNNotificationPresentationOptions","type":"text"},{"text":" ","type":"text"},{"text":"to be applied for foreground notifications","type":"text"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"required":true,"platforms":[{"deprecated":true,"unavailable":false,"beta":false}],"navigatorTitle":[{"text":"jivoAppBannerPresentation:target:category:notification:","kind":"identifier"}],"externalID":"c:@M@JivoSDK@objc(pl)JVAppBannerPresentingDelegate(im)jivoAppBannerPresentation:target:category:notification:","title":"jivoApp(bannerPresentation:target:category:notification:)","modules":[{"name":"JivoSDK"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoApp","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerPresentation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"target","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JVNotificationsTarget","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"category","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JVNotificationsCategory","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsCategory","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions","kind":"typeIdentifier"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate\/jivoApp(bannerPresentation:target:category:notification:)"},"variants":[{"paths":["\/documentation\/jivosdk\/jvappbannerpresentingdelegate\/jivoapp(bannerpresentation:target:category:notification:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvappbannerpresentingdelegate\/jivoapp(bannerpresentation:target:category:notification:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(jivoAppBannerPresentation:target:category:notification:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoApp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerPresentation"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sdk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","text":"Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","text":"JVNotificationsTarget","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget"},{"kind":"text","text":", "},{"kind":"externalParam","text":"category"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory","text":"JVNotificationsCategory","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsCategory"},{"kind":"text","text":", "},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"}],"platforms":["iOS"]}]},{"parameters":[{"name":"sdk","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Reference to JivoSDK","type":"text"}]}]},{"name":"target","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"A target the notification is intended for"}]}]},{"name":"category","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"A category of incoming notification"}],"type":"paragraph"}]},{"name":"notification","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"An original incoming notification"}]}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Presentation Options to be applied for notification"}]}],"kind":"content"}],"kind":"symbol","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","type":"topic","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget":{"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsTarget","kind":"identifier"}],"title":"JVNotificationsTarget","abstract":[{"text":"Target subsystem of Push Notification","type":"text"}],"url":"\/documentation\/jivosdk\/jvnotificationstarget","kind":"symbol","navigatorTitle":[{"text":"JVNotificationsTarget","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppBannerPresentingDelegate":{"deprecated":true,"url":"\/documentation\/jivosdk\/jvappbannerpresentingdelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Determines a way incoming notifications gets displayed"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVAppBannerPresentingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}],"title":"JVAppBannerPresentingDelegate","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppBannerPresentingDelegate/jivoApp(bannerPresentation:target:category:notification:)":{"abstract":[{"text":"Here you can determine UNNotificationPresentationOptions","type":"text"},{"text":" ","type":"text"},{"text":"to be applied for foreground notifications","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"jivoAppBannerPresentation:target:category:notification:"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate\/jivoApp(bannerPresentation:target:category:notification:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoApp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerPresentation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","text":"Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget","kind":"typeIdentifier","text":"JVNotificationsTarget"},{"kind":"text","text":", "},{"kind":"externalParam","text":"category"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsCategory","kind":"typeIdentifier","text":"JVNotificationsCategory"},{"kind":"text","text":", "},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UNNotification","kind":"typeIdentifier","text":"UNNotification"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@UNNotificationPresentationOptions","kind":"typeIdentifier","text":"UNNotificationPresentationOptions"}],"type":"topic","deprecated":true,"title":"jivoApp(bannerPresentation:target:category:notification:)","url":"\/documentation\/jivosdk\/jvappbannerpresentingdelegate\/jivoapp(bannerpresentation:target:category:notification:)","kind":"symbol","required":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"kind":"symbol","url":"\/documentation\/jivosdk\/jivo","title":"Jivo","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory":{"abstract":[{"text":"Event category of notification","type":"text"}],"role":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscategory","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVNotificationsCategory","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"JVNotificationsCategory","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory","title":"JVNotificationsCategory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"unavailable":false,"beta":false,"deprecated":true}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"jivoAppBannerPresentation:target:category:notification:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"jivoAppBannerPresentation:target:category:notification:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"jivoAppBannerPresentation:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","text":"Jivo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"target:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsTarget","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget"},{"text":") ","kind":"text"},{"text":"target","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"category:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"JVNotificationsCategory","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsCategory","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory"},{"kind":"text","text":") "},{"kind":"internalParam","text":"category"},{"kind":"text","text":" "},{"kind":"identifier","text":"notification:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"notification"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Reference to JivoSDK"}],"type":"paragraph"}],"name":"sdk"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"A target the notification is intended for","type":"text"}],"type":"paragraph"}],"name":"target"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"A category of incoming notification","type":"text"}],"type":"paragraph"}],"name":"category"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"An original incoming notification"}],"type":"paragraph"}],"name":"notification"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Presentation Options to be applied for notification"}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"JVNotificationsTarget","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/title"},{"value":[{"kind":"identifier","text":"JVNotificationsTarget"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/fragments"},{"value":[{"text":"JVNotificationsTarget","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/navigatorTitle"},{"value":"JVAppBannerPresentingDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/title"},{"value":[{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/fragments"},{"value":[{"text":"JVAppBannerPresentingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/navigatorTitle"},{"value":"jivoAppBannerPresentation:target:category:notification:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate~1jivoApp(bannerPresentation:target:category:notification:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"jivoAppBannerPresentation:target:category:notification:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate~1jivoApp(bannerPresentation:target:category:notification:)\/fragments"},{"value":"Jivo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"value":[{"kind":"identifier","text":"Jivo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"value":[{"kind":"identifier","text":"Jivo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle"},{"value":"JVNotificationsCategory","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/title"},{"value":[{"kind":"identifier","text":"JVNotificationsCategory"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/fragments"},{"value":[{"kind":"identifier","text":"JVNotificationsCategory"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/navigatorTitle"}]}]}