{"metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@JivoSDK@E@JVNotificationsTarget@JVNotificationsTargetApp","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"app","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVNotificationsTargetApp"}],"modules":[{"name":"JivoSDK"}],"title":"JVNotificationsTarget.app"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationstarget\/app"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnotificationstarget\/app"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/app"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","abstract":[{"text":"Sent by your backend, or by other third-parties","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"app"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget":{"navigatorTitle":[{"text":"JVNotificationsTarget","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Target subsystem of Push Notification"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","url":"\/documentation\/jivosdk\/jvnotificationstarget","type":"topic","kind":"symbol","title":"JVNotificationsTarget","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsTarget"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget/app":{"kind":"symbol","abstract":[{"type":"text","text":"Sent by your backend, or by other third-parties"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/app","type":"topic","url":"\/documentation\/jivosdk\/jvnotificationstarget\/app","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"app"}],"title":"JVNotificationsTarget.app","navigatorTitle":[{"text":"JVNotificationsTargetApp","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"JVNotificationsTargetApp","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"JVNotificationsTargetApp"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"JVNotificationsTargetApp"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/title","value":"JVNotificationsTarget","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/fragments","value":[{"kind":"identifier","text":"JVNotificationsTarget"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/navigatorTitle","value":[{"text":"JVNotificationsTarget","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget~1app\/title","value":"JVNotificationsTargetApp"},{"op":"replace","value":[{"text":"JVNotificationsTargetApp","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget~1app\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}