{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationstarget\/init(rawvalue:)"]}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Initializer","externalID":"s:7JivoSDK21JVNotificationsTargetO8rawValueACSgSi_tcfc","title":"init(rawValue:)","modules":[{"name":"JivoSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"symbolKind":"init"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/init(rawValue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk\/jvnotificationstarget\/init(rawvalue:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/init(rawValue:)","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","role":"collection","url":"\/documentation\/jivosdk","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget":{"kind":"symbol","type":"topic","title":"JVNotificationsTarget","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsTarget"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","role":"symbol","abstract":[{"type":"text","text":"Target subsystem of Push Notification"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVNotificationsTarget","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvnotificationstarget"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/title","value":"JVNotificationsTarget"},{"value":[{"text":"JVNotificationsTarget","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/navigatorTitle","value":[{"kind":"identifier","text":"JVNotificationsTarget"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}