{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/hashValue"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/hash(into:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationstarget\/rawrepresentable-implementations"]}],"kind":"article","metadata":{"title":"RawRepresentable Implementations","roleHeading":"API Collection","modules":[{"name":"JivoSDK"}],"role":"collectionGroup"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget/hash(into:)":{"url":"\/documentation\/jivosdk\/jvnotificationstarget\/hash(into:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/hash(into:)","title":"hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]}},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsTarget"}],"type":"topic","abstract":[{"type":"text","text":"Target subsystem of Push Notification"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","title":"JVNotificationsTarget","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsTarget"}],"url":"\/documentation\/jivosdk\/jvnotificationstarget","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget/hashValue":{"kind":"symbol","title":"hashValue","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/hashValue","url":"\/documentation\/jivosdk\/jvnotificationstarget\/hashvalue","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"type":"topic","role":"symbol","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]}},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","abstract":[],"url":"\/documentation\/jivosdk","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"JVNotificationsTarget","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/title"},{"value":[{"text":"JVNotificationsTarget","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/fragments"},{"value":[{"text":"JVNotificationsTarget","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}