{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"sdk","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Sent by Jivo and intended for JivoSDK","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/sdk"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationstarget\/sdk"]},{"paths":["\/documentation\/jivosdk\/jvnotificationstarget\/sdk"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Case","externalID":"c:@M@JivoSDK@E@JVNotificationsTarget@JVNotificationsTargetSdk","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdk"}],"navigatorTitle":[{"text":"JVNotificationsTargetSdk","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"role":"symbol","title":"JVNotificationsTarget.sdk"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"type":"topic","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget/sdk":{"abstract":[{"type":"text","text":"Sent by Jivo and intended for JivoSDK"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/sdk","title":"JVNotificationsTarget.sdk","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdk"}],"url":"\/documentation\/jivosdk\/jvnotificationstarget\/sdk","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsTargetSdk"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsTarget","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"JVNotificationsTarget","kind":"identifier"}],"abstract":[{"type":"text","text":"Target subsystem of Push Notification"}],"type":"topic","kind":"symbol","title":"JVNotificationsTarget","url":"\/documentation\/jivosdk\/jvnotificationstarget"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"JVNotificationsTargetSdk","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVNotificationsTargetSdk"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"JVNotificationsTargetSdk"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"JVNotificationsTargetSdk","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget~1sdk\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget~1sdk\/fragments","value":[{"text":"JVNotificationsTargetSdk","kind":"identifier"}]},{"value":"JVNotificationsTarget","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/fragments","value":[{"text":"JVNotificationsTarget","kind":"identifier"}]},{"value":[{"text":"JVNotificationsTarget","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}