{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate\/jivoNotifications(accessRequested:proceedBlock:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate"]]},"variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationsdelegate\/jivonotifications(accessrequested:proceedblock:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnotificationsdelegate\/jivonotifications(accessrequested:proceedblock:)"]}],"metadata":{"title":"jivoNotifications(accessRequested:proceedBlock:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessRequested"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"proceedBlock"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","required":true,"symbolKind":"method","modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(pl)JVNotificationsDelegate(im)jivoNotificationsAccessRequested:proceedBlock:","navigatorTitle":[{"text":"jivoNotificationsAccessRequested:proceedBlock:","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(jivoNotificationsAccessRequested:proceedBlock:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessRequested"},{"text":" ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"proceedBlock","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" () -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"sdk","content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Reference to JivoSDK","type":"text"}],"type":"paragraph"}]},{"name":"proceedBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"text":" ","type":"text"},{"type":"text","text":"The callback you call when it’s time"},{"type":"text","text":" "},{"text":"to present the System Request for Push Notifications","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"name":"Tip","style":"tip","content":[{"type":"paragraph","inlineContent":[{"text":"You may want to present your custom UI","type":"text"},{"text":" ","type":"text"},{"text":"to inform user about accessing to Push Notifications,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"before SDK will trigger System Request"}]}],"type":"aside"}]}],"abstract":[{"text":"Called when SDK wants to access Push Notifications","type":"text"}],"sections":[],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","type":"topic","role":"collection","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsDelegate":{"navigatorTitle":[{"text":"JVNotificationsDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Interface to handle notifications events,"},{"text":" ","type":"text"},{"text":"relates to ","type":"text"},{"type":"codeVoice","code":"Jivo.notifications"},{"type":"text","text":" namespace"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsDelegate"}],"title":"JVNotificationsDelegate","type":"topic","url":"\/documentation\/jivosdk\/jvnotificationsdelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsDelegate/jivoNotifications(accessRequested:proceedBlock:)":{"title":"jivoNotifications(accessRequested:proceedBlock:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoNotifications","kind":"identifier"},{"kind":"text","text":"("},{"text":"accessRequested","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"proceedBlock","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","required":true,"url":"\/documentation\/jivosdk\/jvnotificationsdelegate\/jivonotifications(accessrequested:proceedblock:)","abstract":[{"text":"Called when SDK wants to access Push Notifications","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate\/jivoNotifications(accessRequested:proceedBlock:)","navigatorTitle":[{"kind":"identifier","text":"jivoNotificationsAccessRequested:proceedBlock:"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"url":"\/documentation\/jivosdk\/jivo","abstract":[],"title":"Jivo","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","navigatorTitle":[{"kind":"identifier","text":"Jivo"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"jivoNotificationsAccessRequested:proceedBlock:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"jivoNotificationsAccessRequested:proceedBlock:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"jivoNotificationsAccessRequested:","kind":"identifier"},{"kind":"text","text":"("},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sdk"},{"text":" ","kind":"text"},{"kind":"identifier","text":"proceedBlock:"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")()) ","kind":"text"},{"kind":"internalParam","text":"proceedBlock"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate\/title","value":"JVNotificationsDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate\/fragments","value":[{"kind":"identifier","text":"JVNotificationsDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate~1jivoNotifications(accessRequested:proceedBlock:)\/title","op":"replace","value":"jivoNotificationsAccessRequested:proceedBlock:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate~1jivoNotifications(accessRequested:proceedBlock:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jivoNotificationsAccessRequested:proceedBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"}]}]}