{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate\/jivoNotifications(prepareBanner:content:sender:text:)"},"metadata":{"roleHeading":"Instance Method","title":"jivoNotifications(prepareBanner:content:sender:text:)","modules":[{"name":"JivoSDK"}],"required":true,"externalID":"c:@M@JivoSDK@objc(pl)JVNotificationsDelegate(im)jivoNotificationsPrepareBanner:content:sender:text:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoNotifications","kind":"identifier"},{"kind":"text","text":"("},{"text":"prepareBanner","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNMutableNotificationContent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNMutableNotificationContent"},{"kind":"text","text":", "},{"text":"sender","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationContent","text":"UNNotificationContent","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"jivoNotificationsPrepareBanner:content:sender:text:"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(jivoNotificationsPrepareBanner:content:sender:text:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"prepareBanner"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sdk"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"kind":"text","text":", "},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UNMutableNotificationContent","kind":"typeIdentifier","text":"UNMutableNotificationContent"},{"text":", ","kind":"text"},{"text":"sender","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Reference to JivoSDK","type":"text"}],"type":"paragraph"}],"name":"sdk"},{"name":"content","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Original object provided by system","type":"text"}],"type":"paragraph"}]},{"name":"sender","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Display name of person who sent the message","type":"text"}],"type":"paragraph"}]},{"name":"text","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"text":"Textual preview of sent message","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"text":"Adjusted content (if you wish to modify the banner),","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or original content (if you wish to keep things as is),"},{"text":" ","type":"text"},{"text":"or nil (if you wish to avoid showing banner)","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"name":"Tip","content":[{"type":"paragraph","inlineContent":[{"text":"Here you can prepare banner for displaying","type":"text"}]}],"style":"tip","type":"aside"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Called when SDK is going to present Push Notification banner"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationsdelegate\/jivonotifications(preparebanner:content:sender:text:)"]},{"paths":["\/documentation\/jivosdk\/jvnotificationsdelegate\/jivonotifications(preparebanner:content:sender:text:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"abstract":[],"url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"role":"symbol","title":"Jivo","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"symbol","navigatorTitle":[{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsDelegate/jivoNotifications(prepareBanner:content:sender:text:)":{"abstract":[{"type":"text","text":"Called when SDK is going to present Push Notification banner"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoNotifications","kind":"identifier"},{"kind":"text","text":"("},{"text":"prepareBanner","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNMutableNotificationContent","text":"UNMutableNotificationContent"},{"kind":"text","text":", "},{"text":"sender","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"UNNotificationContent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate\/jivoNotifications(prepareBanner:content:sender:text:)","title":"jivoNotifications(prepareBanner:content:sender:text:)","navigatorTitle":[{"kind":"identifier","text":"jivoNotificationsPrepareBanner:content:sender:text:"}],"url":"\/documentation\/jivosdk\/jvnotificationsdelegate\/jivonotifications(preparebanner:content:sender:text:)","type":"topic","kind":"symbol","role":"symbol","required":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsDelegate"}],"url":"\/documentation\/jivosdk\/jvnotificationsdelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate","title":"JVNotificationsDelegate","kind":"symbol","abstract":[{"text":"Interface to handle notifications events,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"relates to "},{"type":"codeVoice","code":"Jivo.notifications"},{"type":"text","text":" namespace"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsDelegate"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"jivoNotificationsPrepareBanner:content:sender:text:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoNotificationsPrepareBanner:content:sender:text:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"jivoNotificationsPrepareBanner:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":" "},{"text":"content:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UNMutableNotificationContent","preciseIdentifier":"c:objc(cs)UNMutableNotificationContent","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"content","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sender"},{"text":" ","kind":"text"},{"text":"text:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate~1jivoNotifications(prepareBanner:content:sender:text:)\/title","value":"jivoNotificationsPrepareBanner:content:sender:text:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jivoNotificationsPrepareBanner:content:sender:text:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate~1jivoNotifications(prepareBanner:content:sender:text:)\/fragments"},{"op":"replace","value":"JVNotificationsDelegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate\/fragments","value":[{"kind":"identifier","text":"JVNotificationsDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}