{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontent\/text"]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsContent\/text","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"s:7JivoSDK22JVNotificationsContentC4textSSvp","modules":[{"name":"JivoSDK"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"text"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsContent"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsContent/text":{"url":"\/documentation\/jivosdk\/jvnotificationscontent\/text","type":"topic","title":"text","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsContent\/text","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsContent":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsContent","url":"\/documentation\/jivosdk\/jvnotificationscontent","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsContent"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsContent","kind":"identifier"}],"type":"topic","title":"JVNotificationsContent","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"type":"topic","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsContent\/title","value":"JVNotificationsContent"},{"value":[{"kind":"identifier","text":"JVNotificationsContent"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsContent\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsContent\/navigatorTitle","op":"replace","value":[{"text":"JVNotificationsContent","kind":"identifier"}]}]}]}