{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/blue","interfaceLanguage":"swift"},"metadata":{"title":"JivoSDKChattingPaletteAlias.blue","modules":[{"name":"JivoSDK"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","platforms":[],"externalID":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias@JivoSDKChattingPaletteAliasBlue","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingPaletteAliasBlue"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blue"}]},"variants":[{"paths":["\/documentation\/jivosdk\/jivosdkchattingpalettealias\/blue"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingpalettealias\/blue"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blue"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias/blue":{"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias\/blue","navigatorTitle":[{"text":"JivoSDKChattingPaletteAliasBlue","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"blue"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/blue","abstract":[],"title":"JivoSDKChattingPaletteAlias.blue","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol","url":"\/documentation\/jivosdk","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias":{"title":"JivoSDKChattingPaletteAlias","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias","type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingPaletteAlias","kind":"identifier"}],"role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"JivoSDKChattingPaletteAliasBlue"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"JivoSDKChattingPaletteAliasBlue","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"JivoSDKChattingPaletteAliasBlue","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"JivoSDKChattingPaletteAliasBlue","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias~1blue\/title"},{"value":[{"text":"JivoSDKChattingPaletteAliasBlue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias~1blue\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias\/title","value":"JivoSDKChattingPaletteAlias"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}