{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"graphite"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdkchattingpalettealias\/graphite"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdkchattingpalettealias\/graphite"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/graphite","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingPaletteAliasGraphite"}],"role":"symbol","title":"JivoSDKChattingPaletteAlias.graphite","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"graphite"}],"symbolKind":"case","externalID":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias@JivoSDKChattingPaletteAliasGraphite","modules":[{"name":"JivoSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias/graphite":{"deprecated":true,"role":"symbol","title":"JivoSDKChattingPaletteAlias.graphite","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"graphite"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/graphite","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingPaletteAliasGraphite"}],"url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias\/graphite"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias":{"deprecated":true,"role":"symbol","title":"JivoSDKChattingPaletteAlias","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"JivoSDKChattingPaletteAliasGraphite"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingPaletteAliasGraphite"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"JivoSDKChattingPaletteAliasGraphite"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias~1graphite\/title","value":"JivoSDKChattingPaletteAliasGraphite"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias~1graphite\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingPaletteAliasGraphite"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias\/title","value":"JivoSDKChattingPaletteAlias"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}