{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"green","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingpalettealias\/green"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingpalettealias\/green"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/green"},"metadata":{"title":"JivoSDKChattingPaletteAlias.green","platforms":[],"roleHeading":"Case","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"text":"JivoSDKChattingPaletteAliasGreen","kind":"identifier"}],"externalID":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias@JivoSDKChattingPaletteAliasGreen","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"green"}]},"kind":"symbol","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/jivosdk","type":"topic","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias/green":{"title":"JivoSDKChattingPaletteAlias.green","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"green","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/green","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"JivoSDKChattingPaletteAliasGreen","kind":"identifier"}],"deprecated":true,"abstract":[],"url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias\/green"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias":{"deprecated":true,"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"kind":"symbol","abstract":[],"title":"JivoSDKChattingPaletteAlias","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias","type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"JivoSDKChattingPaletteAliasGreen","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"JivoSDKChattingPaletteAliasGreen","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"JivoSDKChattingPaletteAliasGreen"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"JivoSDKChattingPaletteAliasGreen","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias~1green\/title"},{"value":[{"kind":"identifier","text":"JivoSDKChattingPaletteAliasGreen"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias~1green\/fragments"},{"value":"JivoSDKChattingPaletteAlias","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}