{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(text:forElement:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/define(text:forelement:)"]},{"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/define(text:forelement:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"define"},{"kind":"text","text":"("},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"forElement","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":")","kind":"text"}],"externalID":"c:@M@JivoSDK@objc(cs)JVDisplayController(im)defineText:forElement:","navigatorTitle":[{"kind":"identifier","text":"defineText:forElement:"}],"modules":[{"name":"JivoSDK"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","title":"define(text:forElement:)"},"abstract":[{"text":"Here you can customize captions and texts for some elements","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(defineText:forElement:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"define"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"forElement"},{"kind":"text","text":" "},{"kind":"internalParam","text":"element"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVDisplayElement","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","title":"Jivo","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"type":"topic","url":"\/documentation\/jivosdk\/jivo","navigatorTitle":[{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"navigatorTitle":[{"kind":"identifier","text":"JVDisplayController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JVDisplayController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController","title":"JVDisplayController","type":"topic","url":"\/documentation\/jivosdk\/jvdisplaycontroller","kind":"symbol","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","isActive":true},{"type":"text","text":" namespace for SDK displaying"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","type":"topic","url":"\/documentation\/jivosdk","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"role":"symbol","abstract":[{"text":"Namespace for SDK displaying","type":"text"}],"kind":"symbol","type":"topic","title":"display","url":"\/documentation\/jivosdk\/jivo\/display","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","navigatorTitle":[{"kind":"identifier","text":"display"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"display"},{"text":": ","kind":"text"},{"text":"JVDisplayController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController","kind":"typeIdentifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","kind":"symbol","abstract":[{"type":"text","text":"UI elements available for customization"}],"title":"JVDisplayElement","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVDisplayElement","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayelement","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/define(text:forElement:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(text:forElement:)","title":"define(text:forElement:)","kind":"symbol","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/define(text:forelement:)","abstract":[{"type":"text","text":"Here you can customize captions and texts for some elements"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"define"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"forElement"},{"kind":"text","text":": "},{"text":"JVDisplayElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"defineText:forElement:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"defineText:forElement:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"defineText:forElement:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"defineText:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"text"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forElement:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","text":"JVDisplayElement","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"element"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo","op":"replace"},{"op":"replace","value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"value":"JVDisplayController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments","value":[{"text":"JVDisplayController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title","value":"display","op":"replace"},{"value":[{"text":"display","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments","op":"replace"},{"value":"JVDisplayElement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments","value":[{"kind":"identifier","text":"JVDisplayElement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1define(text:forElement:)\/title","value":"defineText:forElement:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"defineText:forElement:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1define(text:forElement:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}