{"metadata":{"navigatorTitle":[{"text":"defineImage:forElement:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@JivoSDK@objc(cs)JVDisplayController(im)defineImage:forElement:","title":"define(image:forElement:)","modules":[{"name":"JivoSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"define","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"forElement","kind":"externalParam"},{"kind":"text","text":": "},{"text":"JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(image:forElement:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(defineImage:forElement:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"define"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?, "},{"text":"forElement","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"element"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","text":"JVDisplayElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/define(image:forelement:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/define(image:forelement:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Here you can customize icons for some elements","type":"text"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","type":"topic","kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"type":"topic","abstract":[{"type":"text","text":"Namespace for SDK displaying"}],"role":"symbol","title":"display","navigatorTitle":[{"text":"display","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"display","kind":"identifier"},{"kind":"text","text":": "},{"text":"JVDisplayController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jivo\/display"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"abstract":[{"type":"text","text":"UI elements available for customization"}],"url":"\/documentation\/jivosdk\/jvdisplayelement","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVDisplayElement","kind":"identifier"}],"navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}],"title":"JVDisplayElement","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"type":"topic","abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","type":"reference"},{"text":" namespace for SDK displaying","type":"text"}],"role":"symbol","title":"JVDisplayController","navigatorTitle":[{"text":"JVDisplayController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JVDisplayController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jvdisplaycontroller"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/define(image:forElement:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(image:forElement:)","navigatorTitle":[{"text":"defineImage:forElement:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Here you can customize icons for some elements","type":"text"}],"title":"define(image:forElement:)","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/define(image:forelement:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"define","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forElement"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","text":"JVDisplayElement","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","abstract":[],"role":"symbol","title":"Jivo","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jivo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"defineImage:forElement:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"defineImage:forElement:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"defineImage:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forElement:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","text":"JVDisplayElement"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"element"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"display","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title"},{"value":[{"text":"display","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","value":"JVDisplayElement","op":"replace"},{"op":"replace","value":[{"text":"JVDisplayElement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title","op":"replace","value":"JVDisplayController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments","value":[{"kind":"identifier","text":"JVDisplayController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1define(image:forElement:)\/title","value":"defineImage:forElement:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"defineImage:forElement:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1define(image:forElement:)\/fragments"},{"value":"Jivo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}],"op":"replace"}]}]}