{"abstract":[{"text":"Handler will be called before opening the SDK","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"]]},"metadata":{"modules":[{"name":"JivoSDK"}],"title":"listenToWillAppear(handler:)","navigatorTitle":[{"kind":"identifier","text":"listenToWillAppear:"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@JivoSDK@objc(cs)JVDisplayController(im)listenToWillAppear:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listenToWillAppear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(listenToWillAppear:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listenToWillAppear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" () -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/listentowillappear(handler:)"]},{"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/listentowillappear(handler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/listenToWillAppear(handler:)"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/listenToWillAppear(handler:)":{"abstract":[{"type":"text","text":"Handler will be called before opening the SDK"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/listenToWillAppear(handler:)","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/listentowillappear(handler:)","role":"symbol","navigatorTitle":[{"text":"listenToWillAppear:","kind":"identifier"}],"title":"listenToWillAppear(handler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"listenToWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"handler","kind":"externalParam"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","url":"\/documentation\/jivosdk\/jivo","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"role":"symbol","title":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"url":"\/documentation\/jivosdk\/jvdisplaycontroller","title":"JVDisplayController","navigatorTitle":[{"kind":"identifier","text":"JVDisplayController"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayController"}],"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"type":"codeVoice","code":"Jivo\/display"},{"text":" namespace for SDK displaying","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"listenToWillAppear:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"listenToWillAppear:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"listenToWillAppear:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"kind":"text","text":")()) "},{"kind":"internalParam","text":"handler"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"listenToWillAppear:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1listenToWillAppear(handler:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1listenToWillAppear(handler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"listenToWillAppear:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title","op":"replace","value":"JVDisplayController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments","value":[{"text":"JVDisplayController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JVDisplayController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}