{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(listenToDidDisappear:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listenToDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/listenToDidDisappear(handler:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/listentodiddisappear(handler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/listentodiddisappear(handler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"role":"symbol","title":"listenToDidDisappear(handler:)","navigatorTitle":[{"kind":"identifier","text":"listenToDidDisappear:"}],"modules":[{"name":"JivoSDK"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@JivoSDK@objc(cs)JVDisplayController(im)listenToDidDisappear:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listenToDidDisappear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"abstract":[{"type":"text","text":"Handler will be called after the SDK is closed"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"url":"\/documentation\/jivosdk\/jivo\/display","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"display","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JVDisplayController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController"}],"navigatorTitle":[{"text":"display","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","role":"symbol","title":"display","kind":"symbol","abstract":[{"type":"text","text":"Namespace for SDK displaying"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"url":"\/documentation\/jivosdk\/jivo","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol","title":"Jivo","kind":"symbol","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/listenToDidDisappear(handler:)":{"kind":"symbol","title":"listenToDidDisappear(handler:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"listenToDidDisappear:"}],"url":"\/documentation\/jivosdk\/jvdisplaycontroller\/listentodiddisappear(handler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listenToDidDisappear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/listenToDidDisappear(handler:)","abstract":[{"type":"text","text":"Handler will be called after the SDK is closed"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDisplayController"}],"kind":"symbol","title":"JVDisplayController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVDisplayController"}],"url":"\/documentation\/jivosdk\/jvdisplaycontroller","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController","abstract":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference"},{"text":".","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","type":"reference"},{"text":" namespace for SDK displaying","type":"text"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","abstract":[],"kind":"symbol","title":"JivoSDK","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"listenToDidDisappear:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"listenToDidDisappear:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"listenToDidDisappear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^)()) "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title","value":"display"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments","value":[{"text":"display","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1listenToDidDisappear(handler:)\/title","value":"listenToDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1listenToDidDisappear(handler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"listenToDidDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title","value":"JVDisplayController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments","value":[{"kind":"identifier","text":"JVDisplayController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/navigatorTitle","value":[{"text":"JVDisplayController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}