{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/listenToNavigation(handler:)","interfaceLanguage":"swift"},"abstract":[{"text":"Handler will be called to customize Header Bar appearance","type":"text"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/listentonavigation(handler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/listentonavigation(handler:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(listenToNavigation:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"listenToNavigation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"handler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationBar","kind":"typeIdentifier","text":"UINavigationBar"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem","text":"UINavigationItem"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"text":"listenToNavigation:","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@JivoSDK@objc(cs)JVDisplayController(im)listenToNavigation:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"listenToNavigation"},{"kind":"text","text":"("},{"text":"handler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationBar","text":"UINavigationBar","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem","text":"UINavigationItem"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"listenToNavigation(handler:)","roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","type":"topic","abstract":[],"title":"JivoSDK","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"topic","url":"\/documentation\/jivosdk\/jivo","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"title":"Jivo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/listenToNavigation(handler:)":{"navigatorTitle":[{"text":"listenToNavigation:","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Handler will be called to customize Header Bar appearance","type":"text"}],"url":"\/documentation\/jivosdk\/jvdisplaycontroller\/listentonavigation(handler:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"listenToNavigation","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": ("},{"text":"UINavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationBar"},{"text":", ","kind":"text"},{"text":"UINavigationItem","preciseIdentifier":"c:objc(cs)UINavigationItem","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/listenToNavigation(handler:)","title":"listenToNavigation(handler:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"url":"\/documentation\/jivosdk\/jvdisplaycontroller","abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"text":".","type":"text"},{"code":"Jivo\/display","type":"codeVoice"},{"type":"text","text":" namespace for SDK displaying"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDisplayController"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController","title":"JVDisplayController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDisplayController","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"listenToNavigation:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"listenToNavigation:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"listenToNavigation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"UINavigationBar","preciseIdentifier":"c:objc(cs)UINavigationBar"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"UINavigationItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"handler"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"Jivo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"value":[{"kind":"identifier","text":"Jivo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1listenToNavigation(handler:)\/title","value":"listenToNavigation:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1listenToNavigation(handler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"listenToNavigation:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title","value":"JVDisplayController"},{"value":[{"text":"JVDisplayController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/navigatorTitle","op":"replace","value":[{"text":"JVDisplayController","kind":"identifier"}]}]}]}