{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Handler will be called when SDK needs to display chat UI on screen","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/listenToAppearanceRequest(handler:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/listentoappearancerequest(handler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/listentoappearancerequest(handler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(listenToAppearanceRequest:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listenToAppearanceRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]}]}],"metadata":{"navigatorTitle":[{"text":"listenToAppearanceRequest:","kind":"identifier"}],"role":"symbol","modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(cs)JVDisplayController(im)listenToAppearanceRequest:","title":"listenToAppearanceRequest(handler:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listenToAppearanceRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"title":"JVDisplayController","abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","isActive":true},{"type":"text","text":" namespace for SDK displaying"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDisplayController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController","url":"\/documentation\/jivosdk\/jvdisplaycontroller","role":"symbol","type":"topic","navigatorTitle":[{"text":"JVDisplayController","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"abstract":[],"title":"Jivo","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","navigatorTitle":[{"text":"display","kind":"identifier"}],"role":"symbol","title":"display","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"display","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController","text":"JVDisplayController","kind":"typeIdentifier"}],"url":"\/documentation\/jivosdk\/jivo\/display","abstract":[{"type":"text","text":"Namespace for SDK displaying"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/listenToAppearanceRequest(handler:)":{"abstract":[{"type":"text","text":"Handler will be called when SDK needs to display chat UI on screen"}],"url":"\/documentation\/jivosdk\/jvdisplaycontroller\/listentoappearancerequest(handler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listenToAppearanceRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/listenToAppearanceRequest(handler:)","type":"topic","role":"symbol","kind":"symbol","title":"listenToAppearanceRequest(handler:)","navigatorTitle":[{"text":"listenToAppearanceRequest:","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","title":"JivoSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"listenToAppearanceRequest:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"listenToAppearanceRequest:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"listenToAppearanceRequest:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)()) ","kind":"text"},{"text":"handler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title","op":"replace","value":"JVDisplayController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments","op":"replace","value":[{"text":"JVDisplayController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JVDisplayController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace","value":"Jivo"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace","value":[{"kind":"identifier","text":"Jivo"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title","op":"replace","value":"display"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments","op":"replace","value":[{"kind":"identifier","text":"display"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1listenToAppearanceRequest(handler:)\/title","op":"replace","value":"listenToAppearanceRequest:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1listenToAppearanceRequest(handler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"listenToAppearanceRequest:"}]}]}]}