{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeScreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"presentation","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK27JVDisplayScreenPresentationO","text":"JVDisplayScreenPresentation","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayScreenPresentation"},{"text":") -> ","kind":"text"},{"text":"JVDisplayWrapper","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK16JVDisplayWrapperV"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Determines how module will be presented onscreen"}],"type":"paragraph"}],"name":"presentation"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"]]},"metadata":{"modules":[{"name":"JivoSDK"}],"symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"makeScreen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JVDisplayScreenPresentation","preciseIdentifier":"s:7JivoSDK27JVDisplayScreenPresentationO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"JVDisplayWrapper","preciseIdentifier":"s:7JivoSDK16JVDisplayWrapperV"}],"roleHeading":"Instance Method","title":"makeScreen(_:)","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"13.0"},{"beta":false,"name":"iPadOS","introducedAt":"13.0","deprecated":false,"unavailable":false},{"unavailable":false,"deprecated":false,"introducedAt":"13.0","beta":false,"name":"Mac Catalyst"}],"externalID":"s:7JivoSDK19JVDisplayControllerC10makeScreenyAA0C7WrapperVAA0cF12PresentationOF"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/makescreen(_:)"]}],"abstract":[{"type":"text","text":"Builds module UI for use within SwiftUI context"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/makeScreen(_:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/makeScreen(_:)":{"url":"\/documentation\/jivosdk\/jvdisplaycontroller\/makescreen(_:)","title":"makeScreen(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/makeScreen(_:)","role":"symbol","abstract":[{"text":"Builds module UI for use within SwiftUI context","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"makeScreen","kind":"identifier"},{"kind":"text","text":"("},{"text":"JVDisplayScreenPresentation","preciseIdentifier":"s:7JivoSDK27JVDisplayScreenPresentationO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"JVDisplayWrapper","preciseIdentifier":"s:7JivoSDK16JVDisplayWrapperV"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","url":"\/documentation\/jivosdk\/jivo","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"role":"symbol","title":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayScreenPresentation":{"kind":"symbol","url":"\/documentation\/jivosdk\/jvdisplayscreenpresentation","role":"symbol","title":"JVDisplayScreenPresentation","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVDisplayScreenPresentation"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayScreenPresentation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVDisplayScreenPresentation","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"url":"\/documentation\/jivosdk\/jvdisplaycontroller","title":"JVDisplayController","navigatorTitle":[{"kind":"identifier","text":"JVDisplayController"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayController"}],"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"type":"codeVoice","code":"Jivo\/display"},{"text":" namespace for SDK displaying","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"}},"variantOverrides":[{"patch":[{"op":"replace","value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title","value":"JVDisplayController"},{"value":[{"text":"JVDisplayController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/navigatorTitle","value":[{"text":"JVDisplayController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}