{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"place","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"within"},{"text":" ","kind":"text"},{"text":"navigationController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":", "},{"text":"closeButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JVDisplayCloseButton","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK20JVDisplayCloseButtonO","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton"},{"text":") -> ","kind":"text"},{"text":"JVSessionHandle","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionHandle","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"navigationController","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Your existing UINavigationController to push the JivoSDK into"}],"type":"paragraph"}]},{"name":"closeButton","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Close Button look that mostly fits your needs in this case"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/place(within:closebutton:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","symbolKind":"method","title":"place(within:closeButton:)","externalID":"s:7JivoSDK19JVDisplayControllerC5place6within11closeButtonAA15JVSessionHandleCSgSo012UINavigationD0C_AA0c5CloseH0OtF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"place"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"within"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closeButton"},{"kind":"text","text":": "},{"text":"JVDisplayCloseButton","preciseIdentifier":"s:7JivoSDK20JVDisplayCloseButtonO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"JVSessionHandle","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"JivoSDK"}],"roleHeading":"Instance Method"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/place(within:closeButton:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Cleans entire stack of the passed navigationController,"},{"type":"text","text":" "},{"type":"text","text":"and then places SDK into it (not animated)"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/place(within:closeButton:)":{"title":"place(within:closeButton:)","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/place(within:closeButton:)","role":"symbol","abstract":[{"text":"Cleans entire stack of the passed navigationController,","type":"text"},{"text":" ","type":"text"},{"text":"and then places SDK into it (not animated)","type":"text"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/place(within:closebutton:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"place"},{"kind":"text","text":"("},{"text":"within","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":", "},{"text":"closeButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVDisplayCloseButton","preciseIdentifier":"s:7JivoSDK20JVDisplayCloseButtonO"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle","text":"JVSessionHandle","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionHandle":{"role":"symbol","fragments":[{"kind":"identifier","text":"JVSessionHandle"}],"type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jvsessionhandle","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionHandle","abstract":[],"title":"JVSessionHandle"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayCloseButton"}],"type":"topic","url":"\/documentation\/jivosdk\/jvdisplayclosebutton","title":"JVDisplayCloseButton","abstract":[{"text":"Close Button look","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayCloseButton"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"url":"\/documentation\/jivosdk\/jvdisplaycontroller","title":"JVDisplayController","navigatorTitle":[{"kind":"identifier","text":"JVDisplayController"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayController"}],"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"type":"codeVoice","code":"Jivo\/display"},{"text":" namespace for SDK displaying","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","url":"\/documentation\/jivosdk\/jivo","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"role":"symbol","title":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title","op":"replace","value":"JVDisplayController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments","value":[{"text":"JVDisplayController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JVDisplayController"}]},{"value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle"}]}]}