{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/present(over:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(presentOver:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"text":"over","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionHandle","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle","kind":"typeIdentifier","text":"JVSessionHandle"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Your UIViewController on top of which the JivoSDK will be displayed"}]}],"name":"viewController"}],"kind":"parameters"}],"kind":"symbol","abstract":[{"text":"Displays SDK modally on screen, slides it up from bottom edge (animated)","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/present(over:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/present(over:)"]}],"metadata":{"modules":[{"name":"JivoSDK"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"text":"(","kind":"text"},{"text":"over","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle","kind":"typeIdentifier","text":"JVSessionHandle"},{"text":"?","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"presentOver:"}],"externalID":"c:@M@JivoSDK@objc(cs)JVDisplayController(im)presentOver:","roleHeading":"Instance Method","title":"present(over:)"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/present(over:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/present(over:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"over"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":") -> "},{"text":"JVSessionHandle","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"text":"Displays SDK modally on screen, slides it up from bottom edge (animated)","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"presentOver:"}],"type":"topic","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/present(over:)","role":"symbol","title":"present(over:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"display"}],"abstract":[{"text":"Namespace for SDK displaying","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","url":"\/documentation\/jivosdk\/jivo\/display","title":"display","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"display"},{"text":": ","kind":"text"},{"text":"JVDisplayController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionHandle":{"abstract":[],"url":"\/documentation\/jivosdk\/jvsessionhandle","title":"JVSessionHandle","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"JVSessionHandle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionHandle"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"JVDisplayController","kind":"identifier"}],"abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display"},{"type":"text","text":" namespace for SDK displaying"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController","url":"\/documentation\/jivosdk\/jvdisplaycontroller","type":"topic","title":"JVDisplayController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDisplayController","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"kind":"symbol","role":"symbol","url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"type":"topic","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"title":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"presentOver:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentOver:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionHandle","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle","text":"JVSessionHandle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"presentOver:"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1present(over:)\/title","value":"presentOver:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1present(over:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"presentOver:","kind":"identifier"}]},{"value":"display","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments","value":[{"text":"display","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title","value":"JVDisplayController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments","value":[{"kind":"identifier","text":"JVDisplayController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo","op":"replace"},{"value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}