{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Places SDK into navigation stack (animated)","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/push(into:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"pushInto:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"push","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle","text":"JVSessionHandle"},{"text":"?","kind":"text"}],"modules":[{"name":"JivoSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@JivoSDK@objc(cs)JVDisplayController(im)pushInto:","title":"push(into:)","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(pushInto:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"push","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"text":" ","kind":"text"},{"text":"navigationController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionHandle","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle","kind":"typeIdentifier","text":"JVSessionHandle"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"navigationController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Your existing UINavigationController to push the JivoSDK into"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/push(into:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/push(into:)"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionHandle":{"url":"\/documentation\/jivosdk\/jvsessionhandle","kind":"symbol","type":"topic","title":"JVSessionHandle","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionHandle","role":"symbol","abstract":[],"fragments":[{"text":"JVSessionHandle","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/push(into:)":{"navigatorTitle":[{"kind":"identifier","text":"pushInto:"}],"role":"symbol","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/push(into:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"push"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle","text":"JVSessionHandle","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Places SDK into navigation stack (animated)","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/push(into:)","kind":"symbol","title":"push(into:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"url":"\/documentation\/jivosdk\/jivo","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol","title":"Jivo","navigatorTitle":[{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"url":"\/documentation\/jivosdk\/jvdisplaycontroller","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayController"}],"abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference","isActive":true},{"type":"text","text":"."},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display"},{"text":" namespace for SDK displaying","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController","role":"symbol","title":"JVDisplayController","navigatorTitle":[{"kind":"identifier","text":"JVDisplayController"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"url":"\/documentation\/jivosdk\/jivo\/display","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"display","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController","text":"JVDisplayController"}],"abstract":[{"text":"Namespace for SDK displaying","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","role":"symbol","title":"display","navigatorTitle":[{"text":"display","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","type":"topic","role":"collection","title":"JivoSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"pushInto:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pushInto:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionHandle","text":"JVSessionHandle","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pushInto:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"navigationController"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1push(into:)\/title","value":"pushInto:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1push(into:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"pushInto:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"value":[{"kind":"identifier","text":"Jivo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title","op":"replace","value":"JVDisplayController"},{"value":[{"text":"JVDisplayController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments"},{"op":"replace","value":"display","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title"},{"value":[{"text":"display","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments","op":"replace"}]}]}