{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setExtraItems","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"menu"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayMenu","text":"JVDisplayMenu"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captions"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"handler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"JivoSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setExtraItemsForMenu:captions:handler:"}],"externalID":"c:@M@JivoSDK@objc(cs)JVDisplayController(im)setExtraItemsForMenu:captions:handler:","title":"setExtraItems(menu:captions:handler:)"},"abstract":[{"type":"text","text":"Sets your own extra items to display within menu"}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(setExtraItemsForMenu:captions:handler:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setExtraItems"},{"text":"(","kind":"text"},{"text":"menu","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayMenu","text":"JVDisplayMenu","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayMenu","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captions"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Which menu you wish to attach your extra actions to","type":"text"}],"type":"paragraph"}],"name":"menu"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Captions or titles of your extra actions"}],"type":"paragraph"}],"name":"captions"},{"name":"handler","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Callback that would be called when user taps your custom menu item in specified menu"}],"type":"paragraph"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setExtraItems(menu:captions:handler:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/setextraitems(menu:captions:handler:)"]},{"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/setextraitems(menu:captions:handler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/setExtraItems(menu:captions:handler:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setExtraItems(menu:captions:handler:)","type":"topic","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/setextraitems(menu:captions:handler:)","abstract":[{"type":"text","text":"Sets your own extra items to display within menu"}],"kind":"symbol","title":"setExtraItems(menu:captions:handler:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setExtraItems","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"menu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayMenu","text":"JVDisplayMenu"},{"text":", ","kind":"text"},{"text":"captions","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"handler","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setExtraItemsForMenu:captions:handler:","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayMenu":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDisplayMenu","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Menus available for customization"}],"role":"symbol","title":"JVDisplayMenu","url":"\/documentation\/jivosdk\/jvdisplaymenu","navigatorTitle":[{"kind":"identifier","text":"JVDisplayMenu"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayMenu","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"title":"Jivo","kind":"symbol","url":"\/documentation\/jivosdk\/jivo","role":"symbol","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Jivo"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"navigatorTitle":[{"kind":"identifier","text":"display"}],"abstract":[{"type":"text","text":"Namespace for SDK displaying"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"display","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JVDisplayController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","kind":"symbol","title":"display","url":"\/documentation\/jivosdk\/jivo\/display","role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController","url":"\/documentation\/jivosdk\/jvdisplaycontroller","abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","isActive":true},{"type":"text","text":" namespace for SDK displaying"}],"kind":"symbol","title":"JVDisplayController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVDisplayController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayController"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/jivosdk","type":"topic","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"setExtraItemsForMenu:captions:handler:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"setExtraItemsForMenu:captions:handler:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setExtraItemsForMenu:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"JVDisplayMenu","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayMenu","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayMenu"},{"text":") ","kind":"text"},{"text":"menu","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captions:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"captions"},{"kind":"text","text":" "},{"kind":"identifier","text":"handler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1setExtraItems(menu:captions:handler:)\/title","op":"replace","value":"setExtraItemsForMenu:captions:handler:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setExtraItemsForMenu:captions:handler:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1setExtraItems(menu:captions:handler:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayMenu\/title","value":"JVDisplayMenu"},{"value":[{"text":"JVDisplayMenu","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayMenu\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}]},{"value":"display","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments","value":[{"kind":"identifier","text":"display"}]},{"op":"replace","value":"JVDisplayController","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments","value":[{"kind":"identifier","text":"JVDisplayController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}