{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setLocale(_:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setLocale:"}],"modules":[{"name":"JivoSDK"}],"roleHeading":"Instance Method","role":"symbol","title":"setLocale(_:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setLocale","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"},{"text":"?)","kind":"text"}],"externalID":"c:@M@JivoSDK@objc(cs)JVDisplayController(im)setLocale:"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Sets the custom locale for use instead of system one","type":"text"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/setlocale(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplaycontroller\/setlocale(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(setLocale:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setLocale"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"locale","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"May be helpful in case you implement your own logic"},{"text":" ","type":"text"},{"type":"text","text":"for changing a language locally within your app"}]}],"type":"aside","name":"Note","style":"note"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"role":"symbol","navigatorTitle":[{"text":"display","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"display","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVDisplayController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","title":"display","type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jivo\/display","abstract":[{"type":"text","text":"Namespace for SDK displaying"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"title":"JVDisplayController","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","isActive":true,"type":"reference"},{"text":" namespace for SDK displaying","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JVDisplayController","kind":"identifier"}],"type":"topic","url":"\/documentation\/jivosdk\/jvdisplaycontroller","navigatorTitle":[{"kind":"identifier","text":"JVDisplayController"}],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","kind":"symbol","title":"Jivo","abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/setLocale(_:)":{"abstract":[{"type":"text","text":"Sets the custom locale for use instead of system one"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setLocale"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation6LocaleV","kind":"typeIdentifier","text":"Locale"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setLocale(_:)","type":"topic","title":"setLocale(_:)","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/setlocale(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setLocale:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"setLocale:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"setLocale:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setLocale:"},{"text":"(","kind":"text"},{"text":"NSLocale","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLocale"},{"text":" *) ","kind":"text"},{"text":"locale","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title","value":"display"},{"value":[{"text":"display","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments","op":"replace"},{"op":"replace","value":"JVDisplayController","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments","value":[{"text":"JVDisplayController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}]},{"op":"replace","value":"setLocale:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1setLocale(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setLocale:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1setLocale(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}