{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/never"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/never"]}],"metadata":{"externalID":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingMoment@JivoSDKNotificationsPermissionAskingMomentNever","title":"JivoSDKNotificationsPermissionAskingMoment.never","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"never","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingMomentNever","kind":"identifier"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"never","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/never","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"kind":"symbol","title":"JivoSDK","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMoment"}],"role":"symbol","deprecated":true,"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMoment"}],"title":"JivoSDKNotificationsPermissionAskingMoment","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment/never":{"title":"JivoSDKNotificationsPermissionAskingMoment.never","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/never","abstract":[],"navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingMomentNever","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/never","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"never"}],"kind":"symbol","deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"JivoSDKNotificationsPermissionAskingMomentNever"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JivoSDKNotificationsPermissionAskingMomentNever","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMomentNever"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"JivoSDKNotificationsPermissionAskingMoment","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment\/fragments","value":[{"text":"JivoSDKNotificationsPermissionAskingMoment","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1never\/title","op":"replace","value":"JivoSDKNotificationsPermissionAskingMomentNever"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1never\/fragments","value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMomentNever"}]}]}]}