{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onAppear"}],"roleHeading":"Case","title":"JivoSDKNotificationsPermissionAskingMoment.onAppear","platforms":[],"role":"symbol","modules":[{"name":"JivoSDK"}],"symbolKind":"case","navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnAppear","kind":"identifier"}],"externalID":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingMoment@JivoSDKNotificationsPermissionAskingMomentOnAppear"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/onappear"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/onappear"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onAppear"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAppear"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","type":"topic","role":"collection","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment/onAppear":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"onAppear","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMomentOnAppear"}],"abstract":[],"kind":"symbol","title":"JivoSDKNotificationsPermissionAskingMoment.onAppear","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/onappear","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onAppear","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMoment"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMoment"}],"abstract":[],"kind":"symbol","title":"JivoSDKNotificationsPermissionAskingMoment","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment","deprecated":true}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"JivoSDKNotificationsPermissionAskingMomentOnAppear"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnAppear","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMomentOnAppear"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1onAppear\/title","value":"JivoSDKNotificationsPermissionAskingMomentOnAppear"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1onAppear\/fragments","op":"replace","value":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnAppear","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment\/title","value":"JivoSDKNotificationsPermissionAskingMoment","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment\/fragments","value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMoment"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}