{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onConnect","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnConnect","kind":"identifier"}],"title":"JivoSDKNotificationsPermissionAskingMoment.onConnect","platforms":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConnect","kind":"identifier"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingMoment@JivoSDKNotificationsPermissionAskingMomentOnConnect","symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/onconnect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/onconnect"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConnect","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment/onConnect":{"url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/onconnect","role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onConnect","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConnect","kind":"identifier"}],"navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnConnect","kind":"identifier"}],"title":"JivoSDKNotificationsPermissionAskingMoment.onConnect","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment":{"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JivoSDKNotificationsPermissionAskingMoment","kind":"identifier"}],"type":"topic","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment","navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingMoment","kind":"identifier"}],"title":"JivoSDKNotificationsPermissionAskingMoment","abstract":[],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"JivoSDKNotificationsPermissionAskingMomentOnConnect","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMomentOnConnect"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnConnect","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1onConnect\/title","op":"replace","value":"JivoSDKNotificationsPermissionAskingMomentOnConnect"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1onConnect\/fragments","value":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnConnect","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment\/title","value":"JivoSDKNotificationsPermissionAskingMoment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment\/fragments","value":[{"text":"JivoSDKNotificationsPermissionAskingMoment","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}