{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onSend"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/onsend"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/onsend"]}],"metadata":{"platforms":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSend"}],"externalID":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingMoment@JivoSDKNotificationsPermissionAskingMomentOnSend","role":"symbol","title":"JivoSDKNotificationsPermissionAskingMoment.onSend","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMomentOnSend"}],"modules":[{"name":"JivoSDK"}],"symbolKind":"case"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSend"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment/onSend":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"onSend","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/onsend","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onSend","type":"topic","title":"JivoSDKNotificationsPermissionAskingMoment.onSend","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnSend","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","kind":"symbol","role":"collection","type":"topic","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JivoSDKNotificationsPermissionAskingMoment","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingMoment","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment","abstract":[],"url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment","title":"JivoSDKNotificationsPermissionAskingMoment","kind":"symbol","deprecated":true}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"JivoSDKNotificationsPermissionAskingMomentOnSend"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMomentOnSend"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnSend","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1onSend\/title","value":"JivoSDKNotificationsPermissionAskingMomentOnSend"},{"value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMomentOnSend"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1onSend\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment\/title","value":"JivoSDKNotificationsPermissionAskingMoment","op":"replace"},{"value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMoment"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}