{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment\/onAppear"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAppear"}],"symbolKind":"case","externalID":"c:@M@JivoSDK@E@JVNotificationsPermissionAskingMoment@JVNotificationsPermissionAskingMomentOnAppear","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"JVNotificationsPermissionAskingMomentOnAppear"}],"title":"JVNotificationsPermissionAskingMoment.onAppear","roleHeading":"Case","role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"onAppear","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Ask when JivoSDK becomes onscreen","type":"text"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment\/onappear"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment\/onappear"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsPermissionAskingMoment/onAppear":{"type":"topic","url":"\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment\/onappear","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onAppear","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment\/onAppear","abstract":[{"type":"text","text":"Ask when JivoSDK becomes onscreen"}],"role":"symbol","navigatorTitle":[{"text":"JVNotificationsPermissionAskingMomentOnAppear","kind":"identifier"}],"title":"JVNotificationsPermissionAskingMoment.onAppear","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"type":"topic","title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsPermissionAskingMoment":{"title":"JVNotificationsPermissionAskingMoment","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVNotificationsPermissionAskingMoment","kind":"identifier"}],"abstract":[{"type":"text","text":"Moment to request access to Push Notifications"}],"role":"symbol","navigatorTitle":[{"text":"JVNotificationsPermissionAskingMoment","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"JVNotificationsPermissionAskingMomentOnAppear","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"JVNotificationsPermissionAskingMomentOnAppear","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"JVNotificationsPermissionAskingMomentOnAppear"}],"languages":["occ"]}]}},{"value":"JVNotificationsPermissionAskingMomentOnAppear","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsPermissionAskingMoment~1onAppear\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsPermissionAskingMoment~1onAppear\/fragments","op":"replace","value":[{"text":"JVNotificationsPermissionAskingMomentOnAppear","kind":"identifier"}]},{"op":"replace","value":"JVNotificationsPermissionAskingMoment","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsPermissionAskingMoment\/title"},{"value":[{"text":"JVNotificationsPermissionAskingMoment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsPermissionAskingMoment\/fragments"}]}]}