{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConnect"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"text":"JVNotificationsPermissionAskingMomentOnConnect","kind":"identifier"}],"role":"symbol","externalID":"c:@M@JivoSDK@E@JVNotificationsPermissionAskingMoment@JVNotificationsPermissionAskingMomentOnConnect","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConnect","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"JivoSDK"}],"title":"JVNotificationsPermissionAskingMoment.onConnect","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment\/onConnect"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment\/onconnect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment\/onconnect"]}],"kind":"symbol","abstract":[{"text":"Ask when connected to Jivo","type":"text"},{"type":"text","text":" "},{"type":"text","text":"in "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/startUp(channelID:userToken:)","isActive":true},{"text":" call","type":"text"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","title":"JivoSDK","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/startUp(channelID:userToken:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdksession\/startup(channelid:usertoken:)","title":"startUp(channelID:userToken:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"startUp","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"channelID"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/startUp(channelID:userToken:)","deprecated":true,"type":"topic","navigatorTitle":[{"text":"startUpWithChannelID:userToken:","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsPermissionAskingMoment":{"title":"JVNotificationsPermissionAskingMoment","type":"topic","url":"\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment","kind":"symbol","abstract":[{"type":"text","text":"Moment to request access to Push Notifications"}],"navigatorTitle":[{"kind":"identifier","text":"JVNotificationsPermissionAskingMoment"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsPermissionAskingMoment","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsPermissionAskingMoment/onConnect":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment\/onConnect","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConnect"}],"kind":"symbol","abstract":[{"text":"Ask when connected to Jivo","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/startUp(channelID:userToken:)"},{"text":" call","type":"text"}],"url":"\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment\/onconnect","title":"JVNotificationsPermissionAskingMoment.onConnect","navigatorTitle":[{"text":"JVNotificationsPermissionAskingMomentOnConnect","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"JVNotificationsPermissionAskingMomentOnConnect"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JVNotificationsPermissionAskingMomentOnConnect","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"JVNotificationsPermissionAskingMomentOnConnect","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1startUp(channelID:userToken:)\/title","op":"replace","value":"startUpWithChannelID:userToken:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1startUp(channelID:userToken:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"startUpWithChannelID:userToken:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsPermissionAskingMoment\/title","value":"JVNotificationsPermissionAskingMoment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsPermissionAskingMoment\/fragments","value":[{"text":"JVNotificationsPermissionAskingMoment","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsPermissionAskingMoment~1onConnect\/title","value":"JVNotificationsPermissionAskingMomentOnConnect"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsPermissionAskingMoment~1onConnect\/fragments","value":[{"text":"JVNotificationsPermissionAskingMomentOnConnect","kind":"identifier"}]}]}]}