{"kind":"symbol","variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationsevent\/any"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnotificationsevent\/any"]}],"metadata":{"title":"JVNotificationsEvent.any","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"any"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsEventAny"}],"role":"symbol","externalID":"c:@M@JivoSDK@E@JVNotificationsEvent@JVNotificationsEventAny","modules":[{"name":"JivoSDK"}]},"sections":[],"abstract":[{"text":"Any event","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/any"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"any","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent/any":{"kind":"symbol","title":"JVNotificationsEvent.any","abstract":[{"text":"Any event","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/any","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"any","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVNotificationsEventAny"}],"url":"\/documentation\/jivosdk\/jvnotificationsevent\/any","type":"topic","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent":{"url":"\/documentation\/jivosdk\/jvnotificationsevent","type":"topic","role":"symbol","kind":"symbol","title":"JVNotificationsEvent","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsEvent"}],"abstract":[{"type":"text","text":"Event category of notification"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsEvent","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"JVNotificationsEventAny"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVNotificationsEventAny"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"JVNotificationsEventAny"}],"platforms":["iOS"]}]}},{"value":"JVNotificationsEventAny","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent~1any\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent~1any\/fragments","value":[{"text":"JVNotificationsEventAny","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/title","value":"JVNotificationsEvent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/fragments","value":[{"kind":"identifier","text":"JVNotificationsEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}