{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UNMutableNotificationContent","kind":"typeIdentifier","text":"UNMutableNotificationContent"}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"s:7JivoSDK20JVNotificationsEventC7contentSo28UNMutableNotificationContentCvp","symbolKind":"property","role":"symbol","modules":[{"name":"JivoSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UNMutableNotificationContent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNMutableNotificationContent"}],"roleHeading":"Instance Property","title":"content"},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/content","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationsevent\/content"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsEvent","kind":"identifier"}],"title":"JVNotificationsEvent","type":"topic","navigatorTitle":[{"text":"JVNotificationsEvent","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","kind":"symbol","url":"\/documentation\/jivosdk\/jvnotificationsevent","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent/content":{"title":"content","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNMutableNotificationContent","text":"UNMutableNotificationContent","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/content","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk\/jvnotificationsevent\/content","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/title","value":"JVNotificationsEvent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/fragments","value":[{"kind":"identifier","text":"JVNotificationsEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/navigatorTitle","value":[{"kind":"identifier","text":"JVNotificationsEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}