{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/sender","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"sender","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationsevent\/sender"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sender"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"modules":[{"name":"JivoSDK"}],"roleHeading":"Instance Property","externalID":"s:7JivoSDK20JVNotificationsEventC6senderSSvp","symbolKind":"property","title":"sender"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsEvent"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","url":"\/documentation\/jivosdk\/jvnotificationsevent","navigatorTitle":[{"text":"JVNotificationsEvent","kind":"identifier"}],"title":"JVNotificationsEvent","kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent/sender":{"url":"\/documentation\/jivosdk\/jvnotificationsevent\/sender","role":"symbol","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"sender","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/sender","kind":"symbol","title":"sender","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","type":"topic","abstract":[],"title":"JivoSDK"}},"variantOverrides":[{"patch":[{"value":"JVNotificationsEvent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/fragments","value":[{"text":"JVNotificationsEvent","kind":"identifier"}]},{"value":[{"text":"JVNotificationsEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}