{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/text","interfaceLanguage":"swift"},"metadata":{"externalID":"s:7JivoSDK20JVNotificationsEventC4textSSvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"text","role":"symbol","modules":[{"name":"JivoSDK"}],"symbolKind":"property","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationsevent\/text"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"JVNotificationsEvent","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsEvent","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvnotificationsevent","title":"JVNotificationsEvent","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","abstract":[],"url":"\/documentation\/jivosdk","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent/text":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/text","kind":"symbol","url":"\/documentation\/jivosdk\/jvnotificationsevent\/text","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","title":"text","role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/title","value":"JVNotificationsEvent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/fragments","value":[{"kind":"identifier","text":"JVNotificationsEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/navigatorTitle","value":[{"text":"JVNotificationsEvent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}