{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@JivoSDK@objc(pl)JivoSDKNotificationsDelegate(im)jivoNeedAccessToNotifications:proceedBlock:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"needAccessToNotifications"},{"kind":"text","text":": "},{"text":"JivoSDK","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK"},{"text":", ","kind":"text"},{"text":"proceedBlock","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"platforms":[],"title":"jivo(needAccessToNotifications:proceedBlock:)","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"jivoNeedAccessToNotifications:proceedBlock:"}],"symbolKind":"method","modules":[{"name":"JivoSDK"}]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsDelegate\/jivo(needAccessToNotifications:proceedBlock:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationsdelegate\/jivo(needaccesstonotifications:proceedblock:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationsdelegate\/jivo(needaccesstonotifications:proceedblock:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(jivoNeedAccessToNotifications:proceedBlock:) ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"jivo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"needAccessToNotifications"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sdk"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","text":"JivoSDK"},{"kind":"text","text":", "},{"text":"proceedBlock","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" () -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsDelegate/jivo(needAccessToNotifications:proceedBlock:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"jivo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"needAccessToNotifications"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"proceedBlock"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/jivosdk\/jivosdknotificationsdelegate\/jivo(needaccesstonotifications:proceedblock:)","kind":"symbol","title":"jivo(needAccessToNotifications:proceedBlock:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"jivoNeedAccessToNotifications:proceedBlock:"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsDelegate\/jivo(needAccessToNotifications:proceedBlock:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKNotificationsDelegate"}],"abstract":[],"title":"JivoSDKNotificationsDelegate","url":"\/documentation\/jivosdk\/jivosdknotificationsdelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"JivoSDKNotificationsDelegate","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsDelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","kind":"symbol","abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"kind":"symbol","navigatorTitle":[{"text":"JivoSDK","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","deprecated":true,"title":"JivoSDK","abstract":[],"url":"\/documentation\/jivosdk\/jivosdk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDK","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"jivoNeedAccessToNotifications:proceedBlock:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoNeedAccessToNotifications:proceedBlock:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"jivoNeedAccessToNotifications:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sdk"},{"text":" ","kind":"text"},{"text":"proceedBlock:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"text","text":")()) "},{"kind":"internalParam","text":"proceedBlock"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"jivoNeedAccessToNotifications:proceedBlock:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsDelegate~1jivo(needAccessToNotifications:proceedBlock:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsDelegate~1jivo(needAccessToNotifications:proceedBlock:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"jivoNeedAccessToNotifications:proceedBlock:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsDelegate\/title","value":"JivoSDKNotificationsDelegate"},{"value":[{"kind":"identifier","text":"JivoSDKNotificationsDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsDelegate\/fragments","op":"replace"},{"value":"JivoSDK","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments","value":[{"kind":"identifier","text":"JivoSDK"}],"op":"replace"}]}]}