{"metadata":{"role":"symbol","externalID":"c:@M@JivoSDK@objc(cs)JVNavigationContainer(im)initWithNibName:bundle:","symbolKind":"method","modules":[{"name":"JivoSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"roleHeading":"Instance Method","title":"initWithNibName:bundle:"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer\/initWithNibName:bundle:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithNibName:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"nibNameOrNil","kind":"internalParam"},{"kind":"text","text":" "},{"text":"bundle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","text":"NSBundle","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nibBundleOrNil"},{"kind":"text","text":";"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnavigationcontainer\/initwithnibname:bundle:"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNavigationContainer/initWithNibName:bundle:":{"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer\/initWithNibName:bundle:","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvnavigationcontainer\/initwithnibname:bundle:","type":"topic","title":"initWithNibName:bundle:"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","kind":"symbol","url":"\/documentation\/jivosdk","role":"collection","abstract":[],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNavigationContainer":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer","title":"JVNavigationContainer","url":"\/documentation\/jivosdk\/jvnavigationcontainer","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Descendent of UINavigationController for UI hierarchy"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JVNavigationContainer","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"JVNavigationContainer","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNavigationContainer\/title","value":"JVNavigationContainer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNavigationContainer\/fragments","value":[{"text":"JVNavigationContainer","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"JVNavigationContainer"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNavigationContainer\/navigatorTitle","op":"replace"}]}]}