{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer\/initWithNavigationBarClass:toolbarClass:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnavigationcontainer\/initwithnavigationbarclass:toolbarclass:"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithNavigationBarClass:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Class","preciseIdentifier":"c:@T@Class","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"navigationBarClass","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"toolbarClass:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Class","preciseIdentifier":"c:@T@Class","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"toolbarClass","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"5.0"},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"5.0"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"5.0"}],"modules":[{"name":"JivoSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNavigationBarClass:toolbarClass:"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithNavigationBarClass:toolbarClass:"}],"externalID":"c:@M@JivoSDK@objc(cs)JVNavigationContainer(im)initWithNavigationBarClass:toolbarClass:","title":"initWithNavigationBarClass:toolbarClass:","symbolKind":"method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNavigationContainer":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer","type":"topic","abstract":[{"type":"text","text":"Descendent of UINavigationController for UI hierarchy"}],"title":"JVNavigationContainer","kind":"symbol","url":"\/documentation\/jivosdk\/jvnavigationcontainer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNavigationContainer","kind":"identifier"}],"navigatorTitle":[{"text":"JVNavigationContainer","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","type":"topic","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNavigationContainer/initWithNavigationBarClass:toolbarClass:":{"type":"topic","abstract":[],"url":"\/documentation\/jivosdk\/jvnavigationcontainer\/initwithnavigationbarclass:toolbarclass:","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithNavigationBarClass:toolbarClass:"}],"title":"initWithNavigationBarClass:toolbarClass:","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer\/initWithNavigationBarClass:toolbarClass:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNavigationBarClass:toolbarClass:"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNavigationContainer\/title","value":"JVNavigationContainer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNavigationContainer\/fragments","value":[{"text":"JVNavigationContainer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNavigationContainer\/navigatorTitle","value":[{"text":"JVNavigationContainer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}