{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"current"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/current"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler\/current"]},{"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler\/current"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[],"title":"JivoSDKNotificationsPermissionAskingHandler.current","roleHeading":"Case","modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingHandler@JivoSDKNotificationsPermissionAskingHandlerCurrent","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"current","kind":"identifier"}],"navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingHandlerCurrent","kind":"identifier"}],"symbolKind":"case","role":"symbol"},"sections":[],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","abstract":[],"title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingHandler":{"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler","navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandler"}],"type":"topic","deprecated":true,"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandler"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler","title":"JivoSDKNotificationsPermissionAskingHandler","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingHandler/current":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/current","title":"JivoSDKNotificationsPermissionAskingHandler.current","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler\/current","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandlerCurrent"}],"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"current","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"JivoSDKNotificationsPermissionAskingHandlerCurrent","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandlerCurrent"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandlerCurrent"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler\/title","value":"JivoSDKNotificationsPermissionAskingHandler"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler~1current\/title","value":"JivoSDKNotificationsPermissionAskingHandlerCurrent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler~1current\/fragments","value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandlerCurrent"}]}]}]}