{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdk","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler\/sdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler\/sdk"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"JivoSDKNotificationsPermissionAskingHandler.sdk","symbolKind":"case","externalID":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingHandler@JivoSDKNotificationsPermissionAskingHandlerSdk","platforms":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdk"}],"navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingHandlerSdk","kind":"identifier"}],"role":"symbol","modules":[{"name":"JivoSDK"}],"roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/sdk"},"sections":[],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","type":"topic","role":"collection","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingHandler/sdk":{"deprecated":true,"title":"JivoSDKNotificationsPermissionAskingHandler.sdk","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdk"}],"url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler\/sdk","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/sdk","navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingHandlerSdk","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingHandler":{"url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandler"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandler"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler","role":"symbol","abstract":[],"title":"JivoSDKNotificationsPermissionAskingHandler","deprecated":true}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"JivoSDKNotificationsPermissionAskingHandlerSdk","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandlerSdk"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"JivoSDKNotificationsPermissionAskingHandlerSdk","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"JivoSDKNotificationsPermissionAskingHandlerSdk","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler~1sdk\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler~1sdk\/fragments","op":"replace","value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandlerSdk"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler\/title","value":"JivoSDKNotificationsPermissionAskingHandler"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler\/fragments","value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandler"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}