{"abstract":[{"type":"text","text":"Called when unread counter changes"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate\/jivoSession(updateUnreadCounter:number:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(jivoSessionUpdateUnreadCounter:number:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoSession"},{"text":"(","kind":"text"},{"text":"updateUnreadCounter","kind":"externalParam"},{"kind":"text","text":" "},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"kind":"text","text":", "},{"text":"number","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"sdk","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Reference to JivoSDK"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Actual number to take in account when updating your custom UI indicators","type":"text"}]}],"name":"number"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvsessiondelegate\/jivosession(updateunreadcounter:number:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvsessiondelegate\/jivosession(updateunreadcounter:number:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoSession","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"updateUnreadCounter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"number"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"required":true,"roleHeading":"Instance Method","externalID":"c:@M@JivoSDK@objc(pl)JVSessionDelegate(im)jivoSessionUpdateUnreadCounter:number:","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"text":"jivoSessionUpdateUnreadCounter:number:","kind":"identifier"}],"title":"jivoSession(updateUnreadCounter:number:)","symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"abstract":[],"title":"Jivo","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol","url":"\/documentation\/jivosdk\/jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionDelegate/jivoSession(updateUnreadCounter:number:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate\/jivoSession(updateUnreadCounter:number:)","url":"\/documentation\/jivosdk\/jvsessiondelegate\/jivosession(updateunreadcounter:number:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoSession"},{"kind":"text","text":"("},{"text":"updateUnreadCounter","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"number"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"jivoSessionUpdateUnreadCounter:number:"}],"title":"jivoSession(updateUnreadCounter:number:)","abstract":[{"type":"text","text":"Called when unread counter changes"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"role":"collection","url":"\/documentation\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionDelegate":{"url":"\/documentation\/jivosdk\/jvsessiondelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVSessionDelegate"}],"title":"JVSessionDelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate","abstract":[{"text":"Interface to handle session events,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"relates to "},{"code":"Jivo.session","type":"codeVoice"},{"type":"text","text":" namespace"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"JVSessionDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"jivoSessionUpdateUnreadCounter:number:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jivoSessionUpdateUnreadCounter:number:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"jivoSessionUpdateUnreadCounter:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier","text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sdk"},{"text":" ","kind":"text"},{"kind":"identifier","text":"number:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"number","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"sdk","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Reference to JivoSDK"}]}]},{"name":"number","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Actual number to take in account when updating your custom UI indicators","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace","value":"Jivo"},{"op":"replace","value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"kind":"identifier","text":"Jivo"}]},{"value":"jivoSessionUpdateUnreadCounter:number:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate~1jivoSession(updateUnreadCounter:number:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate~1jivoSession(updateUnreadCounter:number:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"jivoSessionUpdateUnreadCounter:number:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/title","value":"JVSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/fragments","value":[{"text":"JVSessionDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/navigatorTitle","value":[{"text":"JVSessionDelegate","kind":"identifier"}],"op":"replace"}]}]}