{"metadata":{"role":"symbol","title":"JVDebuggingOriginalCatchBehavior.ignore","symbolKind":"case","modules":[{"name":"JivoSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignore","kind":"identifier"}],"externalID":"c:@M@JivoSDK@E@JVDebuggingOriginalCatchBehavior@JVDebuggingOriginalCatchBehaviorIgnore","roleHeading":"Case","navigatorTitle":[{"text":"JVDebuggingOriginalCatchBehaviorIgnore","kind":"identifier"}]},"sections":[],"abstract":[{"type":"text","text":"Ignore an event details"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/ignore","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ignore","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior\/ignore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior\/ignore"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalCatchBehavior/ignore":{"title":"JVDebuggingOriginalCatchBehavior.ignore","abstract":[{"text":"Ignore an event details","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/ignore","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignore","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior\/ignore","navigatorTitle":[{"text":"JVDebuggingOriginalCatchBehaviorIgnore","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalCatchBehavior":{"title":"JVDebuggingOriginalCatchBehavior","abstract":[{"type":"text","text":"SDK behavior for catching logging events"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingOriginalCatchBehavior","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior","navigatorTitle":[{"text":"JVDebuggingOriginalCatchBehavior","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"JVDebuggingOriginalCatchBehaviorIgnore","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JVDebuggingOriginalCatchBehaviorIgnore"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"JVDebuggingOriginalCatchBehaviorIgnore","kind":"identifier"}]}]}},{"value":"JVDebuggingOriginalCatchBehaviorIgnore","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior~1ignore\/title","op":"replace"},{"value":[{"text":"JVDebuggingOriginalCatchBehaviorIgnore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior~1ignore\/fragments"},{"value":"JVDebuggingOriginalCatchBehavior","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior\/title"},{"value":[{"text":"JVDebuggingOriginalCatchBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior\/fragments"}]}]}