{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Log an event details"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keep","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior"]]},"variants":[{"paths":["\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior\/keep"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior\/keep"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/keep","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"case","role":"symbol","externalID":"c:@M@JivoSDK@E@JVDebuggingOriginalCatchBehavior@JVDebuggingOriginalCatchBehaviorKeep","modules":[{"name":"JivoSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keep"}],"roleHeading":"Case","title":"JVDebuggingOriginalCatchBehavior.keep","navigatorTitle":[{"text":"JVDebuggingOriginalCatchBehaviorKeep","kind":"identifier"}]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalCatchBehavior/keep":{"title":"JVDebuggingOriginalCatchBehavior.keep","kind":"symbol","url":"\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior\/keep","type":"topic","role":"symbol","navigatorTitle":[{"text":"JVDebuggingOriginalCatchBehaviorKeep","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/keep","abstract":[{"type":"text","text":"Log an event details"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"keep","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalCatchBehavior":{"navigatorTitle":[{"text":"JVDebuggingOriginalCatchBehavior","kind":"identifier"}],"abstract":[{"type":"text","text":"SDK behavior for catching logging events"}],"url":"\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior","title":"JVDebuggingOriginalCatchBehavior","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDebuggingOriginalCatchBehavior"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"JVDebuggingOriginalCatchBehaviorKeep","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"JVDebuggingOriginalCatchBehaviorKeep","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"JVDebuggingOriginalCatchBehaviorKeep","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior~1keep\/title","op":"replace","value":"JVDebuggingOriginalCatchBehaviorKeep"},{"op":"replace","value":[{"kind":"identifier","text":"JVDebuggingOriginalCatchBehaviorKeep"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior~1keep\/fragments"},{"value":"JVDebuggingOriginalCatchBehavior","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior\/fragments","value":[{"text":"JVDebuggingOriginalCatchBehavior","kind":"identifier"}],"op":"replace"}]}]}