{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(jivoDidRequestShowing:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivo"},{"text":"(","kind":"text"},{"text":"didRequestShowing","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK","text":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattinguidelegate\/jivo(didrequestshowing:)"]},{"paths":["\/documentation\/jivosdk\/jivosdkchattinguidelegate\/jivo(didrequestshowing:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(didRequestShowing:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivo"},{"kind":"text","text":"("},{"text":"didRequestShowing","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK","text":"JivoSDK"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"jivoDidRequestShowing:"}],"title":"jivo(didRequestShowing:)","externalID":"c:@M@JivoSDK@objc(pl)JivoSDKChattingUIDelegate(im)jivoDidRequestShowing:","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","platforms":[],"modules":[{"name":"JivoSDK"}],"required":true},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUIDelegate":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdkchattinguidelegate","role":"symbol","title":"JivoSDKChattingUIDelegate","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingUIDelegate"}],"abstract":[],"type":"topic","deprecated":true,"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKChattingUIDelegate","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"kind":"symbol","navigatorTitle":[{"text":"JivoSDK","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","deprecated":true,"title":"JivoSDK","abstract":[],"url":"\/documentation\/jivosdk\/jivosdk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDK","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUIDelegate/jivo(didRequestShowing:)":{"type":"topic","navigatorTitle":[{"text":"jivoDidRequestShowing:","kind":"identifier"}],"abstract":[],"deprecated":true,"title":"jivo(didRequestShowing:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(didRequestShowing:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"jivo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"didRequestShowing"},{"text":": ","kind":"text"},{"text":"JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"url":"\/documentation\/jivosdk\/jivosdkchattinguidelegate\/jivo(didrequestshowing:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","kind":"symbol","abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"jivoDidRequestShowing:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoDidRequestShowing:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"jivoDidRequestShowing:","kind":"identifier"},{"kind":"text","text":"("},{"text":"JivoSDK","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sdk"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"JivoSDKChattingUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate\/fragments","value":[{"text":"JivoSDKChattingUIDelegate","kind":"identifier"}]},{"op":"replace","value":"JivoSDK","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title"},{"value":[{"kind":"identifier","text":"JivoSDK"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate~1jivo(didRequestShowing:)\/title","value":"jivoDidRequestShowing:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"jivoDidRequestShowing:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate~1jivo(didRequestShowing:)\/fragments"}]}]}