{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(willAppear:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(jivoWillAppear:) ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"willAppear"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sdk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"modules":[{"name":"JivoSDK"}],"title":"jivo(willAppear:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"willAppear"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK"},{"text":")","kind":"text"}],"platforms":[],"symbolKind":"method","navigatorTitle":[{"text":"jivoWillAppear:","kind":"identifier"}],"externalID":"c:@M@JivoSDK@objc(pl)JivoSDKChattingUIDelegate(im)jivoWillAppear:","role":"symbol","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattinguidelegate\/jivo(willappear:)"]},{"paths":["\/documentation\/jivosdk\/jivosdkchattinguidelegate\/jivo(willappear:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUIDelegate/jivo(willAppear:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"jivoWillAppear:"}],"abstract":[],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(willAppear:)","url":"\/documentation\/jivosdk\/jivosdkchattinguidelegate\/jivo(willappear:)","title":"jivo(willAppear:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"jivo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"willAppear","kind":"externalParam"},{"kind":"text","text":": "},{"text":"JivoSDK","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK"},{"kind":"text","text":")"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUIDelegate":{"kind":"symbol","title":"JivoSDKChattingUIDelegate","url":"\/documentation\/jivosdk\/jivosdkchattinguidelegate","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingUIDelegate"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKChattingUIDelegate"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JivoSDK"}],"abstract":[],"url":"\/documentation\/jivosdk\/jivosdk","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDK","kind":"identifier"}],"title":"JivoSDK","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"jivoWillAppear:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"jivoWillAppear:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"jivoWillAppear:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"},{"kind":"text","text":" *) "},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate~1jivo(willAppear:)\/title","value":"jivoWillAppear:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"jivoWillAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate~1jivo(willAppear:)\/fragments"},{"op":"replace","value":"JivoSDKChattingUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate\/title"},{"value":[{"kind":"identifier","text":"JivoSDKChattingUIDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate\/fragments","op":"replace"},{"value":"JivoSDK","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JivoSDK"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}