{"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdkchattinguidelegate\/jivo(diddisappear:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdkchattinguidelegate\/jivo(diddisappear:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivo"},{"text":"(","kind":"text"},{"text":"didDisappear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JivoSDK","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK"},{"kind":"text","text":")"}],"title":"jivo(didDisappear:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"jivoDidDisappear:","kind":"identifier"}],"required":true,"externalID":"c:@M@JivoSDK@objc(pl)JivoSDKChattingUIDelegate(im)jivoDidDisappear:","modules":[{"name":"JivoSDK"}],"platforms":[],"role":"symbol","symbolKind":"method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(jivoDidDisappear:) "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"didDisappear"},{"kind":"text","text":" "},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":": "},{"text":"JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(didDisappear:)"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUIDelegate/jivo(didDisappear:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(didDisappear:)","kind":"symbol","required":true,"url":"\/documentation\/jivosdk\/jivosdkchattinguidelegate\/jivo(diddisappear:)","navigatorTitle":[{"kind":"identifier","text":"jivoDidDisappear:"}],"type":"topic","title":"jivo(didDisappear:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivo"},{"text":"(","kind":"text"},{"text":"didDisappear","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK","text":"JivoSDK"},{"text":")","kind":"text"}],"deprecated":true,"abstract":[],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUIDelegate":{"role":"symbol","title":"JivoSDKChattingUIDelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingUIDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattinguidelegate","navigatorTitle":[{"text":"JivoSDKChattingUIDelegate","kind":"identifier"}],"kind":"symbol","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","title":"JivoSDK","abstract":[],"url":"\/documentation\/jivosdk","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","navigatorTitle":[{"text":"JivoSDK","kind":"identifier"}],"role":"symbol","deprecated":true,"url":"\/documentation\/jivosdk\/jivosdk","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDK"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"jivoDidDisappear:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoDidDisappear:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"jivoDidDisappear:"},{"kind":"text","text":"("},{"text":"JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"},{"kind":"text","text":" *) "},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate~1jivo(didDisappear:)\/title","value":"jivoDidDisappear:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"jivoDidDisappear:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate~1jivo(didDisappear:)\/fragments"},{"value":"JivoSDKChattingUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate\/fragments","value":[{"text":"JivoSDKChattingUIDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title","value":"JivoSDK","op":"replace"},{"value":[{"text":"JivoSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments"}]}]}