{"metadata":{"symbolKind":"method","externalID":"s:7JivoSDK8JVClientC21listenToUnreadCounter7handleryySic_tF","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"JivoSDK"}],"title":"listenToUnreadCounter(handler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listenToUnreadCounter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/jivosdk\/jvclient\/listentounreadcounter(handler:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/listenToUnreadCounter(handler:)"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient"]]},"abstract":[{"text":"Register your handler to observe the unread counter updates","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listenToUnreadCounter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient/listenToUnreadCounter(handler:)":{"role":"symbol","title":"listenToUnreadCounter(handler:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/listenToUnreadCounter(handler:)","url":"\/documentation\/jivosdk\/jvclient\/listentounreadcounter(handler:)","type":"topic","abstract":[{"type":"text","text":"Register your handler to observe the unread counter updates"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"listenToUnreadCounter"},{"text":"(","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"role":"collection","url":"\/documentation\/jivosdk","type":"topic","title":"JivoSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient":{"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient","role":"symbol","navigatorTitle":[{"text":"JVClient","kind":"identifier"}],"title":"JVClient","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVClient","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvclient"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/title","op":"replace","value":"JVClient"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/fragments","op":"replace","value":[{"text":"JVClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/navigatorTitle","op":"replace","value":[{"text":"JVClient","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}