{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvclient\/setcontactinfo(_:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Assigns contact info to user,"},{"type":"text","text":" "},{"type":"text","text":"to reach him easier in future"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setContactInfo"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JVClientContactInfo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientContactInfo","preciseIdentifier":"s:7JivoSDK19JVClientContactInfoa"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/setContactInfo(_:)"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setContactInfo"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK19JVClientContactInfoa","text":"JVClientContactInfo"},{"text":"?)","kind":"text"}],"modules":[{"name":"JivoSDK"}],"externalID":"s:7JivoSDK8JVClientC14setContactInfoyyAA09JVSessioneF0CSgF","role":"symbol","roleHeading":"Instance Method","title":"setContactInfo(_:)","symbolKind":"method"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","kind":"symbol","url":"\/documentation\/jivosdk","role":"collection","abstract":[],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClientContactInfo":{"navigatorTitle":[{"text":"JVClientContactInfo","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"JVClientContactInfo","kind":"identifier"}],"title":"JVClientContactInfo","type":"topic","abstract":[],"url":"\/documentation\/jivosdk\/jvclientcontactinfo","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientContactInfo","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVClient","kind":"identifier"}],"title":"JVClient","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient","navigatorTitle":[{"text":"JVClient","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jvclient"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient/setContactInfo(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setContactInfo"},{"kind":"text","text":"("},{"text":"JVClientContactInfo","preciseIdentifier":"s:7JivoSDK19JVClientContactInfoa","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/jivosdk\/jvclient\/setcontactinfo(_:)","abstract":[{"type":"text","text":"Assigns contact info to user,"},{"type":"text","text":" "},{"text":"to reach him easier in future","type":"text"}],"title":"setContactInfo(_:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/setContactInfo(_:)","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/title","op":"replace","value":"JVClient"},{"value":[{"text":"JVClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/navigatorTitle","op":"replace","value":[{"text":"JVClient","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}