{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCustomData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fields","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"JVClientCustomDataField","preciseIdentifier":"s:7JivoSDK23JVClientCustomDataFielda","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientCustomDataField","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Assigns custom data to user,"},{"type":"text","text":" "},{"type":"text","text":"if needed for your business"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvclient\/setcustomdata(fields:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"s:7JivoSDK8JVClientC13setCustomData6fieldsySayAA09JVSessioneF5FieldCG_tF","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCustomData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fields","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"JVClientCustomDataField","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK23JVClientCustomDataFielda"},{"text":"])","kind":"text"}],"role":"symbol","title":"setCustomData(fields:)","modules":[{"name":"JivoSDK"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/setCustomData(fields:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient"]]},"kind":"symbol","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient":{"title":"JVClient","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVClient","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/jivosdk\/jvclient","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"JVClient","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClientCustomDataField":{"url":"\/documentation\/jivosdk\/jvclientcustomdatafield","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientCustomDataField","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVClientCustomDataField"}],"kind":"symbol","title":"JVClientCustomDataField","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVClientCustomDataField"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient/setCustomData(fields:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCustomData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fields","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"JVClientCustomDataField","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK23JVClientCustomDataFielda"},{"text":"])","kind":"text"}],"abstract":[{"text":"Assigns custom data to user,","type":"text"},{"text":" ","type":"text"},{"text":"if needed for your business","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/setCustomData(fields:)","kind":"symbol","title":"setCustomData(fields:)","url":"\/documentation\/jivosdk\/jvclient\/setcustomdata(fields:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","url":"\/documentation\/jivosdk","role":"collection","kind":"symbol","title":"JivoSDK","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/title","value":"JVClient","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/fragments","value":[{"kind":"identifier","text":"JVClient"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/navigatorTitle","value":[{"kind":"identifier","text":"JVClient"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}