{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutDown"},{"kind":"text","text":"()"}],"title":"shutDown()","role":"symbol","externalID":"s:7JivoSDK8JVClientC8shutDownyyF","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"JivoSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient"]]},"abstract":[{"text":"Closes current connection, clears the local database,","type":"text"},{"text":" ","type":"text"},{"text":"and unsubscribes device from Push Notifications","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/shutDown()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvclient\/shutdown()"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutDown"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"role":"collection","url":"\/documentation\/jivosdk","type":"topic","title":"JivoSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient/shutDown()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutDown"},{"kind":"text","text":"()"}],"url":"\/documentation\/jivosdk\/jvclient\/shutdown()","abstract":[{"text":"Closes current connection, clears the local database,","type":"text"},{"text":" ","type":"text"},{"text":"and unsubscribes device from Push Notifications","type":"text"}],"title":"shutDown()","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/shutDown()"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient":{"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient","role":"symbol","navigatorTitle":[{"text":"JVClient","kind":"identifier"}],"title":"JVClient","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVClient","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvclient"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"JVClient","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/title"},{"op":"replace","value":[{"text":"JVClient","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"JVClient"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/navigatorTitle"}]}]}