{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSend"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment\/onsend"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment\/onsend"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment\/onSend","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Ask when user sends a message"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSend"}],"title":"JVNotificationsPermissionAskingMoment.onSend","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@JivoSDK@E@JVNotificationsPermissionAskingMoment@JVNotificationsPermissionAskingMomentOnSend","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"JVNotificationsPermissionAskingMomentOnSend"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsPermissionAskingMoment":{"role":"symbol","title":"JVNotificationsPermissionAskingMoment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsPermissionAskingMoment"}],"abstract":[{"type":"text","text":"Moment to request access to Push Notifications"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsPermissionAskingMoment"}],"url":"\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsPermissionAskingMoment/onSend":{"role":"symbol","title":"JVNotificationsPermissionAskingMoment.onSend","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSend"}],"abstract":[{"type":"text","text":"Ask when user sends a message"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment\/onSend","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsPermissionAskingMomentOnSend"}],"url":"\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment\/onsend"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"JVNotificationsPermissionAskingMomentOnSend"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JVNotificationsPermissionAskingMomentOnSend"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"JVNotificationsPermissionAskingMomentOnSend"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsPermissionAskingMoment\/title","value":"JVNotificationsPermissionAskingMoment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsPermissionAskingMoment\/fragments","value":[{"kind":"identifier","text":"JVNotificationsPermissionAskingMoment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsPermissionAskingMoment~1onSend\/title","value":"JVNotificationsPermissionAskingMomentOnSend"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsPermissionAskingMoment~1onSend\/fragments","value":[{"kind":"identifier","text":"JVNotificationsPermissionAskingMomentOnSend"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}