{"variants":[{"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"delegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"text":"JVSessionDelegate","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVSessionDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"modules":[{"name":"JivoSDK"}],"symbolKind":"property","externalID":"c:@M@JivoSDK@objc(cs)JVSessionController(py)delegate","roleHeading":"Instance Property"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController"]]},"abstract":[{"type":"text","text":"Object that handles session events"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/delegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(delegate) ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVSessionDelegate","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVSessionDelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController":{"abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session"},{"text":" namespace for managing user session","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVSessionController"}],"title":"JVSessionController","url":"\/documentation\/jivosdk\/jvsessioncontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","navigatorTitle":[{"kind":"identifier","text":"JVSessionController"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionDelegate":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVSessionDelegate"}],"abstract":[{"text":"Interface to handle session events,","type":"text"},{"type":"text","text":" "},{"text":"relates to ","type":"text"},{"code":"Jivo.session","type":"codeVoice"},{"type":"text","text":" namespace"}],"url":"\/documentation\/jivosdk\/jvsessiondelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"JVSessionDelegate","kind":"identifier"}],"title":"JVSessionDelegate","type":"topic","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/delegate":{"role":"symbol","abstract":[{"text":"Object that handles session events","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/delegate","url":"\/documentation\/jivosdk\/jvsessioncontroller\/delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVSessionDelegate","kind":"typeIdentifier","text":"JVSessionDelegate"},{"text":"?","kind":"text"}],"type":"topic","title":"delegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"kind":"symbol","role":"symbol","url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"type":"topic","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"title":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"abstract":[{"type":"text","text":"Namespace for managing user session"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"session"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JVSessionController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController"}],"title":"session","url":"\/documentation\/jivosdk\/jivo\/session","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","navigatorTitle":[{"text":"session","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@JivoSDK@objc(pl)JVSessionDelegate","text":"id<JVSessionDelegate>"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/title","op":"replace","value":"JVSessionController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/fragments","value":[{"kind":"identifier","text":"JVSessionController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/title","value":"JVSessionDelegate","op":"replace"},{"value":[{"text":"JVSessionDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/fragments"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1delegate\/title"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1delegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace","value":"Jivo"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]},{"value":"session","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments","value":[{"text":"session","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}