{"variants":[{"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@JivoSDK@objc(cs)JVSessionController(im)init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","title":"init","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/init"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController":{"url":"\/documentation\/jivosdk\/jvsessioncontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVSessionController","kind":"identifier"}],"title":"JVSessionController","type":"topic","abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","type":"reference","isActive":true},{"type":"text","text":" namespace for managing user session"}],"navigatorTitle":[{"kind":"identifier","text":"JVSessionController"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/init":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/init","url":"\/documentation\/jivosdk\/jvsessioncontroller\/init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/jivosdk","type":"topic","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"role":"symbol","url":"\/documentation\/jivosdk\/jivo\/session","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","navigatorTitle":[{"text":"session","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"kind":"text","text":": "},{"text":"JVSessionController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController"}],"abstract":[{"type":"text","text":"Namespace for managing user session"}],"kind":"symbol","title":"session"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"title":"Jivo","kind":"symbol","url":"\/documentation\/jivosdk\/jivo","role":"symbol","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Jivo"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/title","value":"JVSessionController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/fragments","op":"replace","value":[{"text":"JVSessionController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title","value":"session"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments","value":[{"text":"session","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}