{"metadata":{"externalID":"c:@M@JivoSDK@objc(cs)JVSessionController(im)setContactInfo:","title":"setContactInfo(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setContactInfo"},{"kind":"text","text":"("},{"text":"JVSessionContactInfo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionContactInfo","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setContactInfo:"}],"roleHeading":"Instance Method","modules":[{"name":"JivoSDK"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setContactInfo(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(setContactInfo:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setContactInfo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"info","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionContactInfo","text":"JVSessionContactInfo"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/setcontactinfo(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/setcontactinfo(_:)"]}],"kind":"symbol","abstract":[{"text":"Assigns contact info to user,","type":"text"},{"text":" ","type":"text"},{"text":"to reach him easier in future","type":"text"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","title":"Jivo","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"type":"topic","abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","kind":"symbol","role":"collection","type":"topic","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVSessionController"}],"navigatorTitle":[{"kind":"identifier","text":"JVSessionController"}],"kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvsessioncontroller","role":"symbol","abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","type":"reference","isActive":true},{"type":"text","text":" namespace for managing user session"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","title":"JVSessionController"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setContactInfo(_:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setContactInfo(_:)","title":"setContactInfo(_:)","type":"topic","role":"symbol","abstract":[{"text":"Assigns contact info to user,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to reach him easier in future"}],"navigatorTitle":[{"text":"setContactInfo:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvsessioncontroller\/setcontactinfo(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setContactInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JVSessionContactInfo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionContactInfo","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVSessionController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController"}],"navigatorTitle":[{"text":"session","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jivo\/session","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","title":"session","abstract":[{"type":"text","text":"Namespace for managing user session"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionContactInfo":{"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVSessionContactInfo"}],"kind":"symbol","navigatorTitle":[{"text":"JVSessionContactInfo","kind":"identifier"}],"title":"JVSessionContactInfo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo","abstract":[{"type":"text","text":"Contact Info for user"}],"url":"\/documentation\/jivosdk\/jvsessioncontactinfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setContactInfo:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setContactInfo:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setContactInfo:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionContactInfo","text":"JVSessionContactInfo"},{"kind":"text","text":" *) "},{"text":"info","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/title","value":"JVSessionController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/fragments","value":[{"text":"JVSessionController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"setContactInfo:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setContactInfo(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setContactInfo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setContactInfo:"}]},{"value":"session","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments","op":"replace","value":[{"text":"session","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo\/title","value":"JVSessionContactInfo"},{"value":[{"text":"JVSessionContactInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo\/fragments"}]}]}