{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setCustomData(fields:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(setCustomData:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomData"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionCustomDataField","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionCustomDataField","text":"JVSessionCustomDataField"},{"kind":"text","text":"])"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"title":"setCustomData(fields:)","roleHeading":"Instance Method","externalID":"c:@M@JivoSDK@objc(cs)JVSessionController(im)setCustomData:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setCustomData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionCustomDataField","text":"JVSessionCustomDataField"},{"text":"])","kind":"text"}],"role":"symbol","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"setCustomData:"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Assigns custom data to user,"},{"type":"text","text":" "},{"text":"if needed for your business","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/setcustomdata(fields:)"]},{"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/setcustomdata(fields:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"url":"\/documentation\/jivosdk\/jivo\/session","navigatorTitle":[{"kind":"identifier","text":"session"}],"type":"topic","abstract":[{"type":"text","text":"Namespace for managing user session"}],"title":"session","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController","text":"JVSessionController","kind":"typeIdentifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","title":"Jivo","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Jivo"}],"abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"url":"\/documentation\/jivosdk\/jivo","navigatorTitle":[{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController":{"url":"\/documentation\/jivosdk\/jvsessioncontroller","navigatorTitle":[{"text":"JVSessionController","kind":"identifier"}],"type":"topic","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","isActive":true,"type":"reference"},{"text":" namespace for managing user session","type":"text"}],"title":"JVSessionController","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVSessionController"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","role":"collection","type":"topic","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionCustomDataField":{"navigatorTitle":[{"text":"JVSessionCustomDataField","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jvsessioncustomdatafield","title":"JVSessionCustomDataField","role":"symbol","abstract":[{"type":"text","text":"Custom Data Field for user"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionCustomDataField","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVSessionCustomDataField","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setCustomData(fields:)":{"url":"\/documentation\/jivosdk\/jvsessioncontroller\/setcustomdata(fields:)","navigatorTitle":[{"text":"setCustomData:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Assigns custom data to user,"},{"type":"text","text":" "},{"text":"if needed for your business","type":"text"}],"title":"setCustomData(fields:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setCustomData(fields:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCustomData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionCustomDataField","text":"JVSessionCustomDataField","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"setCustomData:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setCustomData:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setCustomData:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<JVSessionCustomDataField *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fields"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"session","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title","op":"replace"},{"value":[{"kind":"identifier","text":"session"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/title","value":"JVSessionController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVSessionController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField\/title","value":"JVSessionCustomDataField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField\/fragments","value":[{"text":"JVSessionCustomDataField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setCustomData(fields:)\/title","op":"replace","value":"setCustomData:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setCustomData(fields:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setCustomData:"}]}]}]}