{"abstract":[{"type":"text","text":"Specifies preferred server for SDK to connect to Jivo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setPreferredServer(_:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","role":"symbol","title":"setPreferredServer(_:)","navigatorTitle":[{"text":"setPreferredServer:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPreferredServer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JVSessionServer","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVSessionServer"},{"text":")","kind":"text"}],"modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(cs)JVSessionController(im)setPreferredServer:"},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/setpreferredserver(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/setpreferredserver(_:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(setPreferredServer:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreferredServer"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"server","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVSessionServer","text":"JVSessionServer"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"topic","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}],"kind":"symbol","role":"symbol","title":"Jivo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController":{"role":"symbol","navigatorTitle":[{"text":"JVSessionController","kind":"identifier"}],"type":"topic","url":"\/documentation\/jivosdk\/jvsessioncontroller","abstract":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference"},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","isActive":true,"type":"reference"},{"type":"text","text":" namespace for managing user session"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVSessionController"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","kind":"symbol","title":"JVSessionController"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"url":"\/documentation\/jivosdk\/jivo\/session","role":"symbol","type":"topic","abstract":[{"text":"Namespace for managing user session","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController","text":"JVSessionController","kind":"typeIdentifier"}],"title":"session","navigatorTitle":[{"kind":"identifier","text":"session"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","url":"\/documentation\/jivosdk","kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setPreferredServer(_:)":{"url":"\/documentation\/jivosdk\/jvsessioncontroller\/setpreferredserver(_:)","role":"symbol","type":"topic","abstract":[{"text":"Specifies preferred server for SDK to connect to Jivo","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setPreferredServer(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPreferredServer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVSessionServer","text":"JVSessionServer"},{"text":")","kind":"text"}],"title":"setPreferredServer(_:)","navigatorTitle":[{"kind":"identifier","text":"setPreferredServer:"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVSessionServer"}],"url":"\/documentation\/jivosdk\/jvsessionserver","title":"JVSessionServer","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVSessionServer"}],"abstract":[{"text":"Primary Jivo servers, by geographical region","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"setPreferredServer:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"setPreferredServer:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setPreferredServer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVSessionServer","text":"JVSessionServer"},{"text":") ","kind":"text"},{"text":"server","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"Jivo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/title","op":"replace","value":"JVSessionController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/fragments","value":[{"text":"JVSessionController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title","value":"session","op":"replace"},{"value":[{"kind":"identifier","text":"session"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setPreferredServer(_:)\/title","value":"setPreferredServer:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setPreferredServer(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setPreferredServer:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer\/title","value":"JVSessionServer","op":"replace"},{"op":"replace","value":[{"text":"JVSessionServer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}