{"metadata":{"externalID":"s:7JivoSDK19JVSessionControllerC5setup8widgetID14clientIdentityAA8JVClientCSS_AA0jI0OtF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setup","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"widgetID"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientIdentity"},{"text":": ","kind":"text"},{"text":"JVClientIdentity","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK16JVClientIdentityO"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVClient","kind":"typeIdentifier","text":"JVClient"}],"symbolKind":"method","role":"symbol","modules":[{"name":"JivoSDK"}],"roleHeading":"Instance Method","title":"setup(widgetID:clientIdentity:)"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setup(widgetID:clientIdentity:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"widgetID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"clientIdentity"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientIdentity","text":"JVClientIdentity","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK16JVClientIdentityO"},{"text":") -> ","kind":"text"},{"text":"JVClient","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVClient","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Your widget_id in Jivo"}]}],"name":"widgetID"},{"name":"clientIdentity","content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Either JWT token that you generate to identify a client and keep a history,"},{"text":" ","type":"text"},{"text":"or anonymous mode for temporary chat sessions","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please take a look here for details about user token:"},{"text":" ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/common_user_token"}]}],"name":"Important"},{"type":"aside","style":"warning","name":"Warning","content":[{"inlineContent":[{"type":"text","text":"Please avoid calling this method while SDK is displayed onscreen"}],"type":"paragraph"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/setup(widgetid:clientidentity:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Starts a logical session for user,","type":"text"},{"text":" ","type":"text"},{"text":"by either creating a new session or resuming existing one","type":"text"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController":{"navigatorTitle":[{"kind":"identifier","text":"JVSessionController"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","title":"JVSessionController","url":"\/documentation\/jivosdk\/jvsessioncontroller","role":"symbol","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","type":"reference","isActive":true},{"text":" namespace for managing user session","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVSessionController","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setup(widgetID:clientIdentity:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setup","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"widgetID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"clientIdentity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7JivoSDK16JVClientIdentityO","text":"JVClientIdentity","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"JVClient","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVClient"}],"role":"symbol","abstract":[{"type":"text","text":"Starts a logical session for user,"},{"type":"text","text":" "},{"type":"text","text":"by either creating a new session or resuming existing one"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setup(widgetID:clientIdentity:)","url":"\/documentation\/jivosdk\/jvsessioncontroller\/setup(widgetid:clientidentity:)","title":"setup(widgetID:clientIdentity:)","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"abstract":[],"title":"Jivo","url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","title":"JivoSDK","kind":"symbol"},"https://jivochat.github.io/JivoSDK-iOS/documentation/jivosdk/common_user_token":{"type":"link","identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/common_user_token","title":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/common_user_token","titleInlineContent":[{"type":"text","text":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/common_user_token"}],"url":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/common_user_token"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"session","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVSessionController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController"}],"navigatorTitle":[{"text":"session","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Namespace for managing user session"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","url":"\/documentation\/jivosdk\/jivo\/session","title":"session","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClientIdentity":{"url":"\/documentation\/jivosdk\/jvclientidentity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JVClientIdentity","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVClientIdentity"}],"kind":"symbol","title":"JVClientIdentity","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientIdentity"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVClient"}],"title":"JVClient","navigatorTitle":[{"kind":"identifier","text":"JVClient"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvclient"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/title","value":"JVSessionController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/fragments","op":"replace","value":[{"text":"JVSessionController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/navigatorTitle","value":[{"text":"JVSessionController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"value":[{"text":"Jivo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"value":[{"text":"Jivo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle"},{"op":"replace","value":"session","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title"},{"value":[{"text":"session","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments"},{"value":"JVClient","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/title"},{"op":"replace","value":[{"text":"JVClient","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/fragments"},{"value":[{"kind":"identifier","text":"JVClient"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/navigatorTitle","op":"replace"}]}]}