{"kind":"symbol","metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutDown"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"shutDown"}],"externalID":"c:@M@JivoSDK@objc(cs)JVSessionController(im)shutDown","title":"shutDown()","role":"symbol","modules":[{"name":"JivoSDK"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/shutDown()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(shutDown) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutDown"},{"kind":"text","text":"()"}],"languages":["swift"]}]},{"mentions":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref"],"kind":"mentions"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"You also may use another form:"}],"type":"paragraph"},{"code":["let client = Jivo.session.setup(...)","client.shutDown()"],"syntax":"swift","type":"codeListing"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/shutdown()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/shutdown()"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Closes current connection, clears the local database,","type":"text"},{"text":" ","type":"text"},{"text":"and unsubscribes device from Push Notifications","type":"text"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/common_user_token":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token","url":"\/documentation\/jivosdk\/common_user_token","kind":"article","abstract":[{"type":"text","text":"Required for keeping chat history alive"}],"role":"article","title":"User Token and JWT","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","role":"collection","abstract":[],"url":"\/documentation\/jivosdk","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/shutDown()":{"kind":"symbol","role":"symbol","url":"\/documentation\/jivosdk\/jvsessioncontroller\/shutdown()","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/shutDown()","abstract":[{"text":"Closes current connection, clears the local database,","type":"text"},{"text":" ","type":"text"},{"text":"and unsubscribes device from Push Notifications","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutDown"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"shutDown"}],"title":"shutDown()"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","abstract":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference"},{"text":".","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","type":"reference"},{"text":" namespace for managing user session","type":"text"}],"title":"JVSessionController","role":"symbol","url":"\/documentation\/jivosdk\/jvsessioncontroller","type":"topic","navigatorTitle":[{"text":"JVSessionController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVSessionController","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"url":"\/documentation\/jivosdk\/jivo\/session","title":"session","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"session"}],"abstract":[{"type":"text","text":"Namespace for managing user session"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVSessionController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/flutter_api_ref":{"abstract":[{"text":"Dart API","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","url":"\/documentation\/jivosdk\/flutter_api_ref","title":"API Reference","type":"topic","kind":"article","role":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","kind":"symbol","title":"Jivo","url":"\/documentation\/jivosdk\/jivo","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/react_api_ref":{"role":"article","url":"\/documentation\/jivosdk\/react_api_ref","abstract":[{"type":"text","text":"JavaScript API"}],"type":"topic","title":"API Reference","kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"shutDown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"shutDown","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"shutDown","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1shutDown()\/title","value":"shutDown"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shutDown"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1shutDown()\/fragments","op":"replace"},{"value":"JVSessionController","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/title","op":"replace"},{"value":[{"text":"JVSessionController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"JVSessionController"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/navigatorTitle","op":"replace"},{"value":"session","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title","op":"replace"},{"value":[{"text":"session","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments","op":"replace"},{"value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","op":"replace"}]}]}