{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"startUp","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelID"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"startUpWithChannelID:userToken:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@JivoSDK@objc(cs)JVSessionController(im)startUpWithChannelID:userToken:","modules":[{"name":"JivoSDK"}],"title":"startUp(channelID:userToken:)","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/startup(channelid:usertoken:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvsessioncontroller\/startup(channelid:usertoken:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/startUp(channelID:userToken:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(startUpWithChannelID:userToken:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startUp"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"channelID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"userToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"channelID","content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Your channel ID in Jivo (same as widget_id)","type":"text"}],"type":"paragraph"}]},{"name":"userToken","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"text":" ","type":"text"},{"text":"An unique string that you generate to identify a client,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and it determines whether it is necessary to create a new session with a new dialog,"},{"type":"text","text":" "},{"type":"text","text":"or restore an existing one and load the history of the initiated dialog (should be a JWT token)"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"style":"important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please take a look at “User Token and JWT” section of SDK Documentation"},{"type":"text","text":" "},{"type":"text","text":"to learn more about how to use JWT here"}]}],"name":"Important"},{"name":"Warning","content":[{"inlineContent":[{"type":"text","text":"Please avoid calling this method while SDK is displayed onscreen"}],"type":"paragraph"}],"style":"warning","type":"aside"}]}],"abstract":[{"text":"Establishes connection between SDK and Jivo,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"by either creating a new session or resuming existing one"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"kind":"symbol","role":"symbol","url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"type":"topic","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"title":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController":{"abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session"},{"text":" namespace for managing user session","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVSessionController"}],"title":"JVSessionController","url":"\/documentation\/jivosdk\/jvsessioncontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","navigatorTitle":[{"kind":"identifier","text":"JVSessionController"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/startUp(channelID:userToken:)":{"role":"symbol","abstract":[{"text":"Establishes connection between SDK and Jivo,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"by either creating a new session or resuming existing one"}],"kind":"symbol","navigatorTitle":[{"text":"startUpWithChannelID:userToken:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/startUp(channelID:userToken:)","url":"\/documentation\/jivosdk\/jvsessioncontroller\/startup(channelid:usertoken:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startUp"},{"kind":"text","text":"("},{"text":"channelID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"userToken","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"startUp(channelID:userToken:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"abstract":[{"type":"text","text":"Namespace for managing user session"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"session"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JVSessionController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController"}],"title":"session","url":"\/documentation\/jivosdk\/jivo\/session","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","navigatorTitle":[{"text":"session","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"startUpWithChannelID:userToken:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startUpWithChannelID:userToken:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"startUpWithChannelID:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"channelID","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"userToken:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"userToken"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/title","value":"JVSessionController"},{"value":[{"text":"JVSessionController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/fragments","op":"replace"},{"value":"startUpWithChannelID:userToken:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1startUp(channelID:userToken:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1startUp(channelID:userToken:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startUpWithChannelID:userToken:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title","value":"session"},{"value":[{"kind":"identifier","text":"session"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}