{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(debugging) "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"debugging","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","kind":"typeIdentifier","text":"JVDebuggingController"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For details, see "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","isActive":true,"type":"reference"},{"text":" reference","type":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivo\/debugging-swift.type.property"]},{"paths":["\/documentation\/jivosdk\/jivo\/debugging-swift.type.property"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"debugging","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController","text":"JVDebuggingController","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"debugging"}],"symbolKind":"property","title":"debugging","externalID":"c:@CM@JivoSDK@objc(cs)Jivo(cpy)debugging","roleHeading":"Type Property","extendedModule":"JivoSDK"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"]]},"abstract":[{"text":"Namespace for SDK debugging","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging-swift.type.property"},"kind":"symbol","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"role":"symbol","abstract":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference"},{"text":".","type":"text"},{"type":"codeVoice","code":"Jivo\/debugging"},{"type":"text","text":" namespace for SDK debugging"}],"title":"JVDebuggingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVDebuggingController","kind":"identifier"}],"navigatorTitle":[{"text":"JVDebuggingController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","url":"\/documentation\/jivosdk\/jvdebuggingcontroller","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging-swift.type.property":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"debugging","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JVDebuggingController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"debugging","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging-swift.type.property","type":"topic","url":"\/documentation\/jivosdk\/jivo\/debugging-swift.type.property","abstract":[{"type":"text","text":"Namespace for SDK debugging"}],"title":"debugging","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","kind":"symbol","url":"\/documentation\/jivosdk","role":"collection","abstract":[],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"type":"topic","title":"Jivo","url":"\/documentation\/jivosdk\/jivo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"debugging"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"debugging","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController","kind":"typeIdentifier","text":"JVDebuggingController"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"debugging"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"JVDebuggingController","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments","op":"replace","value":[{"text":"JVDebuggingController","kind":"identifier"}]},{"op":"replace","value":[{"text":"JVDebuggingController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging-swift.type.property\/title","value":"debugging"},{"value":[{"kind":"identifier","text":"debugging"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging-swift.type.property\/fragments"},{"value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Jivo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle"}]}]}