{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications-swift.property","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"JivoSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifications"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","text":"JVNotificationsController"}],"role":"symbol","externalID":"c:@M@JivoSDK@objc(cs)Jivo(py)notifications","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"notifications"}],"title":"notifications"},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jivo\/notifications-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivo\/notifications-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"notifications","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","text":"JVNotificationsController"}]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","url":"\/documentation\/jivosdk\/jivo","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"role":"symbol","title":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"kind":"symbol","title":"JVNotificationsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsController"}],"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"type":"codeVoice","code":"Jivo\/notifications"},{"type":"text","text":" namespace for Push Notifications"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","role":"symbol","navigatorTitle":[{"text":"JVNotificationsController","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvnotificationscontroller"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications-swift.property":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notifications"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","kind":"typeIdentifier","text":"JVNotificationsController"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications-swift.property","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"notifications","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivo\/notifications-swift.property","type":"topic","abstract":[],"title":"notifications"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"notifications","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"notifications","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"JVNotificationsController","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController"},{"kind":"text","text":" * "},{"kind":"identifier","text":"notifications"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"kind":"identifier","text":"Jivo"}],"op":"replace"},{"value":"JVNotificationsController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title"},{"value":[{"text":"JVNotificationsController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"JVNotificationsController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications-swift.property\/title","op":"replace","value":"notifications"},{"value":[{"kind":"identifier","text":"notifications"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications-swift.property\/fragments"}]}]}