{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"]]},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"notifications"}],"modules":[{"name":"JivoSDK"}],"title":"notifications","roleHeading":"Type Property","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notifications"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","text":"JVNotificationsController","kind":"typeIdentifier"}],"externalID":"c:@CM@JivoSDK@objc(cs)Jivo(cpy)notifications"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Namespace for Push Notifications"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"notifications","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","kind":"typeIdentifier","text":"JVNotificationsController","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"For details, see ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","isActive":true,"type":"reference"},{"type":"text","text":" reference"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivo\/notifications"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivo\/notifications"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"navigatorTitle":[{"text":"JVNotificationsController","kind":"identifier"}],"abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference","isActive":true},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","isActive":true,"type":"reference"},{"text":" namespace for Push Notifications","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JVNotificationsController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","title":"JVNotificationsController","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvnotificationscontroller"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","abstract":[],"title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"navigatorTitle":[{"text":"notifications","kind":"identifier"}],"abstract":[{"type":"text","text":"Namespace for Push Notifications"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"notifications","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","text":"JVNotificationsController","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","title":"notifications","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jivo\/notifications"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"kind":"symbol","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","url":"\/documentation\/jivosdk\/jivo","abstract":[],"role":"symbol","title":"Jivo","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"notifications","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"notifications","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","text":"JVNotificationsController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"notifications","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"JVNotificationsController","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments","value":[{"kind":"identifier","text":"JVNotificationsController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title","value":"notifications"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments","op":"replace","value":[{"kind":"identifier","text":"notifications"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace","value":"Jivo"},{"value":[{"kind":"identifier","text":"Jivo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"}]}]}