{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","interfaceLanguage":"swift"},"sections":[],"metadata":{"navigatorTitle":[{"text":"session","kind":"identifier"}],"roleHeading":"Type Property","symbolKind":"property","modules":[{"name":"JivoSDK"}],"role":"symbol","externalID":"c:@CM@JivoSDK@objc(cs)Jivo(cpy)session","title":"session","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController","text":"JVSessionController"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/jivosdk\/jivo\/session"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivo\/session"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController","kind":"typeIdentifier","text":"JVSessionController","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"For details, see ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","isActive":true,"type":"reference"},{"text":" reference","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Namespace for managing user session"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController":{"url":"\/documentation\/jivosdk\/jvsessioncontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVSessionController","kind":"identifier"}],"title":"JVSessionController","abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session"},{"text":" namespace for managing user session","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","type":"topic","navigatorTitle":[{"text":"JVSessionController","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","type":"topic","url":"\/documentation\/jivosdk","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"role":"symbol","abstract":[{"text":"Namespace for managing user session","type":"text"}],"kind":"symbol","type":"topic","title":"session","url":"\/documentation\/jivosdk\/jivo\/session","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","navigatorTitle":[{"kind":"identifier","text":"session"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"session"},{"text":": ","kind":"text"},{"text":"JVSessionController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController","kind":"typeIdentifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","title":"Jivo","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"type":"topic","url":"\/documentation\/jivosdk\/jivo","navigatorTitle":[{"text":"Jivo","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"session","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"session"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","kind":"typeIdentifier","text":"JVSessionController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController"},{"kind":"text","text":" * "},{"kind":"identifier","text":"session"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/title","value":"JVSessionController"},{"value":[{"text":"JVSessionController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title","op":"replace","value":"session"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments","value":[{"text":"session","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}]}]}]}