{"metadata":{"title":"delegate","roleHeading":"Instance Property","platforms":[],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(pl)JivoSDKSessionDelegate","text":"JivoSDKSessionDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKSession(py)delegate","modules":[{"name":"JivoSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdksession\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdksession\/delegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/delegate"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(delegate) "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionDelegate","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JivoSDKSessionDelegate","text":"JivoSDKSessionDelegate"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/delegate":{"title":"delegate","url":"\/documentation\/jivosdk\/jivosdksession\/delegate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"text":"JivoSDKSessionDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JivoSDKSessionDelegate"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"deprecated":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/delegate","kind":"symbol","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionDelegate":{"title":"JivoSDKSessionDelegate","url":"\/documentation\/jivosdk\/jivosdksessiondelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"JivoSDKSessionDelegate","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"JivoSDKSessionDelegate","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionDelegate","type":"topic","kind":"symbol","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JivoSDKSession","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/jivosdk\/jivosdksession","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","title":"JivoSDKSession","role":"symbol","type":"topic","navigatorTitle":[{"text":"JivoSDKSession","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"delegate","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"id<JivoSDKSessionDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@JivoSDK@objc(pl)JivoSDKSessionDelegate"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1delegate\/title","op":"replace","value":"delegate"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1delegate\/fragments"},{"value":"JivoSDKSessionDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionDelegate\/fragments","value":[{"kind":"identifier","text":"JivoSDKSessionDelegate"}]},{"value":"JivoSDKSession","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"JivoSDKSession"}]}]}]}