{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[],"navigatorTitle":[{"kind":"identifier","text":"setClientInfo:"}],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKSession(im)setClientInfo:","modules":[{"name":"JivoSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setClientInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionClientInfo","text":"JivoSDKSessionClientInfo"},{"text":"?)","kind":"text"}],"symbolKind":"method","title":"setClientInfo(_:)","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(setClientInfo:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setClientInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo","kind":"typeIdentifier","text":"JivoSDKSessionClientInfo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionClientInfo"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdksession\/setclientinfo(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdksession\/setclientinfo(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setClientInfo(_:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","url":"\/documentation\/jivosdk\/jivosdksession","abstract":[],"deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKSession"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JivoSDKSession"}],"title":"JivoSDKSession","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","url":"\/documentation\/jivosdk","title":"JivoSDK","type":"topic","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/setClientInfo(_:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setClientInfo(_:)","url":"\/documentation\/jivosdk\/jivosdksession\/setclientinfo(_:)","abstract":[],"deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setClientInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JivoSDKSessionClientInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionClientInfo"},{"kind":"text","text":"?)"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setClientInfo:"}],"title":"setClientInfo(_:)","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionClientInfo":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo","url":"\/documentation\/jivosdk\/jivosdksessionclientinfo","abstract":[],"deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JivoSDKSessionClientInfo","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"JivoSDKSessionClientInfo","kind":"identifier"}],"title":"JivoSDKSessionClientInfo","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setClientInfo:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setClientInfo:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setClientInfo:","kind":"identifier"},{"kind":"text","text":"("},{"text":"JivoSDKSessionClientInfo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionClientInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"JivoSDKSession","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/fragments","value":[{"kind":"identifier","text":"JivoSDKSession"}],"op":"replace"},{"value":"setClientInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1setClientInfo(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1setClientInfo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setClientInfo:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionClientInfo\/title","value":"JivoSDKSessionClientInfo","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionClientInfo\/fragments","value":[{"text":"JivoSDKSessionClientInfo","kind":"identifier"}],"op":"replace"}]}]}