{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setCustomData(fields:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(setCustomData:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomData"},{"kind":"text","text":"("},{"text":"fields","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionCustomDataField","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionCustomDataField","kind":"typeIdentifier","text":"JivoSDKSessionCustomDataField"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdksession\/setcustomdata(fields:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdksession\/setcustomdata(fields:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setCustomData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionCustomDataField","text":"JivoSDKSessionCustomDataField","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"modules":[{"name":"JivoSDK"}],"roleHeading":"Instance Method","title":"setCustomData(fields:)","role":"symbol","platforms":[],"symbolKind":"method","navigatorTitle":[{"text":"setCustomData:","kind":"identifier"}],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKSession(im)setCustomData:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionCustomDataField":{"title":"JivoSDKSessionCustomDataField","url":"\/documentation\/jivosdk\/jivosdksessioncustomdatafield","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JivoSDKSessionCustomDataField","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionCustomDataField","navigatorTitle":[{"text":"JivoSDKSessionCustomDataField","kind":"identifier"}],"deprecated":true,"abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/setCustomData(fields:)":{"navigatorTitle":[{"text":"setCustomData:","kind":"identifier"}],"deprecated":true,"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setCustomData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fields"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"JivoSDKSessionCustomDataField","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionCustomDataField"},{"kind":"text","text":"])"}],"abstract":[],"url":"\/documentation\/jivosdk\/jivosdksession\/setcustomdata(fields:)","title":"setCustomData(fields:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setCustomData(fields:)","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession":{"navigatorTitle":[{"text":"JivoSDKSession","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdksession","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKSession","kind":"identifier"}],"title":"JivoSDKSession","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","deprecated":true,"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setCustomData:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"setCustomData:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"setCustomData:"},{"kind":"text","text":"("},{"text":"NSArray<JivoSDKSessionCustomDataField *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fields"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionCustomDataField\/title","value":"JivoSDKSessionCustomDataField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionCustomDataField\/fragments","value":[{"text":"JivoSDKSessionCustomDataField","kind":"identifier"}]},{"value":"setCustomData:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1setCustomData(fields:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"setCustomData:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1setCustomData(fields:)\/fragments"},{"value":"JivoSDKSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/fragments","value":[{"text":"JivoSDKSession","kind":"identifier"}],"op":"replace"}]}]}