{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setPreferredServer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JivoSDKSessionServer","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKSessionServer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":[],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKSession(im)setPreferredServer:","symbolKind":"method","modules":[{"name":"JivoSDK"}],"title":"setPreferredServer(_:)","navigatorTitle":[{"kind":"identifier","text":"setPreferredServer:"}],"role":"symbol","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession"]]},"variants":[{"paths":["\/documentation\/jivosdk\/jivosdksession\/setpreferredserver(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdksession\/setpreferredserver(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setPreferredServer(_:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(setPreferredServer:) "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPreferredServer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"server","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKSessionServer","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer","text":"JivoSDKSessionServer"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/setPreferredServer(_:)":{"title":"setPreferredServer(_:)","kind":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setPreferredServer(_:)","url":"\/documentation\/jivosdk\/jivosdksession\/setpreferredserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPreferredServer"},{"text":"(","kind":"text"},{"text":"JivoSDKSessionServer","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKSessionServer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setPreferredServer:","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer":{"title":"JivoSDKSessionServer","kind":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer","url":"\/documentation\/jivosdk\/jivosdksessionserver","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKSessionServer","kind":"identifier"}],"navigatorTitle":[{"text":"JivoSDKSessionServer","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession":{"navigatorTitle":[{"text":"JivoSDKSession","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdksession","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKSession","kind":"identifier"}],"title":"JivoSDKSession","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","deprecated":true,"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"setPreferredServer:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPreferredServer:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setPreferredServer:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKSessionServer","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer","text":"JivoSDKSessionServer"},{"kind":"text","text":") "},{"text":"server","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1setPreferredServer(_:)\/title","value":"setPreferredServer:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1setPreferredServer(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setPreferredServer:","kind":"identifier"}],"op":"replace"},{"value":"JivoSDKSessionServer","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer\/fragments","value":[{"kind":"identifier","text":"JivoSDKSessionServer"}]},{"value":"JivoSDKSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/fragments","value":[{"kind":"identifier","text":"JivoSDKSession"}]}]}]}