{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateCustomData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionCustomData","text":"JivoSDKSessionCustomData"},{"text":"?)","kind":"text"}],"role":"symbol","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKSession(im)updateCustomData:","modules":[{"name":"JivoSDK"}],"platforms":[],"roleHeading":"Instance Method","title":"updateCustomData(_:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"updateCustomData:"}]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Renamed to setClientInfo:","type":"text"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/updateCustomData(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdksession\/updatecustomdata(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdksession\/updatecustomdata(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(updateCustomData:) "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updateCustomData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"text":": ","kind":"text"},{"text":"JivoSDKSessionCustomData","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionCustomData","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionCustomData","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionCustomData":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JivoSDKSessionCustomData","kind":"identifier"}],"role":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/jivosdk\/jivosdksessioncustomdata","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionCustomData","kind":"symbol","abstract":[],"title":"JivoSDKSessionCustomData","navigatorTitle":[{"text":"JivoSDKSessionCustomData","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/updateCustomData(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateCustomData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionCustomData","text":"JivoSDKSessionCustomData"},{"text":"?)","kind":"text"}],"role":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/jivosdk\/jivosdksession\/updatecustomdata(_:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/updateCustomData(_:)","kind":"symbol","abstract":[],"title":"updateCustomData(_:)","navigatorTitle":[{"text":"updateCustomData:","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKSession"}],"url":"\/documentation\/jivosdk\/jivosdksession","deprecated":true,"role":"symbol","title":"JivoSDKSession","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","navigatorTitle":[{"kind":"identifier","text":"JivoSDKSession"}],"kind":"symbol","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"updateCustomData:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateCustomData:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"updateCustomData:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JivoSDKSessionCustomData","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionCustomData","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionCustomData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"JivoSDKSessionCustomData","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionCustomData\/title","op":"replace"},{"value":[{"text":"JivoSDKSessionCustomData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionCustomData\/fragments"},{"op":"replace","value":"updateCustomData:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1updateCustomData(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1updateCustomData(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateCustomData:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/title","value":"JivoSDKSession"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/fragments","value":[{"text":"JivoSDKSession","kind":"identifier"}]}]}]}