{"topicSections":[{"title":"Setup","anchor":"Setup","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_channel_setup","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_project_config","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_swiftpm_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/native_usage_basics"],"anchor":"For-native-project","title":"For native project"},{"title":"For React Native project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_module_bridge","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/react_usage_basics"],"anchor":"For-React-Native-project"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_plugin_bridge","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/flutter_usage_basics"],"anchor":"For-Flutter-project","title":"For Flutter project"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionCustomDataField","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"],"title":"Classes","anchor":"Classes","generated":true},{"anchor":"Protocols","title":"Protocols","generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate"]},{"title":"Type Aliases","generated":true,"anchor":"Type-Aliases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientContactInfo","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientCustomDataField","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsOptionsOutput","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsOptionsResolver"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientIdentity","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingExportStatus","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalRecordBehavior","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayMenu","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayScreenPresentation","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionHandleError","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer"],"anchor":"Enumerations","title":"Enumerations","generated":true},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Swift","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/UIKit","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/UserNotifications"],"title":"Extended Modules","anchor":"Extended-Modules","generated":true}],"sections":[],"metadata":{"modules":[{"name":"JivoSDK"}],"externalID":"JivoSDK","symbolKind":"module","role":"collection","title":"JivoSDK","roleHeading":"Framework"},"kind":"symbol","hierarchy":{"paths":[[]]},"primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Jivo Mobile SDK (hereinafter referred to as SDK) is the mobile framework for integrating Jivo Business Chat into your app","type":"text"}]},{"content":[{"inlineContent":[{"text":"May not work properly under VPN","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note","name":"Note"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"variants":[{"paths":["\/documentation\/jivosdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDebuggingController"}],"navigatorTitle":[{"text":"JVDebuggingController","kind":"identifier"}],"type":"topic","title":"JVDebuggingController","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging"},{"text":" namespace for SDK debugging","type":"text"}],"url":"\/documentation\/jivosdk\/jvdebuggingcontroller"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/common_user_token":{"url":"\/documentation\/jivosdk\/common_user_token","abstract":[{"type":"text","text":"Required for keeping chat history alive"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token","type":"topic","title":"User Token and JWT","role":"article","kind":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/react_pod_link":{"type":"topic","title":"Link to SDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_pod_link","url":"\/documentation\/jivosdk\/react_pod_link","abstract":[{"type":"text","text":"Using CocoaPods"}],"role":"article","kind":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","kind":"symbol","abstract":[],"url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayMenu":{"title":"JVDisplayMenu","abstract":[{"type":"text","text":"Menus available for customization"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayMenu"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayMenu","url":"\/documentation\/jivosdk\/jvdisplaymenu","role":"symbol","navigatorTitle":[{"text":"JVDisplayMenu","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppBannerPresentingDelegate":{"navigatorTitle":[{"text":"JVAppBannerPresentingDelegate","kind":"identifier"}],"type":"topic","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jvappbannerpresentingdelegate","title":"JVAppBannerPresentingDelegate","abstract":[{"text":"Determines a way incoming notifications gets displayed","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsOptionsOutput":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsOptionsOutput","abstract":[{"text":"Transfers UNNotificationPresentationOptions into system for its internal needs","type":"text"}],"title":"JVNotificationsOptionsOutput","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsOptionsOutput","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvnotificationsoptionsoutput","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsOptionsOutput"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/react_module_bridge":{"abstract":[{"text":"JavaScript Bridge","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_module_bridge","type":"topic","title":"Module Bridge","url":"\/documentation\/jivosdk\/react_module_bridge","kind":"article","role":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/UIKit":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/UIKit","url":"\/documentation\/jivosdk\/uikit","abstract":[],"title":"UIKit","kind":"symbol","type":"topic","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKVersionNumber":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKVersionNumber","role":"symbol","title":"JivoSDKVersionNumber","url":"\/documentation\/jivosdk\/jivosdkversionnumber","type":"topic","abstract":[{"type":"text","text":"Project version number for JivoSDK."}],"kind":"symbol","fragments":[{"kind":"identifier","text":"JivoSDKVersionNumber"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClientContactInfo":{"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"JVClientContactInfo","kind":"identifier"}],"title":"JVClientContactInfo","navigatorTitle":[{"kind":"identifier","text":"JVClientContactInfo"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientContactInfo","url":"\/documentation\/jivosdk\/jvclientcontactinfo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/native_api_ref":{"abstract":[{"type":"text","text":"Swift API"}],"url":"\/documentation\/jivosdk\/native_api_ref","kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_api_ref","title":"API Reference","type":"topic","role":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton":{"abstract":[{"text":"Close Button look","type":"text"}],"navigatorTitle":[{"text":"JVDisplayCloseButton","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayCloseButton"}],"kind":"symbol","title":"JVDisplayCloseButton","url":"\/documentation\/jivosdk\/jvdisplayclosebutton","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKVersionString":{"url":"\/documentation\/jivosdk\/jivosdkversionstring","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKVersionString","fragments":[{"kind":"identifier","text":"JivoSDKVersionString"}],"type":"topic","title":"JivoSDKVersionString","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Project version string for JivoSDK."}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/react_api_ref":{"title":"API Reference","abstract":[{"text":"JavaScript API","type":"text"}],"url":"\/documentation\/jivosdk\/react_api_ref","role":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref","kind":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"navigatorTitle":[{"text":"notifications","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"notifications","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","text":"JVNotificationsController","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Namespace for Push Notifications"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","kind":"symbol","title":"notifications","url":"\/documentation\/jivosdk\/jivo\/notifications","role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/native_swiftpm_link":{"abstract":[{"type":"text","text":"Primary option"}],"url":"\/documentation\/jivosdk\/native_swiftpm_link","kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_swiftpm_link","role":"article","title":"Link to SDK using SwiftPM","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionDelegate":{"abstract":[{"type":"text","text":"Interface to handle session events,"},{"type":"text","text":" "},{"type":"text","text":"relates to "},{"code":"Jivo.session","type":"codeVoice"},{"type":"text","text":" namespace"}],"url":"\/documentation\/jivosdk\/jvsessiondelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate","kind":"symbol","title":"JVSessionDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVSessionDelegate"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVSessionDelegate"}]},"doc://org.cocoapods.JivoSDK/tutorials/JivoSDK/flutter_usage_basics":{"abstract":[{"type":"text","text":"Some scenarios of how to use SDK"}],"url":"\/tutorials\/jivosdk\/flutter_usage_basics","identifier":"doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/flutter_usage_basics","title":"Basic usage","kind":"project","role":"project","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","title":"Jivo","kind":"symbol","url":"\/documentation\/jivosdk\/jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient","navigatorTitle":[{"kind":"identifier","text":"JVClient"}],"abstract":[],"url":"\/documentation\/jivosdk\/jvclient","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVClient","kind":"identifier"}],"title":"JVClient","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionContactInfo":{"navigatorTitle":[{"kind":"identifier","text":"JVSessionContactInfo"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVSessionContactInfo"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo","abstract":[{"type":"text","text":"Contact Info for user"}],"type":"topic","role":"symbol","title":"JVSessionContactInfo","url":"\/documentation\/jivosdk\/jvsessioncontactinfo"},"doc://org.cocoapods.JivoSDK/tutorials/JivoSDK/react_usage_basics":{"title":"Basic usage","abstract":[{"text":"Some scenarios of how to use SDK","type":"text"}],"url":"\/tutorials\/jivosdk\/react_usage_basics","role":"project","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/react_usage_basics","kind":"project"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/flutter_api_ref":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","type":"topic","kind":"article","title":"API Reference","abstract":[{"type":"text","text":"Dart API"}],"url":"\/documentation\/jivosdk\/flutter_api_ref","role":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsOptionsResolver":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsOptionsResolver","abstract":[{"type":"text","text":"Determines UNNotificationPresentationOptions, based on event parameters"}],"title":"JVNotificationsOptionsResolver","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsOptionsResolver"}],"url":"\/documentation\/jivosdk\/jvnotificationsoptionsresolver","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsOptionsResolver"}],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/common_project_config":{"role":"article","kind":"article","url":"\/documentation\/jivosdk\/common_project_config","abstract":[{"text":"Permissions and Push Notifications","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_project_config","type":"topic","title":"Setup your Project"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalRecordBehavior":{"url":"\/documentation\/jivosdk\/jvdebuggingoriginalrecordbehavior","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalRecordBehavior","title":"JVDebuggingOriginalRecordBehavior","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDebuggingOriginalRecordBehavior"}],"navigatorTitle":[{"kind":"identifier","text":"JVDebuggingOriginalRecordBehavior"}],"abstract":[{"type":"text","text":"SDK behavior for recording entries"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/common_channel_setup":{"title":"Create a Channel","role":"article","type":"topic","abstract":[{"type":"text","text":"Mobile SDK"}],"url":"\/documentation\/jivosdk\/common_channel_setup","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_channel_setup","kind":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClientCustomDataField":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientCustomDataField","navigatorTitle":[{"kind":"identifier","text":"JVClientCustomDataField"}],"url":"\/documentation\/jivosdk\/jvclientcustomdatafield","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVClientCustomDataField","kind":"identifier"}],"title":"JVClientCustomDataField","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"url":"\/documentation\/jivosdk\/jivo\/display","abstract":[{"type":"text","text":"Namespace for SDK displaying"}],"navigatorTitle":[{"text":"display","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","type":"topic","title":"display","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"display"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController","text":"JVDisplayController","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.JivoSDK/tutorials/JivoSDK/native_usage_basics":{"title":"Basic usage","abstract":[{"type":"text","text":"Some scenarios of how to use SDK"}],"url":"\/tutorials\/jivosdk\/native_usage_basics","role":"project","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/native_usage_basics","kind":"project"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/flutter_pod_link":{"role":"article","title":"Link to SDK","abstract":[{"type":"text","text":"Using CocoaPods"}],"url":"\/documentation\/jivosdk\/flutter_pod_link","kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_pod_link","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionHandle":{"title":"JVSessionHandle","role":"symbol","fragments":[{"kind":"identifier","text":"JVSessionHandle"}],"type":"topic","abstract":[],"url":"\/documentation\/jivosdk\/jvsessionhandle","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionHandle","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer":{"abstract":[{"text":"Primary Jivo servers, by geographical region","type":"text"}],"navigatorTitle":[{"text":"JVSessionServer","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVSessionServer"}],"kind":"symbol","title":"JVSessionServer","url":"\/documentation\/jivosdk\/jvsessionserver","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/native_pod_link":{"role":"article","kind":"article","abstract":[{"text":"Alternative option","type":"text"}],"url":"\/documentation\/jivosdk\/native_pod_link","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_pod_link","type":"topic","title":"Link to SDK using CocoaPods"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionCustomDataField":{"navigatorTitle":[{"text":"JVSessionCustomDataField","kind":"identifier"}],"abstract":[{"type":"text","text":"Custom Data Field for user"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVSessionCustomDataField","kind":"identifier"}],"title":"JVSessionCustomDataField","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionCustomDataField","url":"\/documentation\/jivosdk\/jvsessioncustomdatafield","role":"symbol","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugging"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController","text":"JVDebuggingController","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"debugging","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","abstract":[{"type":"text","text":"Namespace for SDK debugging"}],"type":"topic","url":"\/documentation\/jivosdk\/jivo\/debugging","title":"debugging","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Swift":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Swift","url":"\/documentation\/jivosdk\/swift","title":"Swift"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsPermissionAskingMoment":{"abstract":[{"text":"Moment to request access to Push Notifications","type":"text"}],"role":"symbol","type":"topic","title":"JVNotificationsPermissionAskingMoment","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVNotificationsPermissionAskingMoment","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVNotificationsPermissionAskingMoment"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment","kind":"symbol","url":"\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController":{"title":"JVSessionController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVSessionController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVSessionController"}],"abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"text":".","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session"},{"type":"text","text":" namespace for managing user session"}],"url":"\/documentation\/jivosdk\/jvsessioncontroller"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"url":"\/documentation\/jivosdk\/jivo\/session","abstract":[{"type":"text","text":"Namespace for managing user session"}],"navigatorTitle":[{"text":"session","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","type":"topic","title":"session","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"session"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController","text":"JVSessionController","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/flutter_plugin_bridge":{"title":"Plugin Bridge","role":"article","kind":"article","url":"\/documentation\/jivosdk\/flutter_plugin_bridge","type":"topic","abstract":[{"type":"text","text":"Dart Bridge"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_plugin_bridge"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayScreenPresentation":{"navigatorTitle":[{"text":"JVDisplayScreenPresentation","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDisplayScreenPresentation","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayscreenpresentation","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayScreenPresentation","type":"topic","kind":"symbol","abstract":[],"title":"JVDisplayScreenPresentation","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate":{"url":"\/documentation\/jivosdk\/jvappdelegate","navigatorTitle":[{"text":"JVAppDelegate","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVAppDelegate","kind":"identifier"}],"type":"topic","abstract":[{"text":"Feel free to use this class as parent for your own App Delegate, for easier SDK integration","type":"text"}],"deprecated":true,"kind":"symbol","title":"JVAppDelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNavigationContainer":{"abstract":[{"text":"Descendent of UINavigationController for UI hierarchy","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVNavigationContainer","kind":"identifier"}],"navigatorTitle":[{"text":"JVNavigationContainer","kind":"identifier"}],"title":"JVNavigationContainer","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvnavigationcontainer"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"title":"JVDisplayElement","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVDisplayElement","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayelement","abstract":[{"text":"UI elements available for customization","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","type":"topic","navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"navigatorTitle":[{"kind":"identifier","text":"JVNotificationsController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsController","kind":"identifier"}],"abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","isActive":true},{"type":"text","text":" namespace for Push Notifications"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","kind":"symbol","title":"JVNotificationsController","url":"\/documentation\/jivosdk\/jvnotificationscontroller","role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionHandleError":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVSessionHandleError"}],"title":"JVSessionHandleError","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"JVSessionHandleError","kind":"identifier"}],"type":"topic","url":"\/documentation\/jivosdk\/jvsessionhandleerror","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionHandleError"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent":{"navigatorTitle":[{"text":"JVNotificationsEvent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsEvent"}],"url":"\/documentation\/jivosdk\/jvnotificationsevent","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","type":"topic","kind":"symbol","abstract":[],"title":"JVNotificationsEvent","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","url":"\/documentation\/jivosdk\/jvnotificationstarget","type":"topic","kind":"symbol","abstract":[{"text":"Target subsystem of Push Notification","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVNotificationsTarget","kind":"identifier"}],"title":"JVNotificationsTarget","navigatorTitle":[{"text":"JVNotificationsTarget","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClientIdentity":{"url":"\/documentation\/jivosdk\/jvclientidentity","abstract":[],"navigatorTitle":[{"text":"JVClientIdentity","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientIdentity","type":"topic","title":"JVClientIdentity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVClientIdentity"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingLevel":{"navigatorTitle":[{"text":"JVDebuggingLevel","kind":"identifier"}],"abstract":[{"type":"text","text":"Level of logging verbosity,"},{"type":"text","text":" "},{"type":"text","text":"relates to "},{"type":"codeVoice","code":"Jivo.debugging"},{"type":"text","text":" namespace"}],"role":"symbol","title":"JVDebuggingLevel","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDebuggingLevel"}],"url":"\/documentation\/jivosdk\/jvdebugginglevel","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory":{"url":"\/documentation\/jivosdk\/jvnotificationscategory","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsCategory"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Event category of notification"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory","role":"symbol","title":"JVNotificationsCategory","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsCategory"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingExportStatus":{"abstract":[{"text":"Determines how logs archiving operation was completed","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVDebuggingExportStatus","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingExportStatus","type":"topic","navigatorTitle":[{"text":"JVDebuggingExportStatus","kind":"identifier"}],"title":"JVDebuggingExportStatus","url":"\/documentation\/jivosdk\/jvdebuggingexportstatus","kind":"symbol","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/UserNotifications":{"abstract":[],"role":"collection","kind":"symbol","title":"UserNotifications","url":"\/documentation\/jivosdk\/usernotifications","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/UserNotifications","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"title":"JVDisplayController","kind":"symbol","role":"symbol","abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","isActive":true,"type":"reference"},{"text":" namespace for SDK displaying","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVDisplayController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayController"}],"url":"\/documentation\/jivosdk\/jvdisplaycontroller","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_channel_setup","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_project_config","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token"],"anchor":"Setup","title":"Setup"},{"anchor":"For-native-project","title":"For native project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_swiftpm_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/native_usage_basics"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_module_bridge","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/react_usage_basics"],"anchor":"For-React-Native-project","title":"For React Native project"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_plugin_bridge","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/flutter_usage_basics"],"title":"For Flutter project","anchor":"For-Flutter-project"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionCustomDataField","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionHandle","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"],"title":"Classes","anchor":"Classes","generated":true},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate"],"anchor":"Protocols","generated":true},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKVersionNumber","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKVersionString"],"generated":true,"title":"Variables","anchor":"Variables"},{"generated":true,"anchor":"Enumerations","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget"],"title":"Enumerations"}],"op":"replace"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":"JVDebuggingController","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments","value":[{"text":"JVDebuggingController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/navigatorTitle","value":[{"kind":"identifier","text":"JVDebuggingController"}],"op":"replace"},{"value":"JVAppBannerPresentingDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/title"},{"value":[{"text":"JVAppBannerPresentingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title","value":"notifications","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments","op":"replace","value":[{"text":"notifications","kind":"identifier"}]},{"value":"JVSessionDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/title"},{"op":"replace","value":[{"text":"JVSessionDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"JVSessionDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/title","value":"JVClient","op":"replace"},{"value":[{"kind":"identifier","text":"JVClient"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/navigatorTitle","value":[{"text":"JVClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo\/title","op":"replace","value":"JVSessionContactInfo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo\/fragments","value":[{"kind":"identifier","text":"JVSessionContactInfo"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo\/navigatorTitle","value":[{"text":"JVSessionContactInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title","value":"display","op":"replace"},{"value":[{"text":"display","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField\/title","value":"JVSessionCustomDataField"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField\/fragments","value":[{"text":"JVSessionCustomDataField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField\/navigatorTitle","op":"replace","value":[{"text":"JVSessionCustomDataField","kind":"identifier"}]},{"op":"replace","value":"debugging","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/fragments","op":"replace","value":[{"kind":"identifier","text":"debugging"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/title","op":"replace","value":"JVSessionController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/fragments","op":"replace","value":[{"text":"JVSessionController","kind":"identifier"}]},{"value":[{"text":"JVSessionController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/navigatorTitle","op":"replace"},{"value":"session","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title"},{"value":[{"text":"session","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/title","op":"replace","value":"JVAppDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/fragments","value":[{"kind":"identifier","text":"JVAppDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/navigatorTitle","value":[{"text":"JVAppDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNavigationContainer\/title","value":"JVNavigationContainer"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNavigationContainer\/fragments","op":"replace","value":[{"text":"JVNavigationContainer","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"JVNavigationContainer"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNavigationContainer\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title","op":"replace","value":"JVNotificationsController"},{"value":[{"text":"JVNotificationsController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/navigatorTitle","value":[{"text":"JVNotificationsController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/title","value":"JVNotificationsEvent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/fragments","value":[{"kind":"identifier","text":"JVNotificationsEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/navigatorTitle","value":[{"text":"JVNotificationsEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/title","value":"JVNotificationsTarget"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/fragments","op":"replace","value":[{"text":"JVNotificationsTarget","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/navigatorTitle","value":[{"kind":"identifier","text":"JVNotificationsTarget"}],"op":"replace"},{"op":"replace","value":"JVNotificationsCategory","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/fragments","value":[{"kind":"identifier","text":"JVNotificationsCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/navigatorTitle","value":[{"text":"JVNotificationsCategory","kind":"identifier"}]},{"value":"JVDisplayController","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title","op":"replace"},{"value":[{"text":"JVDisplayController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/navigatorTitle","value":[{"kind":"identifier","text":"JVDisplayController"}]}]}]}