{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/jivosdk\/jivosdkdebugging\/archivelogs(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdkdebugging\/archivelogs(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(archiveLogsWithCompletionHandler:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"archiveLogs"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"JivoSDKArchivingStatus","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKArchivingStatus","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"archiveLogs","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"JivoSDKArchivingStatus","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKArchivingStatus"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging(im)archiveLogsWithCompletionHandler:","modules":[{"name":"JivoSDK"}],"platforms":[],"roleHeading":"Instance Method","title":"archiveLogs(completion:)","navigatorTitle":[{"kind":"identifier","text":"archiveLogsWithCompletionHandler:"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging\/archiveLogs(completion:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","url":"\/documentation\/jivosdk","kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebugging":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/jivosdk\/jivosdkdebugging","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKDebugging"}],"title":"JivoSDKDebugging","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging","navigatorTitle":[{"kind":"identifier","text":"JivoSDKDebugging"}],"deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus":{"navigatorTitle":[{"kind":"identifier","text":"JivoSDKArchivingStatus"}],"url":"\/documentation\/jivosdk\/jivosdkarchivingstatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKArchivingStatus","kind":"identifier"}],"role":"symbol","abstract":[],"deprecated":true,"title":"JivoSDKArchivingStatus","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebugging/archiveLogs(completion:)":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/jivosdk\/jivosdkdebugging\/archivelogs(completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"archiveLogs"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"JivoSDKArchivingStatus","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKArchivingStatus","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"title":"archiveLogs(completion:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging\/archiveLogs(completion:)","navigatorTitle":[{"text":"archiveLogsWithCompletionHandler:","kind":"identifier"}],"deprecated":true}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"archiveLogsWithCompletionHandler:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"archiveLogsWithCompletionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"archiveLogsWithCompletionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JivoSDKArchivingStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKArchivingStatus","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}]}]}},{"value":"JivoSDKDebugging","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging\/fragments","value":[{"kind":"identifier","text":"JivoSDKDebugging"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus\/title","op":"replace","value":"JivoSDKArchivingStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus\/fragments","value":[{"kind":"identifier","text":"JivoSDKArchivingStatus"}]},{"op":"replace","value":"archiveLogsWithCompletionHandler:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging~1archiveLogs(completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"archiveLogsWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging~1archiveLogs(completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}