{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkdebugging\/level"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkdebugging\/level"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(level) ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"level","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKDebuggingLevel","text":"JivoSDKDebuggingLevel","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging\/level"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"level","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKDebuggingLevel","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKDebuggingLevel"}],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging(py)level","navigatorTitle":[{"kind":"identifier","text":"level"}],"title":"level","roleHeading":"Instance Property","platforms":[],"modules":[{"name":"JivoSDK"}],"symbolKind":"property"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebugging":{"navigatorTitle":[{"text":"JivoSDKDebugging","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JivoSDKDebugging","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging","type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdkdebugging","title":"JivoSDKDebugging","abstract":[],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebugging/level":{"navigatorTitle":[{"text":"level","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKDebuggingLevel","text":"JivoSDKDebuggingLevel","kind":"typeIdentifier"}],"deprecated":true,"type":"topic","url":"\/documentation\/jivosdk\/jivosdkdebugging\/level","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging\/level","abstract":[],"title":"level","role":"symbol","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebuggingLevel":{"navigatorTitle":[{"text":"JivoSDKDebuggingLevel","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKDebuggingLevel"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel","type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdkdebugginglevel","title":"JivoSDKDebuggingLevel","abstract":[],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","type":"topic","url":"\/documentation\/jivosdk","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"level","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"level"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKDebuggingLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKDebuggingLevel","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel"},{"kind":"text","text":" "},{"text":"level","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"JivoSDKDebugging","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging\/fragments","value":[{"text":"JivoSDKDebugging","kind":"identifier"}]},{"value":"level","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging~1level\/title"},{"value":[{"text":"level","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging~1level\/fragments"},{"op":"replace","value":"JivoSDKDebuggingLevel","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel\/fragments","op":"replace","value":[{"kind":"identifier","text":"JivoSDKDebuggingLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}