{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/full","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkdebugginglevel\/full"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkdebugginglevel\/full"]}],"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@JivoSDK@E@JivoSDKDebuggingLevel@JivoSDKDebuggingLevelFull","modules":[{"name":"JivoSDK"}],"platforms":[],"title":"JivoSDKDebuggingLevel.full","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"full"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"JivoSDKDebuggingLevelFull"}]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebuggingLevel/full":{"navigatorTitle":[{"text":"JivoSDKDebuggingLevelFull","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/jivosdk\/jivosdkdebugginglevel\/full","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/full","title":"JivoSDKDebuggingLevel.full","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebuggingLevel":{"navigatorTitle":[{"text":"JivoSDKDebuggingLevel","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/jivosdk\/jivosdkdebugginglevel","abstract":[],"type":"topic","title":"JivoSDKDebuggingLevel","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKDebuggingLevel"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","abstract":[],"url":"\/documentation\/jivosdk","title":"JivoSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"JivoSDKDebuggingLevelFull","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JivoSDKDebuggingLevelFull"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"JivoSDKDebuggingLevelFull","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel~1full\/title","value":"JivoSDKDebuggingLevelFull"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel~1full\/fragments","value":[{"text":"JivoSDKDebuggingLevelFull","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel\/title","op":"replace","value":"JivoSDKDebuggingLevel"},{"value":[{"text":"JivoSDKDebuggingLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}