{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkdebugginglevel\/silent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkdebugginglevel\/silent"]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/silent","interfaceLanguage":"swift"},"metadata":{"platforms":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"silent"}],"externalID":"c:@M@JivoSDK@E@JivoSDKDebuggingLevel@JivoSDKDebuggingLevelSilent","roleHeading":"Case","title":"JivoSDKDebuggingLevel.silent","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKDebuggingLevelSilent"}],"role":"symbol","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"silent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","type":"topic","role":"collection","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebuggingLevel/silent":{"role":"symbol","title":"JivoSDKDebuggingLevel.silent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JivoSDKDebuggingLevelSilent"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"silent","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/silent","type":"topic","abstract":[],"url":"\/documentation\/jivosdk\/jivosdkdebugginglevel\/silent"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebuggingLevel":{"type":"topic","url":"\/documentation\/jivosdk\/jivosdkdebugginglevel","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKDebuggingLevel","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel","role":"symbol","title":"JivoSDKDebuggingLevel","navigatorTitle":[{"text":"JivoSDKDebuggingLevel","kind":"identifier"}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"JivoSDKDebuggingLevelSilent","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JivoSDKDebuggingLevelSilent","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"JivoSDKDebuggingLevelSilent"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel~1silent\/title","op":"replace","value":"JivoSDKDebuggingLevelSilent"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel~1silent\/fragments","op":"replace","value":[{"kind":"identifier","text":"JivoSDKDebuggingLevelSilent"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel\/title","value":"JivoSDKDebuggingLevel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel\/fragments","value":[{"text":"JivoSDKDebuggingLevel","kind":"identifier"}]}]}]}