{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"asia"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdksessionserver\/asia"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdksessionserver\/asia"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/asia","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"JivoSDKSessionServerAsia"}],"role":"symbol","title":"JivoSDKSessionServer.asia","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"asia"}],"symbolKind":"case","externalID":"c:@M@JivoSDK@E@JivoSDKSessionServer@JivoSDKSessionServerAsia","modules":[{"name":"JivoSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer":{"deprecated":true,"role":"symbol","title":"JivoSDKSessionServer","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKSessionServer"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JivoSDKSessionServer"}],"url":"\/documentation\/jivosdk\/jivosdksessionserver"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer/asia":{"deprecated":true,"role":"symbol","title":"JivoSDKSessionServer.asia","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"asia"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/asia","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JivoSDKSessionServerAsia"}],"url":"\/documentation\/jivosdk\/jivosdksessionserver\/asia"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"JivoSDKSessionServerAsia"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JivoSDKSessionServerAsia"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"JivoSDKSessionServerAsia"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer\/title","value":"JivoSDKSessionServer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer\/fragments","value":[{"kind":"identifier","text":"JivoSDKSessionServer"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1asia\/title","value":"JivoSDKSessionServerAsia"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1asia\/fragments","value":[{"kind":"identifier","text":"JivoSDKSessionServerAsia"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}