{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/handleRemoteNotification(containingUserInfo:)"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdknotifications\/handleremotenotification(containinguserinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdknotifications\/handleremotenotification(containinguserinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications"]]},"metadata":{"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications(im)handleRemoteNotificationContainingUserInfo:","roleHeading":"Instance Method","modules":[{"name":"JivoSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleRemoteNotification"},{"kind":"text","text":"("},{"text":"containingUserInfo","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"handleRemoteNotificationContainingUserInfo:","kind":"identifier"}],"platforms":[],"title":"handleRemoteNotification(containingUserInfo:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(handleRemoteNotificationContainingUserInfo:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleRemoteNotification","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"containingUserInfo"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"userInfo"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","type":"topic","url":"\/documentation\/jivosdk","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications":{"type":"topic","role":"symbol","deprecated":true,"kind":"symbol","title":"JivoSDKNotifications","url":"\/documentation\/jivosdk\/jivosdknotifications","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKNotifications"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotifications"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/handleRemoteNotification(containingUserInfo:)":{"url":"\/documentation\/jivosdk\/jivosdknotifications\/handleremotenotification(containinguserinfo:)","title":"handleRemoteNotification(containingUserInfo:)","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleRemoteNotification","kind":"identifier"},{"text":"(","kind":"text"},{"text":"containingUserInfo","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/handleRemoteNotification(containingUserInfo:)","navigatorTitle":[{"kind":"identifier","text":"handleRemoteNotificationContainingUserInfo:"}],"deprecated":true,"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"handleRemoteNotificationContainingUserInfo:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleRemoteNotificationContainingUserInfo:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"handleRemoteNotificationContainingUserInfo:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"userInfo"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"JivoSDKNotifications","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/fragments","value":[{"text":"JivoSDKNotifications","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1handleRemoteNotification(containingUserInfo:)\/title","value":"handleRemoteNotificationContainingUserInfo:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1handleRemoteNotification(containingUserInfo:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"handleRemoteNotificationContainingUserInfo:","kind":"identifier"}]}]}]}