{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"jivoNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"prepareBanner"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sdk"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNMutableNotificationContent","preciseIdentifier":"c:objc(cs)UNMutableNotificationContent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sender","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Reference to JivoSDK"}]}],"name":"sdk"},{"name":"content","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"text":" ","type":"text"},{"text":"Original object provided by system","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Display name of person who sent the message","type":"text"}]}],"name":"sender"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Textual preview of sent message"}],"type":"paragraph"}],"name":"text"}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Adjusted content (if you wish to modify the banner),","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or original content (if you wish to keep things as is),"},{"type":"text","text":" "},{"text":"or nil (if you wish to avoid showing banner)","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"content":[{"inlineContent":[{"type":"text","text":"Here you can prepare banner for displaying"}],"type":"paragraph"}],"style":"tip","name":"Tip","type":"aside"}]}],"abstract":[{"type":"text","text":"Called when SDK is going to present Push Notification banner"}],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdknotifications\/jivonotifications(preparebanner:content:sender:text:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdknotifications\/jivonotifications(preparebanner:content:sender:text:)"]}],"sections":[],"metadata":{"title":"jivoNotifications(prepareBanner:content:sender:text:)","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"jivoNotificationsPrepareBanner:content:sender:text:","kind":"identifier"}],"platforms":[],"roleHeading":"Instance Method","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications(im)jivoNotificationsPrepareBanner:content:sender:text:","modules":[{"name":"JivoSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoNotifications"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"prepareBanner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UNMutableNotificationContent","kind":"typeIdentifier","text":"UNMutableNotificationContent"},{"kind":"text","text":", "},{"text":"sender","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationContent","text":"UNNotificationContent"},{"kind":"text","text":"?"}]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/jivoNotifications(prepareBanner:content:sender:text:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/jivoNotifications(prepareBanner:content:sender:text:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoNotifications"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"prepareBanner"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UNMutableNotificationContent","kind":"typeIdentifier","text":"UNMutableNotificationContent"},{"text":", ","kind":"text"},{"text":"sender","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationContent","text":"UNNotificationContent","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/jivoNotifications(prepareBanner:content:sender:text:)","title":"jivoNotifications(prepareBanner:content:sender:text:)","kind":"symbol","abstract":[{"type":"text","text":"Called when SDK is going to present Push Notification banner"}],"type":"topic","url":"\/documentation\/jivosdk\/jivosdknotifications\/jivonotifications(preparebanner:content:sender:text:)","navigatorTitle":[{"kind":"identifier","text":"jivoNotificationsPrepareBanner:content:sender:text:"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","kind":"symbol","title":"Jivo","abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications":{"title":"JivoSDKNotifications","url":"\/documentation\/jivosdk\/jivosdknotifications","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKNotifications"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications","navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotifications"}],"deprecated":true,"abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"jivoNotificationsPrepareBanner:content:sender:text:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jivoNotificationsPrepareBanner:content:sender:text:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"kind":"text","text":" *) "},{"text":"jivoNotificationsPrepareBanner:","kind":"identifier"},{"kind":"text","text":"("},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":" *) ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"content:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNMutableNotificationContent","text":"UNMutableNotificationContent"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"content"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"sender","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"text:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"jivoNotificationsPrepareBanner:content:sender:text:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1jivoNotifications(prepareBanner:content:sender:text:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"jivoNotificationsPrepareBanner:content:sender:text:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1jivoNotifications(prepareBanner:content:sender:text:)\/fragments","op":"replace"},{"op":"replace","value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/title","value":"JivoSDKNotifications"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/fragments","value":[{"text":"JivoSDKNotifications","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}