{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessRequested"},{"text":" ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"proceedBlock"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" () -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"text":" ","type":"text"},{"text":"Reference to JivoSDK","type":"text"}],"type":"paragraph"}],"name":"sdk"},{"name":"proceedBlock","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The callback you call when it’s time"},{"type":"text","text":" "},{"text":"to present the System Request for Push Notifications","type":"text"}]}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"style":"tip","name":"Tip","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You may want to present your custom UI"},{"text":" ","type":"text"},{"type":"text","text":"to inform user about accessing to Push Notifications,"},{"type":"text","text":" "},{"text":"before SDK will trigger System Request","type":"text"}]}],"type":"aside"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdknotifications\/jivonotifications(accessrequested:proceedblock:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdknotifications\/jivonotifications(accessrequested:proceedblock:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoNotifications"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accessRequested"},{"kind":"text","text":": "},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"proceedBlock"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"jivoNotifications(accessRequested:proceedBlock:)","modules":[{"name":"JivoSDK"}],"roleHeading":"Instance Method","role":"symbol","platforms":[],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications(im)jivoNotificationsAccessRequested:proceedBlock:","symbolKind":"method","navigatorTitle":[{"text":"jivoNotificationsAccessRequested:proceedBlock:","kind":"identifier"}]},"abstract":[{"text":"Called when SDK wants to access Push Notifications","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/jivoNotifications(accessRequested:proceedBlock:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"url":"\/documentation\/jivosdk\/jivo","kind":"symbol","title":"Jivo","role":"symbol","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","kind":"symbol","abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/jivoNotifications(accessRequested:proceedBlock:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoNotifications"},{"kind":"text","text":"("},{"text":"accessRequested","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":", ","kind":"text"},{"text":"proceedBlock","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"jivoNotifications(accessRequested:proceedBlock:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/jivoNotifications(accessRequested:proceedBlock:)","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdknotifications\/jivonotifications(accessrequested:proceedblock:)","type":"topic","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"jivoNotificationsAccessRequested:proceedBlock:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when SDK wants to access Push Notifications"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKNotifications"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotifications"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications","title":"JivoSDKNotifications","type":"topic","url":"\/documentation\/jivosdk\/jivosdknotifications","deprecated":true}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"jivoNotificationsAccessRequested:proceedBlock:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"jivoNotificationsAccessRequested:proceedBlock:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"jivoNotificationsAccessRequested:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sdk"},{"text":" ","kind":"text"},{"text":"proceedBlock:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")()) ","kind":"text"},{"text":"proceedBlock","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1jivoNotifications(accessRequested:proceedBlock:)\/title","value":"jivoNotificationsAccessRequested:proceedBlock:"},{"value":[{"kind":"text","text":"- "},{"text":"jivoNotificationsAccessRequested:proceedBlock:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1jivoNotifications(accessRequested:proceedBlock:)\/fragments"},{"value":"JivoSDKNotifications","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/fragments","value":[{"kind":"identifier","text":"JivoSDKNotifications"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}