{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdknotifications\/setpushtoken(hex:)"]},{"paths":["\/documentation\/jivosdk\/jivosdknotifications\/setpushtoken(hex:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPushToken(hex:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPushToken"},{"kind":"text","text":"("},{"text":"hex","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"role":"symbol","title":"setPushToken(hex:)","roleHeading":"Instance Method","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications(im)setPushTokenHex:","navigatorTitle":[{"text":"setPushTokenHex:","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"platforms":[],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(setPushTokenHex:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setPushToken","kind":"identifier"},{"kind":"text","text":"("},{"text":"hex","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","title":"JivoSDK","abstract":[],"url":"\/documentation\/jivosdk","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications":{"deprecated":true,"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications","abstract":[],"url":"\/documentation\/jivosdk\/jivosdknotifications","navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotifications"}],"role":"symbol","title":"JivoSDKNotifications","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKNotifications","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/setPushToken(hex:)":{"url":"\/documentation\/jivosdk\/jivosdknotifications\/setpushtoken(hex:)","type":"topic","deprecated":true,"title":"setPushToken(hex:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPushToken","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"hex"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setPushTokenHex:"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPushToken(hex:)","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"setPushTokenHex:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPushTokenHex:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"setPushTokenHex:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"hex"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/title","value":"JivoSDKNotifications"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/fragments","value":[{"text":"JivoSDKNotifications","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1setPushToken(hex:)\/title","value":"setPushTokenHex:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1setPushToken(hex:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPushTokenHex:"}],"op":"replace"}]}]}