{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedPreparing","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkarchivingstatus\/failedpreparing"]},{"paths":["\/documentation\/jivosdk\/jivosdkarchivingstatus\/failedpreparing"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/failedPreparing"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"JivoSDKArchivingStatusFailedPreparing","kind":"identifier"}],"externalID":"c:@M@JivoSDK@E@JivoSDKArchivingStatus@JivoSDKArchivingStatusFailedPreparing","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedPreparing"}],"title":"JivoSDKArchivingStatus.failedPreparing","modules":[{"name":"JivoSDK"}],"platforms":[],"roleHeading":"Case"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus":{"navigatorTitle":[{"kind":"identifier","text":"JivoSDKArchivingStatus"}],"url":"\/documentation\/jivosdk\/jivosdkarchivingstatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKArchivingStatus","kind":"identifier"}],"role":"symbol","abstract":[],"deprecated":true,"title":"JivoSDKArchivingStatus","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus/failedPreparing":{"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/failedPreparing","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failedPreparing"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKArchivingStatusFailedPreparing"}],"url":"\/documentation\/jivosdk\/jivosdkarchivingstatus\/failedpreparing","deprecated":true,"role":"symbol","title":"JivoSDKArchivingStatus.failedPreparing"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","url":"\/documentation\/jivosdk","kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"JivoSDKArchivingStatusFailedPreparing","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"JivoSDKArchivingStatusFailedPreparing","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"JivoSDKArchivingStatusFailedPreparing","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus\/title","op":"replace","value":"JivoSDKArchivingStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus\/fragments","value":[{"kind":"identifier","text":"JivoSDKArchivingStatus"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus~1failedPreparing\/title","value":"JivoSDKArchivingStatusFailedPreparing"},{"value":[{"kind":"identifier","text":"JivoSDKArchivingStatusFailedPreparing"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus~1failedPreparing\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}