{"metadata":{"title":"JivoSDKArchivingStatus.failedAccessing","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failedAccessing","kind":"identifier"}],"role":"symbol","modules":[{"name":"JivoSDK"}],"platforms":[],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"JivoSDKArchivingStatusFailedAccessing"}],"externalID":"c:@M@JivoSDK@E@JivoSDKArchivingStatus@JivoSDKArchivingStatusFailedAccessing"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/failedAccessing","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedAccessing"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/jivosdk\/jivosdkarchivingstatus\/failedaccessing"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkarchivingstatus\/failedaccessing"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/jivosdk","type":"topic","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus/failedAccessing":{"deprecated":true,"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"JivoSDKArchivingStatusFailedAccessing","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/failedAccessing","title":"JivoSDKArchivingStatus.failedAccessing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedAccessing"}],"role":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jivosdkarchivingstatus\/failedaccessing"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus","url":"\/documentation\/jivosdk\/jivosdkarchivingstatus","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKArchivingStatus"}],"role":"symbol","title":"JivoSDKArchivingStatus","navigatorTitle":[{"text":"JivoSDKArchivingStatus","kind":"identifier"}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"JivoSDKArchivingStatusFailedAccessing"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JivoSDKArchivingStatusFailedAccessing"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"JivoSDKArchivingStatusFailedAccessing","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus~1failedAccessing\/title","value":"JivoSDKArchivingStatusFailedAccessing"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus~1failedAccessing\/fragments","op":"replace","value":[{"text":"JivoSDKArchivingStatusFailedAccessing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus\/title","op":"replace","value":"JivoSDKArchivingStatus"},{"op":"replace","value":[{"text":"JivoSDKArchivingStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus\/fragments"}]}]}