{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus"]]},"variants":[{"paths":["\/documentation\/jivosdk\/jivosdkarchivingstatus\/success"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkarchivingstatus\/success"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/success","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"JivoSDKArchivingStatus.success","externalID":"c:@M@JivoSDK@E@JivoSDKArchivingStatus@JivoSDKArchivingStatusSuccess","platforms":[],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"success","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"role":"symbol","navigatorTitle":[{"text":"JivoSDKArchivingStatusSuccess","kind":"identifier"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdkarchivingstatus","navigatorTitle":[{"text":"JivoSDKArchivingStatus","kind":"identifier"}],"deprecated":true,"title":"JivoSDKArchivingStatus","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKArchivingStatus"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","type":"topic","role":"collection","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus/success":{"role":"symbol","navigatorTitle":[{"text":"JivoSDKArchivingStatusSuccess","kind":"identifier"}],"title":"JivoSDKArchivingStatus.success","type":"topic","url":"\/documentation\/jivosdk\/jivosdkarchivingstatus\/success","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"kind":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/success","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"JivoSDKArchivingStatusSuccess","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"JivoSDKArchivingStatusSuccess","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"JivoSDKArchivingStatusSuccess"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus\/title","op":"replace","value":"JivoSDKArchivingStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus\/fragments","op":"replace","value":[{"text":"JivoSDKArchivingStatus","kind":"identifier"}]},{"value":"JivoSDKArchivingStatusSuccess","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus~1success\/title"},{"value":[{"kind":"identifier","text":"JivoSDKArchivingStatusSuccess"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus~1success\/fragments","op":"replace"}]}]}