{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingDelegate\/jivoDebugging(catchEvent:text:)"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"jivoDebugging","kind":"identifier"},{"kind":"text","text":"("},{"text":"catchEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"kind":"text","text":", "},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"text":"JVDebuggingOriginalCatchBehavior","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingOriginalCatchBehavior","kind":"typeIdentifier"}],"title":"jivoDebugging(catchEvent:text:)","roleHeading":"Instance Method","modules":[{"name":"JivoSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"jivoDebuggingWithCatchEvent:text:","kind":"identifier"}],"required":true,"role":"symbol","externalID":"c:@M@JivoSDK@objc(pl)JVDebuggingDelegate(im)jivoDebuggingWithCatchEvent:text:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoDebugging","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"catchEvent"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"text":"JVDebuggingOriginalCatchBehavior","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingOriginalCatchBehavior"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingDelegate"]]},"variants":[{"paths":["\/documentation\/jivosdk\/jvdebuggingdelegate\/jivodebugging(catchevent:text:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdebuggingdelegate\/jivodebugging(catchevent:text:)"]}],"abstract":[{"type":"text","text":"Called when SDK is going to log event,"},{"text":" ","type":"text"},{"type":"text","text":"here you are able to replace the standard behavior with your own implementation"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingDelegate/jivoDebugging(catchEvent:text:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingDelegate\/jivoDebugging(catchEvent:text:)","abstract":[{"type":"text","text":"Called when SDK is going to log event,"},{"type":"text","text":" "},{"text":"here you are able to replace the standard behavior with your own implementation","type":"text"}],"type":"topic","navigatorTitle":[{"text":"jivoDebuggingWithCatchEvent:text:","kind":"identifier"}],"title":"jivoDebugging(catchEvent:text:)","url":"\/documentation\/jivosdk\/jvdebuggingdelegate\/jivodebugging(catchevent:text:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDebugging"},{"kind":"text","text":"("},{"kind":"externalParam","text":"catchEvent"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"text":"JVDebuggingOriginalCatchBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingOriginalCatchBehavior"}],"required":true,"kind":"symbol","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","title":"JivoSDK","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalCatchBehavior":{"title":"JVDebuggingOriginalCatchBehavior","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDebuggingOriginalCatchBehavior"}],"abstract":[{"type":"text","text":"SDK behavior for catching logging events"}],"url":"\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDebuggingOriginalCatchBehavior"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingDelegate":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingDelegate","abstract":[{"text":"Interface to control debugging process,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"relates to "},{"type":"codeVoice","code":"Jivo.debugging"},{"text":" namespace","type":"text"}],"type":"topic","navigatorTitle":[{"text":"JVDebuggingDelegate","kind":"identifier"}],"title":"JVDebuggingDelegate","url":"\/documentation\/jivosdk\/jvdebuggingdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDebuggingDelegate"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"kind":"symbol","url":"\/documentation\/jivosdk\/jivo","title":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"jivoDebuggingWithCatchEvent:text:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"jivoDebuggingWithCatchEvent:text:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingOriginalCatchBehavior","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingOriginalCatchBehavior"},{"kind":"text","text":") "},{"text":"jivoDebuggingWithCatchEvent:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"catchEvent","kind":"internalParam"},{"kind":"text","text":" "},{"text":"text:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"text"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"jivoDebuggingWithCatchEvent:text:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingDelegate~1jivoDebugging(catchEvent:text:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingDelegate~1jivoDebugging(catchEvent:text:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoDebuggingWithCatchEvent:text:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior\/title","op":"replace","value":"JVDebuggingOriginalCatchBehavior"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior\/fragments","value":[{"text":"JVDebuggingOriginalCatchBehavior","kind":"identifier"}]},{"value":"JVDebuggingDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingDelegate\/fragments","value":[{"kind":"identifier","text":"JVDebuggingDelegate"}]},{"op":"replace","value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"op":"replace","value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}