{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attach"}]}]}],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDisplayMenuAttach"}],"modules":[{"name":"JivoSDK"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"attach","kind":"identifier"}],"externalID":"c:@M@JivoSDK@E@JVDisplayMenu@JVDisplayMenuAttach","title":"JVDisplayMenu.attach","symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplaymenu\/attach"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplaymenu\/attach"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayMenu"]]},"abstract":[{"text":"Attach Menu in replying area","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayMenu\/attach","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayMenu/attach":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Attach Menu in replying area","type":"text"}],"navigatorTitle":[{"text":"JVDisplayMenuAttach","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayMenu\/attach","url":"\/documentation\/jivosdk\/jvdisplaymenu\/attach","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attach"}],"title":"JVDisplayMenu.attach"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayMenu":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDisplayMenu"}],"abstract":[{"text":"Menus available for customization","type":"text"}],"type":"topic","title":"JVDisplayMenu","navigatorTitle":[{"text":"JVDisplayMenu","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayMenu","url":"\/documentation\/jivosdk\/jvdisplaymenu","kind":"symbol","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","title":"JivoSDK","abstract":[],"url":"\/documentation\/jivosdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"JVDisplayMenuAttach","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"JVDisplayMenuAttach","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"JVDisplayMenuAttach","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayMenu~1attach\/title","value":"JVDisplayMenuAttach"},{"op":"replace","value":[{"text":"JVDisplayMenuAttach","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayMenu~1attach\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayMenu\/title","value":"JVDisplayMenu","op":"replace"},{"value":[{"text":"JVDisplayMenu","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayMenu\/fragments","op":"replace"}]}]}