{"variants":[{"paths":["\/documentation\/jivosdk\/common_project_config"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/common_project_config"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"sections":[],"metadata":{"title":"Setup your Project","modules":[{"name":"JivoSDK"}],"role":"article","roleHeading":"Article"},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_channel_setup","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token"],"title":"Setup","generated":true}],"abstract":[{"type":"text","text":"Permissions and Push Notifications"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_project_config","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"#1: Application Permissions","anchor":"1-Application-Permissions","type":"heading"},{"inlineContent":[{"type":"text","text":"SDK needs access to device camera and gallery."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"For necessary permissions, add these appropriate keys to your "},{"type":"codeVoice","code":"Info.plist"},{"text":":","type":"text"}],"type":"paragraph"},{"rows":[[[{"inlineContent":[{"type":"text","text":"key"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Purpose"}]}]],[[{"inlineContent":[{"type":"text","text":"NSCameraUsageDescription"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Access to camera so that your customers can take photos with camera"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"NSPhotoLibraryUsageDescription","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Access to gallery so that your customers can send photos from gallery"}]}]]],"header":"row","type":"table"},{"style":"warning","name":"Warning","type":"aside","content":[{"inlineContent":[{"text":"Without these keys, your app may crash when SDK will be accessing camera or gallery","type":"text"}],"type":"paragraph"}]},{"anchor":"2-Apple-Push-Notifications-service","type":"heading","text":"#2: Apple Push Notifications service","level":2},{"type":"heading","text":"Capabilities","level":4,"anchor":"Capabilities"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Make sure you have "},{"type":"codeVoice","code":"Push Notifications"},{"text":" capability in your project settings under ","type":"text"},{"type":"codeVoice","code":"Signing & Capabilities"},{"type":"text","text":" tab."}]},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"Push Notifications are sent "},{"type":"strong","inlineContent":[{"text":"only in production environment","type":"text"}]}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"In other words, they can only be tested when distributed via AdHoc, TestFlight, or App Store.","type":"text"}]}],"name":"Important","style":"important"},{"text":"Localization","anchor":"Localization","type":"heading","level":4},{"inlineContent":[{"type":"text","text":"Our Push Notifications use client-side localization (read more in "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/usernotifications\/setting_up_a_remote_notification_server\/generating_a_remote_notification","isActive":true},{"text":" by Apple), for which localization keys are specified as title and message, so you need to add following keys into localization files ","type":"text"},{"code":"Localizable.strings","type":"codeVoice"},{"text":" of your project:","type":"text"}],"type":"paragraph"},{"type":"table","header":"row","rows":[[[{"inlineContent":[{"text":"Key","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"Purpose","type":"text"}]}]],[[{"inlineContent":[{"code":"JV_MESSAGE_TITLE","type":"codeVoice"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Push Notification header key"}]}]],[[{"inlineContent":[{"type":"codeVoice","code":"JV_MESSAGE"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"text":"Push Notification body key","type":"text"}]}]]]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In addition to these keys, we also pass extra arguments within Push Notification payload which you can also use when localizing text:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"First argument contains a person name","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Second argument contains a message text","type":"text"}]}]}]},{"inlineContent":[{"text":"Here is an example of how the localization might look:","type":"text"}],"type":"paragraph"},{"type":"codeListing","code":["\"JV_MESSAGE_TITLE\" = \"Support Team\"; ","\"JV_MESSAGE\" = \"%1$@: %2$@\";"],"syntax":null}]}],"kind":"article","references":{"https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification":{"titleInlineContent":[{"type":"text","text":"“Localize Your Alert Messages”"}],"type":"link","url":"https:\/\/developer.apple.com\/documentation\/usernotifications\/setting_up_a_remote_notification_server\/generating_a_remote_notification","title":"“Localize Your Alert Messages”","identifier":"https:\/\/developer.apple.com\/documentation\/usernotifications\/setting_up_a_remote_notification_server\/generating_a_remote_notification"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/common_channel_setup":{"kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_channel_setup","type":"topic","role":"article","title":"Create a Channel","url":"\/documentation\/jivosdk\/common_channel_setup","abstract":[{"text":"Mobile SDK","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/common_user_token":{"title":"User Token and JWT","kind":"article","url":"\/documentation\/jivosdk\/common_user_token","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token","type":"topic","role":"article","abstract":[{"type":"text","text":"Required for keeping chat history alive"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/seeAlsoSections","value":[{"generated":true,"title":"Setup","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_channel_setup","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token"]}],"op":"replace"}]}]}