{"abstract":[{"text":"Required for keeping chat history alive","type":"text"}],"sections":[],"kind":"article","metadata":{"title":"User Token and JWT","roleHeading":"Article","modules":[{"name":"JivoSDK"}],"role":"article"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/common_user_token"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/common_user_token"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_channel_setup","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_project_config"],"title":"Setup"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"primaryContentSections":[{"content":[{"level":2,"text":"Overview","type":"heading","anchor":"Overview"},{"inlineContent":[{"type":"text","text":"For security reasons, chat history by default has a temporary nature and gets killed when providing another credentials into "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference","isActive":true},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","isActive":true},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/startUp(channelID:userToken:)","type":"reference","isActive":true},{"type":"text","text":", or by calling "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference","isActive":true},{"text":".","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session"},{"type":"text","text":"."},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/shutDown()"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"It means, for example, if your client logs-out and then logs-in again, you may see him as entirely new client."},{"text":"\n","type":"text"},{"text":"Even in case he uses the same login credentials, and even in case you provide the same user_token for him into SDK.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To keep chat history alive between login sessions, you have to generate JWT token and use it as user_token."},{"text":"\n","type":"text"},{"text":"Below, we explain how to do that.","type":"text"}]},{"text":"#1: Prepare secret","type":"heading","anchor":"1-Prepare-secret","level":2},{"inlineContent":[{"type":"text","text":"First, you need to create your global "},{"type":"codeVoice","code":"secret"},{"type":"text","text":" which you’ll use for generating JWT tokens."},{"type":"text","text":"\n"},{"type":"text","text":"Please create it accordingly to RFC 7519, with length of 256 bit."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Then, share this secret with us by sending it to "},{"identifier":"info@jivosite.com","type":"reference","isActive":true},{"type":"text","text":" from e-mail address of your account’s administrator,"},{"type":"text","text":"\n"},{"type":"text","text":"and tell us your Mobile SDK Channel ID so we can configure our JWT environment for you."}]},{"type":"aside","style":"tip","content":[{"type":"paragraph","inlineContent":[{"text":"You may found this resource useful to generate, sign, and check JWT tokens: ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/jwt.io\/"}]}],"name":"Tip"},{"anchor":"2-Generate-token","level":2,"type":"heading","text":"#2: Generate token"},{"type":"paragraph","inlineContent":[{"text":"JWT tokens you will generate for your clients, must be:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"unique across your account"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"constant for individual client","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"encrypted using your "},{"type":"codeVoice","code":"secret"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"Minimal JWT payload must contain “id” field which acts like a client identifier, so here is example of such JWT payload:","type":"text"}]},{"code":["{","    \"id\": \"egor531@example.com\"","}"],"syntax":null,"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"Finally, you should feed your JWT as userToken parameter into:","type":"text"},{"text":"\n","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference","isActive":true},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","isActive":true},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/startUp(channelID:userToken:)","isActive":true}]},{"name":"Important","type":"aside","style":"important","content":[{"type":"paragraph","inlineContent":[{"text":"For security reasons, you’d better generate JWT tokens on your back-end,","type":"text"},{"text":"\n","type":"text"},{"type":"text","text":"rather than doing it directly in the mobile app (because your "},{"code":"secret","type":"codeVoice"},{"text":" might be stolen)","type":"text"}]}]}],"kind":"content"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","title":"JivoSDK","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController","text":"JVSessionController","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"Namespace for managing user session"}],"url":"\/documentation\/jivosdk\/jivo\/session","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"session"}],"title":"session"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"kind":"symbol","url":"\/documentation\/jivosdk\/jivo","title":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/shutDown()":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/shutDown()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shutDown"},{"kind":"text","text":"()"}],"title":"shutDown()","type":"topic","abstract":[{"text":"Closes current connection, clears the local database,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and unsubscribes device from Push Notifications"}],"navigatorTitle":[{"kind":"identifier","text":"shutDown"}],"url":"\/documentation\/jivosdk\/jvsessioncontroller\/shutdown()","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/common_project_config":{"url":"\/documentation\/jivosdk\/common_project_config","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_project_config","abstract":[{"type":"text","text":"Permissions and Push Notifications"}],"kind":"article","role":"article","title":"Setup your Project","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/startUp(channelID:userToken:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/startUp(channelID:userToken:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startUp"},{"kind":"text","text":"("},{"text":"channelID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"userToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"startUp(channelID:userToken:)","type":"topic","abstract":[{"type":"text","text":"Establishes connection between SDK and Jivo,"},{"type":"text","text":" "},{"type":"text","text":"by either creating a new session or resuming existing one"}],"navigatorTitle":[{"text":"startUpWithChannelID:userToken:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvsessioncontroller\/startup(channelid:usertoken:)","role":"symbol"},"info@jivosite.com":{"title":"info@jivosite.com","identifier":"info@jivosite.com","type":"link","titleInlineContent":[{"text":"info@jivosite.com","type":"text"}],"url":"info@jivosite.com"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/common_channel_setup":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_channel_setup","abstract":[{"text":"Mobile SDK","type":"text"}],"url":"\/documentation\/jivosdk\/common_channel_setup","kind":"article","role":"article","title":"Create a Channel","type":"topic"},"https://jwt.io/":{"identifier":"https:\/\/jwt.io\/","type":"link","title":"jwt.io","titleInlineContent":[{"type":"text","text":"jwt.io"}],"url":"https:\/\/jwt.io\/"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_channel_setup","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_project_config"],"generated":true,"title":"Setup"}]},{"op":"replace","value":"session","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments","value":[{"text":"session","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace","value":[{"kind":"identifier","text":"Jivo"}]},{"op":"replace","value":"shutDown","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1shutDown()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"shutDown","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1shutDown()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1startUp(channelID:userToken:)\/title","op":"replace","value":"startUpWithChannelID:userToken:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1startUp(channelID:userToken:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startUpWithChannelID:userToken:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}