{"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_channel_setup"},"seeAlsoSections":[{"anchor":"Setup","generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_project_config","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token"],"title":"Setup"}],"primaryContentSections":[{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use SDK, you need a channel of type “Mobile SDK”"}]},{"content":[{"inlineContent":[{"type":"text","text":"Available for "},{"type":"reference","isActive":true,"identifier":"https:\/\/www.jivochat.com\/pricing\/"},{"text":" only","type":"text"}],"type":"paragraph"}],"type":"aside","style":"important","name":"Important"},{"level":2,"type":"heading","anchor":"1-Create-channel","text":"#1: Create channel"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Log in to your Jivo account"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Navigate to channels screen: "},{"code":"Manage -> Channels","type":"codeVoice"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Create new channel of type “Mobile SDK”"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"channel_setup_1"}]}]}],"type":"unorderedList"},{"type":"heading","anchor":"2-Push-Notifications","level":2,"text":"#2: Push Notifications"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Make sure you have APNs Key configured in P8 format. If not, you can create it within "},{"code":"Keys","type":"codeVoice"},{"type":"text","text":" section of your account page at "},{"isActive":true,"type":"reference","identifier":"developer.apple.com"},{"type":"text","text":", and then download it."}]},{"inlineContent":[{"text":"Add your key into your Jivo account for your ","type":"text"},{"type":"codeVoice","code":"Mobile SDK"},{"type":"text","text":" channel."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"To do this, please navigate step-by-step:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"“Management”","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"“Channels”"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"“Mobile SDK” (button “Settings”)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"“PUSH Settings”"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"“Upload p8 key”"}]}]}]},{"type":"paragraph","inlineContent":[{"identifier":"channel_setup_3","type":"image"}]},{"inlineContent":[{"type":"text","text":"Then, you need to specify:"}],"type":"paragraph"},{"header":"row","type":"table","rows":[[[{"inlineContent":[{"text":"Parameter","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Purpose"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"key_id"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Key ID itself"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"team_id"}]}],[{"type":"paragraph","inlineContent":[{"text":"Team ID of your Apple Developer Program account","type":"text"}]}]],[[{"inlineContent":[{"text":"bundle_id","type":"text"}],"type":"paragraph"}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Bundle ID of your app"}]}]]]},{"inlineContent":[{"identifier":"channel_setup_4","type":"image"}],"type":"paragraph"},{"type":"heading","level":2,"anchor":"3-Inspect-configuration","text":"#3: Inspect configuration"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Navigate to settings of created channel, section ","type":"text"},{"type":"codeVoice","code":"\"Options\""}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Copy ","type":"text"},{"code":"widget_id","type":"codeVoice"},{"text":" in the ","type":"text"},{"type":"codeVoice","code":"\"Jivo Mobile SDK parameters\""},{"text":" section for later use","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"channel_setup_2"}]},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"You should use "},{"code":"widget_id","type":"codeVoice"},{"type":"text","text":" value wherever "},{"code":"channelID","type":"codeVoice"},{"text":" is required","type":"text"}],"type":"paragraph"}],"style":"note","name":"Note"}]}]}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/jivosdk\/common_channel_setup"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/common_channel_setup"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Article","role":"article","title":"Create a Channel","modules":[{"name":"JivoSDK"}]},"abstract":[{"type":"text","text":"Mobile SDK"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"references":{"channel_setup_1":{"alt":"Channel Creation","type":"image","identifier":"channel_setup_1","variants":[{"url":"\/images\/org.cocoapods.JivoSDK\/channel_setup_1.jpeg","traits":["1x","light"]}]},"channel_setup_4":{"type":"image","alt":"Channel APNs Settings: specify the parameters","identifier":"channel_setup_4","variants":[{"url":"\/images\/org.cocoapods.JivoSDK\/channel_setup_4.jpeg","traits":["1x","light"]}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","title":"JivoSDK","type":"topic","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/common_user_token":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token","abstract":[{"type":"text","text":"Required for keeping chat history alive"}],"role":"article","kind":"article","title":"User Token and JWT","url":"\/documentation\/jivosdk\/common_user_token"},"https://www.jivochat.com/pricing/":{"title":"Enterprise plan","type":"link","titleInlineContent":[{"type":"text","text":"Enterprise plan"}],"identifier":"https:\/\/www.jivochat.com\/pricing\/","url":"https:\/\/www.jivochat.com\/pricing\/"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/common_project_config":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_project_config","kind":"article","abstract":[{"type":"text","text":"Permissions and Push Notifications"}],"title":"Setup your Project","url":"\/documentation\/jivosdk\/common_project_config","role":"article"},"developer.apple.com":{"title":"developer.apple.com","type":"link","titleInlineContent":[{"text":"developer.apple.com","type":"text"}],"identifier":"developer.apple.com","url":"developer.apple.com"},"channel_setup_3":{"alt":"Channel APNs Settings: upload the key","type":"image","identifier":"channel_setup_3","variants":[{"url":"\/images\/org.cocoapods.JivoSDK\/channel_setup_3.jpeg","traits":["1x","light"]}]},"channel_setup_2":{"type":"image","alt":"Channel Settings","identifier":"channel_setup_2","variants":[{"url":"\/images\/org.cocoapods.JivoSDK\/channel_setup_2.jpeg","traits":["1x","light"]}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"title":"Setup","generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_project_config","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token"],"anchor":"Setup"}],"op":"replace","path":"\/seeAlsoSections"}]}]}