{"kind":"article","sections":[],"abstract":[{"text":"Using CocoaPods","type":"text"}],"metadata":{"modules":[{"name":"JivoSDK"}],"role":"article","roleHeading":"Article","title":"Link to SDK"},"variants":[{"paths":["\/documentation\/jivosdk\/flutter_pod_link"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/flutter_pod_link"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Repos","level":2,"anchor":"Repos"},{"inlineContent":[{"text":"Specify the following sources at the beginning of your ","type":"text"},{"code":"Podfile","type":"codeVoice"},{"text":":","type":"text"}],"type":"paragraph"},{"syntax":"ruby","type":"codeListing","code":["source 'https:\/\/github.com\/cocoapods\/specs' ","source 'https:\/\/github.com\/jivochat\/cocoapods-repo'"]},{"type":"heading","text":"Dependency","level":2,"anchor":"Dependency"},{"inlineContent":[{"type":"text","text":"Add SDK as dependency into your "},{"type":"codeVoice","code":"ios\/Podfile"},{"text":":","type":"text"}],"type":"paragraph"},{"syntax":"ruby","type":"codeListing","code":["pod 'JivoSDK'"]},{"inlineContent":[{"type":"text","text":"In case you have your project created via standard Flutter template, your resulting directive might look as following:"}],"type":"paragraph"},{"syntax":"ruby","type":"codeListing","code":["target 'Runner' do","    use_frameworks!","    use_modular_headers!","","    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))","    pod 'JivoSDK'","  ","    target 'RunnerTests' do","        inherit! :search_paths","    end","end"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_pod_link","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"seeAlsoSections":[{"generated":true,"anchor":"For-Flutter-project","title":"For Flutter project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_plugin_bridge","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/flutter_usage_basics"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/flutter_api_ref":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","role":"article","kind":"article","url":"\/documentation\/jivosdk\/flutter_api_ref","title":"API Reference","abstract":[{"text":"Dart API","type":"text"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","url":"\/documentation\/jivosdk","title":"JivoSDK","abstract":[],"kind":"symbol","role":"collection"},"doc://org.cocoapods.JivoSDK/tutorials/JivoSDK/flutter_usage_basics":{"url":"\/tutorials\/jivosdk\/flutter_usage_basics","abstract":[{"type":"text","text":"Some scenarios of how to use SDK"}],"role":"project","title":"Basic usage","kind":"project","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/flutter_usage_basics"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/flutter_plugin_bridge":{"role":"article","title":"Plugin Bridge","abstract":[{"text":"Dart Bridge","type":"text"}],"kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_plugin_bridge","url":"\/documentation\/jivosdk\/flutter_plugin_bridge"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"generated":true,"anchor":"For-Flutter-project","title":"For Flutter project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_plugin_bridge","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/flutter_usage_basics"]}],"path":"\/seeAlsoSections","op":"replace"}]}]}