{"variants":[{"paths":["\/documentation\/jivosdk\/flutter_plugin_bridge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/flutter_plugin_bridge"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_plugin_bridge","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Dart Bridge"}],"sections":[],"primaryContentSections":[{"kind":"content","content":[{"text":"Import plugin","level":2,"anchor":"Import-plugin","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Please import these items from directory "},{"type":"codeVoice","code":"[JivoSDK\/Adapters\/Flutter]"},{"type":"text","text":":"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"jivosdk_plugin"},{"type":"text","text":" folder into your Flutter project"}],"type":"paragraph"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Please keep it up-to-date alongwith SDK updates","type":"text"}]}],"type":"aside","name":"Important","style":"important"},{"text":"Link to plugin","level":2,"anchor":"Link-to-plugin","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Now, please specify SDK dependency in your project’s’ ","type":"text"},{"code":"pubspec.yaml","type":"codeVoice"},{"text":" file:","type":"text"}]},{"syntax":null,"code":["dependencies:","  jivosdk_plugin:","    path: .\/jivosdk_plugin"],"type":"codeListing"}]}],"kind":"article","metadata":{"title":"Plugin Bridge","modules":[{"name":"JivoSDK"}],"roleHeading":"Article","role":"article"},"schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"title":"For Flutter project","generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/flutter_usage_basics"],"anchor":"For-Flutter-project"}],"references":{"doc://org.cocoapods.JivoSDK/tutorials/JivoSDK/flutter_usage_basics":{"kind":"project","title":"Basic usage","identifier":"doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/flutter_usage_basics","type":"topic","url":"\/tutorials\/jivosdk\/flutter_usage_basics","abstract":[{"type":"text","text":"Some scenarios of how to use SDK"}],"role":"project"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/flutter_api_ref":{"url":"\/documentation\/jivosdk\/flutter_api_ref","title":"API Reference","kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","type":"topic","abstract":[{"type":"text","text":"Dart API"}],"role":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/flutter_pod_link":{"url":"\/documentation\/jivosdk\/flutter_pod_link","type":"topic","role":"article","title":"Link to SDK","kind":"article","abstract":[{"type":"text","text":"Using CocoaPods"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_pod_link"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"generated":true,"anchor":"For-Flutter-project","title":"For Flutter project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/flutter_usage_basics"]}],"op":"replace","path":"\/seeAlsoSections"}]}]}