{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref"},"variants":[{"paths":["\/documentation\/jivosdk\/flutter_api_ref"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/flutter_api_ref"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"article","roleHeading":"Article","modules":[{"name":"JivoSDK"}],"title":"API Reference"},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"content":[{"level":2,"type":"heading","anchor":"Session","text":"Session"},{"code":["Future<void> Jivo.session.setPreferredServer(JVSessionServer server) async"],"type":"codeListing","syntax":null},{"inlineContent":[{"text":"Same as ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"code":"Jivo\/session","type":"codeVoice"},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setPreferredServer(_:)","isActive":true}],"type":"paragraph"},{"code":["Future<void> Jivo.session.startUp({required String channelID, required String userToken}) async"],"syntax":null,"type":"codeListing"},{"inlineContent":[{"type":"text","text":"Same as "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference","isActive":true},{"text":".","type":"text"},{"type":"codeVoice","code":"Jivo\/session"},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setup(widgetID:clientIdentity:)","isActive":true}],"type":"paragraph"},{"type":"codeListing","code":["Future<void> Jivo.session.setContactInfo({String? name, String? email, String? phone, String? brief}) async"],"syntax":null},{"type":"paragraph","inlineContent":[{"text":"Same as ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"codeVoice","code":"Jivo\/session"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setContactInfo(_:)"}]},{"syntax":null,"code":["Future<void> Jivo.session.setCustomData(List<JVSessionCustomDataField> fields) async"],"type":"codeListing"},{"inlineContent":[{"text":"Same as ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"type":"codeVoice","code":"Jivo\/session"},{"type":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setCustomData(fields:)","type":"reference","isActive":true}],"type":"paragraph"},{"code":["Future<void> Jivo.session.shutDown() async"],"syntax":null,"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Same as "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"type":"codeVoice","code":"Jivo\/session"},{"type":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/shutDown()","isActive":true,"type":"reference"}]},{"type":"codeListing","code":["void Jivo.session.startWatchingUnreadCounter(Function watcher)"],"syntax":null},{"inlineContent":[{"type":"text","text":"Same as "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference"},{"text":".","type":"text"},{"type":"codeVoice","code":"Jivo\/session"},{"text":".","type":"text"},{"type":"codeVoice","code":"JVSessionController\/delegate"},{"text":" -> ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate\/jivoSession(updateUnreadCounter:number:)"}],"type":"paragraph"},{"text":"Display","type":"heading","anchor":"Display","level":2},{"code":["Future<bool> Jivo.display.isOnscreen async"],"type":"codeListing","syntax":null},{"type":"paragraph","inlineContent":[{"type":"text","text":"Same as "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"type":"text","text":"."},{"code":"Jivo\/display","type":"codeVoice"},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/isOnscreen","type":"reference","isActive":true}]},{"syntax":null,"code":["Future<void> Jivo.display.setLocale(Locale locale) async"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"Same as ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"text":".","type":"text"},{"code":"Jivo\/display","type":"codeVoice"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setLocale(_:)"}]},{"code":["Future<void> Jivo.display.present() async"],"syntax":null,"type":"codeListing"},{"inlineContent":[{"text":"Same as ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference","isActive":true},{"text":".","type":"text"},{"code":"Jivo\/display","type":"codeVoice"},{"text":".","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/present(over:)","isActive":true},{"text":" calling with root view controller","type":"text"}],"type":"paragraph"},{"code":["void Jivo.display.executeWhenAsksToAppear(Function executor)"],"type":"codeListing","syntax":null},{"inlineContent":[{"text":"Same as ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"text":".","type":"text"},{"code":"Jivo\/display","type":"codeVoice"},{"text":".","type":"text"},{"type":"codeVoice","code":"JVDisplayController\/delegate"},{"type":"text","text":" -> "},{"type":"codeVoice","code":"JVDisplayDelegate\/jivoDisplay(asksToAppear:)"}],"type":"paragraph"},{"anchor":"Notifications","level":2,"type":"heading","text":"Notifications"},{"type":"codeListing","code":["Future<void> Jivo.notifications.setPermissionAsking(JVNotificationsPermissionAskingMoment moment) async"],"syntax":null},{"inlineContent":[{"text":"Same as ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"text":".","type":"text"},{"code":"Jivo\/notifications","type":"codeVoice"},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionAsking(at:)","isActive":true}],"type":"paragraph"},{"text":"Debugging","anchor":"Debugging","level":2,"type":"heading"},{"syntax":null,"type":"codeListing","code":["Future<void> Jivo.debugging.setLevel(JVDebuggingLevel level) async"]},{"inlineContent":[{"text":"Same as ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"type":"codeVoice","code":"Jivo\/debugging"},{"text":".","type":"text"},{"type":"codeVoice","code":"JVDebuggingController\/level"}],"type":"paragraph"},{"type":"codeListing","code":["Future<void> Jivo.debugging.archiveLogs({required Function completion}) async"],"syntax":null},{"inlineContent":[{"text":"Same as ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"text":".","type":"text"},{"type":"codeVoice","code":"Jivo\/debugging"},{"type":"text","text":"."},{"code":"JVDebuggingController\/archiveLogs(completion:)","type":"codeVoice"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Dart API"}],"seeAlsoSections":[{"title":"For Flutter project","anchor":"For-Flutter-project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_plugin_bridge","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/flutter_usage_basics"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setPreferredServer(_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setPreferredServer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK15JVSessionServerO","text":"JVSessionServer"},{"text":")","kind":"text"}],"url":"\/documentation\/jivosdk\/jvsessioncontroller\/setpreferredserver(_:)","abstract":[{"text":"Specifies preferred server for SDK to connect to Jivo","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setPreferredServer(_:)","role":"symbol","title":"setPreferredServer(_:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"type":"topic","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setPermissionAsking(at:)":{"title":"setPermissionAsking(at:)","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setpermissionasking(at:)","abstract":[{"text":"Specifies when SDK should request access to Push Notifications","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPermissionAsking","kind":"identifier"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK37JVNotificationsPermissionAskingMomentO","text":"JVNotificationsPermissionAskingMoment"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionAsking(at:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionDelegate/jivoSession(updateUnreadCounter:number:)":{"navigatorTitle":[{"text":"jivoSessionUpdateUnreadCounter:number:","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoSession"},{"text":"(","kind":"text"},{"text":"updateUnreadCounter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"number"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","title":"jivoSession(updateUnreadCounter:number:)","required":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate\/jivoSession(updateUnreadCounter:number:)","url":"\/documentation\/jivosdk\/jvsessiondelegate\/jivosession(updateunreadcounter:number:)","abstract":[{"text":"Called when unread counter changes","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/setLocale(_:)":{"title":"setLocale(_:)","type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/setlocale(_:)","abstract":[{"text":"Sets the custom locale for use instead of system one","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setLocale","kind":"identifier"},{"kind":"text","text":"("},{"text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setLocale(_:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/present(over:)":{"title":"present(over:)","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/present(over:)","abstract":[{"type":"text","text":"Displays SDK modally on screen, slides it up from bottom edge (animated)"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"kind":"text","text":"("},{"text":"over","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"JVSessionHandle","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"presentOver:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/present(over:)"},"doc://org.cocoapods.JivoSDK/tutorials/JivoSDK/flutter_usage_basics":{"kind":"project","identifier":"doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/flutter_usage_basics","abstract":[{"text":"Some scenarios of how to use SDK","type":"text"}],"role":"project","type":"topic","url":"\/tutorials\/jivosdk\/flutter_usage_basics","title":"Basic usage"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/shutDown()":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shutDown"},{"text":"()","kind":"text"}],"title":"shutDown()","kind":"symbol","navigatorTitle":[{"text":"shutDown","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/shutDown()","url":"\/documentation\/jivosdk\/jvsessioncontroller\/shutdown()","abstract":[{"type":"text","text":"Closes current connection, clears the local database,"},{"type":"text","text":" "},{"type":"text","text":"and unsubscribes device from Push Notifications"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/isOnscreen":{"title":"isOnscreen","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/isOnscreen","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/isonscreen","abstract":[{"text":"Determines whether SDK is currently in UI hierarchy","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOnscreen","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isOnscreen"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setup(widgetID:clientIdentity:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"widgetID"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientIdentity"},{"text":": ","kind":"text"},{"text":"JVClientIdentity","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK16JVClientIdentityO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"JVClient","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVClient"}],"title":"setup(widgetID:clientIdentity:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setup(widgetID:clientIdentity:)","url":"\/documentation\/jivosdk\/jvsessioncontroller\/setup(widgetid:clientidentity:)","abstract":[{"type":"text","text":"Starts a logical session for user,"},{"type":"text","text":" "},{"type":"text","text":"by either creating a new session or resuming existing one"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setCustomData(fields:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setCustomData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fields"},{"text":": [","kind":"text"},{"text":"JVClientCustomDataField","preciseIdentifier":"s:7JivoSDK23JVClientCustomDataFielda","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"navigatorTitle":[{"text":"setCustomData:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setCustomData(fields:)","url":"\/documentation\/jivosdk\/jvsessioncontroller\/setcustomdata(fields:)","abstract":[{"type":"text","text":"Assigns custom data to user,"},{"type":"text","text":" "},{"text":"if needed for your business","type":"text"}],"kind":"symbol","role":"symbol","title":"setCustomData(fields:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/flutter_plugin_bridge":{"title":"Plugin Bridge","kind":"article","type":"topic","abstract":[{"text":"Dart Bridge","type":"text"}],"url":"\/documentation\/jivosdk\/flutter_plugin_bridge","role":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_plugin_bridge"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setContactInfo(_:)":{"type":"topic","abstract":[{"text":"Assigns contact info to user,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to reach him easier in future"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setContactInfo(_:)","navigatorTitle":[{"text":"setContactInfo:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvsessioncontroller\/setcontactinfo(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setContactInfo"},{"text":"(","kind":"text"},{"text":"JVClientContactInfo","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK19JVClientContactInfoa"},{"text":"?)","kind":"text"}],"title":"setContactInfo(_:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"title":"Jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"role":"symbol","url":"\/documentation\/jivosdk\/jivo","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/flutter_pod_link":{"kind":"article","type":"topic","url":"\/documentation\/jivosdk\/flutter_pod_link","role":"article","title":"Link to SDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_pod_link","abstract":[{"text":"Using CocoaPods","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":[{"anchor":"For-Flutter-project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_plugin_bridge","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/flutter_usage_basics"],"title":"For Flutter project","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","value":"jivoSessionUpdateUnreadCounter:number:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate~1jivoSession(updateUnreadCounter:number:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate~1jivoSession(updateUnreadCounter:number:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"jivoSessionUpdateUnreadCounter:number:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1present(over:)\/title","value":"presentOver:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"presentOver:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1present(over:)\/fragments"},{"value":"shutDown","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1shutDown()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"shutDown","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1shutDown()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1isOnscreen\/title","op":"replace","value":"isOnscreen"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1isOnscreen\/fragments","value":[{"text":"isOnscreen","kind":"identifier"}]},{"value":"setCustomData:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setCustomData(fields:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setCustomData(fields:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setCustomData:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"setContactInfo:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setContactInfo(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setContactInfo(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setContactInfo:"}],"op":"replace"},{"value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace"},{"op":"replace","value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"text":"Jivo","kind":"identifier"}]}]}]}