{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler"]},{"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandler"}],"platforms":[],"modules":[{"name":"JivoSDK"}],"title":"JivoSDKNotificationsPermissionAskingHandler","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandler"}],"symbolKind":"enum","roleHeading":"Enumeration","role":"symbol","externalID":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingHandler"},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"type":"conformsTo"}],"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/current","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/sdk"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/init(rawValue:)"]},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(JivoSDKNotificationsPermissionAskingHandler) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKNotificationsPermissionAskingHandler","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingHandler/sdk":{"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler\/sdk","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"sdk","kind":"identifier"}],"navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingHandlerSdk","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/sdk","type":"topic","abstract":[],"role":"symbol","title":"JivoSDKNotificationsPermissionAskingHandler.sdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingHandler/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/RawRepresentable-Implementations"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingHandler/current":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/current","type":"topic","title":"JivoSDKNotificationsPermissionAskingHandler.current","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler\/current","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandlerCurrent"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"current","kind":"identifier"}],"deprecated":true,"abstract":[]},"doc://org.cocoapods.JivoSDK/SH":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingHandler/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/init(rawValue:)","deprecated":true,"kind":"symbol","abstract":[],"role":"symbol"},"doc://org.cocoapods.JivoSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingHandler":{"url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler","title":"JivoSDKNotificationsPermissionAskingHandler","abstract":[],"deprecated":true,"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKNotificationsPermissionAskingHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandler"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingHandler/Equatable-Implementations":{"kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskinghandler\/equatable-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"JivoSDKNotificationsPermissionAskingHandler"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JivoSDKNotificationsPermissionAskingHandler","kind":"identifier"}]},{"op":"replace","value":[{"text":"JivoSDKNotificationsPermissionAskingHandler","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/current","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingHandler\/sdk"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler~1sdk\/title","op":"replace","value":"JivoSDKNotificationsPermissionAskingHandlerSdk"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler~1sdk\/fragments","value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingHandlerSdk"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler~1current\/title","value":"JivoSDKNotificationsPermissionAskingHandlerCurrent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler~1current\/fragments","value":[{"text":"JivoSDKNotificationsPermissionAskingHandlerCurrent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler\/title","value":"JivoSDKNotificationsPermissionAskingHandler","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingHandler\/fragments","value":[{"text":"JivoSDKNotificationsPermissionAskingHandler","kind":"identifier"}],"op":"replace"}]}]}