{"kind":"symbol","metadata":{"externalID":"c:@M@JivoSDK@objc(cs)JivoSDK","roleHeading":"Class","title":"JivoSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JivoSDK","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"platforms":[],"navigatorTitle":[{"text":"JivoSDK","kind":"identifier"}],"role":"symbol","symbolKind":"class"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/chattingUI-swift.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/debugging-swift.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/notifications-swift.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/session-swift.property"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/Jivo"],"title":"Type Aliases"},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/chattingUI-swift.type.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/debugging-swift.type.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/notifications-swift.type.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/session-swift.type.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/shared"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(JivoSDK) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDK"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdk"]},{"paths":["\/documentation\/jivosdk\/jivosdk"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/shared":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"shared"}],"title":"shared","abstract":[],"role":"symbol","deprecated":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/shared","url":"\/documentation\/jivosdk\/jivosdk\/shared","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/debugging-swift.type.property":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/debugging-swift.type.property","type":"topic","title":"debugging","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"debugging"}],"deprecated":true,"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugging","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging","text":"JivoSDKDebugging","kind":"typeIdentifier"}],"url":"\/documentation\/jivosdk\/jivosdk\/debugging-swift.type.property"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"abstract":[],"role":"symbol","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDK","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdk","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JivoSDK"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/chattingUI-swift.property":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/chattingUI-swift.property","deprecated":true,"title":"chattingUI","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdk\/chattingui-swift.property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"chattingUI"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI","text":"JivoSDKChattingUI","kind":"typeIdentifier"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"chattingUI","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/Jivo":{"title":"JivoSDK.Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/Jivo","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"deprecated":true,"url":"\/documentation\/jivosdk\/jivosdk\/jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/session-swift.type.property":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/session-swift.type.property","deprecated":true,"title":"session","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdk\/session-swift.type.property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKSession","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"session"}]},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.JivoSDK/SH":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/notifications-swift.property":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/notifications-swift.property","deprecated":true,"title":"notifications","url":"\/documentation\/jivosdk\/jivosdk\/notifications-swift.property","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifications"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications","text":"JivoSDKNotifications"}],"type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"notifications","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/notifications-swift.type.property":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/notifications-swift.type.property","deprecated":true,"title":"notifications","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdk\/notifications-swift.type.property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifications"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications","text":"JivoSDKNotifications","kind":"typeIdentifier"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"notifications","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/debugging-swift.property":{"url":"\/documentation\/jivosdk\/jivosdk\/debugging-swift.property","kind":"symbol","role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"debugging"}],"title":"debugging","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"debugging","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JivoSDKDebugging","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/debugging-swift.property"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","type":"topic","kind":"symbol","abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/chattingUI-swift.type.property":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/chattingUI-swift.type.property","deprecated":true,"title":"chattingUI","url":"\/documentation\/jivosdk\/jivosdk\/chattingui-swift.type.property","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chattingUI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI","text":"JivoSDKChattingUI"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"chattingUI","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/session-swift.property":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/session-swift.property","deprecated":true,"title":"session","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdk\/session-swift.property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKSession","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"session"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"JivoSDK","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JivoSDK","kind":"identifier"}]},{"value":[{"text":"JivoSDK","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/chattingUI-swift.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/debugging-swift.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/notifications-swift.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/session-swift.property"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/chattingUI-swift.type.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/debugging-swift.type.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/notifications-swift.type.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/session-swift.type.property","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/shared"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"JivoSDK","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1shared\/title","value":"shared"},{"value":[{"text":"shared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1shared\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1debugging-swift.type.property\/title","value":"debugging"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1debugging-swift.type.property\/fragments","value":[{"text":"debugging","kind":"identifier"}],"op":"replace"},{"value":"JivoSDK","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments","op":"replace","value":[{"text":"JivoSDK","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1chattingUI-swift.property\/title","value":"chattingUI"},{"value":[{"text":"chattingUI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1chattingUI-swift.property\/fragments"},{"value":"session","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1session-swift.type.property\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1session-swift.type.property\/fragments","value":[{"text":"session","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1notifications-swift.property\/title","value":"notifications"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1notifications-swift.property\/fragments","op":"replace","value":[{"text":"notifications","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1notifications-swift.type.property\/title","value":"notifications"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1notifications-swift.type.property\/fragments","value":[{"text":"notifications","kind":"identifier"}]},{"value":"debugging","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1debugging-swift.property\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1debugging-swift.property\/fragments","value":[{"text":"debugging","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1chattingUI-swift.type.property\/title","value":"chattingUI","op":"replace"},{"value":[{"text":"chattingUI","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1chattingUI-swift.type.property\/fragments","op":"replace"},{"value":"session","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1session-swift.property\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1session-swift.property\/fragments","value":[{"text":"session","kind":"identifier"}]}]}]}