{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(JivoSDKDebugging) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKDebugging"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"metadata":{"title":"JivoSDKDebugging","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging","platforms":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKDebugging"}],"modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKDebugging"}],"symbolKind":"class","roleHeading":"Class"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging\/level"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging\/archiveLogs(completion:)"]}],"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkdebugging"]},{"paths":["\/documentation\/jivosdk\/jivosdkdebugging"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebugging/init":{"title":"init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging\/init","type":"topic","url":"\/documentation\/jivosdk\/jivosdkdebugging\/init","kind":"symbol","role":"symbol"},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebugging/archiveLogs(completion:)":{"kind":"symbol","navigatorTitle":[{"text":"archiveLogsWithCompletionHandler:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"archiveLogs"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKArchivingStatus","text":"JivoSDKArchivingStatus"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/jivosdk\/jivosdkdebugging\/archivelogs(completion:)","role":"symbol","title":"archiveLogs(completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging\/archiveLogs(completion:)","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebugging":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging","type":"topic","role":"symbol","deprecated":true,"title":"JivoSDKDebugging","url":"\/documentation\/jivosdk\/jivosdkdebugging","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JivoSDKDebugging","kind":"identifier"}],"navigatorTitle":[{"text":"JivoSDKDebugging","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebugging/level":{"title":"level","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"level","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKDebuggingLevel","kind":"typeIdentifier","text":"JivoSDKDebuggingLevel"}],"navigatorTitle":[{"kind":"identifier","text":"level"}],"deprecated":true,"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging\/level","type":"topic","url":"\/documentation\/jivosdk\/jivosdkdebugging\/level","kind":"symbol","role":"symbol"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"JivoSDKDebugging","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"JivoSDKDebugging","kind":"identifier"}],"op":"replace"},{"value":[{"text":"JivoSDKDebugging","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging\/level"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging\/archiveLogs(completion:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging\/init"],"title":"Instance Methods"}],"path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKDebugging","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging~1archiveLogs(completion:)\/title","value":"archiveLogsWithCompletionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging~1archiveLogs(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"archiveLogsWithCompletionHandler:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging\/title","value":"JivoSDKDebugging"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging\/fragments","value":[{"text":"JivoSDKDebugging","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging~1level\/title","op":"replace","value":"level"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging~1level\/fragments","value":[{"text":"level","kind":"identifier"}]}]}]}