{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(JivoSDKArchivingStatus) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKArchivingStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"metadata":{"title":"JivoSDKArchivingStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKArchivingStatus"}],"navigatorTitle":[{"text":"JivoSDKArchivingStatus","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","platforms":[],"modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@E@JivoSDKArchivingStatus"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/failedAccessing","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/failedPreparing","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/success"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/init(rawValue:)"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkarchivingstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkarchivingstatus"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus/success":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/success","url":"\/documentation\/jivosdk\/jivosdkarchivingstatus\/success","kind":"symbol","deprecated":true,"title":"JivoSDKArchivingStatus.success","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"success","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKArchivingStatusSuccess"}],"type":"topic","abstract":[],"role":"symbol"},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/jivosdk\/jivosdkarchivingstatus\/rawrepresentable-implementations"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"deprecated":true,"kind":"symbol","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/jivosdk\/jivosdkarchivingstatus\/init(rawvalue:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/init(rawValue:)","title":"init(rawValue:)"},"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol","url":"\/documentation\/jivosdk","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus/failedAccessing":{"type":"topic","title":"JivoSDKArchivingStatus.failedAccessing","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/failedAccessing","abstract":[],"role":"symbol","url":"\/documentation\/jivosdk\/jivosdkarchivingstatus\/failedaccessing","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedAccessing","kind":"identifier"}],"navigatorTitle":[{"text":"JivoSDKArchivingStatusFailedAccessing","kind":"identifier"}],"deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus/failedPreparing":{"kind":"symbol","navigatorTitle":[{"text":"JivoSDKArchivingStatusFailedPreparing","kind":"identifier"}],"role":"symbol","abstract":[],"deprecated":true,"title":"JivoSDKArchivingStatus.failedPreparing","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedPreparing","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/failedPreparing","type":"topic","url":"\/documentation\/jivosdk\/jivosdkarchivingstatus\/failedpreparing"},"doc://org.cocoapods.JivoSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus/Equatable-Implementations":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/Equatable-Implementations","role":"collectionGroup","url":"\/documentation\/jivosdk\/jivosdkarchivingstatus\/equatable-implementations","abstract":[],"kind":"article","type":"topic","title":"Equatable Implementations"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKArchivingStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKArchivingStatus"}],"navigatorTitle":[{"text":"JivoSDKArchivingStatus","kind":"identifier"}],"kind":"symbol","deprecated":true,"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/jivosdk\/jivosdkarchivingstatus","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus","title":"JivoSDKArchivingStatus"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"JivoSDKArchivingStatus","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JivoSDKArchivingStatus","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"JivoSDKArchivingStatus","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/failedAccessing","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/failedPreparing","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKArchivingStatus\/success"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JivoSDKArchivingStatus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus~1success\/title","value":"JivoSDKArchivingStatusSuccess"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus~1success\/fragments","value":[{"kind":"identifier","text":"JivoSDKArchivingStatusSuccess"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus~1failedAccessing\/title","value":"JivoSDKArchivingStatusFailedAccessing","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus~1failedAccessing\/fragments","value":[{"text":"JivoSDKArchivingStatusFailedAccessing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus~1failedPreparing\/title","op":"replace","value":"JivoSDKArchivingStatusFailedPreparing"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus~1failedPreparing\/fragments","value":[{"text":"JivoSDKArchivingStatusFailedPreparing","kind":"identifier"}],"op":"replace"},{"value":"JivoSDKArchivingStatus","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKArchivingStatus\/fragments","value":[{"text":"JivoSDKArchivingStatus","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}