{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKSessionServer","kind":"identifier"}],"platforms":[],"roleHeading":"Enumeration","navigatorTitle":[{"text":"JivoSDKSessionServer","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"title":"JivoSDKSessionServer","externalID":"c:@M@JivoSDK@E@JivoSDKSessionServer"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/asia","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/auto","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/europe","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/russia"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(JivoSDKSessionServer) "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKSessionServer"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdksessionserver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdksessionserver"]}],"references":{"doc://org.cocoapods.JivoSDK/SH":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer/auto":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/auto","navigatorTitle":[{"kind":"identifier","text":"JivoSDKSessionServerAuto"}],"kind":"symbol","title":"JivoSDKSessionServer.auto","url":"\/documentation\/jivosdk\/jivosdksessionserver\/auto","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"auto"}],"deprecated":true,"role":"symbol"},"doc://org.cocoapods.JivoSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer/russia":{"title":"JivoSDKSessionServer.russia","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKSessionServerRussia"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"russia","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/russia","role":"symbol","deprecated":true,"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdksessionserver\/russia"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/jivosdk\/jivosdksessionserver\/rawrepresentable-implementations","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer/init(rawValue:)":{"title":"init(rawValue:)","deprecated":true,"abstract":[],"url":"\/documentation\/jivosdk\/jivosdksessionserver\/init(rawvalue:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/init(rawValue:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.JivoSDK/SY":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer":{"title":"JivoSDKSessionServer","kind":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer","url":"\/documentation\/jivosdk\/jivosdksessionserver","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKSessionServer","kind":"identifier"}],"navigatorTitle":[{"text":"JivoSDKSessionServer","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer/Equatable-Implementations":{"url":"\/documentation\/jivosdk\/jivosdksessionserver\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/Equatable-Implementations","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer/europe":{"navigatorTitle":[{"text":"JivoSDKSessionServerEurope","kind":"identifier"}],"type":"topic","title":"JivoSDKSessionServer.europe","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"europe","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/jivosdk\/jivosdksessionserver\/europe","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/europe"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer/asia":{"url":"\/documentation\/jivosdk\/jivosdksessionserver\/asia","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asia","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"JivoSDKSessionServerAsia","kind":"identifier"}],"type":"topic","deprecated":true,"abstract":[],"kind":"symbol","title":"JivoSDKSessionServer.asia","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/asia"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"JivoSDKSessionServer","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"text":"JivoSDKSessionServer","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JivoSDKSessionServer"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/asia","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/auto","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/europe","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/russia"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKSessionServer","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1auto\/title","value":"JivoSDKSessionServerAuto","op":"replace"},{"value":[{"text":"JivoSDKSessionServerAuto","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1auto\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1russia\/title","value":"JivoSDKSessionServerRussia"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1russia\/fragments","op":"replace","value":[{"text":"JivoSDKSessionServerRussia","kind":"identifier"}]},{"value":"JivoSDKSessionServer","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JivoSDKSessionServer"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1europe\/title","op":"replace","value":"JivoSDKSessionServerEurope"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1europe\/fragments","value":[{"text":"JivoSDKSessionServerEurope","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1asia\/title","value":"JivoSDKSessionServerAsia"},{"op":"replace","value":[{"text":"JivoSDKSessionServerAsia","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1asia\/fragments"}]}]}