{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivo"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"metadata":{"title":"Jivo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"externalID":"c:@M@JivoSDK@objc(cs)Jivo","role":"symbol","modules":[{"name":"JivoSDK"}]},"topicSections":[{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(Jivo) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"mentions":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_api_ref","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token"],"kind":"mentions"},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"style":"important","name":"Important","content":[{"inlineContent":[{"type":"text","text":"Full documentation is here:"},{"type":"text","text":"\n"},{"identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/","type":"reference","isActive":true}],"type":"paragraph"}],"type":"aside"},{"items":[{"content":[{"level":2,"text":"Quick start","anchor":"Quick-start","type":"heading"},{"inlineContent":[{"text":"First, start SDK session after you have authorized your client wherever in your logic (like example below):","type":"text"},{"text":"\n","type":"text"},{"identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/common_user_token","type":"reference","isActive":true}],"type":"paragraph"},{"syntax":"swift","code":["func handleUserLogin() {","    let client = Jivo.session.setup(","        widgetID: \"YOUR_WIDGET_ID\",","        clientIdentity: .jwt(\"USER_TOKEN_IN_JWT_FORMAT\")","    )","","    client.setClientInfo(...) \/\/ optional","    client.setCustomData(...) \/\/ optional","","    client.listenToUnreadCounter { number in","        \/\/ read updates here","    }","}"],"type":"codeListing"},{"inlineContent":[{"text":"Second, present the SDK onto screen whenever you need it (like example below):","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["\/\/ UIKit","func handleSupportButtonTap() {","    if let navigationController {","        Jivo.display.push(into: navigationController)","    }","    else {","        Jivo.display.present(over: self)","    }","}","","\/\/ SwiftUI","var body: some View {","    Text(\"Tech Support\")","        .fullScreenCover(isPresented: $shouldPresentChat) {","            Jivo.display.makeScreen(.modal)","        }","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"To support Push Notifications, you should provide us Push Token (like example below):"}],"type":"paragraph"},{"syntax":"swift","code":["func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {","    \/\/ ... your existing logic ...","","    Jivo.notifications.setPushToken(data: deviceToken)","}","","func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {","    \/\/ ... your existing logic ...","","    Jivo.notifications.setPushToken(error: error)","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"To handle and display incoming notifications, please implement three another methods (like example below):"}],"type":"paragraph"},{"syntax":"swift","code":["func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","    \/\/ ... your existing logic ...","","    UNUserNotificationCenter.current().delegate = self","","    if Jivo.notifications.handleLaunch(options: launchOptions) {","        Jivo.display.present(over: rootViewController)","    }","    ","    return true","}","","func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {","    if let result = Jivo.notifications.didReceiveRemoteNotification(userInfo: userInfo) {","        completionHandler(result)","        return","    }","","    \/\/ ... your existing logic ...","}","","func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {","    if let options = Jivo.notifications.willPresent(notification: notification, preferableOptions: .banner) {","        completionHandler(options)","        return","    }","","    \/\/ ... your existing logic ...","}","","func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {","    if Jivo.notifications.didReceive(response: response) {","        Jivo.display.present(over: rootViewController)","        completionHandler()","    }","","    \/\/ ... your existing logic ...","}"],"type":"codeListing"}]},{"content":[{"anchor":"May-be-interesting-for-you","type":"heading","level":2,"text":"May be interesting for you:"},{"items":[{"content":[{"inlineContent":[{"isActive":true,"identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/tutorials\/jivosdk\/native_usage_basics","type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/common_user_token","isActive":true,"overridingTitleInlineContent":[{"type":"text","text":"User token and history"}],"overridingTitle":"User token and history","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/jvdisplaycontroller"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/common_project_config\/#Localization"}]}]}],"type":"unorderedList"}]}],"type":"unorderedList"}],"kind":"content"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/flutter_api_ref":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","type":"topic","url":"\/documentation\/jivosdk\/flutter_api_ref","title":"API Reference","role":"article","abstract":[{"text":"Dart API","type":"text"}],"kind":"article"},"https://jivochat.github.io/JivoSDK-iOS/tutorials/jivosdk/native_usage_basics":{"title":"Basic SDK usage","type":"link","titleInlineContent":[{"type":"text","text":"Basic SDK usage"}],"url":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/tutorials\/jivosdk\/native_usage_basics","identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/tutorials\/jivosdk\/native_usage_basics"},"doc://org.cocoapods.JivoSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"https://jivochat.github.io/JivoSDK-iOS/":{"title":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/","type":"link","titleInlineContent":[{"type":"text","text":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/"}],"url":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/","identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/native_api_ref":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_api_ref","abstract":[{"type":"text","text":"Swift API"}],"role":"article","kind":"article","type":"topic","url":"\/documentation\/jivosdk\/native_api_ref","title":"API Reference"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/react_api_ref":{"role":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref","url":"\/documentation\/jivosdk\/react_api_ref","title":"API Reference","abstract":[{"text":"JavaScript API","type":"text"}],"type":"topic","kind":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/common_user_token":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/common_user_token","url":"\/documentation\/jivosdk\/common_user_token","role":"article","type":"topic","title":"User Token and JWT","kind":"article","abstract":[{"text":"Required for keeping chat history alive","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"debugging","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugging","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JVDebuggingController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","title":"debugging","type":"topic","abstract":[{"type":"text","text":"Namespace for SDK debugging"}],"url":"\/documentation\/jivosdk\/jivo\/debugging"},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController","text":"JVSessionController"}],"type":"topic","kind":"symbol","abstract":[{"text":"Namespace for managing user session","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"session"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","title":"session","url":"\/documentation\/jivosdk\/jivo\/session"},"doc://org.cocoapods.JivoSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH"},"https://jivochat.github.io/JivoSDK-iOS/documentation/jivosdk/jvdisplaycontroller":{"identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/jvdisplaycontroller","url":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/jvdisplaycontroller","title":"UI customization","titleInlineContent":[{"type":"text","text":"UI customization"}],"type":"link"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","navigatorTitle":[{"text":"display","kind":"identifier"}],"role":"symbol","title":"display","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"display","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController","text":"JVDisplayController","kind":"typeIdentifier"}],"url":"\/documentation\/jivosdk\/jivo\/display","abstract":[{"type":"text","text":"Namespace for SDK displaying"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"abstract":[],"title":"Jivo","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"https://jivochat.github.io/JivoSDK-iOS/documentation/jivosdk/common_project_config/#Localization":{"title":"Notifications localization","type":"link","titleInlineContent":[{"type":"text","text":"Notifications localization"}],"url":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/common_project_config\/#Localization","identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/common_project_config\/#Localization"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifications","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JVNotificationsController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","kind":"typeIdentifier"}],"url":"\/documentation\/jivosdk\/jivo\/notifications","abstract":[{"type":"text","text":"Namespace for Push Notifications"}],"title":"notifications","navigatorTitle":[{"text":"notifications","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications"},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/init":{"type":"topic","url":"\/documentation\/jivosdk\/jivo\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/init","kind":"symbol","abstract":[],"title":"init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","title":"JivoSDK"},"https://jivochat.github.io/JivoSDK-iOS/documentation/jivosdk/common_user_token":{"identifier":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/common_user_token","url":"https:\/\/jivochat.github.io\/JivoSDK-iOS\/documentation\/jivosdk\/common_user_token","title":"How to generate User Token in JWT format","titleInlineContent":[{"type":"text","text":"How to generate User Token in JWT format"}],"type":"link"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"Jivo"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/init"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session"],"title":"Type Properties","anchor":"Type-Properties","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","value":"debugging","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/title"},{"op":"replace","value":[{"text":"debugging","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/fragments"},{"op":"replace","value":"session","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title"},{"op":"replace","value":[{"kind":"identifier","text":"session"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments"},{"op":"replace","value":"display","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title"},{"op":"replace","value":[{"text":"display","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments"},{"op":"replace","value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"op":"replace","value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"op":"replace","value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle"},{"op":"replace","value":"notifications","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title"},{"op":"replace","value":[{"text":"notifications","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments"}]}]}