{"kind":"symbol","metadata":{"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKNotifications","role":"symbol","symbolKind":"class","modules":[{"name":"JivoSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKNotifications","kind":"identifier"}],"navigatorTitle":[{"text":"JivoSDKNotifications","kind":"identifier"}],"platforms":[],"roleHeading":"Class","title":"JivoSDKNotifications"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdknotifications"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdknotifications"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/delegate"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/handleNotification(_:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/handleNotification(response:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/handleRemoteNotification(containingUserInfo:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/jivoNotifications(accessRequested:proceedBlock:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/jivoNotifications(prepareBanner:content:sender:text:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPermissionAsking(at:handler:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPushToken(data:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPushToken(hex:)"],"title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(JivoSDKNotifications) "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKNotifications","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/handleRemoteNotification(containingUserInfo:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handleRemoteNotification","kind":"identifier"},{"text":"(","kind":"text"},{"text":"containingUserInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"title":"handleRemoteNotification(containingUserInfo:)","url":"\/documentation\/jivosdk\/jivosdknotifications\/handleremotenotification(containinguserinfo:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/handleRemoteNotification(containingUserInfo:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"handleRemoteNotificationContainingUserInfo:"}],"type":"topic","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/delegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(pl)JivoSDKNotificationsDelegate","text":"JivoSDKNotificationsDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[],"title":"delegate","url":"\/documentation\/jivosdk\/jivosdknotifications\/delegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/delegate","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/setPushToken(hex:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPushToken","kind":"identifier"},{"kind":"text","text":"("},{"text":"hex","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"abstract":[],"title":"setPushToken(hex:)","url":"\/documentation\/jivosdk\/jivosdknotifications\/setpushtoken(hex:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPushToken(hex:)","role":"symbol","navigatorTitle":[{"text":"setPushTokenHex:","kind":"identifier"}],"type":"topic","deprecated":true},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/setPermissionAsking(at:handler:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPermissionAsking"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingMoment","text":"JivoSDKNotificationsPermissionAskingMoment","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"handler","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingHandler","kind":"typeIdentifier","text":"JivoSDKNotificationsPermissionAskingHandler"},{"kind":"text","text":")"}],"abstract":[],"title":"setPermissionAsking(at:handler:)","url":"\/documentation\/jivosdk\/jivosdknotifications\/setpermissionasking(at:handler:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPermissionAsking(at:handler:)","role":"symbol","navigatorTitle":[{"text":"setPermissionAskingAt:handler:","kind":"identifier"}],"type":"topic","deprecated":true},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsDelegate"}],"abstract":[{"text":"Interface to handle notifications events,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"relates to "},{"code":"Jivo.notifications","type":"codeVoice"},{"type":"text","text":" namespace"}],"title":"JVNotificationsDelegate","url":"\/documentation\/jivosdk\/jvnotificationsdelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate","role":"symbol","navigatorTitle":[{"text":"JVNotificationsDelegate","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP"},"doc://org.cocoapods.JivoSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/handleNotification(response:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleNotification","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationResponse","kind":"typeIdentifier","text":"UNNotificationResponse"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"title":"handleNotification(response:)","url":"\/documentation\/jivosdk\/jivosdknotifications\/handlenotification(response:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/handleNotification(response:)","role":"symbol","navigatorTitle":[{"text":"handleNotificationResponse:","kind":"identifier"}],"type":"topic","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/init":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"abstract":[],"title":"init","url":"\/documentation\/jivosdk\/jivosdknotifications\/init","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/handleNotification(_:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleNotification","kind":"identifier"},{"kind":"text","text":"("},{"text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[],"title":"handleNotification(_:)","url":"\/documentation\/jivosdk\/jivosdknotifications\/handlenotification(_:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/handleNotification(_:)","role":"symbol","navigatorTitle":[{"text":"handleNotification:","kind":"identifier"}],"type":"topic","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/jivoNotifications(accessRequested:proceedBlock:)":{"kind":"symbol","type":"topic","title":"jivoNotifications(accessRequested:proceedBlock:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"jivoNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accessRequested","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"proceedBlock","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"url":"\/documentation\/jivosdk\/jivosdknotifications\/jivonotifications(accessrequested:proceedblock:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/jivoNotifications(accessRequested:proceedBlock:)","deprecated":true,"abstract":[{"type":"text","text":"Called when SDK wants to access Push Notifications"}],"navigatorTitle":[{"text":"jivoNotificationsAccessRequested:proceedBlock:","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/setPushToken(data:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPushToken"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?)","kind":"text"}],"abstract":[],"title":"setPushToken(data:)","url":"\/documentation\/jivosdk\/jivosdknotifications\/setpushtoken(data:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPushToken(data:)","role":"symbol","navigatorTitle":[{"text":"setPushTokenData:","kind":"identifier"}],"type":"topic","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications/jivoNotifications(prepareBanner:content:sender:text:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoNotifications","kind":"identifier"},{"kind":"text","text":"("},{"text":"prepareBanner","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier","text":"Jivo"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UNMutableNotificationContent","preciseIdentifier":"c:objc(cs)UNMutableNotificationContent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sender","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UNNotificationContent","text":"UNNotificationContent","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Called when SDK is going to present Push Notification banner"}],"title":"jivoNotifications(prepareBanner:content:sender:text:)","url":"\/documentation\/jivosdk\/jivosdknotifications\/jivonotifications(preparebanner:content:sender:text:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/jivoNotifications(prepareBanner:content:sender:text:)","role":"symbol","navigatorTitle":[{"text":"jivoNotificationsPrepareBanner:content:sender:text:","kind":"identifier"}],"type":"topic","deprecated":true},"doc://org.cocoapods.JivoSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications":{"kind":"symbol","title":"JivoSDKNotifications","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKNotifications"}],"url":"\/documentation\/jivosdk\/jivosdknotifications","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications","deprecated":true,"abstract":[],"navigatorTitle":[{"text":"JivoSDKNotifications","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"JivoSDKNotifications"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"JivoSDKNotifications","kind":"identifier"}]},{"value":[{"text":"JivoSDKNotifications","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/handleNotification(_:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/handleNotification(response:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/handleRemoteNotification(containingUserInfo:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/init","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/jivoNotifications(accessRequested:proceedBlock:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/jivoNotifications(prepareBanner:content:sender:text:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPermissionAsking(at:handler:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPushToken(data:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications\/setPushToken(hex:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate"],"title":"Conforms To","type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"JivoSDKNotifications","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1handleRemoteNotification(containingUserInfo:)\/title","value":"handleRemoteNotificationContainingUserInfo:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1handleRemoteNotification(containingUserInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleRemoteNotificationContainingUserInfo:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1delegate\/title","value":"delegate"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1delegate\/fragments"},{"value":"setPushTokenHex:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1setPushToken(hex:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1setPushToken(hex:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setPushTokenHex:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1setPermissionAsking(at:handler:)\/title","op":"replace","value":"setPermissionAskingAt:handler:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPermissionAskingAt:handler:"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1setPermissionAsking(at:handler:)\/fragments"},{"value":"JVNotificationsDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate\/title"},{"value":[{"text":"JVNotificationsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1handleNotification(response:)\/title","op":"replace","value":"handleNotificationResponse:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"handleNotificationResponse:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1handleNotification(response:)\/fragments"},{"value":"handleNotification:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1handleNotification(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"handleNotification:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1handleNotification(_:)\/fragments"},{"value":"jivoNotificationsAccessRequested:proceedBlock:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1jivoNotifications(accessRequested:proceedBlock:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1jivoNotifications(accessRequested:proceedBlock:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"jivoNotificationsAccessRequested:proceedBlock:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1setPushToken(data:)\/title","value":"setPushTokenData:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPushTokenData:"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1setPushToken(data:)\/fragments","op":"replace"},{"value":"jivoNotificationsPrepareBanner:content:sender:text:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1jivoNotifications(prepareBanner:content:sender:text:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications~1jivoNotifications(prepareBanner:content:sender:text:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"jivoNotificationsPrepareBanner:content:sender:text:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/title","op":"replace","value":"JivoSDKNotifications"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/fragments","op":"replace","value":[{"kind":"identifier","text":"JivoSDKNotifications"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}