{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(JivoSDKDebuggingLevel) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JivoSDKDebuggingLevel","kind":"identifier"}]}]}],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/full","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/silent"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"JivoSDKDebuggingLevel"}],"symbolKind":"enum","roleHeading":"Enumeration","externalID":"c:@M@JivoSDK@E@JivoSDKDebuggingLevel","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKDebuggingLevel"}],"title":"JivoSDKDebuggingLevel","platforms":[],"modules":[{"name":"JivoSDK"}]},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdkdebugginglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkdebugginglevel"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebuggingLevel/Equatable-Implementations":{"role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/jivosdk\/jivosdkdebugginglevel\/equatable-implementations","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebuggingLevel/silent":{"role":"symbol","navigatorTitle":[{"text":"JivoSDKDebuggingLevelSilent","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/silent","abstract":[],"title":"JivoSDKDebuggingLevel.silent","url":"\/documentation\/jivosdk\/jivosdkdebugginglevel\/silent","deprecated":true,"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"silent"}]},"doc://org.cocoapods.JivoSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebuggingLevel/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/jivosdk\/jivosdkdebugginglevel\/rawrepresentable-implementations","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebuggingLevel/init(rawValue:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","url":"\/documentation\/jivosdk\/jivosdkdebugginglevel\/init(rawvalue:)","deprecated":true,"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebuggingLevel/full":{"role":"symbol","url":"\/documentation\/jivosdk\/jivosdkdebugginglevel\/full","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"}],"kind":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/full","title":"JivoSDKDebuggingLevel.full","navigatorTitle":[{"kind":"identifier","text":"JivoSDKDebuggingLevelFull"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebuggingLevel":{"deprecated":true,"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKDebuggingLevel"}],"title":"JivoSDKDebuggingLevel","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jivosdkdebugginglevel","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel","navigatorTitle":[{"text":"JivoSDKDebuggingLevel","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"JivoSDKDebuggingLevel","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JivoSDKDebuggingLevel"}],"op":"replace"},{"op":"replace","value":[{"text":"JivoSDKDebuggingLevel","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/full","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebuggingLevel\/silent"],"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKDebuggingLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"JivoSDKDebuggingLevelSilent","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel~1silent\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel~1silent\/fragments","value":[{"text":"JivoSDKDebuggingLevelSilent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel~1full\/title","op":"replace","value":"JivoSDKDebuggingLevelFull"},{"op":"replace","value":[{"text":"JivoSDKDebuggingLevelFull","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel~1full\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel\/title","value":"JivoSDKDebuggingLevel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebuggingLevel\/fragments","value":[{"text":"JivoSDKDebuggingLevel","kind":"identifier"}]}]}]}