{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias"},"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/blue","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/graphite","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/green"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/standard"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/RawRepresentable-Implementations"],"generated":true}],"metadata":{"externalID":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingPaletteAlias","kind":"identifier"}],"symbolKind":"enum","navigatorTitle":[{"text":"JivoSDKChattingPaletteAlias","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"platforms":[],"title":"JivoSDKChattingPaletteAlias","role":"symbol","roleHeading":"Enumeration"},"kind":"symbol","variants":[{"paths":["\/documentation\/jivosdk\/jivosdkchattingpalettealias"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdkchattingpalettealias"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(JivoSDKChattingPaletteAlias) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias/green":{"type":"topic","navigatorTitle":[{"text":"JivoSDKChattingPaletteAliasGreen","kind":"identifier"}],"title":"JivoSDKChattingPaletteAlias.green","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/green","url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias\/green","role":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"green","kind":"identifier"}],"deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias/Equatable-Implementations":{"url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias\/equatable-implementations","kind":"article","title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/Equatable-Implementations","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias/graphite":{"url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias\/graphite","navigatorTitle":[{"text":"JivoSDKChattingPaletteAliasGraphite","kind":"identifier"}],"kind":"symbol","title":"JivoSDKChattingPaletteAlias.graphite","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/graphite","role":"symbol","deprecated":true,"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"graphite"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias/init(rawValue:)":{"url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/init(rawValue:)","role":"symbol","deprecated":true,"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias/standard":{"url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias\/standard","kind":"symbol","title":"standard","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/standard","role":"symbol","deprecated":true,"abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"standard","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias","kind":"typeIdentifier","text":"JivoSDKChattingPaletteAlias"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias/RawRepresentable-Implementations":{"kind":"article","type":"topic","title":"RawRepresentable Implementations","url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/RawRepresentable-Implementations","role":"collectionGroup"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","type":"topic","role":"collection","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias/blue":{"url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias\/blue","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingPaletteAliasBlue"}],"kind":"symbol","title":"JivoSDKChattingPaletteAlias.blue","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/blue","role":"symbol","deprecated":true,"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"blue","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias","title":"JivoSDKChattingPaletteAlias","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias","abstract":[],"role":"symbol","deprecated":true},"doc://org.cocoapods.JivoSDK/SH":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/SY":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"JivoSDKChattingPaletteAlias","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"JivoSDKChattingPaletteAlias","kind":"identifier"}]},{"value":[{"text":"JivoSDKChattingPaletteAlias","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/blue","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/graphite","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias\/green"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingPaletteAlias","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias~1green\/title","value":"JivoSDKChattingPaletteAliasGreen"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias~1green\/fragments","value":[{"text":"JivoSDKChattingPaletteAliasGreen","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias~1graphite\/title","op":"replace","value":"JivoSDKChattingPaletteAliasGraphite"},{"value":[{"text":"JivoSDKChattingPaletteAliasGraphite","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias~1graphite\/fragments","op":"replace"},{"value":"JivoSDKChattingPaletteAliasBlue","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias~1blue\/title"},{"op":"replace","value":[{"kind":"identifier","text":"JivoSDKChattingPaletteAliasBlue"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias~1blue\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias\/title","value":"JivoSDKChattingPaletteAlias"},{"op":"replace","value":[{"text":"JivoSDKChattingPaletteAlias","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}