{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(JivoSDKNotificationsDelegate) "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"JivoSDKNotificationsDelegate","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsDelegate"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsDelegate\/jivo(needAccessToNotifications:proceedBlock:)"],"title":"Instance Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"metadata":{"title":"JivoSDKNotificationsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKNotificationsDelegate","kind":"identifier"}],"roleHeading":"Protocol","symbolKind":"protocol","platforms":[],"modules":[{"name":"JivoSDK"}],"role":"symbol","navigatorTitle":[{"text":"JivoSDKNotificationsDelegate","kind":"identifier"}],"externalID":"c:@M@JivoSDK@objc(pl)JivoSDKNotificationsDelegate"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationsdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationsdelegate"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","abstract":[],"url":"\/documentation\/jivosdk","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsDelegate":{"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKNotificationsDelegate","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/jivosdk\/jivosdknotificationsdelegate","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsDelegate","navigatorTitle":[{"text":"JivoSDKNotificationsDelegate","kind":"identifier"}],"kind":"symbol","title":"JivoSDKNotificationsDelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsDelegate/jivo(needAccessToNotifications:proceedBlock:)":{"navigatorTitle":[{"kind":"identifier","text":"jivoNeedAccessToNotifications:proceedBlock:"}],"deprecated":true,"abstract":[],"type":"topic","url":"\/documentation\/jivosdk\/jivosdknotificationsdelegate\/jivo(needaccesstonotifications:proceedblock:)","title":"jivo(needAccessToNotifications:proceedBlock:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsDelegate\/jivo(needAccessToNotifications:proceedBlock:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"needAccessToNotifications"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK","text":"JivoSDK"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"proceedBlock"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"JivoSDKNotificationsDelegate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JivoSDKNotificationsDelegate"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JivoSDKNotificationsDelegate"}]},{"value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsDelegate\/jivo(needAccessToNotifications:proceedBlock:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKNotificationsDelegate"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsDelegate\/title","value":"JivoSDKNotificationsDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsDelegate\/fragments","value":[{"kind":"identifier","text":"JivoSDKNotificationsDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsDelegate~1jivo(needAccessToNotifications:proceedBlock:)\/title","value":"jivoNeedAccessToNotifications:proceedBlock:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"jivoNeedAccessToNotifications:proceedBlock:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsDelegate~1jivo(needAccessToNotifications:proceedBlock:)\/fragments","op":"replace"}]}]}