{"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/init()","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/init(name:email:phone:brief:)"],"title":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/debugDescription","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/hasAllFields","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/hasAnyField"],"title":"Instance Properties"}],"metadata":{"platforms":[],"title":"JivoSDKSessionClientInfo","modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKSessionClientInfo","roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JivoSDKSessionClientInfo","kind":"identifier"}],"navigatorTitle":[{"text":"JivoSDKSessionClientInfo","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdksessionclientinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdksessionclientinfo"]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(JivoSDKSessionClientInfo) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKSessionClientInfo"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionClientInfo/hasAnyField":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/hasAnyField","title":"hasAnyField","url":"\/documentation\/jivosdk\/jivosdksessionclientinfo\/hasanyfield","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hasAnyField","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"deprecated":true},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol","url":"\/documentation\/jivosdk","type":"topic"},"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP"},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionClientInfo/init()":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","abstract":[],"deprecated":true,"title":"init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/init()","type":"topic","url":"\/documentation\/jivosdk\/jivosdksessionclientinfo\/init()"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionClientInfo/debugDescription":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/debugDescription","type":"topic","navigatorTitle":[{"text":"debugDescription","kind":"identifier"}],"abstract":[],"deprecated":true,"title":"debugDescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"debugDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/jivosdk\/jivosdksessionclientinfo\/debugdescription"},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionClientInfo/hasAllFields":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hasAllFields","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"hasAllFields","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/hasAllFields","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdksessionclientinfo\/hasallfields","role":"symbol","deprecated":true,"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionClientInfo/init(name:email:phone:brief:)":{"navigatorTitle":[{"text":"initWithName:email:phone:brief:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/jivosdk\/jivosdksessionclientinfo\/init(name:email:phone:brief:)","abstract":[],"title":"init(name:email:phone:brief:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/init(name:email:phone:brief:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"email"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"phone","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"brief","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"deprecated":true,"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionClientInfo":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JivoSDKSessionClientInfo"}],"abstract":[],"deprecated":true,"title":"JivoSDKSessionClientInfo","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JivoSDKSessionClientInfo","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdksessionclientinfo"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"JivoSDKSessionClientInfo","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"text":"JivoSDKSessionClientInfo","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"JivoSDKSessionClientInfo"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/debugDescription"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/init()","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionClientInfo\/init(name:email:phone:brief:)"]}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"JivoSDKSessionClientInfo","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionClientInfo~1init()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionClientInfo~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"op":"replace"},{"value":"debugDescription","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionClientInfo~1debugDescription\/title","op":"replace"},{"value":[{"kind":"identifier","text":"debugDescription"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionClientInfo~1debugDescription\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionClientInfo~1init(name:email:phone:brief:)\/title","value":"initWithName:email:phone:brief:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithName:email:phone:brief:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionClientInfo~1init(name:email:phone:brief:)\/fragments"},{"value":"JivoSDKSessionClientInfo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionClientInfo\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"JivoSDKSessionClientInfo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionClientInfo\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}