{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(JivoSDKChattingConfig) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JivoSDKChattingConfig","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKChattingConfig","kind":"identifier"}],"roleHeading":"Class","platforms":[],"navigatorTitle":[{"text":"JivoSDKChattingConfig","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"title":"JivoSDKChattingConfig","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig"},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingconfig"]},{"paths":["\/documentation\/jivosdk\/jivosdkchattingconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"],"title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig\/init(locale:icon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig\/init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)"],"title":"Initializers"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingConfig/init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig\/init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","title":"init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"locale","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"useDefaultIcon"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"customIcon"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"titlePlaceholder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"titleColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"text":"subtitleCaption","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"subtitleColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outgoingColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":"?, ","kind":"text"},{"text":"inputPlaceholder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inputPrefill"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"activeMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"offlineMessage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"outcomingPalette","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKChattingPaletteAlias","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithLocale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdkchattingconfig\/init(locale:usedefaulticon:customicon:titleplaceholder:titlecolor:subtitlecaption:subtitlecolor:outgoingcolor:inputplaceholder:inputprefill:activemessage:offlinemessage:outcomingpalette:)","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingConfig":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdkchattingconfig","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingConfig","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingConfig"}],"title":"JivoSDKChattingConfig","type":"topic","abstract":[]},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingConfig/init(locale:icon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)":{"abstract":[],"kind":"symbol","title":"init(locale:icon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","url":"\/documentation\/jivosdk\/jivosdkchattingconfig\/init(locale:icon:titleplaceholder:titlecolor:subtitlecaption:subtitlecolor:outgoingcolor:inputplaceholder:inputprefill:activemessage:offlinemessage:outcomingpalette:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"locale","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"icon","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7JivoSDK0A20SDKTitleBarIconStyleO","text":"JivoSDKTitleBarIconStyle","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"titlePlaceholder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"titleColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?, ","kind":"text"},{"text":"subtitleCaption","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"subtitleColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"text":"outgoingColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inputPlaceholder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"inputPrefill","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"activeMessage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"offlineMessage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"outcomingPalette","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JivoSDKChattingPaletteAlias","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig\/init(locale:icon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","role":"symbol","deprecated":true,"type":"topic"},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"JivoSDKChattingConfig","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"JivoSDKChattingConfig","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JivoSDKChattingConfig"}],"op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig\/init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKChattingConfig","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]}},{"value":"initWithLocale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig~1init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig~1init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithLocale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig\/title","value":"JivoSDKChattingConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig\/fragments","value":[{"text":"JivoSDKChattingConfig","kind":"identifier"}]}]}]}