{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"],"type":"conformsTo"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/delegate","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/isDisplaying"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(asksToAppear:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineColor:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineImage:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineText:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(didDisappear:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(willAppear:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:closeButton:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:closeButton:config:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:config:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/present(over:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/present(over:config:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/push(into:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/push(into:config:)"],"title":"Instance Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(JivoSDKChattingUI) "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKChattingUI"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingui"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingui"]}],"sections":[],"metadata":{"platforms":[],"modules":[{"name":"JivoSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKChattingUI"}],"navigatorTitle":[{"text":"JivoSDKChattingUI","kind":"identifier"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","title":"JivoSDKChattingUI","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKChattingUI"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","type":"topic"},"doc://org.cocoapods.JivoSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/present(over:)":{"deprecated":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"over","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":")","kind":"text"}],"title":"present(over:)","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"presentOver:"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/present(over:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/present(over:)","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/init":{"type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"kind":"symbol","title":"init","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/init","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/init","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/push(into:config:)":{"deprecated":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"push"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":", "},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"text":"JivoSDKChattingConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig"},{"kind":"text","text":")"}],"title":"push(into:config:)","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"pushInto:withConfig:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/push(into:config:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/push(into:config:)","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/isDisplaying":{"deprecated":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isDisplaying","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","title":"isDisplaying","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isDisplaying"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/isdisplaying","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/isDisplaying","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/jivoDisplay(didDisappear:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(didDisappear:)","title":"jivoDisplay(didDisappear:)","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoDisplay","kind":"identifier"},{"kind":"text","text":"("},{"text":"didDisappear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":")","kind":"text"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(diddisappear:)","role":"symbol","abstract":[{"type":"text","text":"Called after the SDK is closed"}],"navigatorTitle":[{"text":"jivoDisplayDidDisappear:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/push(into:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/push(into:)","title":"push(into:)","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"push","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController"},{"text":")","kind":"text"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/push(into:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"pushInto:"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI":{"title":"JivoSDKChattingUI","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingUI","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"deprecated":true,"navigatorTitle":[{"text":"JivoSDKChattingUI","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/jivoDisplay(defineImage:forElement:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineImage:forElement:)","title":"jivoDisplay(defineImage:forElement:)","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"defineImage"},{"text":": ","kind":"text"},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"forElement","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(defineimage:forelement:)","role":"symbol","abstract":[{"type":"text","text":"DEPRECATED"},{"type":"text","text":" "},{"text":"Please use Jivo.display.define(image:forElement:) instead","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"jivoDisplayDefineImage:forElement:"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/place(within:)":{"navigatorTitle":[{"text":"placeWithin:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:)","type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattingui\/place(within:)","title":"place(within:)","role":"symbol","deprecated":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"place"},{"kind":"text","text":"("},{"text":"within","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController"},{"kind":"text","text":")"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/jivoDisplay(defineText:forElement:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineText:forElement:)","title":"jivoDisplay(defineText:forElement:)","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"defineText"},{"text":": ","kind":"text"},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"forElement","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","kind":"typeIdentifier","text":"JVDisplayElement"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(definetext:forelement:)","role":"symbol","abstract":[{"type":"text","text":"DEPRECATED"},{"text":" ","type":"text"},{"type":"text","text":"Please use Jivo.display.define(text:forElement:) instead"}],"navigatorTitle":[{"text":"jivoDisplayDefineText:forElement:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/jivoDisplay(defineColor:forElement:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineColor:forElement:)","title":"jivoDisplay(defineColor:forElement:)","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"defineColor"},{"text":": ","kind":"text"},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"forElement","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?","kind":"text"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(definecolor:forelement:)","role":"symbol","abstract":[{"type":"text","text":"DEPRECATED"},{"type":"text","text":" "},{"text":"Please use Jivo.display.define(color:forElement:) instead","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"jivoDisplayDefineColor:forElement:"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/place(within:closeButton:config:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:closeButton:config:)","title":"place(within:closeButton:config:)","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"place","kind":"identifier"},{"text":"(","kind":"text"},{"text":"within","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"closeButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton","text":"JivoSDKChattingCloseButton"},{"text":", ","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"text":"JivoSDKChattingConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig"},{"text":")","kind":"text"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/place(within:closebutton:config:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"placeWithin:closeButton:withConfig:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/delegate":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/delegate","title":"delegate","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(pl)JivoSDKChattingUIDelegate","text":"JivoSDKChattingUIDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/delegate","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/present(over:config:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/present(over:config:)","title":"present(over:config:)","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"kind":"text","text":"("},{"text":"over","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"text":"JivoSDKChattingConfig","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/present(over:config:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"presentOver:withConfig:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/place(within:config:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:config:)","title":"place(within:config:)","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"place","kind":"identifier"},{"kind":"text","text":"("},{"text":"within","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"text":", ","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig","text":"JivoSDKChattingConfig","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/place(within:config:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"placeWithin:withConfig:"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate","url":"\/documentation\/jivosdk\/jvdisplaydelegate","title":"JVDisplayDelegate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"JVDisplayDelegate","kind":"identifier"}],"abstract":[{"text":"Interface to control displaying lifecycle,","type":"text"},{"type":"text","text":" "},{"text":"relates to ","type":"text"},{"code":"Jivo.display","type":"codeVoice"},{"type":"text","text":" namespace"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayDelegate"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/jivoDisplay(willAppear:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(willAppear:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"kind":"text","text":"("},{"text":"willAppear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Called before opening the SDK"}],"deprecated":true,"navigatorTitle":[{"text":"jivoDisplayWillAppear:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(willappear:)","role":"symbol","title":"jivoDisplay(willAppear:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/place(within:closeButton:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:closeButton:)","title":"place(within:closeButton:)","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"place","kind":"identifier"},{"kind":"text","text":"("},{"text":"within","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"text":", ","kind":"text"},{"text":"closeButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"JivoSDKChattingCloseButton","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/place(within:closebutton:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"placeWithin:closeButton:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI/jivoDisplay(asksToAppear:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(asksToAppear:)","title":"jivoDisplay(asksToAppear:)","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"text":"(","kind":"text"},{"text":"asksToAppear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":")","kind":"text"}],"url":"\/documentation\/jivosdk\/jivosdkchattingui\/jivodisplay(askstoappear:)","role":"symbol","abstract":[{"text":"Called when SDK needs to display chat UI on screen","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"jivoDisplayAsksToAppear:"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"JivoSDKChattingUI","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JivoSDKChattingUI","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"JivoSDKChattingUI"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/delegate","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/isDisplaying"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/init","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(asksToAppear:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineColor:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineImage:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(defineText:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(didDisappear:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/jivoDisplay(willAppear:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:closeButton:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:closeButton:config:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/place(within:config:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/present(over:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/present(over:config:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/push(into:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI\/push(into:config:)"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate"],"title":"Conforms To","type":"conformsTo"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKChattingUI"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"presentOver:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1present(over:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1present(over:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentOver:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1push(into:config:)\/title","op":"replace","value":"pushInto:withConfig:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pushInto:withConfig:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1push(into:config:)\/fragments"},{"value":"isDisplaying","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1isDisplaying\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1isDisplaying\/fragments","value":[{"text":"isDisplaying","kind":"identifier"}]},{"value":"jivoDisplayDidDisappear:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(didDisappear:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(didDisappear:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"jivoDisplayDidDisappear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1push(into:)\/title","value":"pushInto:"},{"value":[{"kind":"text","text":"- "},{"text":"pushInto:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1push(into:)\/fragments"},{"value":"JivoSDKChattingUI","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingUI"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(defineImage:forElement:)\/title","value":"jivoDisplayDefineImage:forElement:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jivoDisplayDefineImage:forElement:"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(defineImage:forElement:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:)\/title","op":"replace","value":"placeWithin:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"placeWithin:"}],"op":"replace"},{"value":"jivoDisplayDefineText:forElement:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(defineText:forElement:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(defineText:forElement:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoDisplayDefineText:forElement:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(defineColor:forElement:)\/title","value":"jivoDisplayDefineColor:forElement:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(defineColor:forElement:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"jivoDisplayDefineColor:forElement:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:closeButton:config:)\/title","value":"placeWithin:closeButton:withConfig:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"placeWithin:closeButton:withConfig:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:closeButton:config:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1delegate\/title","op":"replace","value":"delegate"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1present(over:config:)\/title","op":"replace","value":"presentOver:withConfig:"},{"value":[{"kind":"text","text":"- "},{"text":"presentOver:withConfig:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1present(over:config:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:config:)\/title","value":"placeWithin:withConfig:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:config:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"placeWithin:withConfig:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"JVDisplayDelegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/fragments","value":[{"kind":"identifier","text":"JVDisplayDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(willAppear:)\/title","value":"jivoDisplayWillAppear:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"jivoDisplayWillAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(willAppear:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:closeButton:)\/title","value":"placeWithin:closeButton:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"placeWithin:closeButton:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1place(within:closeButton:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(asksToAppear:)\/title","value":"jivoDisplayAsksToAppear:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI~1jivoDisplay(asksToAppear:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"jivoDisplayAsksToAppear:","kind":"identifier"}],"op":"replace"}]}]}