{"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/jivoSession(updateUnreadCounter:number:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setClientInfo(_:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setCustomData(fields:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setPreferredServer(_:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/shutDown()","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/startUp(channelID:userToken:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/updateCustomData(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(JivoSDKSession) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKSession"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKSession","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKSession"}],"platforms":[],"symbolKind":"class","role":"symbol","roleHeading":"Class","title":"JivoSDKSession","externalID":"c:@M@JivoSDK@objc(cs)JivoSDKSession","modules":[{"name":"JivoSDK"}]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdksession"]},{"paths":["\/documentation\/jivosdk\/jivosdksession"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"url":"\/documentation\/jivosdk\/jivosdksession\/init","title":"init","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/init","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","abstract":[]},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/startUp(channelID:userToken:)":{"url":"\/documentation\/jivosdk\/jivosdksession\/startup(channelid:usertoken:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/startUp(channelID:userToken:)","deprecated":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startUpWithChannelID:userToken:"}],"abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startUp","kind":"identifier"},{"text":"(","kind":"text"},{"text":"channelID","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"JVClient","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVClient"}],"title":"startUp(channelID:userToken:)"},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionDelegate":{"abstract":[{"type":"text","text":"Interface to handle session events,"},{"text":" ","type":"text"},{"type":"text","text":"relates to "},{"code":"Jivo.session","type":"codeVoice"},{"text":" namespace","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVSessionDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"JVSessionDelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate","navigatorTitle":[{"text":"JVSessionDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/jivosdk\/jvsessiondelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/delegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(pl)JivoSDKSessionDelegate","text":"JivoSDKSessionDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/delegate","url":"\/documentation\/jivosdk\/jivosdksession\/delegate","role":"symbol","title":"delegate","type":"topic","deprecated":true,"abstract":[]},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession":{"deprecated":true,"url":"\/documentation\/jivosdk\/jivosdksession","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"JivoSDKSession","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKSession","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","title":"JivoSDKSession"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/jivoSession(updateUnreadCounter:number:)":{"abstract":[{"type":"text","text":"Called when unread counter changes"}],"title":"jivoSession(updateUnreadCounter:number:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/jivoSession(updateUnreadCounter:number:)","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdksession\/jivosession(updateunreadcounter:number:)","navigatorTitle":[{"text":"jivoSessionUpdateUnreadCounter:number:","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"updateUnreadCounter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":", ","kind":"text"},{"text":"number","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/shutDown()":{"url":"\/documentation\/jivosdk\/jivosdksession\/shutdown()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"shutDown","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shutDown"}],"title":"shutDown()","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/shutDown()","role":"symbol","abstract":[],"deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/setClientInfo(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setClientInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"JivoSDKSessionClientInfo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionClientInfo","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setClientInfo(_:)","deprecated":true,"url":"\/documentation\/jivosdk\/jivosdksession\/setclientinfo(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setClientInfo:"}],"title":"setClientInfo(_:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/setCustomData(fields:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCustomData","kind":"identifier"},{"kind":"text","text":"("},{"text":"fields","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"JivoSDKSessionCustomDataField","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionCustomDataField"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setCustomData:"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setCustomData(fields:)","url":"\/documentation\/jivosdk\/jivosdksession\/setcustomdata(fields:)","role":"symbol","title":"setCustomData(fields:)","type":"topic","deprecated":true,"abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/setPreferredServer(_:)":{"url":"\/documentation\/jivosdk\/jivosdksession\/setpreferredserver(_:)","type":"topic","kind":"symbol","role":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setPreferredServer(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setPreferredServer","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKSessionServer","kind":"typeIdentifier","text":"JivoSDKSessionServer"},{"kind":"text","text":")"}],"abstract":[],"navigatorTitle":[{"text":"setPreferredServer:","kind":"identifier"}],"title":"setPreferredServer(_:)"},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession/updateCustomData(_:)":{"role":"symbol","title":"updateCustomData(_:)","type":"topic","url":"\/documentation\/jivosdk\/jivosdksession\/updatecustomdata(_:)","navigatorTitle":[{"text":"updateCustomData:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/updateCustomData(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCustomData"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSessionCustomData","text":"JivoSDKSessionCustomData"},{"text":"?)","kind":"text"}],"abstract":[],"kind":"symbol","deprecated":true},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"JivoSDKSession","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"JivoSDKSession"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"JivoSDKSession","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/delegate"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/init","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/jivoSession(updateUnreadCounter:number:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setClientInfo(_:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setCustomData(fields:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/setPreferredServer(_:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/shutDown()","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/startUp(channelID:userToken:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession\/updateCustomData(_:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate"],"title":"Conforms To","type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKSession","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"startUpWithChannelID:userToken:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1startUp(channelID:userToken:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1startUp(channelID:userToken:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"startUpWithChannelID:userToken:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/title","value":"JVSessionDelegate","op":"replace"},{"value":[{"text":"JVSessionDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/fragments"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1delegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","value":"JivoSDKSession","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/fragments","value":[{"kind":"identifier","text":"JivoSDKSession"}]},{"value":"jivoSessionUpdateUnreadCounter:number:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1jivoSession(updateUnreadCounter:number:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1jivoSession(updateUnreadCounter:number:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoSessionUpdateUnreadCounter:number:"}]},{"value":"shutDown","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1shutDown()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"shutDown"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1shutDown()\/fragments"},{"value":"setClientInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1setClientInfo(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setClientInfo:"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1setClientInfo(_:)\/fragments","op":"replace"},{"value":"setCustomData:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1setCustomData(fields:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1setCustomData(fields:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setCustomData:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1setPreferredServer(_:)\/title","value":"setPreferredServer:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setPreferredServer:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1setPreferredServer(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1updateCustomData(_:)\/title","value":"updateCustomData:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession~1updateCustomData(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateCustomData:"}],"op":"replace"}]}]}