{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(JivoSDKNotificationsPermissionAskingMoment) "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMoment"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"variants":[{"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment"]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMoment"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKNotificationsPermissionAskingMoment","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"platforms":[],"title":"JivoSDKNotificationsPermissionAskingMoment","externalID":"c:@M@JivoSDK@E@JivoSDKNotificationsPermissionAskingMoment","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/never","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onAppear","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onConnect","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onSend"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/init(rawValue:)"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"kind":"symbol","relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"]}],"references":{"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment/RawRepresentable-Implementations":{"abstract":[],"kind":"article","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/RawRepresentable-Implementations","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/rawrepresentable-implementations"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment/onConnect":{"type":"topic","title":"JivoSDKNotificationsPermissionAskingMoment.onConnect","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/onconnect","role":"symbol","abstract":[],"navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnConnect","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onConnect","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConnect","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment/init(rawValue:)":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/init(rawValue:)","type":"topic","role":"symbol","kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/init(rawvalue:)","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","title":"JivoSDK","abstract":[],"url":"\/documentation\/jivosdk","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment/onAppear":{"navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnAppear","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onAppear"}],"abstract":[],"kind":"symbol","title":"JivoSDKNotificationsPermissionAskingMoment.onAppear","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onAppear","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/onappear"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment/onSend":{"abstract":[],"role":"symbol","type":"topic","title":"JivoSDKNotificationsPermissionAskingMoment.onSend","navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMomentOnSend"}],"deprecated":true,"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSend","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/onsend","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onSend"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment/never":{"deprecated":true,"navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingMomentNever","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/never","role":"symbol","type":"topic","title":"JivoSDKNotificationsPermissionAskingMoment.never","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/never","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"never","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment":{"type":"topic","navigatorTitle":[{"text":"JivoSDKNotificationsPermissionAskingMoment","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKNotificationsPermissionAskingMoment","kind":"identifier"}],"role":"symbol","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment","kind":"symbol","title":"JivoSDKNotificationsPermissionAskingMoment"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotificationsPermissionAskingMoment/Equatable-Implementations":{"type":"topic","abstract":[],"title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/Equatable-Implementations","url":"\/documentation\/jivosdk\/jivosdknotificationspermissionaskingmoment\/equatable-implementations","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"JivoSDKNotificationsPermissionAskingMoment"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"JivoSDKNotificationsPermissionAskingMoment","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"JivoSDKNotificationsPermissionAskingMoment","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/never","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onAppear","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onConnect","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotificationsPermissionAskingMoment\/onSend"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMoment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"JivoSDKNotificationsPermissionAskingMomentOnConnect","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1onConnect\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1onConnect\/fragments","value":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnConnect","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1onAppear\/title","value":"JivoSDKNotificationsPermissionAskingMomentOnAppear","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1onAppear\/fragments","op":"replace","value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMomentOnAppear"}]},{"value":"JivoSDKNotificationsPermissionAskingMomentOnSend","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1onSend\/title"},{"value":[{"text":"JivoSDKNotificationsPermissionAskingMomentOnSend","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1onSend\/fragments"},{"op":"replace","value":"JivoSDKNotificationsPermissionAskingMomentNever","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1never\/title"},{"value":[{"kind":"identifier","text":"JivoSDKNotificationsPermissionAskingMomentNever"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment~1never\/fragments"},{"value":"JivoSDKNotificationsPermissionAskingMoment","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment\/title"},{"value":[{"text":"JivoSDKNotificationsPermissionAskingMoment","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotificationsPermissionAskingMoment\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}