{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdksessiondelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdksessiondelegate"]}],"metadata":{"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"JivoSDKSessionDelegate","kind":"identifier"}],"externalID":"c:@M@JivoSDK@objc(pl)JivoSDKSessionDelegate","navigatorTitle":[{"text":"JivoSDKSessionDelegate","kind":"identifier"}],"platforms":[],"symbolKind":"protocol","modules":[{"name":"JivoSDK"}],"title":"JivoSDKSessionDelegate","role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionDelegate"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(JivoSDKSessionDelegate) ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKSessionDelegate"}]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionDelegate":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionDelegate","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKSessionDelegate"}],"title":"JivoSDKSessionDelegate","url":"\/documentation\/jivosdk\/jivosdksessiondelegate","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKSessionDelegate","kind":"identifier"}],"deprecated":true,"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"JivoSDKSessionDelegate","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"JivoSDKSessionDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"JivoSDKSessionDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"JivoSDKSessionDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionDelegate\/title","op":"replace","value":"JivoSDKSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionDelegate\/fragments","value":[{"text":"JivoSDKSessionDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}