{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"metadata":{"platforms":[],"symbolKind":"enum","externalID":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingCloseButton"}],"title":"JivoSDKChattingCloseButton","modules":[{"name":"JivoSDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKChattingCloseButton"}],"roleHeading":"Enumeration"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/back","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/dismiss","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/omit"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(JivoSDKChattingCloseButton) "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKChattingCloseButton"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingclosebutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingclosebutton"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton/RawRepresentable-Implementations":{"url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/RawRepresentable-Implementations","role":"collectionGroup","kind":"article","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton/Equatable-Implementations":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/Equatable-Implementations","abstract":[],"kind":"article","url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","type":"topic","kind":"symbol","abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton/omit":{"deprecated":true,"url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton\/omit","title":"JivoSDKChattingCloseButton.omit","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"omit","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/omit","navigatorTitle":[{"text":"JivoSDKChattingCloseButtonOmit","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton":{"title":"JivoSDKChattingCloseButton","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKChattingCloseButton","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingCloseButton"}],"kind":"symbol","deprecated":true,"url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton","type":"topic"},"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.JivoSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","deprecated":true,"url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton\/init(rawvalue:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/init(rawValue:)","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton/back":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/back","abstract":[],"kind":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingCloseButtonBack"}],"url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton\/back","role":"symbol","title":"JivoSDKChattingCloseButton.back","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"back"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton/dismiss":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/dismiss","kind":"symbol","abstract":[],"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingCloseButtonDismiss"}],"url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton\/dismiss","role":"symbol","title":"JivoSDKChattingCloseButton.dismiss","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"JivoSDKChattingCloseButton","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingCloseButton"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"JivoSDKChattingCloseButton","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/back","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/dismiss","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/omit"]}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKChattingCloseButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"JivoSDKChattingCloseButtonOmit","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton~1omit\/title"},{"value":[{"text":"JivoSDKChattingCloseButtonOmit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton~1omit\/fragments"},{"op":"replace","value":"JivoSDKChattingCloseButton","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton\/title"},{"value":[{"kind":"identifier","text":"JivoSDKChattingCloseButton"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton\/fragments","op":"replace"},{"op":"replace","value":"JivoSDKChattingCloseButtonBack","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton~1back\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton~1back\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingCloseButtonBack"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton~1dismiss\/title","op":"replace","value":"JivoSDKChattingCloseButtonDismiss"},{"value":[{"text":"JivoSDKChattingCloseButtonDismiss","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton~1dismiss\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}