{"variants":[{"paths":["\/documentation\/jivosdk\/jivosdkchattinguidelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattinguidelegate"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(JivoSDKChattingUIDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKChattingUIDelegate","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"symbolKind":"protocol","modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(pl)JivoSDKChattingUIDelegate","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingUIDelegate"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKChattingUIDelegate"}],"title":"JivoSDKChattingUIDelegate","role":"symbol","platforms":[]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(didDisappear:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(didRequestShowing:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(willAppear:)"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUIDelegate/jivo(willAppear:)":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(willAppear:)","navigatorTitle":[{"kind":"identifier","text":"jivoWillAppear:"}],"deprecated":true,"url":"\/documentation\/jivosdk\/jivosdkchattinguidelegate\/jivo(willappear:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"willAppear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK"},{"text":")","kind":"text"}],"title":"jivo(willAppear:)","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUIDelegate/jivo(didDisappear:)":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(didDisappear:)","navigatorTitle":[{"kind":"identifier","text":"jivoDidDisappear:"}],"deprecated":true,"url":"\/documentation\/jivosdk\/jivosdkchattinguidelegate\/jivo(diddisappear:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivo"},{"kind":"text","text":"("},{"text":"didDisappear","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK"},{"text":")","kind":"text"}],"title":"jivo(didDisappear:)","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"type":"topic","title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUIDelegate/jivo(didRequestShowing:)":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(didRequestShowing:)","navigatorTitle":[{"kind":"identifier","text":"jivoDidRequestShowing:"}],"deprecated":true,"url":"\/documentation\/jivosdk\/jivosdkchattinguidelegate\/jivo(didrequestshowing:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"didRequestShowing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDK","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDK"},{"text":")","kind":"text"}],"title":"jivo(didRequestShowing:)","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUIDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingUIDelegate","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattinguidelegate","title":"JivoSDKChattingUIDelegate","navigatorTitle":[{"text":"JivoSDKChattingUIDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"JivoSDKChattingUIDelegate"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"kind":"identifier","text":"JivoSDKChattingUIDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"JivoSDKChattingUIDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(didDisappear:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(didRequestShowing:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUIDelegate\/jivo(willAppear:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKChattingUIDelegate","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate~1jivo(willAppear:)\/title","value":"jivoWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate~1jivo(willAppear:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate~1jivo(didDisappear:)\/title","value":"jivoDidDisappear:"},{"value":[{"text":"- ","kind":"text"},{"text":"jivoDidDisappear:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate~1jivo(didDisappear:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate~1jivo(didRequestShowing:)\/title","value":"jivoDidRequestShowing:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate~1jivo(didRequestShowing:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoDidRequestShowing:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate\/title","op":"replace","value":"JivoSDKChattingUIDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUIDelegate\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingUIDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}