{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvappdelegate"]},{"paths":["\/documentation\/jivosdk\/jvappdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/bannerPresentingDelegate"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didFailToRegisterForRemoteNotificationsWithError:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didFinishLaunchingWithOptions:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/jivoApp(bannerPresentation:target:category:notification:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)"],"anchor":"Instance-Methods"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/UIApplicationDelegate-Implementations"],"title":"Default Implementations"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)UIResponder"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/s8SendableP","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIApplicationDelegate","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UNUserNotificationCenterDelegate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(JVAppDelegate) "},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JVAppDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"class","modules":[{"name":"JivoSDK"}],"title":"JVAppDelegate","platforms":[],"roleHeading":"Class","externalID":"c:@M@JivoSDK@objc(cs)JVAppDelegate","role":"symbol","navigatorTitle":[{"text":"JVAppDelegate","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVAppDelegate","kind":"identifier"}]},"abstract":[{"text":"Feel free to use this class as parent for your own App Delegate, for easier SDK integration","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.JivoSDK/objc(pl)UNUserNotificationCenterDelegate":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UNUserNotificationCenterDelegate","title":"UNUserNotificationCenterDelegate","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/application(_:didFailToRegisterForRemoteNotificationsWithError:)":{"deprecated":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didFailToRegisterForRemoteNotificationsWithError:)","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/jivosdk\/jvappdelegate\/application(_:didfailtoregisterforremotenotificationswitherror:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didFailToRegisterForRemoteNotificationsWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"application:didFailToRegisterForRemoteNotificationsWithError:"}],"kind":"symbol","title":"application(_:didFailToRegisterForRemoteNotificationsWithError:)"},"doc://org.cocoapods.JivoSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/UIApplicationDelegate-Implementations":{"kind":"article","abstract":[],"title":"UIApplicationDelegate Implementations","url":"\/documentation\/jivosdk\/jvappdelegate\/uiapplicationdelegate-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/UIApplicationDelegate-Implementations"},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)":{"title":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","kind":"symbol","url":"\/documentation\/jivosdk\/jvappdelegate\/application(_:didreceiveremotenotification:fetchcompletionhandler:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}],"deprecated":true,"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"text":"fetchCompletionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@E@UIBackgroundFetchResult","kind":"typeIdentifier","text":"UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/userNotificationCenter(_:didReceive:withCompletionHandler:)":{"navigatorTitle":[{"text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvappdelegate\/usernotificationcenter(_:didreceive:withcompletionhandler:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotificationCenter"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","text":"UNUserNotificationCenter","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationResponse","text":"UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","deprecated":true,"title":"userNotificationCenter(_:didReceive:withCompletionHandler:)"},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/userNotificationCenter(_:willPresent:withCompletionHandler:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"userNotificationCenter:willPresentNotification:withCompletionHandler:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotificationCenter"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","text":"UNUserNotificationCenter"},{"kind":"text","text":", "},{"text":"willPresent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": ("},{"text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"userNotificationCenter(_:willPresent:withCompletionHandler:)","abstract":[],"role":"symbol","deprecated":true,"url":"\/documentation\/jivosdk\/jvappdelegate\/usernotificationcenter(_:willpresent:withcompletionhandler:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)","kind":"symbol"},"doc://org.cocoapods.JivoSDK/objc(pl)UIApplicationDelegate":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIApplicationDelegate","title":"UIApplicationDelegate","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/bannerPresentingDelegate":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/bannerPresentingDelegate","abstract":[],"deprecated":true,"type":"topic","kind":"symbol","title":"bannerPresentingDelegate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerPresentingDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVAppBannerPresentingDelegate","text":"JVAppBannerPresentingDelegate"},{"text":"?","kind":"text"}],"url":"\/documentation\/jivosdk\/jvappdelegate\/bannerpresentingdelegate"},"doc://org.cocoapods.JivoSDK/SH":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)":{"navigatorTitle":[{"text":"application:didRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":", "},{"text":"didRegisterForRemoteNotificationsWithDeviceToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvappdelegate\/application(_:didregisterforremotenotificationswithdevicetoken:)","title":"application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","role":"symbol"},"doc://org.cocoapods.JivoSDK/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/application(_:didFinishLaunchingWithOptions:)":{"navigatorTitle":[{"text":"application:didFinishLaunchingWithOptions:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"text":": [","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey","kind":"typeIdentifier","text":"LaunchOptionsKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/jivosdk\/jvappdelegate\/application(_:didfinishlaunchingwithoptions:)","type":"topic","title":"application(_:didFinishLaunchingWithOptions:)","deprecated":true,"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didFinishLaunchingWithOptions:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate":{"url":"\/documentation\/jivosdk\/jvappdelegate","abstract":[{"type":"text","text":"Feel free to use this class as parent for your own App Delegate, for easier SDK integration"}],"title":"JVAppDelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JVAppDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"JVAppDelegate","kind":"identifier"}],"type":"topic","deprecated":true,"role":"symbol"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvappdelegate\/init","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/init","role":"symbol","title":"init"},"doc://org.cocoapods.JivoSDK/objc(cs)UIResponder":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)UIResponder","title":"UIResponder","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppBannerPresentingDelegate":{"title":"JVAppBannerPresentingDelegate","navigatorTitle":[{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}],"kind":"symbol","deprecated":true,"abstract":[{"text":"Determines a way incoming notifications gets displayed","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate","url":"\/documentation\/jivosdk\/jvappbannerpresentingdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/jivoApp(bannerPresentation:target:category:notification:)":{"navigatorTitle":[{"text":"jivoAppBannerPresentation:target:category:notification:","kind":"identifier"}],"abstract":[{"text":"Here you can determine UNNotificationPresentationOptions","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to be applied for foreground notifications"}],"deprecated":true,"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/jivosdk\/jvappdelegate\/jivoapp(bannerpresentation:target:category:notification:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/jivoApp(bannerPresentation:target:category:notification:)","title":"jivoApp(bannerPresentation:target:category:notification:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoApp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerPresentation"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget","text":"JVNotificationsTarget"},{"kind":"text","text":", "},{"kind":"externalParam","text":"category"},{"text":": ","kind":"text"},{"text":"JVNotificationsCategory","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsCategory"},{"kind":"text","text":", "},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":") -> ","kind":"text"},{"text":"UNNotificationPresentationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"replace","value":[]},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"JVAppDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JVAppDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"JVAppDelegate","kind":"identifier"}]},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didFailToRegisterForRemoteNotificationsWithError:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didFinishLaunchingWithOptions:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/init","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/jivoApp(bannerPresentation:target:category:notification:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)UIResponder"],"kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIApplicationDelegate","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UNUserNotificationCenterDelegate"],"title":"Conforms To","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"JVAppDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIResponder","text":"UIResponder","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1application(_:didFailToRegisterForRemoteNotificationsWithError:)\/title","op":"replace","value":"application:didFailToRegisterForRemoteNotificationsWithError:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1application(_:didFailToRegisterForRemoteNotificationsWithError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"application:didFailToRegisterForRemoteNotificationsWithError:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/title","value":"application:didReceiveRemoteNotification:fetchCompletionHandler:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"application:didReceiveRemoteNotification:fetchCompletionHandler:","kind":"identifier"}],"op":"replace"},{"value":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1userNotificationCenter(_:willPresent:withCompletionHandler:)\/title","value":"userNotificationCenter:willPresentNotification:withCompletionHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1userNotificationCenter(_:willPresent:withCompletionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userNotificationCenter:willPresentNotification:withCompletionHandler:","kind":"identifier"}]},{"op":"replace","value":"application:didRegisterForRemoteNotificationsWithDeviceToken:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1application(_:didRegisterForRemoteNotificationsWithDeviceToken:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"application:didRegisterForRemoteNotificationsWithDeviceToken:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1application(_:didRegisterForRemoteNotificationsWithDeviceToken:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1application(_:didFinishLaunchingWithOptions:)\/title","op":"replace","value":"application:didFinishLaunchingWithOptions:"},{"value":[{"text":"- ","kind":"text"},{"text":"application:didFinishLaunchingWithOptions:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1application(_:didFinishLaunchingWithOptions:)\/fragments","op":"replace"},{"op":"replace","value":"JVAppDelegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/title"},{"value":[{"text":"JVAppDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"JVAppDelegate"}]},{"op":"replace","value":"JVAppBannerPresentingDelegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/title"},{"value":[{"text":"JVAppBannerPresentingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1jivoApp(bannerPresentation:target:category:notification:)\/title","op":"replace","value":"jivoAppBannerPresentation:target:category:notification:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"jivoAppBannerPresentation:target:category:notification:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1jivoApp(bannerPresentation:target:category:notification:)\/fragments"}]}]}