{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(JVAppBannerPresentingDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jvappbannerpresentingdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvappbannerpresentingdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Determines a way incoming notifications gets displayed"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}],"title":"JVAppBannerPresentingDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@JivoSDK@objc(pl)JVAppBannerPresentingDelegate","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate\/jivoApp(bannerPresentation:target:event:notification:)"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate":{"role":"symbol","title":"JVAppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVAppDelegate"}],"abstract":[{"type":"text","text":"Feel free to use this class as parent for your own App Delegate, for easier SDK integration"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVAppDelegate"}],"url":"\/documentation\/jivosdk\/jvappdelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppBannerPresentingDelegate":{"role":"symbol","title":"JVAppBannerPresentingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}],"abstract":[{"type":"text","text":"Determines a way incoming notifications gets displayed"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}],"url":"\/documentation\/jivosdk\/jvappbannerpresentingdelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppBannerPresentingDelegate/jivoApp(bannerPresentation:target:event:notification:)":{"navigatorTitle":[{"kind":"identifier","text":"jivoAppBannerPresentation:target:event:notification:"}],"role":"symbol","title":"jivoApp(bannerPresentation:target:event:notification:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoApp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerPresentation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVNotificationsTarget","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget"},{"kind":"text","text":", "},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVNotificationsEvent","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"}],"abstract":[{"type":"text","text":"Here you can determine UNNotificationPresentationOptions"},{"type":"text","text":" "},{"type":"text","text":"to be applied for foreground notifications"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate\/jivoApp(bannerPresentation:target:event:notification:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/jivosdk\/jvappbannerpresentingdelegate\/jivoapp(bannerpresentation:target:event:notification:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"JVAppBannerPresentingDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate\/jivoApp(bannerPresentation:target:event:notification:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/title","value":"JVAppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/fragments","value":[{"kind":"identifier","text":"JVAppDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/title","value":"JVAppBannerPresentingDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/fragments","value":[{"kind":"identifier","text":"JVAppBannerPresentingDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate~1jivoApp(bannerPresentation:target:event:notification:)\/title","value":"jivoAppBannerPresentation:target:event:notification:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate~1jivoApp(bannerPresentation:target:event:notification:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jivoAppBannerPresentation:target:event:notification:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}