{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVClientCustomDataField"},{"kind":"text","text":" = "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionCustomDataField","kind":"typeIdentifier","text":"JVSessionCustomDataField","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionCustomDataField"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientCustomDataField","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"JVClientCustomDataField"}],"externalID":"s:7JivoSDK23JVClientCustomDataFielda","roleHeading":"Type Alias","modules":[{"name":"JivoSDK"}],"title":"JVClientCustomDataField","role":"symbol","symbolKind":"typealias","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"JVClientCustomDataField","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvclientcustomdatafield"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionCustomDataField":{"role":"symbol","navigatorTitle":[{"text":"JVSessionCustomDataField","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionCustomDataField","type":"topic","abstract":[{"text":"Custom Data Field for user","type":"text"}],"title":"JVSessionCustomDataField","url":"\/documentation\/jivosdk\/jvsessioncustomdatafield","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVSessionCustomDataField","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","kind":"symbol","title":"JivoSDK","type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClientCustomDataField":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClientCustomDataField","kind":"symbol","navigatorTitle":[{"text":"JVClientCustomDataField","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","title":"JVClientCustomDataField","url":"\/documentation\/jivosdk\/jvclientcustomdatafield","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVClientCustomDataField","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField\/title","op":"replace","value":"JVSessionCustomDataField"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField\/fragments","op":"replace","value":[{"text":"JVSessionCustomDataField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JVSessionCustomDataField"}]}]}]}