{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"metadata":{"title":"JVClient","navigatorTitle":[{"text":"JVClient","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVClient","kind":"identifier"}],"externalID":"c:@M@JivoSDK@objc(cs)JVClient","symbolKind":"class","roleHeading":"Class","modules":[{"name":"JivoSDK"}]},"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/listenToUnreadCounter(handler:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/setContactInfo(_:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/setCustomData(fields:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/shutDown()"]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvclient"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvclient"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVClient","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.JivoSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient/listenToUnreadCounter(handler:)":{"kind":"symbol","abstract":[{"type":"text","text":"Register your handler to observe the unread counter updates"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listenToUnreadCounter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"listenToUnreadCounter(handler:)","type":"topic","url":"\/documentation\/jivosdk\/jvclient\/listentounreadcounter(handler:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/listenToUnreadCounter(handler:)","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient/setContactInfo(_:)":{"abstract":[{"text":"Assigns contact info to user,","type":"text"},{"text":" ","type":"text"},{"text":"to reach him easier in future","type":"text"}],"title":"setContactInfo(_:)","kind":"symbol","url":"\/documentation\/jivosdk\/jvclient\/setcontactinfo(_:)","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/setContactInfo(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setContactInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JVClientContactInfo","preciseIdentifier":"s:7JivoSDK19JVClientContactInfoa","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient/shutDown()":{"abstract":[{"type":"text","text":"Closes current connection, clears the local database,"},{"type":"text","text":" "},{"type":"text","text":"and unsubscribes device from Push Notifications"}],"kind":"symbol","type":"topic","title":"shutDown()","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/shutDown()","role":"symbol","url":"\/documentation\/jivosdk\/jvclient\/shutdown()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shutDown","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.JivoSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","kind":"symbol","type":"topic","role":"collection","abstract":[],"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient/setCustomData(fields:)":{"abstract":[{"text":"Assigns custom data to user,","type":"text"},{"text":" ","type":"text"},{"text":"if needed for your business","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"JVClientCustomDataField","preciseIdentifier":"s:7JivoSDK23JVClientCustomDataFielda"},{"kind":"text","text":"])"}],"url":"\/documentation\/jivosdk\/jvclient\/setcustomdata(fields:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient\/setCustomData(fields:)","title":"setCustomData(fields:)"},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP"},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVClient":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVClient"}],"title":"JVClient","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVClient"}],"url":"\/documentation\/jivosdk\/jvclient","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVClient","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"JVClient","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"JVClient","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"JVClient","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVClient","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"JVClient","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/title","op":"replace"},{"value":[{"text":"JVClient","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/fragments","op":"replace"},{"value":[{"text":"JVClient","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVClient\/navigatorTitle","op":"replace"}]}]}