{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/ignore","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/keep"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/RawRepresentable-Implementations"],"generated":true}],"abstract":[{"type":"text","text":"SDK behavior for catching logging events"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(JVDebuggingOriginalCatchBehavior) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingOriginalCatchBehavior","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVDebuggingOriginalCatchBehavior","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVDebuggingOriginalCatchBehavior"}],"title":"JVDebuggingOriginalCatchBehavior","symbolKind":"enum","roleHeading":"Enumeration","role":"symbol","modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@E@JVDebuggingOriginalCatchBehavior"},"references":{"doc://org.cocoapods.JivoSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalCatchBehavior/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","abstract":[],"title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/RawRepresentable-Implementations","url":"\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior\/rawrepresentable-implementations"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalCatchBehavior":{"role":"symbol","navigatorTitle":[{"text":"JVDebuggingOriginalCatchBehavior","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"SDK behavior for catching logging events","type":"text"}],"title":"JVDebuggingOriginalCatchBehavior","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingOriginalCatchBehavior","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalCatchBehavior/ignore":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/ignore","url":"\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior\/ignore","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ignore","kind":"identifier"}],"navigatorTitle":[{"text":"JVDebuggingOriginalCatchBehaviorIgnore","kind":"identifier"}],"title":"JVDebuggingOriginalCatchBehavior.ignore","abstract":[{"type":"text","text":"Ignore an event details"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalCatchBehavior/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/Equatable-Implementations","url":"\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior\/equatable-implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalCatchBehavior/keep":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/keep","url":"\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior\/keep","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keep"}],"navigatorTitle":[{"text":"JVDebuggingOriginalCatchBehaviorKeep","kind":"identifier"}],"title":"JVDebuggingOriginalCatchBehavior.keep","abstract":[{"type":"text","text":"Log an event details"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","type":"topic","kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalCatchBehavior/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/init(rawValue:)","url":"\/documentation\/jivosdk\/jvdebuggingoriginalcatchbehavior\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.JivoSDK/SY":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"JVDebuggingOriginalCatchBehavior","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVDebuggingOriginalCatchBehavior"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"JVDebuggingOriginalCatchBehavior","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/ignore","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalCatchBehavior\/keep"]}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDebuggingOriginalCatchBehavior"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"JVDebuggingOriginalCatchBehavior","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior\/title"},{"value":[{"kind":"identifier","text":"JVDebuggingOriginalCatchBehavior"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior~1ignore\/title","value":"JVDebuggingOriginalCatchBehaviorIgnore"},{"op":"replace","value":[{"text":"JVDebuggingOriginalCatchBehaviorIgnore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior~1ignore\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior~1keep\/title","value":"JVDebuggingOriginalCatchBehaviorKeep"},{"value":[{"text":"JVDebuggingOriginalCatchBehaviorKeep","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingOriginalCatchBehavior~1keep\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}