{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdebuggingarchivestatus"]},{"paths":["\/documentation\/jivosdk\/jvdebuggingarchivestatus"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"symbolKind":"enum","title":"JVDebuggingArchiveStatus","role":"symbol","roleHeading":"Enumeration","externalID":"c:@M@JivoSDK@E@JVDebuggingArchiveStatus","navigatorTitle":[{"kind":"identifier","text":"JVDebuggingArchiveStatus"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingArchiveStatus","kind":"identifier"}],"modules":[{"name":"JivoSDK"}]},"kind":"symbol","relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"kind":"relationships","title":"Conforms To"}],"abstract":[{"type":"text","text":"Determines how logs archiving operation was completed"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(JVDebuggingArchiveStatus) "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVDebuggingArchiveStatus","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/failedAccessing","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/failedPreparing","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/success"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/init(rawValue:)"]},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","url":"\/documentation\/jivosdk","type":"topic","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/SH":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/Equatable-Implementations","url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus\/equatable-implementations","kind":"article","type":"topic","title":"Equatable Implementations","role":"collectionGroup"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus/success":{"type":"topic","url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus\/success","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"}],"kind":"symbol","title":"JVDebuggingArchiveStatus.success","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/success","abstract":[{"type":"text","text":"Archive is ready"}],"navigatorTitle":[{"kind":"identifier","text":"JVDebuggingArchiveStatusSuccess"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus/failedAccessing":{"navigatorTitle":[{"text":"JVDebuggingArchiveStatusFailedAccessing","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Failed accessing"}],"url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus\/failedaccessing","title":"JVDebuggingArchiveStatus.failedAccessing","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/failedAccessing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failedAccessing","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus/failedPreparing":{"title":"JVDebuggingArchiveStatus.failedPreparing","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failedPreparing"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/failedPreparing","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"JVDebuggingArchiveStatusFailedPreparing","kind":"identifier"}],"abstract":[{"type":"text","text":"Failed archiving"}],"url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus\/failedpreparing"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus":{"kind":"symbol","role":"symbol","abstract":[{"text":"Determines how logs archiving operation was completed","type":"text"}],"url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDebuggingArchiveStatus"}],"title":"JVDebuggingArchiveStatus","navigatorTitle":[{"kind":"identifier","text":"JVDebuggingArchiveStatus"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/init(rawValue:)","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.JivoSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.JivoSDK/SY":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus/RawRepresentable-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"JVDebuggingArchiveStatus","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JVDebuggingArchiveStatus","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"JVDebuggingArchiveStatus","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/failedAccessing","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/failedPreparing","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus\/success"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingArchiveStatus","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"JVDebuggingArchiveStatusSuccess","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus~1success\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus~1success\/fragments","value":[{"text":"JVDebuggingArchiveStatusSuccess","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus~1failedAccessing\/title","value":"JVDebuggingArchiveStatusFailedAccessing","op":"replace"},{"value":[{"kind":"identifier","text":"JVDebuggingArchiveStatusFailedAccessing"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus~1failedAccessing\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus~1failedPreparing\/title","value":"JVDebuggingArchiveStatusFailedPreparing"},{"value":[{"text":"JVDebuggingArchiveStatusFailedPreparing","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus~1failedPreparing\/fragments","op":"replace"},{"value":"JVDebuggingArchiveStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVDebuggingArchiveStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}