{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingDelegate","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Interface to control debugging process,"},{"text":" ","type":"text"},{"text":"relates to ","type":"text"},{"type":"codeVoice","code":"Jivo.debugging"},{"text":" namespace","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"variants":[{"paths":["\/documentation\/jivosdk\/jvdebuggingdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdebuggingdelegate"]}],"metadata":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingDelegate","kind":"identifier"}],"roleHeading":"Protocol","modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(pl)JVDebuggingDelegate","symbolKind":"protocol","navigatorTitle":[{"text":"JVDebuggingDelegate","kind":"identifier"}],"title":"JVDebuggingDelegate"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingDelegate\/jivoDebugging(catchEvent:text:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(JVDebuggingDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingDelegate","kind":"identifier"}]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingDelegate":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingDelegate","abstract":[{"text":"Interface to control debugging process,","type":"text"},{"type":"text","text":" "},{"text":"relates to ","type":"text"},{"type":"codeVoice","code":"Jivo.debugging"},{"type":"text","text":" namespace"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jvdebuggingdelegate","type":"topic","role":"symbol","title":"JVDebuggingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDebuggingDelegate"}],"navigatorTitle":[{"text":"JVDebuggingDelegate","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","type":"topic","role":"collection","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingDelegate/jivoDebugging(catchEvent:text:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"jivoDebugging","kind":"identifier"},{"kind":"text","text":"("},{"text":"catchEvent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"JVDebuggingOriginalCatchBehavior","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingOriginalCatchBehavior"}],"required":true,"type":"topic","title":"jivoDebugging(catchEvent:text:)","url":"\/documentation\/jivosdk\/jvdebuggingdelegate\/jivodebugging(catchevent:text:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingDelegate\/jivoDebugging(catchEvent:text:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Called when SDK is going to log event,"},{"type":"text","text":" "},{"text":"here you are able to replace the standard behavior with your own implementation","type":"text"}],"navigatorTitle":[{"text":"jivoDebuggingWithCatchEvent:text:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"JVDebuggingDelegate","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"JVDebuggingDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"JVDebuggingDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingDelegate\/jivoDebugging(catchEvent:text:)"],"title":"Instance Methods"}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDebuggingDelegate"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingDelegate\/title","op":"replace","value":"JVDebuggingDelegate"},{"value":[{"kind":"identifier","text":"JVDebuggingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingDelegate~1jivoDebugging(catchEvent:text:)\/title","op":"replace","value":"jivoDebuggingWithCatchEvent:text:"},{"value":[{"text":"- ","kind":"text"},{"text":"jivoDebuggingWithCatchEvent:text:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingDelegate~1jivoDebugging(catchEvent:text:)\/fragments"}]}]}