{"kind":"symbol","metadata":{"modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"JVDebuggingLevel"}],"role":"symbol","externalID":"c:@M@JivoSDK@E@JVDebuggingLevel","title":"JVDebuggingLevel","roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JVDebuggingLevel","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel\/full","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel\/silent"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel\/RawRepresentable-Implementations"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdebugginglevel"]},{"paths":["\/documentation\/jivosdk\/jvdebugginglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(JVDebuggingLevel) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingLevel","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel"},"abstract":[{"type":"text","text":"Level of logging verbosity,"},{"text":" ","type":"text"},{"text":"relates to ","type":"text"},{"type":"codeVoice","code":"Jivo.debugging"},{"type":"text","text":" namespace"}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"kind":"relationships"}],"references":{"doc://org.cocoapods.JivoSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY"},"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingLevel/full":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"}],"abstract":[{"type":"text","text":"Capture everything"}],"navigatorTitle":[{"text":"JVDebuggingLevelFull","kind":"identifier"}],"role":"symbol","title":"JVDebuggingLevel.full","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel\/full","url":"\/documentation\/jivosdk\/jvdebugginglevel\/full"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingLevel/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","url":"\/documentation\/jivosdk\/jvdebugginglevel\/equatable-implementations","title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel\/Equatable-Implementations","type":"topic","kind":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingLevel/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel\/RawRepresentable-Implementations","url":"\/documentation\/jivosdk\/jvdebugginglevel\/rawrepresentable-implementations"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingLevel/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","url":"\/documentation\/jivosdk\/jvdebugginglevel\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel\/init(rawValue:)","type":"topic","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingLevel/silent":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"silent","kind":"identifier"}],"abstract":[{"type":"text","text":"Capture nothing"}],"navigatorTitle":[{"text":"JVDebuggingLevelSilent","kind":"identifier"}],"role":"symbol","title":"JVDebuggingLevel.silent","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel\/silent","url":"\/documentation\/jivosdk\/jvdebugginglevel\/silent"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingLevel":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDebuggingLevel"}],"abstract":[{"type":"text","text":"Level of logging verbosity,"},{"type":"text","text":" "},{"type":"text","text":"relates to "},{"code":"Jivo.debugging","type":"codeVoice"},{"type":"text","text":" namespace"}],"navigatorTitle":[{"text":"JVDebuggingLevel","kind":"identifier"}],"role":"symbol","url":"\/documentation\/jivosdk\/jvdebugginglevel","title":"JVDebuggingLevel","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"JVDebuggingLevel","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"JVDebuggingLevel","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"JVDebuggingLevel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel\/full","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel\/silent"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVDebuggingLevel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"JVDebuggingLevelFull","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingLevel~1full\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingLevel~1full\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVDebuggingLevelFull"}]},{"op":"replace","value":"JVDebuggingLevelSilent","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingLevel~1silent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"JVDebuggingLevelSilent"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingLevel~1silent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingLevel\/title","value":"JVDebuggingLevel"},{"value":[{"text":"JVDebuggingLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingLevel\/fragments"}]}]}