{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(JVDisplayCloseButton) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JVDisplayCloseButton","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Enumeration","navigatorTitle":[{"text":"JVDisplayCloseButton","kind":"identifier"}],"role":"symbol","externalID":"c:@M@JivoSDK@E@JVDisplayCloseButton","title":"JVDisplayCloseButton","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayCloseButton"}],"modules":[{"name":"JivoSDK"}],"symbolKind":"enum"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplayclosebutton"]},{"paths":["\/documentation\/jivosdk\/jvdisplayclosebutton"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"abstract":[{"type":"text","text":"Close Button look"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/back","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/dismiss","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/omit"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/init(rawValue:)"]},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"sections":[],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/init(rawValue:)","abstract":[],"url":"\/documentation\/jivosdk\/jvdisplayclosebutton\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton/Equatable-Implementations":{"url":"\/documentation\/jivosdk\/jvdisplayclosebutton\/equatable-implementations","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/Equatable-Implementations","type":"topic","title":"Equatable Implementations"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton":{"kind":"symbol","title":"JVDisplayCloseButton","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton","abstract":[{"type":"text","text":"Close Button look"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayCloseButton"}],"url":"\/documentation\/jivosdk\/jvdisplayclosebutton","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVDisplayCloseButton","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","url":"\/documentation\/jivosdk","title":"JivoSDK","type":"topic","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton/back":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/back","role":"symbol","url":"\/documentation\/jivosdk\/jvdisplayclosebutton\/back","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayCloseButtonBack"}],"title":"JVDisplayCloseButton.back","kind":"symbol","type":"topic","abstract":[{"text":"Back symbol, like “<”","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/RawRepresentable-Implementations","abstract":[],"kind":"article","type":"topic","url":"\/documentation\/jivosdk\/jvdisplayclosebutton\/rawrepresentable-implementations","role":"collectionGroup"},"doc://org.cocoapods.JivoSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH"},"doc://org.cocoapods.JivoSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton/dismiss":{"abstract":[{"type":"text","text":"Cross symbol, like “X”"}],"kind":"symbol","title":"JVDisplayCloseButton.dismiss","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayCloseButtonDismiss"}],"url":"\/documentation\/jivosdk\/jvdisplayclosebutton\/dismiss","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/dismiss","role":"symbol"},"doc://org.cocoapods.JivoSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayCloseButton/omit":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/omit","role":"symbol","title":"JVDisplayCloseButton.omit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"No symbol"}],"navigatorTitle":[{"text":"JVDisplayCloseButtonOmit","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"omit","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayclosebutton\/omit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"JVDisplayCloseButton","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"JVDisplayCloseButton","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"JVDisplayCloseButton","kind":"identifier"}]},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/back","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/dismiss","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayCloseButton\/omit"]}],"path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayCloseButton"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton\/title","value":"JVDisplayCloseButton","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVDisplayCloseButton"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton~1back\/title","value":"JVDisplayCloseButtonBack","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton~1back\/fragments","value":[{"kind":"identifier","text":"JVDisplayCloseButtonBack"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton~1dismiss\/title","value":"JVDisplayCloseButtonDismiss","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton~1dismiss\/fragments","value":[{"kind":"identifier","text":"JVDisplayCloseButtonDismiss"}],"op":"replace"},{"value":"JVDisplayCloseButtonOmit","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton~1omit\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayCloseButton~1omit\/fragments","value":[{"text":"JVDisplayCloseButtonOmit","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}