{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"text":".","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","isActive":true},{"text":" namespace for SDK displaying","type":"text"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/delegate","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/isOnscreen"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(color:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(image:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(text:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/place(within:closeButton:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/present(over:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/push(into:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setExtraItems(menu:captions:handler:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setLocale(_:)"],"title":"Instance Methods"}],"metadata":{"modules":[{"name":"JivoSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDisplayController"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayController"}],"title":"JVDisplayController","role":"symbol","symbolKind":"class","externalID":"c:@M@JivoSDK@objc(cs)JVDisplayController","roleHeading":"Class"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(JVDisplayController) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVDisplayController","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdisplaycontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplaycontroller"]}],"sections":[],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/push(into:)":{"type":"topic","title":"push(into:)","abstract":[{"type":"text","text":"Places SDK into navigation stack (animated)"}],"url":"\/documentation\/jivosdk\/jvdisplaycontroller\/push(into:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/push(into:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pushInto:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"push","kind":"identifier"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/setExtraItems(menu:captions:handler:)":{"title":"setExtraItems(menu:captions:handler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setExtraItems"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"menu"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JVDisplayMenu","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayMenu"},{"kind":"text","text":", "},{"text":"captions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"handler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/setextraitems(menu:captions:handler:)","navigatorTitle":[{"kind":"identifier","text":"setExtraItemsForMenu:captions:handler:"}],"abstract":[{"text":"Sets your own extra items to display within menu","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setExtraItems(menu:captions:handler:)","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/init":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"title":"init","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/init","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/init"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/place(within:closeButton:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"place"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"within"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController"},{"text":", ","kind":"text"},{"text":"closeButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayCloseButton","text":"JVDisplayCloseButton"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"placeWithin:closeButton:"}],"type":"topic","role":"symbol","abstract":[{"text":"Cleans entire stack of the passed navigationController,","type":"text"},{"text":" ","type":"text"},{"text":"and then places SDK into it (not animated)","type":"text"}],"title":"place(within:closeButton:)","kind":"symbol","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/place(within:closebutton:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/place(within:closeButton:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/present(over:)":{"abstract":[{"type":"text","text":"Displays SDK modally on screen, slides it up from bottom edge (animated)"}],"title":"present(over:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"over"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"presentOver:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/present(over:)","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/present(over:)","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/define(text:forElement:)":{"title":"define(text:forElement:)","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/define(text:forelement:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"define","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"forElement","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","text":"JVDisplayElement","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"defineText:forElement:"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(text:forElement:)","type":"topic","abstract":[{"text":"Here you can customize captions and texts for some elements","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"title":"Jivo","type":"topic","abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","url":"\/documentation\/jivosdk\/jivo","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/define(color:forElement:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/define(color:forelement:)","navigatorTitle":[{"kind":"identifier","text":"defineColor:forElement:"}],"abstract":[{"type":"text","text":"Here you can customize colors for some elements"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(color:forElement:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"define","kind":"identifier"},{"text":"(","kind":"text"},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"text":"forElement","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","text":"JVDisplayElement"},{"text":")","kind":"text"}],"title":"define(color:forElement:)","type":"topic"},"doc://org.cocoapods.JivoSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/define(image:forElement:)":{"abstract":[{"type":"text","text":"Here you can customize icons for some elements"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(image:forElement:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defineImage:forElement:"}],"type":"topic","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/define(image:forelement:)","title":"define(image:forElement:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"define","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forElement"},{"kind":"text","text":": "},{"text":"JVDisplayElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","url":"\/documentation\/jivosdk","title":"JivoSDK","type":"topic","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/delegate":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate","type":"topic","abstract":[{"type":"text","text":"Object that controls displaying lifecycle"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVDisplayDelegate","text":"JVDisplayDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/jivosdk\/jvdisplaycontroller\/delegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVDisplayController"}],"url":"\/documentation\/jivosdk\/jvdisplaycontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVDisplayController","kind":"identifier"}],"role":"symbol","title":"JVDisplayController","abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"text":".","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display"},{"text":" namespace for SDK displaying","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"navigatorTitle":[{"kind":"identifier","text":"display"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","title":"display","kind":"symbol","url":"\/documentation\/jivosdk\/jivo\/display","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"display","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController","text":"JVDisplayController","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Namespace for SDK displaying"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/SH":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/setLocale(_:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setLocale(_:)","navigatorTitle":[{"text":"setLocale:","kind":"identifier"}],"title":"setLocale(_:)","type":"topic","abstract":[{"type":"text","text":"Sets the custom locale for use instead of system one"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setLocale","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"},{"kind":"text","text":"?)"}],"url":"\/documentation\/jivosdk\/jvdisplaycontroller\/setlocale(_:)"},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/isOnscreen":{"title":"isOnscreen","abstract":[{"type":"text","text":"Determines whether SDK is currently in UI hierarchy"}],"navigatorTitle":[{"kind":"identifier","text":"isOnscreen"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOnscreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/isOnscreen","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/isonscreen","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"JVDisplayController","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JVDisplayController"}],"op":"replace"},{"value":[{"text":"JVDisplayController","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/delegate","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/isOnscreen"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(color:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(image:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/define(text:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/init","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/place(within:closeButton:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/present(over:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/push(into:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setExtraItems(menu:captions:handler:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setLocale(_:)"]}],"path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"JVDisplayController","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1push(into:)\/title","value":"pushInto:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1push(into:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pushInto:"}]},{"value":"setExtraItemsForMenu:captions:handler:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1setExtraItems(menu:captions:handler:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setExtraItemsForMenu:captions:handler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1setExtraItems(menu:captions:handler:)\/fragments"},{"value":"placeWithin:closeButton:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1place(within:closeButton:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1place(within:closeButton:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"placeWithin:closeButton:","kind":"identifier"}]},{"op":"replace","value":"presentOver:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1present(over:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"presentOver:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1present(over:)\/fragments","op":"replace"},{"value":"defineText:forElement:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1define(text:forElement:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1define(text:forElement:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"defineText:forElement:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1define(color:forElement:)\/title","value":"defineColor:forElement:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1define(color:forElement:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"defineColor:forElement:","kind":"identifier"}]},{"value":"defineImage:forElement:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1define(image:forElement:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1define(image:forElement:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"defineImage:forElement:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1delegate\/title","value":"delegate"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"op":"replace","value":"JVDisplayController","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/title"},{"op":"replace","value":[{"text":"JVDisplayController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title","value":"display"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments","value":[{"text":"display","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1setLocale(_:)\/title","op":"replace","value":"setLocale:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setLocale:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1setLocale(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1isOnscreen\/title","op":"replace","value":"isOnscreen"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1isOnscreen\/fragments","op":"replace","value":[{"text":"isOnscreen","kind":"identifier"}]}]}]}