{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"JVDisplayElement","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration","title":"JVDisplayElement","externalID":"c:@M@JivoSDK@E@JVDisplayElement","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVDisplayElement","kind":"identifier"}],"modules":[{"name":"JivoSDK"}]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/attachCamera","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/attachFile","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/attachLibrary","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/headerIcon","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/headerSubtitle","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/headerTitle","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/messageHello","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/messageOffline","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/outgoingElements","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormCommentPlaceholder","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormPostSubmitTitle","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormPreSubmitTitle","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormSubmitCaption","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/replyPlaceholder","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/replyPrefill"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/init(rawValue:)"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"abstract":[{"text":"UI elements available for customization","type":"text"}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(JVDisplayElement) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDisplayElement","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/jivosdk\/jvdisplayelement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvdisplayelement"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/rateFormSubmitCaption":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rateFormSubmitCaption","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Caption for Submit Button within Rate Form"},{"text":" ","type":"text"},{"type":"text","text":"customizable: text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormSubmitCaption","kind":"symbol","title":"JVDisplayElement.rateFormSubmitCaption","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDisplayElementRateFormSubmitCaption"}],"url":"\/documentation\/jivosdk\/jvdisplayelement\/rateformsubmitcaption"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/headerIcon":{"role":"symbol","navigatorTitle":[{"text":"JVDisplayElementHeaderIcon","kind":"identifier"}],"type":"topic","title":"JVDisplayElement.headerIcon","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headerIcon","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayelement\/headericon","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/headerIcon","abstract":[{"type":"text","text":"Back button in Header Bar,"},{"type":"text","text":" "},{"text":"customizable: image","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","kind":"symbol","abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","type":"topic"},"doc://org.cocoapods.JivoSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/headerSubtitle":{"title":"JVDisplayElement.headerSubtitle","navigatorTitle":[{"text":"JVDisplayElementHeaderSubtitle","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/headerSubtitle","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"headerSubtitle","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Second line in Header Bar,"},{"type":"text","text":" "},{"text":"customizable: text, color","type":"text"}],"url":"\/documentation\/jivosdk\/jvdisplayelement\/headersubtitle"},"doc://org.cocoapods.JivoSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/attachCamera":{"url":"\/documentation\/jivosdk\/jvdisplayelement\/attachcamera","title":"JVDisplayElement.attachCamera","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/attachCamera","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attachCamera"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDisplayElementAttachCamera"}],"role":"symbol","abstract":[{"text":"Caption for “Take a Photo” action in Attach Menu,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"customizable: text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/jivosdk\/jvdisplayelement\/rawrepresentable-implementations","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/attachFile":{"url":"\/documentation\/jivosdk\/jvdisplayelement\/attachfile","kind":"symbol","role":"symbol","title":"JVDisplayElement.attachFile","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"attachFile","kind":"identifier"}],"abstract":[{"type":"text","text":"Caption for “Pick a Document” action in Attach Menu,"},{"text":" ","type":"text"},{"type":"text","text":"customizable: text"}],"navigatorTitle":[{"text":"JVDisplayElementAttachFile","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/attachFile","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement":{"title":"JVDisplayElement","kind":"symbol","abstract":[{"text":"UI elements available for customization","type":"text"}],"url":"\/documentation\/jivosdk\/jvdisplayelement","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JVDisplayElement","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayElement"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/Equatable-Implementations":{"role":"collectionGroup","type":"topic","title":"Equatable Implementations","kind":"article","url":"\/documentation\/jivosdk\/jvdisplayelement\/equatable-implementations","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/Equatable-Implementations","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/rateFormPostSubmitTitle":{"url":"\/documentation\/jivosdk\/jvdisplayelement\/rateformpostsubmittitle","navigatorTitle":[{"text":"JVDisplayElementRateFormPostSubmitTitle","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormPostSubmitTitle","title":"JVDisplayElement.rateFormPostSubmitTitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateFormPostSubmitTitle"}],"type":"topic","abstract":[{"text":"Caption for Finish Button within Rate Form","type":"text"},{"type":"text","text":" "},{"text":"customizable: text","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/headerTitle":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/headerTitle","kind":"symbol","url":"\/documentation\/jivosdk\/jvdisplayelement\/headertitle","role":"symbol","title":"JVDisplayElement.headerTitle","navigatorTitle":[{"kind":"identifier","text":"JVDisplayElementHeaderTitle"}],"abstract":[{"text":"First line in Header Bar,","type":"text"},{"text":" ","type":"text"},{"text":"customizable: text, color","type":"text"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headerTitle","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/attachLibrary":{"abstract":[{"text":"Caption for “Choose from Library” action in Attach Menu,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"customizable: text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachLibrary"}],"type":"topic","kind":"symbol","title":"JVDisplayElement.attachLibrary","role":"symbol","navigatorTitle":[{"text":"JVDisplayElementAttachLibrary","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayelement\/attachlibrary","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/attachLibrary"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/outgoingElements":{"title":"JVDisplayElement.outgoingElements","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/outgoingElements","navigatorTitle":[{"text":"JVDisplayElementOutgoingElements","kind":"identifier"}],"abstract":[{"type":"text","text":"Outgoing elements from client,"},{"type":"text","text":" "},{"text":"customizable: color","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"outgoingElements"}],"kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvdisplayelement\/outgoingelements"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/messageHello":{"role":"symbol","navigatorTitle":[{"text":"JVDisplayElementMessageHello","kind":"identifier"}],"type":"topic","title":"JVDisplayElement.messageHello","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageHello","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayelement\/messagehello","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/messageHello","abstract":[{"text":"Textual content of Hello Message in chat,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"customizable: text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/replyPrefill":{"role":"symbol","navigatorTitle":[{"text":"JVDisplayElementReplyPrefill","kind":"identifier"}],"type":"topic","title":"JVDisplayElement.replyPrefill","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replyPrefill","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayelement\/replyprefill","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/replyPrefill","abstract":[{"type":"text","text":"Text to prefill the replying area,"},{"type":"text","text":" "},{"text":"customizable: text","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/init(rawValue:)":{"abstract":[],"role":"symbol","url":"\/documentation\/jivosdk\/jvdisplayelement\/init(rawvalue:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/init(rawValue:)","type":"topic","kind":"symbol","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/replyPlaceholder":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replyPlaceholder","kind":"identifier"}],"abstract":[{"type":"text","text":"Placeholder for replying area,"},{"text":" ","type":"text"},{"text":"customizable: text","type":"text"}],"url":"\/documentation\/jivosdk\/jvdisplayelement\/replyplaceholder","title":"JVDisplayElement.replyPlaceholder","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"JVDisplayElementReplyPlaceholder","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/replyPlaceholder"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/messageOffline":{"role":"symbol","navigatorTitle":[{"text":"JVDisplayElementMessageOffline","kind":"identifier"}],"type":"topic","title":"JVDisplayElement.messageOffline","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageOffline","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayelement\/messageoffline","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/messageOffline","abstract":[{"text":"Textual content of Offline Message in chat,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"customizable: text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/rateFormCommentPlaceholder":{"navigatorTitle":[{"kind":"identifier","text":"JVDisplayElementRateFormCommentPlaceholder"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateFormCommentPlaceholder"}],"url":"\/documentation\/jivosdk\/jvdisplayelement\/rateformcommentplaceholder","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Placeholder for Comment Field within Rate Form"},{"text":" ","type":"text"},{"type":"text","text":"customizable: text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormCommentPlaceholder","title":"JVDisplayElement.rateFormCommentPlaceholder"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayElement/rateFormPreSubmitTitle":{"role":"symbol","navigatorTitle":[{"text":"JVDisplayElementRateFormPreSubmitTitle","kind":"identifier"}],"type":"topic","title":"JVDisplayElement.rateFormPreSubmitTitle","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rateFormPreSubmitTitle","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdisplayelement\/rateformpresubmittitle","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormPreSubmitTitle","abstract":[{"type":"text","text":"Title for Rate Form"},{"type":"text","text":" "},{"text":"customizable: text","type":"text"}]},"doc://org.cocoapods.JivoSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"JVDisplayElement"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"JVDisplayElement","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"JVDisplayElement","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/attachCamera","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/attachFile","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/attachLibrary","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/headerIcon","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/headerSubtitle","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/headerTitle","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/messageHello","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/messageOffline","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/outgoingElements","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormCommentPlaceholder","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormPostSubmitTitle","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormPreSubmitTitle","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/rateFormSubmitCaption","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/replyPlaceholder","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayElement\/replyPrefill"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDisplayElement","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"JVDisplayElementRateFormSubmitCaption","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormSubmitCaption\/title","op":"replace"},{"value":[{"text":"JVDisplayElementRateFormSubmitCaption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormSubmitCaption\/fragments"},{"value":"JVDisplayElementHeaderIcon","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1headerIcon\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"JVDisplayElementHeaderIcon"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1headerIcon\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1headerSubtitle\/title","value":"JVDisplayElementHeaderSubtitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1headerSubtitle\/fragments","value":[{"kind":"identifier","text":"JVDisplayElementHeaderSubtitle"}]},{"value":"JVDisplayElementAttachCamera","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1attachCamera\/title"},{"value":[{"text":"JVDisplayElementAttachCamera","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1attachCamera\/fragments"},{"value":"JVDisplayElementAttachFile","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1attachFile\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1attachFile\/fragments","value":[{"kind":"identifier","text":"JVDisplayElementAttachFile"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/title","value":"JVDisplayElement"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement\/fragments","value":[{"kind":"identifier","text":"JVDisplayElement"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormPostSubmitTitle\/title","value":"JVDisplayElementRateFormPostSubmitTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormPostSubmitTitle\/fragments","value":[{"text":"JVDisplayElementRateFormPostSubmitTitle","kind":"identifier"}]},{"op":"replace","value":"JVDisplayElementHeaderTitle","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1headerTitle\/title"},{"op":"replace","value":[{"text":"JVDisplayElementHeaderTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1headerTitle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1attachLibrary\/title","value":"JVDisplayElementAttachLibrary"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1attachLibrary\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVDisplayElementAttachLibrary"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1outgoingElements\/title","value":"JVDisplayElementOutgoingElements"},{"value":[{"text":"JVDisplayElementOutgoingElements","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1outgoingElements\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1messageHello\/title","value":"JVDisplayElementMessageHello"},{"value":[{"kind":"identifier","text":"JVDisplayElementMessageHello"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1messageHello\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1replyPrefill\/title","value":"JVDisplayElementReplyPrefill"},{"op":"replace","value":[{"kind":"identifier","text":"JVDisplayElementReplyPrefill"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1replyPrefill\/fragments"},{"value":"JVDisplayElementReplyPlaceholder","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1replyPlaceholder\/title"},{"op":"replace","value":[{"kind":"identifier","text":"JVDisplayElementReplyPlaceholder"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1replyPlaceholder\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1messageOffline\/title","value":"JVDisplayElementMessageOffline","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1messageOffline\/fragments","value":[{"kind":"identifier","text":"JVDisplayElementMessageOffline"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormCommentPlaceholder\/title","value":"JVDisplayElementRateFormCommentPlaceholder"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormCommentPlaceholder\/fragments","value":[{"text":"JVDisplayElementRateFormCommentPlaceholder","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormPreSubmitTitle\/title","value":"JVDisplayElementRateFormPreSubmitTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayElement~1rateFormPreSubmitTitle\/fragments","value":[{"kind":"identifier","text":"JVDisplayElementRateFormPreSubmitTitle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}