{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(JVDisplayDelegate) "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayDelegate"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/jivosdk\/jvdisplaydelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdisplaydelegate"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"metadata":{"externalID":"c:@M@JivoSDK@objc(pl)JVDisplayDelegate","roleHeading":"Protocol","title":"JVDisplayDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayDelegate"}],"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"JVDisplayDelegate"}],"role":"symbol","modules":[{"name":"JivoSDK"}]},"abstract":[{"text":"Interface to control displaying lifecycle,","type":"text"},{"type":"text","text":" "},{"text":"relates to ","type":"text"},{"code":"Jivo.display","type":"codeVoice"},{"type":"text","text":" namespace"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(asksToAppear:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(customizeHeader:navigationBar:navigationItem:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineColor:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineImage:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineText:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(didDisappear:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(willAppear:)"]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"],"type":"conformingTypes"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","type":"topic","kind":"symbol","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingUI":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingUI","kind":"identifier"}],"type":"topic","kind":"symbol","title":"JivoSDKChattingUI","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingUI"}],"deprecated":true,"url":"\/documentation\/jivosdk\/jivosdkchattingui","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(customizeHeader:navigationBar:navigationItem:)":{"title":"jivoDisplay(customizeHeader:navigationBar:navigationItem:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(customizeHeader:navigationBar:navigationItem:)","abstract":[{"type":"text","text":"Called to customize Header Bar appearance"}],"type":"topic","url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(customizeheader:navigationbar:navigationitem:)","navigatorTitle":[{"text":"jivoDisplayCustomizeHeader:navigationBar:navigationItem:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customizeHeader"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"navigationBar"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationBar","kind":"typeIdentifier","text":"UINavigationBar"},{"kind":"text","text":", "},{"text":"navigationItem","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem","text":"UINavigationItem"},{"kind":"text","text":")"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(defineText:forElement:)":{"title":"jivoDisplay(defineText:forElement:)","navigatorTitle":[{"kind":"identifier","text":"jivoDisplayDefineText:forElement:"}],"role":"symbol","url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(definetext:forelement:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"defineText"},{"kind":"text","text":": "},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forElement"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","kind":"typeIdentifier","text":"JVDisplayElement"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineText:forElement:)","abstract":[{"text":"DEPRECATED","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Please use Jivo.display.define(text:forElement:) instead"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(willAppear:)":{"url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(willappear:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(willAppear:)","abstract":[{"text":"Called before opening the SDK","type":"text"}],"kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoDisplay"},{"kind":"text","text":"("},{"kind":"externalParam","text":"willAppear"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"jivoDisplayWillAppear:","kind":"identifier"}],"title":"jivoDisplay(willAppear:)","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(defineImage:forElement:)":{"url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(defineimage:forelement:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineImage:forElement:)","abstract":[{"type":"text","text":"DEPRECATED"},{"type":"text","text":" "},{"type":"text","text":"Please use Jivo.display.define(image:forElement:) instead"}],"kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"defineImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"kind":"text","text":", "},{"text":"forElement","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JVDisplayElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"jivoDisplayDefineImage:forElement:","kind":"identifier"}],"title":"jivoDisplay(defineImage:forElement:)","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(defineColor:forElement:)":{"abstract":[{"type":"text","text":"DEPRECATED"},{"text":" ","type":"text"},{"type":"text","text":"Please use Jivo.display.define(color:forElement:) instead"}],"kind":"symbol","type":"topic","required":true,"title":"jivoDisplay(defineColor:forElement:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"kind":"text","text":"("},{"text":"defineColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forElement"},{"text":": ","kind":"text"},{"text":"JVDisplayElement","preciseIdentifier":"c:@M@JivoSDK@E@JVDisplayElement","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineColor:forElement:)","url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(definecolor:forelement:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"jivoDisplayDefineColor:forElement:"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(didDisappear:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoDisplay"},{"kind":"text","text":"("},{"kind":"externalParam","text":"didDisappear"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":")"}],"role":"symbol","title":"jivoDisplay(didDisappear:)","navigatorTitle":[{"kind":"identifier","text":"jivoDisplayDidDisappear:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(didDisappear:)","type":"topic","url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(diddisappear:)","required":true,"abstract":[{"text":"Called after the SDK is closed","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate":{"abstract":[{"type":"text","text":"Interface to control displaying lifecycle,"},{"type":"text","text":" "},{"text":"relates to ","type":"text"},{"code":"Jivo.display","type":"codeVoice"},{"type":"text","text":" namespace"}],"url":"\/documentation\/jivosdk\/jvdisplaydelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDisplayDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"JVDisplayDelegate"}],"title":"JVDisplayDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayDelegate/jivoDisplay(asksToAppear:)":{"abstract":[{"text":"Called when SDK needs to display chat UI on screen","type":"text"}],"url":"\/documentation\/jivosdk\/jvdisplaydelegate\/jivodisplay(askstoappear:)","type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoDisplay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"asksToAppear","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"jivoDisplayAsksToAppear:"}],"title":"jivoDisplay(asksToAppear:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(asksToAppear:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"JVDisplayDelegate","path":"\/metadata\/title","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JVDisplayDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JVDisplayDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(asksToAppear:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(customizeHeader:navigationBar:navigationItem:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineColor:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineImage:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(defineText:forElement:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(didDisappear:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayDelegate\/jivoDisplay(willAppear:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingUI"],"type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"JVDisplayDelegate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/title","value":"JivoSDKChattingUI","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingUI\/fragments","value":[{"text":"JivoSDKChattingUI","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(customizeHeader:navigationBar:navigationItem:)\/title","value":"jivoDisplayCustomizeHeader:navigationBar:navigationItem:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(customizeHeader:navigationBar:navigationItem:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"jivoDisplayCustomizeHeader:navigationBar:navigationItem:","kind":"identifier"}]},{"value":"jivoDisplayDefineText:forElement:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(defineText:forElement:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"jivoDisplayDefineText:forElement:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(defineText:forElement:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(willAppear:)\/title","value":"jivoDisplayWillAppear:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(willAppear:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"jivoDisplayWillAppear:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(defineImage:forElement:)\/title","value":"jivoDisplayDefineImage:forElement:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"jivoDisplayDefineImage:forElement:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(defineImage:forElement:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(defineColor:forElement:)\/title","op":"replace","value":"jivoDisplayDefineColor:forElement:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jivoDisplayDefineColor:forElement:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(defineColor:forElement:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(didDisappear:)\/title","value":"jivoDisplayDidDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(didDisappear:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoDisplayDidDisappear:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/title","value":"JVDisplayDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate\/fragments","value":[{"text":"JVDisplayDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(asksToAppear:)\/title","value":"jivoDisplayAsksToAppear:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoDisplayAsksToAppear:"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayDelegate~1jivoDisplay(asksToAppear:)\/fragments"}]}]}