{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JVNavigationContainer","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"style":"tip","name":"Tip","type":"aside","content":[{"inlineContent":[{"text":"Feel free to use this class for UI setup using ","type":"text"},{"code":"appearance(whenContainedInInstancesOf:)","type":"codeVoice"}],"type":"paragraph"}]}]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)UINavigationController"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSCoding","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/s8SendableP","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.JivoSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Descendent of UINavigationController for UI hierarchy"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnavigationcontainer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnavigationcontainer"]}],"metadata":{"role":"symbol","modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(cs)JVNavigationContainer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVNavigationContainer","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","title":"JVNavigationContainer","navigatorTitle":[{"text":"JVNavigationContainer","kind":"identifier"}]},"references":{"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.JivoSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNavigationContainer/initWithNavigationBarClass:toolbarClass:":{"type":"topic","title":"initWithNavigationBarClass:toolbarClass:","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer\/initWithNavigationBarClass:toolbarClass:","kind":"symbol","navigatorTitle":[{"text":"initWithNavigationBarClass:toolbarClass:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithNavigationBarClass:toolbarClass:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/jivosdk\/jvnavigationcontainer\/initwithnavigationbarclass:toolbarclass:"},"doc://org.cocoapods.JivoSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.JivoSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.JivoSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.JivoSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.JivoSDK/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNavigationContainer/initWithCoder:":{"kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"title":"initWithCoder:","url":"\/documentation\/jivosdk\/jvnavigationcontainer\/initwithcoder:","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer\/initWithCoder:"},"doc://org.cocoapods.JivoSDK/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIContentContainer"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNavigationContainer/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"type":"topic","url":"\/documentation\/jivosdk\/jvnavigationcontainer\/initwithnibname:bundle:","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer\/initWithNibName:bundle:","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","url":"\/documentation\/jivosdk","title":"JivoSDK","type":"topic","abstract":[]},"doc://org.cocoapods.JivoSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.JivoSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.JivoSDK/objc(cs)UINavigationController":{"type":"unresolvable","title":"UINavigationController","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)UINavigationController"},"doc://org.cocoapods.JivoSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSExtensionRequestHandling"},"doc://org.cocoapods.JivoSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNavigationContainer/initWithRootViewController:":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer\/initWithRootViewController:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRootViewController:","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/jivosdk\/jvnavigationcontainer\/initwithrootviewcontroller:","title":"initWithRootViewController:","navigatorTitle":[{"text":"initWithRootViewController:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNavigationContainer":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVNavigationContainer","kind":"identifier"}],"title":"JVNavigationContainer","url":"\/documentation\/jivosdk\/jvnavigationcontainer","navigatorTitle":[{"text":"JVNavigationContainer","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer","type":"topic","abstract":[{"text":"Descendent of UINavigationController for UI hierarchy","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"JVNavigationContainer"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"JVNavigationContainer"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"JVNavigationContainer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"add","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer\/initWithCoder:","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer\/initWithNavigationBarClass:toolbarClass:","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer\/initWithNibName:bundle:","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNavigationContainer\/initWithRootViewController:"]}]},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)UINavigationController"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNavigationContainer","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNavigationContainer\/title","value":"JVNavigationContainer"},{"value":[{"kind":"identifier","text":"JVNavigationContainer"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNavigationContainer\/fragments"}]}]}