{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"JVNotificationsOptionsResolver","kind":"identifier"},{"text":" = (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget","text":"JVNotificationsTarget","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget"},{"text":", ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","text":"JVNotificationsEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsEvent"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationsoptionsresolver"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"JivoSDK"}],"title":"JVNotificationsOptionsResolver","symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsOptionsResolver"}],"navigatorTitle":[{"text":"JVNotificationsOptionsResolver","kind":"identifier"}],"role":"symbol","roleHeading":"Type Alias","externalID":"s:7JivoSDK30JVNotificationsOptionsResolvera"},"abstract":[{"type":"text","text":"Determines UNNotificationPresentationOptions, based on event parameters"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsOptionsResolver"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"type":"topic","title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsOptionsResolver":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsOptionsResolver","url":"\/documentation\/jivosdk\/jvnotificationsoptionsresolver","role":"symbol","title":"JVNotificationsOptionsResolver","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsOptionsResolver"}],"type":"topic","navigatorTitle":[{"text":"JVNotificationsOptionsResolver","kind":"identifier"}],"abstract":[{"text":"Determines UNNotificationPresentationOptions, based on event parameters","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget":{"url":"\/documentation\/jivosdk\/jvnotificationstarget","title":"JVNotificationsTarget","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsTarget"}],"navigatorTitle":[{"text":"JVNotificationsTarget","kind":"identifier"}],"abstract":[{"text":"Target subsystem of Push Notification","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent":{"abstract":[{"type":"text","text":"Event category of notification"}],"title":"JVNotificationsEvent","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"JVNotificationsEvent","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsEvent"}],"type":"topic","url":"\/documentation\/jivosdk\/jvnotificationsevent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/title","value":"JVNotificationsTarget","op":"replace"},{"op":"replace","value":[{"text":"JVNotificationsTarget","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/fragments"},{"op":"replace","value":"JVNotificationsEvent","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/fragments","value":[{"text":"JVNotificationsEvent","kind":"identifier"}],"op":"replace"}]}]}