{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(JVNotificationsEvent) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVNotificationsEvent","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Event category of notification"}],"metadata":{"role":"symbol","symbolKind":"enum","modules":[{"name":"JivoSDK"}],"title":"JVNotificationsEvent","navigatorTitle":[{"text":"JVNotificationsEvent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsEvent"}],"roleHeading":"Enumeration","externalID":"c:@M@JivoSDK@E@JVNotificationsEvent"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationsevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvnotificationsevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"title":"Conforms To"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/any"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/init(rawValue:)"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent":{"abstract":[{"text":"Event category of notification","type":"text"}],"type":"topic","url":"\/documentation\/jivosdk\/jvnotificationsevent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsEvent"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsEvent"}],"kind":"symbol","title":"JVNotificationsEvent","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","abstract":[],"title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent/any":{"role":"symbol","url":"\/documentation\/jivosdk\/jvnotificationsevent\/any","title":"JVNotificationsEvent.any","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/any","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Any event"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"any","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVNotificationsEventAny"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent/init(rawValue:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/jivosdk\/jvnotificationsevent\/init(rawvalue:)","abstract":[],"type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}]},"doc://org.cocoapods.JivoSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent/Equatable-Implementations":{"role":"collectionGroup","kind":"article","url":"\/documentation\/jivosdk\/jvnotificationsevent\/equatable-implementations","abstract":[],"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/Equatable-Implementations"},"doc://org.cocoapods.JivoSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","url":"\/documentation\/jivosdk\/jvnotificationsevent\/rawrepresentable-implementations","abstract":[],"type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/RawRepresentable-Implementations"},"doc://org.cocoapods.JivoSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"JVNotificationsEvent"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"JVNotificationsEvent","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"JVNotificationsEvent"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent\/any"],"title":"Enumeration Cases"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsEvent"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"JVNotificationsEvent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/title"},{"value":[{"text":"JVNotificationsEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent~1any\/title","value":"JVNotificationsEventAny"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent~1any\/fragments","value":[{"kind":"identifier","text":"JVNotificationsEventAny"}],"op":"replace"}]}]}