{"abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","isActive":true},{"type":"text","text":" namespace for Push Notifications"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/didReceive(response:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/didReceiveRemoteNotification(userInfo:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/handleIncoming(userInfo:completionHandler:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/handleLaunch(options:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setContentTransformer(block:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionAsking(at:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionIntro(provider:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(data:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(error:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(hex:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/willPresent(notification:preferableOptions:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsController"}],"navigatorTitle":[{"kind":"identifier","text":"JVNotificationsController"}],"roleHeading":"Class","symbolKind":"class","modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(cs)JVNotificationsController","title":"JVNotificationsController","role":"symbol"},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(JVNotificationsController) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsController"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/handleIncoming(userInfo:completionHandler:)":{"abstract":[{"text":"Processes userInfo of Push Notification","type":"text"},{"text":" ","type":"text"},{"text":"For ObjC code","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleIncoming","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@E@UIBackgroundFetchResult","text":"UIBackgroundFetchResult","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/handleincoming(userinfo:completionhandler:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"handleIncomingWithUserInfo:completionHandler:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/handleIncoming(userInfo:completionHandler:)","title":"handleIncoming(userInfo:completionHandler:)"},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"},"doc://org.cocoapods.JivoSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setPushToken(hex:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPushToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setPushTokenHex:"}],"type":"topic","title":"setPushToken(hex:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(hex:)","abstract":[{"type":"text","text":"Associate the Push Token with current user using his userToken in hex-string form"}],"url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setpushtoken(hex:)"},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","type":"topic","url":"\/documentation\/jivosdk\/jvnotificationscontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsController","kind":"identifier"}],"navigatorTitle":[{"text":"JVNotificationsController","kind":"identifier"}],"role":"symbol","title":"JVNotificationsController","kind":"symbol","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications"},{"type":"text","text":" namespace for Push Notifications"}]},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/didReceiveRemoteNotification(userInfo:)":{"url":"\/documentation\/jivosdk\/jvnotificationscontroller\/didreceiveremotenotification(userinfo:)","type":"topic","abstract":[{"text":"Processes userInfo of Push Notification","type":"text"},{"text":" ","type":"text"},{"text":"For Swift code","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/didReceiveRemoteNotification(userInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRemoteNotification"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBackgroundFetchResult","text":"UIBackgroundFetchResult"},{"kind":"text","text":"?"}],"kind":"symbol","title":"didReceiveRemoteNotification(userInfo:)"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setPermissionAsking(at:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionAsking(at:)","title":"setPermissionAsking(at:)","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setpermissionasking(at:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPermissionAsking","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JVNotificationsPermissionAskingMoment","preciseIdentifier":"s:7JivoSDK37JVNotificationsPermissionAskingMomentO","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Specifies when SDK should request access to Push Notifications","type":"text"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/didReceive(response:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"response","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationResponse","text":"UNNotificationResponse","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/didReceive(response:)","title":"didReceive(response:)","navigatorTitle":[{"text":"didReceiveResponse:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvnotificationscontroller\/didreceive(response:)","abstract":[{"type":"text","text":"Processes the User Response"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","title":"JivoSDK","abstract":[],"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setContentTransformer(block:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setContentTransformer(block:)","role":"symbol","navigatorTitle":[{"text":"setContentTransformerBlock:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setcontenttransformer(block:)","kind":"symbol","title":"setContentTransformer(block:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setContentTransformer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"block","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"JVNotificationsEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsEvent"},{"text":") -> ","kind":"text"},{"text":"UNNotificationContent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Handler will be called when SDK is going to present Push Notification banner","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/willPresent(notification:preferableOptions:)":{"abstract":[{"type":"text","text":"Determines the presentation options Notification"},{"type":"text","text":" "},{"type":"text","text":"For Swift code"}],"type":"topic","title":"willPresent(notification:preferableOptions:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/willPresent(notification:preferableOptions:)","kind":"symbol","role":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/willpresent(notification:preferableoptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPresent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"preferableOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"url":"\/documentation\/jivosdk\/jivo\/notifications","title":"notifications","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Namespace for Push Notifications"}],"navigatorTitle":[{"text":"notifications","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifications","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JVNotificationsController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController"}]},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","url":"\/documentation\/jivosdk\/jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol","abstract":[],"kind":"symbol","title":"Jivo","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/handleLaunch(options:)":{"url":"\/documentation\/jivosdk\/jvnotificationscontroller\/handlelaunch(options:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/handleLaunch(options:)","title":"handleLaunch(options:)","type":"topic","kind":"symbol","abstract":[{"text":"Handle the possible Push Notification","type":"text"},{"text":" ","type":"text"},{"text":"at the moment of application launching","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"handleLaunchWithOptions:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleLaunch","kind":"identifier"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey","text":"LaunchOptionsKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setPermissionIntro(provider:)":{"type":"topic","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setpermissionintro(provider:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionIntro(provider:)","kind":"symbol","role":"symbol","title":"setPermissionIntro(provider:)","abstract":[{"type":"text","text":"Handler will be called when SDK wants to access Push Notifications"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPermissionIntro","kind":"identifier"},{"text":"(","kind":"text"},{"text":"provider","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setPermissionIntroProvider:","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setPushToken(data:)":{"title":"setPushToken(data:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPushToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(data:)","navigatorTitle":[{"text":"setPushTokenData:","kind":"identifier"}],"abstract":[{"text":"Associate the Push Token with current user using his userToken in raw-binary form","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setpushtoken(data:)","type":"topic"},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setPushToken(error:)":{"title":"setPushToken(error:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"setPushTokenError:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPushToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setpushtoken(error:)","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(error:)","abstract":[{"text":"Notify about userToken is unavailable","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"JVNotificationsController","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"JVNotificationsController","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"JVNotificationsController","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/didReceive(response:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/handleIncoming(userInfo:completionHandler:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/handleLaunch(options:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setContentTransformer(block:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionIntro(provider:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(data:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(error:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(hex:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1handleIncoming(userInfo:completionHandler:)\/title","value":"handleIncomingWithUserInfo:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1handleIncoming(userInfo:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleIncomingWithUserInfo:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPushToken(hex:)\/title","value":"setPushTokenHex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPushToken(hex:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setPushTokenHex:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title","value":"JVNotificationsController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments","value":[{"kind":"identifier","text":"JVNotificationsController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/navigatorTitle","value":[{"text":"JVNotificationsController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1didReceive(response:)\/title","value":"didReceiveResponse:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1didReceive(response:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveResponse:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setContentTransformer(block:)\/title","value":"setContentTransformerBlock:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setContentTransformer(block:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setContentTransformerBlock:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title","value":"notifications"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments","value":[{"text":"notifications","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"kind":"identifier","text":"Jivo"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1handleLaunch(options:)\/title","value":"handleLaunchWithOptions:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1handleLaunch(options:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleLaunchWithOptions:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPermissionIntro(provider:)\/title","value":"setPermissionIntroProvider:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPermissionIntro(provider:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setPermissionIntroProvider:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPushToken(data:)\/title","value":"setPushTokenData:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPushToken(data:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setPushTokenData:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPushToken(error:)\/title","value":"setPushTokenError:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPushToken(error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPushTokenError:"}]}]}]}