{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"kind":"symbol","abstract":[{"type":"text","text":"Target subsystem of Push Notification"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/app","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/sdk"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(JVNotificationsTarget) "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsTarget"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationstarget"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnotificationstarget"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"JivoSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVNotificationsTarget","kind":"identifier"}],"symbolKind":"enum","title":"JVNotificationsTarget","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsTarget"}],"role":"symbol","externalID":"c:@M@JivoSDK@E@JVNotificationsTarget","roleHeading":"Enumeration"},"references":{"doc://org.cocoapods.JivoSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget/RawRepresentable-Implementations":{"url":"\/documentation\/jivosdk\/jvnotificationstarget\/rawrepresentable-implementations","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget/init(rawValue:)":{"type":"topic","role":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/init(rawValue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jvnotificationstarget\/init(rawvalue:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/Equatable-Implementations","url":"\/documentation\/jivosdk\/jvnotificationstarget\/equatable-implementations","abstract":[],"kind":"article","type":"topic","title":"Equatable Implementations"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","type":"topic","role":"collection","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget/sdk":{"type":"topic","title":"JVNotificationsTarget.sdk","url":"\/documentation\/jivosdk\/jvnotificationstarget\/sdk","abstract":[{"type":"text","text":"Sent by Jivo and intended for JivoSDK"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/sdk","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"sdk","kind":"identifier"}],"navigatorTitle":[{"text":"JVNotificationsTargetSdk","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget":{"url":"\/documentation\/jivosdk\/jvnotificationstarget","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","title":"JVNotificationsTarget","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsTarget"}],"abstract":[{"type":"text","text":"Target subsystem of Push Notification"}],"kind":"symbol","navigatorTitle":[{"text":"JVNotificationsTarget","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget/app":{"navigatorTitle":[{"text":"JVNotificationsTargetApp","kind":"identifier"}],"abstract":[{"text":"Sent by your backend, or by other third-parties","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/app","type":"topic","title":"JVNotificationsTarget.app","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"app"}],"url":"\/documentation\/jivosdk\/jvnotificationstarget\/app","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"JVNotificationsTarget","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"JVNotificationsTarget","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"JVNotificationsTarget","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/app","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget\/sdk"]}],"op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JVNotificationsTarget","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget~1sdk\/title","value":"JVNotificationsTargetSdk","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget~1sdk\/fragments","value":[{"kind":"identifier","text":"JVNotificationsTargetSdk"}],"op":"replace"},{"value":"JVNotificationsTarget","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/title"},{"value":[{"text":"JVNotificationsTarget","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/fragments","op":"replace"},{"value":"JVNotificationsTargetApp","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget~1app\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget~1app\/fragments","value":[{"text":"JVNotificationsTargetApp","kind":"identifier"}],"op":"replace"}]}]}