{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationsdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnotificationsdelegate"]}],"abstract":[{"text":"Interface to handle notifications events,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"relates to "},{"type":"codeVoice","code":"Jivo.notifications"},{"type":"text","text":" namespace"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"relationshipsSections":[{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications"]}],"metadata":{"externalID":"c:@M@JivoSDK@objc(pl)JVNotificationsDelegate","symbolKind":"protocol","navigatorTitle":[{"text":"JVNotificationsDelegate","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","modules":[{"name":"JivoSDK"}],"title":"JVNotificationsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"JVNotificationsDelegate","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate\/jivoNotifications(accessRequested:proceedBlock:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate\/jivoNotifications(prepareBanner:content:sender:text:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(JVNotificationsDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsDelegate","kind":"identifier"}]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsDelegate/jivoNotifications(prepareBanner:content:sender:text:)":{"navigatorTitle":[{"kind":"identifier","text":"jivoNotificationsPrepareBanner:content:sender:text:"}],"url":"\/documentation\/jivosdk\/jvnotificationsdelegate\/jivonotifications(preparebanner:content:sender:text:)","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate\/jivoNotifications(prepareBanner:content:sender:text:)","title":"jivoNotifications(prepareBanner:content:sender:text:)","kind":"symbol","required":true,"abstract":[{"type":"text","text":"Called when SDK is going to present Push Notification banner"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoNotifications","kind":"identifier"},{"text":"(","kind":"text"},{"text":"prepareBanner","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":", "},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNMutableNotificationContent","preciseIdentifier":"c:objc(cs)UNMutableNotificationContent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sender","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationContent","kind":"typeIdentifier","text":"UNNotificationContent"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection","url":"\/documentation\/jivosdk","abstract":[],"title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsDelegate/jivoNotifications(accessRequested:proceedBlock:)":{"navigatorTitle":[{"text":"jivoNotificationsAccessRequested:proceedBlock:","kind":"identifier"}],"type":"topic","url":"\/documentation\/jivosdk\/jvnotificationsdelegate\/jivonotifications(accessrequested:proceedblock:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate\/jivoNotifications(accessRequested:proceedBlock:)","title":"jivoNotifications(accessRequested:proceedBlock:)","kind":"symbol","required":true,"abstract":[{"type":"text","text":"Called when SDK wants to access Push Notifications"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoNotifications"},{"text":"(","kind":"text"},{"text":"accessRequested","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"proceedBlock","kind":"externalParam"},{"kind":"text","text":": () -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsDelegate":{"title":"JVNotificationsDelegate","url":"\/documentation\/jivosdk\/jvnotificationsdelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsDelegate"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsDelegate"}],"abstract":[{"text":"Interface to handle notifications events,","type":"text"},{"text":" ","type":"text"},{"text":"relates to ","type":"text"},{"type":"codeVoice","code":"Jivo.notifications"},{"text":" namespace","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKNotifications":{"title":"JivoSDKNotifications","url":"\/documentation\/jivosdk\/jivosdknotifications","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKNotifications"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications","navigatorTitle":[{"kind":"identifier","text":"JivoSDKNotifications"}],"deprecated":true,"abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"JVNotificationsDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"JVNotificationsDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"JVNotificationsDelegate","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate\/jivoNotifications(accessRequested:proceedBlock:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate\/jivoNotifications(prepareBanner:content:sender:text:)"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKNotifications"]}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVNotificationsDelegate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate~1jivoNotifications(prepareBanner:content:sender:text:)\/title","value":"jivoNotificationsPrepareBanner:content:sender:text:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"jivoNotificationsPrepareBanner:content:sender:text:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate~1jivoNotifications(prepareBanner:content:sender:text:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate~1jivoNotifications(accessRequested:proceedBlock:)\/title","op":"replace","value":"jivoNotificationsAccessRequested:proceedBlock:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate~1jivoNotifications(accessRequested:proceedBlock:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoNotificationsAccessRequested:proceedBlock:"}]},{"op":"replace","value":"JVNotificationsDelegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate\/title"},{"value":[{"text":"JVNotificationsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate\/fragments"},{"op":"replace","value":"JivoSDKNotifications","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKNotifications\/fragments","value":[{"kind":"identifier","text":"JivoSDKNotifications"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}