{"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"kind":"symbol","abstract":[{"text":"Event category of notification","type":"text"}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsCategory","kind":"identifier"}],"navigatorTitle":[{"text":"JVNotificationsCategory","kind":"identifier"}],"role":"symbol","modules":[{"name":"JivoSDK"}],"title":"JVNotificationsCategory","externalID":"c:@M@JivoSDK@E@JVNotificationsCategory","symbolKind":"enum","roleHeading":"Enumeration"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(JVNotificationsCategory) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsCategory","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/any"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationscategory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvnotificationscategory"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory":{"navigatorTitle":[{"text":"JVNotificationsCategory","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory","kind":"symbol","title":"JVNotificationsCategory","url":"\/documentation\/jivosdk\/jvnotificationscategory","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsCategory","kind":"identifier"}],"type":"topic","abstract":[{"text":"Event category of notification","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscategory\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/init(rawValue:)","abstract":[],"type":"topic"},"doc://org.cocoapods.JivoSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory/Equatable-Implementations":{"type":"topic","kind":"article","role":"collectionGroup","abstract":[],"url":"\/documentation\/jivosdk\/jvnotificationscategory\/equatable-implementations","title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/Equatable-Implementations"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory/RawRepresentable-Implementations":{"type":"topic","kind":"article","role":"collectionGroup","abstract":[],"url":"\/documentation\/jivosdk\/jvnotificationscategory\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/RawRepresentable-Implementations"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory/any":{"url":"\/documentation\/jivosdk\/jvnotificationscategory\/any","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsCategoryAny"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"any"}],"title":"JVNotificationsCategory.any","abstract":[{"type":"text","text":"Any event"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/any"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"JVNotificationsCategory","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JVNotificationsCategory"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"JVNotificationsCategory","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory\/any"],"anchor":"Enumeration-Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsCategory","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/title","value":"JVNotificationsCategory","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/fragments","value":[{"text":"JVNotificationsCategory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/navigatorTitle","value":[{"text":"JVNotificationsCategory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory~1any\/title","value":"JVNotificationsCategoryAny","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory~1any\/fragments","value":[{"text":"JVNotificationsCategoryAny","kind":"identifier"}],"op":"replace"}]}]}