{"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setContactInfo(_:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setCustomData(fields:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setPreferredServer(_:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/shutDown()","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/startUp(channelID:userToken:)"]}],"metadata":{"externalID":"c:@M@JivoSDK@objc(cs)JVSessionController","modules":[{"name":"JivoSDK"}],"title":"JVSessionController","navigatorTitle":[{"text":"JVSessionController","kind":"identifier"}],"symbolKind":"class","role":"symbol","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JVSessionController","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvsessioncontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvsessioncontroller"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController"},"abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference","isActive":true},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session"},{"type":"text","text":" namespace for managing user session"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(JVSessionController) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVSessionController"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/startUp(channelID:userToken:)":{"type":"topic","url":"\/documentation\/jivosdk\/jvsessioncontroller\/startup(channelid:usertoken:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/startUp(channelID:userToken:)","abstract":[{"type":"text","text":"Establishes connection between SDK and Jivo,"},{"type":"text","text":" "},{"text":"by either creating a new session or resuming existing one","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"startUp","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"channelID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"userToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"startUpWithChannelID:userToken:"}],"role":"symbol","title":"startUp(channelID:userToken:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/shutDown()":{"role":"symbol","url":"\/documentation\/jivosdk\/jvsessioncontroller\/shutdown()","abstract":[{"type":"text","text":"Closes current connection, clears the local database,"},{"type":"text","text":" "},{"type":"text","text":"and unsubscribes device from Push Notifications"}],"kind":"symbol","navigatorTitle":[{"text":"shutDown","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/shutDown()","title":"shutDown()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shutDown"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/delegate":{"abstract":[{"type":"text","text":"Object that handles session events"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/delegate","type":"topic","url":"\/documentation\/jivosdk\/jvsessioncontroller\/delegate","kind":"symbol","title":"delegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVSessionDelegate","text":"JVSessionDelegate"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"role":"symbol","abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","title":"Jivo","url":"\/documentation\/jivosdk\/jivo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Jivo"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setContactInfo(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setContactInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionContactInfo","text":"JVSessionContactInfo"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"setContactInfo:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jvsessioncontroller\/setcontactinfo(_:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setContactInfo(_:)","role":"symbol","abstract":[{"type":"text","text":"Assigns contact info to user,"},{"type":"text","text":" "},{"text":"to reach him easier in future","type":"text"}],"title":"setContactInfo(_:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/init","url":"\/documentation\/jivosdk\/jvsessioncontroller\/init","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/SH":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol","url":"\/documentation\/jivosdk","type":"topic"},"doc://org.cocoapods.JivoSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"type":"topic","url":"\/documentation\/jivosdk\/jivo\/session","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","abstract":[{"type":"text","text":"Namespace for managing user session"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"text":"JVSessionController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController"}],"navigatorTitle":[{"kind":"identifier","text":"session"}],"role":"symbol","title":"session"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController":{"type":"topic","title":"JVSessionController","abstract":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference"},{"type":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","type":"reference","isActive":true},{"text":" namespace for managing user session","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVSessionController","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvsessioncontroller","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVSessionController"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setPreferredServer(_:)":{"abstract":[{"text":"Specifies preferred server for SDK to connect to Jivo","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setPreferredServer(_:)","title":"setPreferredServer(_:)","url":"\/documentation\/jivosdk\/jvsessioncontroller\/setpreferredserver(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setPreferredServer:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setPreferredServer","kind":"identifier"},{"kind":"text","text":"("},{"text":"JVSessionServer","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVSessionServer"},{"kind":"text","text":")"}]},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setCustomData(fields:)":{"url":"\/documentation\/jivosdk\/jvsessioncontroller\/setcustomdata(fields:)","abstract":[{"text":"Assigns custom data to user,","type":"text"},{"text":" ","type":"text"},{"text":"if needed for your business","type":"text"}],"title":"setCustomData(fields:)","navigatorTitle":[{"text":"setCustomData:","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setCustomData(fields:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setCustomData","kind":"identifier"},{"kind":"text","text":"("},{"text":"fields","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionCustomDataField","text":"JVSessionCustomDataField"},{"text":"])","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"JVSessionController"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"JVSessionController"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JVSessionController"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/delegate"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/init","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setContactInfo(_:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setCustomData(fields:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setPreferredServer(_:)","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/shutDown()","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/startUp(channelID:userToken:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"JVSessionController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"startUpWithChannelID:userToken:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1startUp(channelID:userToken:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"startUpWithChannelID:userToken:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1startUp(channelID:userToken:)\/fragments"},{"value":"shutDown","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1shutDown()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1shutDown()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shutDown"}]},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1delegate\/title"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1delegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}]},{"value":"setContactInfo:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setContactInfo(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setContactInfo:"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setContactInfo(_:)\/fragments","op":"replace"},{"value":"session","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments","value":[{"text":"session","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/title","value":"JVSessionController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController\/fragments","value":[{"text":"JVSessionController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setPreferredServer(_:)\/title","value":"setPreferredServer:"},{"value":[{"kind":"text","text":"- "},{"text":"setPreferredServer:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setPreferredServer(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setCustomData(fields:)\/title","value":"setCustomData:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCustomData:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setCustomData(fields:)\/fragments"}]}]}