{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(JVSessionDelegate) ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVSessionDelegate"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate\/jivoSession(updateUnreadCounter:number:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"abstract":[{"type":"text","text":"Interface to handle session events,"},{"type":"text","text":" "},{"type":"text","text":"relates to "},{"code":"Jivo.session","type":"codeVoice"},{"text":" namespace","type":"text"}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVSessionDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVSessionDelegate"}],"role":"symbol","roleHeading":"Protocol","title":"JVSessionDelegate","modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(pl)JVSessionDelegate","symbolKind":"protocol"},"variants":[{"paths":["\/documentation\/jivosdk\/jvsessiondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvsessiondelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVSessionDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"JVSessionDelegate","kind":"identifier"}],"type":"topic","abstract":[{"text":"Interface to handle session events,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"relates to "},{"type":"codeVoice","code":"Jivo.session"},{"type":"text","text":" namespace"}],"url":"\/documentation\/jivosdk\/jvsessiondelegate","kind":"symbol","title":"JVSessionDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","url":"\/documentation\/jivosdk","title":"JivoSDK","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionDelegate/jivoSession(updateUnreadCounter:number:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate\/jivoSession(updateUnreadCounter:number:)","abstract":[{"type":"text","text":"Called when unread counter changes"}],"url":"\/documentation\/jivosdk\/jvsessiondelegate\/jivosession(updateunreadcounter:number:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"updateUnreadCounter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"number","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"jivoSessionUpdateUnreadCounter:number:","kind":"identifier"}],"required":true,"title":"jivoSession(updateUnreadCounter:number:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"JVSessionDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"JVSessionDelegate","kind":"identifier"}]},{"value":[{"text":"JVSessionDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionDelegate\/jivoSession(updateUnreadCounter:number:)"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVSessionDelegate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"JVSessionDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/title"},{"value":[{"text":"JVSessionDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"JVSessionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate~1jivoSession(updateUnreadCounter:number:)\/title","value":"jivoSessionUpdateUnreadCounter:number:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoSessionUpdateUnreadCounter:number:"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionDelegate~1jivoSession(updateUnreadCounter:number:)\/fragments","op":"replace"}]}]}