{"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionCustomDataField"},"metadata":{"navigatorTitle":[{"text":"JVSessionCustomDataField","kind":"identifier"}],"symbolKind":"class","role":"symbol","modules":[{"name":"JivoSDK"}],"title":"JVSessionCustomDataField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVSessionCustomDataField"}],"roleHeading":"Class","externalID":"c:@M@JivoSDK@objc(cs)JVSessionCustomDataField"},"abstract":[{"type":"text","text":"Custom Data Field for user"}],"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionCustomDataField\/init(title:key:content:link:)"],"generated":true,"title":"Initializers"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvsessioncustomdatafield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvsessioncustomdatafield"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(JVSessionCustomDataField) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVSessionCustomDataField","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionCustomDataField":{"abstract":[{"type":"text","text":"Custom Data Field for user"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVSessionCustomDataField","kind":"identifier"}],"navigatorTitle":[{"text":"JVSessionCustomDataField","kind":"identifier"}],"type":"topic","title":"JVSessionCustomDataField","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionCustomDataField","url":"\/documentation\/jivosdk\/jvsessioncustomdatafield"},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject"},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionCustomDataField/init(title:key:content:link:)":{"abstract":[],"url":"\/documentation\/jivosdk\/jvsessioncustomdatafield\/init(title:key:content:link:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithTitle:key:content:link:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionCustomDataField\/init(title:key:content:link:)","type":"topic","title":"init(title:key:content:link:)","kind":"symbol","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"role":"collection","url":"\/documentation\/jivosdk","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"JVSessionCustomDataField"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"JVSessionCustomDataField","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"JVSessionCustomDataField","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionCustomDataField\/init(title:key:content:link:)"],"generated":true,"title":"Instance Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVSessionCustomDataField"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"JVSessionCustomDataField","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField\/title"},{"op":"replace","value":[{"text":"JVSessionCustomDataField","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField\/fragments"},{"value":[{"text":"JVSessionCustomDataField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField~1init(title:key:content:link:)\/title","op":"replace","value":"initWithTitle:key:content:link:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTitle:key:content:link:"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionCustomDataField~1init(title:key:content:link:)\/fragments","op":"replace"}]}]}