{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(JVSessionContactInfo) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVSessionContactInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jvsessioncontactinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvsessioncontactinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP","doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Contact Info for user"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVSessionContactInfo"}],"title":"JVSessionContactInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@JivoSDK@objc(cs)JVSessionContactInfo","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"JVSessionContactInfo"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo\/init()","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo\/init(name:email:phone:brief:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo\/debugDescription"]}],"references":{"doc://org.cocoapods.JivoSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(pl)NSObject"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionContactInfo/init(name:email:phone:brief:)":{"role":"symbol","title":"init(name:email:phone:brief:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"brief"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo\/init(name:email:phone:brief:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithName:email:phone:brief:"}],"url":"\/documentation\/jivosdk\/jvsessioncontactinfo\/init(name:email:phone:brief:)"},"doc://org.cocoapods.JivoSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s7CVarArgP"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionContactInfo/debugDescription":{"role":"symbol","title":"debugDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo\/debugDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"debugDescription"}],"url":"\/documentation\/jivosdk\/jvsessioncontactinfo\/debugdescription"},"doc://org.cocoapods.JivoSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionContactInfo/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/jivosdk\/jvsessioncontactinfo\/init()"},"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ"},"doc://org.cocoapods.JivoSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionContactInfo":{"role":"symbol","title":"JVSessionContactInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVSessionContactInfo"}],"abstract":[{"type":"text","text":"Contact Info for user"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVSessionContactInfo"}],"url":"\/documentation\/jivosdk\/jvsessioncontactinfo"},"doc://org.cocoapods.JivoSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.JivoSDK\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"JVSessionContactInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JVSessionContactInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JVSessionContactInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo\/debugDescription"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo\/init()","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionContactInfo\/init(name:email:phone:brief:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVSessionContactInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo~1init(name:email:phone:brief:)\/title","value":"initWithName:email:phone:brief:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo~1init(name:email:phone:brief:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:email:phone:brief:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo~1debugDescription\/title","value":"debugDescription"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo~1debugDescription\/fragments","value":[{"kind":"identifier","text":"debugDescription"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo\/title","value":"JVSessionContactInfo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionContactInfo\/fragments","value":[{"kind":"identifier","text":"JVSessionContactInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}