{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer"},"abstract":[{"type":"text","text":"Primary Jivo servers, by geographical region"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(JVSessionServer) "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVSessionServer","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/asia","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/auto","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/europe","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/russia"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/Equatable-Implementations","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/SQ","doc:\/\/org.cocoapods.JivoSDK\/SH","doc:\/\/org.cocoapods.JivoSDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jvsessionserver"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvsessionserver"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"metadata":{"modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@E@JVSessionServer","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVSessionServer","kind":"identifier"}],"title":"JVSessionServer","roleHeading":"Enumeration","role":"symbol","navigatorTitle":[{"text":"JVSessionServer","kind":"identifier"}]},"references":{"doc://org.cocoapods.JivoSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer/asia":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/asia","role":"symbol","url":"\/documentation\/jivosdk\/jvsessionserver\/asia","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"asia","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"JVSessionServerAsia","kind":"identifier"}],"kind":"symbol","title":"JVSessionServer.asia"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer/auto":{"url":"\/documentation\/jivosdk\/jvsessionserver\/auto","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/auto","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVSessionServerAuto"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}],"type":"topic","title":"JVSessionServer.auto"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer/russia":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"russia","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvsessionserver\/russia","title":"JVSessionServer.russia","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/russia","role":"symbol","navigatorTitle":[{"text":"JVSessionServerRussia","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer/Equatable-Implementations":{"kind":"article","url":"\/documentation\/jivosdk\/jvsessionserver\/equatable-implementations","abstract":[],"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/Equatable-Implementations","role":"collectionGroup"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/jivosdk\/jvsessionserver\/rawrepresentable-implementations","abstract":[],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","role":"collection","type":"topic","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer/init(rawValue:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/jivosdk\/jvsessionserver\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/init(rawValue:)","role":"symbol"},"doc://org.cocoapods.JivoSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.JivoSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.JivoSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"JVSessionServer","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer","title":"JVSessionServer","url":"\/documentation\/jivosdk\/jvsessionserver","abstract":[{"type":"text","text":"Primary Jivo servers, by geographical region"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVSessionServer"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionServer/europe":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"europe","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvsessionserver\/europe","title":"JVSessionServer.europe","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/europe","role":"symbol","navigatorTitle":[{"text":"JVSessionServerEurope","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"JVSessionServer","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"JVSessionServer","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JVSessionServer"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/asia","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/auto","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/europe","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionServer\/russia"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVSessionServer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"JVSessionServerAsia","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer~1asia\/title"},{"value":[{"kind":"identifier","text":"JVSessionServerAsia"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer~1asia\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer~1auto\/title","value":"JVSessionServerAuto","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer~1auto\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVSessionServerAuto"}]},{"value":"JVSessionServerRussia","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer~1russia\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer~1russia\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVSessionServerRussia"}]},{"value":"JVSessionServer","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer\/fragments","value":[{"kind":"identifier","text":"JVSessionServer"}],"op":"replace"},{"value":"JVSessionServerEurope","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer~1europe\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionServer~1europe\/fragments","value":[{"kind":"identifier","text":"JVSessionServerEurope"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}