{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/native_swiftpm_link"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/native_swiftpm_link"]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_swiftpm_link","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"For native project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/native_usage_basics"],"anchor":"For-native-project","generated":true}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"content":[{"anchor":"Dependency","text":"Dependency","level":2,"type":"heading"},{"inlineContent":[{"text":"Add SDK as dependency into your project:","type":"text"}],"type":"paragraph"},{"syntax":null,"code":["https:\/\/github.com\/JivoChat\/JivoSDK-iOS.git"],"type":"codeListing"}],"kind":"content"}],"abstract":[{"type":"text","text":"Primary option"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"kind":"article","metadata":{"roleHeading":"Article","title":"Link to SDK using SwiftPM","modules":[{"name":"JivoSDK"}],"role":"article"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/native_api_ref":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_api_ref","title":"API Reference","role":"article","kind":"article","abstract":[{"text":"Swift API","type":"text"}],"url":"\/documentation\/jivosdk\/native_api_ref"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","abstract":[],"url":"\/documentation\/jivosdk","title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic"},"doc://org.cocoapods.JivoSDK/tutorials/JivoSDK/native_usage_basics":{"url":"\/tutorials\/jivosdk\/native_usage_basics","identifier":"doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/native_usage_basics","type":"topic","abstract":[{"type":"text","text":"Some scenarios of how to use SDK"}],"role":"project","title":"Basic usage","kind":"project"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/native_pod_link":{"type":"topic","title":"Link to SDK using CocoaPods","kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_pod_link","abstract":[{"text":"Alternative option","type":"text"}],"url":"\/documentation\/jivosdk\/native_pod_link","role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"For-native-project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/native_usage_basics"],"title":"For native project","generated":true}]}]}]}