{"variants":[{"paths":["\/documentation\/jivosdk\/native_pod_link"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/native_pod_link"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"JivoSDK"}],"title":"Link to SDK"},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_pod_link","interfaceLanguage":"swift"},"abstract":[{"text":"Using CocoaPods","type":"text"}],"primaryContentSections":[{"content":[{"level":2,"type":"heading","text":"Repos","anchor":"Repos"},{"type":"paragraph","inlineContent":[{"text":"Specify the following sources at the beginning of your ","type":"text"},{"type":"codeVoice","code":"Podfile"},{"text":":","type":"text"}]},{"syntax":"ruby","code":["source 'https:\/\/github.com\/cocoapods\/specs' ","source 'https:\/\/github.com\/jivochat\/cocoapods-repo'"],"type":"codeListing"},{"level":2,"anchor":"Dependency","text":"Dependency","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add SDK as dependency into your "},{"code":"Podfile","type":"codeVoice"},{"text":":","type":"text"}]},{"syntax":"ruby","code":["pod 'JivoSDK'"],"type":"codeListing"}],"kind":"content"}],"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"seeAlsoSections":[{"title":"For native project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/native_usage_basics"],"generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/native_api_ref":{"type":"topic","url":"\/documentation\/jivosdk\/native_api_ref","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_api_ref","title":"API Reference","abstract":[{"type":"text","text":"Swift API"}],"kind":"article","role":"article"},"doc://org.cocoapods.JivoSDK/tutorials/JivoSDK/native_usage_basics":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/native_usage_basics","type":"topic","url":"\/tutorials\/jivosdk\/native_usage_basics","abstract":[{"text":"Some scenarios of how to use SDK","type":"text"}],"role":"project","title":"Basic usage","kind":"project"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","type":"topic","kind":"symbol","abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/native_usage_basics"],"title":"For native project"}],"op":"replace","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}