{"sections":[],"primaryContentSections":[{"content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"For native projects, "},{"type":"strong","inlineContent":[{"type":"text","text":"SDK API"}]},{"type":"text","text":" is divided into several namespaces:"}],"type":"paragraph"},{"header":"row","type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"text":"Namespace","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Meaning"}]}]],[[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Entry point"}]}]],[[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference"},{"text":".","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","type":"reference"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Responsible for everything related to the communication session, such as connection and client data"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Responsible for everything related to the visual representation of chat on screen"}]}]],[[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Contains methods responsible for setting up and processing Push Notifications"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","isActive":true}]}],[{"type":"paragraph","inlineContent":[{"text":"Helps debugging the SDK","type":"text"}]}]]]}],"kind":"content"}],"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_api_ref","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/native_api_ref"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/native_api_ref"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Article","title":"API Reference","role":"article","modules":[{"name":"JivoSDK"}]},"abstract":[{"type":"text","text":"Swift API"}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_swiftpm_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_pod_link","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/native_usage_basics"],"anchor":"For-native-project","title":"For native project","generated":true}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"navigatorTitle":[{"text":"debugging","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","url":"\/documentation\/jivosdk\/jivo\/debugging","kind":"symbol","role":"symbol","title":"debugging","abstract":[{"text":"Namespace for SDK debugging","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugging","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController","text":"JVDebuggingController","kind":"typeIdentifier"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","title":"JivoSDK","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/native_swiftpm_link":{"role":"article","kind":"article","url":"\/documentation\/jivosdk\/native_swiftpm_link","abstract":[{"text":"Primary option","type":"text"}],"type":"topic","title":"Link to SDK using SwiftPM","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_swiftpm_link"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/native_pod_link":{"abstract":[{"text":"Alternative option","type":"text"}],"title":"Link to SDK using CocoaPods","role":"article","type":"topic","url":"\/documentation\/jivosdk\/native_pod_link","kind":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_pod_link"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifications"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","text":"JVNotificationsController"}],"url":"\/documentation\/jivosdk\/jivo\/notifications","title":"notifications","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"notifications"}],"type":"topic","abstract":[{"text":"Namespace for Push Notifications","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"title":"Jivo","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"type":"topic","url":"\/documentation\/jivosdk\/jivo","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"type":"topic","url":"\/documentation\/jivosdk\/jivo\/display","abstract":[{"type":"text","text":"Namespace for SDK displaying"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","kind":"symbol","navigatorTitle":[{"text":"display","kind":"identifier"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"display","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JVDisplayController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController"}],"title":"display"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"kind":"symbol","url":"\/documentation\/jivosdk\/jivo\/session","type":"topic","navigatorTitle":[{"kind":"identifier","text":"session"}],"abstract":[{"text":"Namespace for managing user session","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","title":"session","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController","text":"JVSessionController"}]},"doc://org.cocoapods.JivoSDK/tutorials/JivoSDK/native_usage_basics":{"type":"topic","title":"Basic usage","identifier":"doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/native_usage_basics","abstract":[{"text":"Some scenarios of how to use SDK","type":"text"}],"kind":"project","role":"project","url":"\/tutorials\/jivosdk\/native_usage_basics"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"For-native-project","title":"For native project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_swiftpm_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/native_pod_link","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/native_usage_basics"]}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/title","value":"debugging"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/fragments","value":[{"kind":"identifier","text":"debugging"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title","value":"notifications"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments","value":[{"kind":"identifier","text":"notifications"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title","value":"display"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments","value":[{"text":"display","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title","value":"session"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments","value":[{"text":"session","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}