{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/react_pod_link"]},{"paths":["\/documentation\/jivosdk\/react_pod_link"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_module_bridge","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/react_usage_basics"],"title":"For React Native project","generated":true}],"kind":"article","abstract":[{"text":"Using CocoaPods","type":"text"}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Repos","text":"Repos","level":2,"type":"heading"},{"inlineContent":[{"text":"Specify the following sources at the beginning of your ","type":"text"},{"type":"codeVoice","code":"Podfile"},{"text":":","type":"text"}],"type":"paragraph"},{"type":"codeListing","code":["source 'https:\/\/github.com\/cocoapods\/specs' ","source 'https:\/\/github.com\/jivochat\/cocoapods-repo'"],"syntax":"ruby"},{"level":2,"text":"Plugin","anchor":"Plugin","type":"heading"},{"inlineContent":[{"type":"text","text":"For SDK proper cooperation with React Native, you should install special plugin:"}],"type":"paragraph"},{"type":"codeListing","syntax":"sh","code":["gem install cocoapods-user-defined-build-types"]},{"inlineContent":[{"type":"text","text":"Then activate this plugin using directives in your "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":":"}],"type":"paragraph"},{"type":"codeListing","syntax":"ruby","code":["plugin 'cocoapods-user-defined-build-types'","enable_user_defined_build_types!"]},{"level":2,"type":"heading","text":"Dependency","anchor":"Dependency"},{"type":"paragraph","inlineContent":[{"text":"Add SDK as dynamic dependency in your ","type":"text"},{"type":"codeVoice","code":"Podfile"},{"text":":","type":"text"}]},{"syntax":"ruby","code":["pod 'JivoSDK', :build_type => :dynamic_framework"],"type":"codeListing"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_pod_link","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"article","title":"Link to SDK","modules":[{"name":"JivoSDK"}],"roleHeading":"Article"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"type":"topic","title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/react_api_ref":{"kind":"article","title":"API Reference","type":"topic","url":"\/documentation\/jivosdk\/react_api_ref","role":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref","abstract":[{"type":"text","text":"JavaScript API"}]},"doc://org.cocoapods.JivoSDK/tutorials/JivoSDK/react_usage_basics":{"role":"project","identifier":"doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/react_usage_basics","type":"topic","url":"\/tutorials\/jivosdk\/react_usage_basics","kind":"project","title":"Basic usage","abstract":[{"text":"Some scenarios of how to use SDK","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/react_module_bridge":{"kind":"article","title":"Module Bridge","type":"topic","url":"\/documentation\/jivosdk\/react_module_bridge","role":"article","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_module_bridge","abstract":[{"text":"JavaScript Bridge","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"add","value":null},{"value":[{"title":"For React Native project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_module_bridge","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/react_usage_basics"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}