{"primaryContentSections":[{"content":[{"text":"Session","type":"heading","anchor":"Session","level":2},{"type":"codeListing","syntax":null,"code":["Jivo.setPreferredServer(server)"]},{"inlineContent":[{"type":"text","text":"Same as "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","type":"reference"},{"text":".","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setPreferredServer(_:)"}],"type":"paragraph"},{"inlineContent":[{"code":"server","type":"codeVoice"},{"text":" is one of possible strings:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"auto"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"europe"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"russia","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"asia"}]}]}]},{"code":["Jivo.startUp(channelID, userToken)"],"type":"codeListing","syntax":null},{"type":"paragraph","inlineContent":[{"text":"Same as ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"text":".","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","type":"reference"},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setup(widgetID:clientIdentity:)","isActive":true}]},{"type":"codeListing","syntax":null,"code":["Jivo.setContactInfo(info)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Same as "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference","isActive":true},{"text":".","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","isActive":true},{"type":"text","text":"."},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setContactInfo(_:)"}]},{"inlineContent":[{"code":"info","type":"codeVoice"},{"text":" is an object containing zero or more string-to-string pairs with following keys:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"name"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"email"}]}]},{"content":[{"inlineContent":[{"text":"phone","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"brief"}],"type":"paragraph"}]}],"type":"unorderedList"},{"syntax":null,"code":["Jivo.setCustomData(fields)"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"Same as ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"text":".","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session"},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setCustomData(fields:)","isActive":true}]},{"type":"paragraph","inlineContent":[{"code":"fields","type":"codeVoice"},{"text":" is an array containing zero or more fields, each field is an object containing string-to-string pairs with following keys:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"title"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"key"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"content","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"link"}],"type":"paragraph"}]}]},{"code":["Jivo.shutDown()"],"syntax":null,"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Same as "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference"},{"type":"text","text":"."},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","type":"reference"},{"type":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/shutDown()","type":"reference","isActive":true}]},{"anchor":"Display","level":2,"type":"heading","text":"Display"},{"code":["Jivo.isOnscreen(callback)"],"syntax":null,"type":"codeListing"},{"inlineContent":[{"text":"Fires ","type":"text"},{"type":"codeVoice","code":"callback"},{"text":" passing an array with single boolean value of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","type":"reference","isActive":true},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/isOnscreen","type":"reference","isActive":true}],"type":"paragraph"},{"type":"codeListing","syntax":null,"code":["Jivo.setLocale(localeID)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Same as "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference","isActive":true},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","isActive":true},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setLocale(_:)","isActive":true,"type":"reference"}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"localeID"},{"text":" is a locale identifier","type":"text"}]},{"syntax":null,"code":["Jivo.present()"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"Same as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","isActive":true},{"text":".","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/present(over:)"},{"type":"text","text":" calling with root view controller"}],"type":"paragraph"},{"syntax":null,"type":"codeListing","code":["Jivo.setPresentationRequestHandler(callback)"]},{"inlineContent":[{"type":"text","text":"Sets "},{"code":"callback","type":"codeVoice"},{"type":"text","text":" to be called when SDK will request to display itself"}],"type":"paragraph"},{"type":"heading","text":"Notifications","anchor":"Notifications","level":2},{"syntax":null,"type":"codeListing","code":["Jivo.setPermissionAskingAt(moment)"]},{"inlineContent":[{"type":"text","text":"Same as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","isActive":true,"type":"reference"},{"type":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionAsking(at:)","isActive":true,"type":"reference"}],"type":"paragraph"},{"inlineContent":[{"type":"codeVoice","code":"moment"},{"text":" is one of possible strings:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"never","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"onconnect"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"onappear","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"onsend","type":"text"}],"type":"paragraph"}]}]},{"code":["Jivo.setPushToken(hex)"],"type":"codeListing","syntax":null},{"inlineContent":[{"type":"text","text":"Same as "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","isActive":true,"type":"reference"},{"text":".","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(hex:)"}],"type":"paragraph"},{"code":["Jivo.handlePushPayload(userInfo)"],"type":"codeListing","syntax":null},{"inlineContent":[{"text":"Same as ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications"},{"text":".","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/handleIncoming(userInfo:completionHandler:)","type":"reference"}],"type":"paragraph"},{"type":"heading","level":2,"text":"Debugging","anchor":"Debugging"},{"type":"codeListing","syntax":null,"code":["Jivo.setDebuggingLevel(level)"]},{"inlineContent":[{"text":"Same as ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","isActive":true,"type":"reference"},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/setLevel(_:)","isActive":true,"type":"reference"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"code":"level","type":"codeVoice"},{"type":"text","text":" is one of possible strings:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"silent"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"full","type":"text"}]}]}]},{"code":["Jivo.archiveLogs(callback)"],"type":"codeListing","syntax":null},{"type":"paragraph","inlineContent":[{"type":"text","text":"Will fire "},{"type":"codeVoice","code":"callback"},{"type":"text","text":" passing two arguments:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"local url of archived logs"}]}]},{"content":[{"inlineContent":[{"text":"operation status such as “success”, “failedAccessing”, “failedPreparing”, or “failed”","type":"text"}],"type":"paragraph"}]}]}],"kind":"content"}],"metadata":{"roleHeading":"Article","modules":[{"name":"JivoSDK"}],"title":"API Reference","role":"article"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/react_api_ref"]},{"paths":["\/documentation\/jivosdk\/react_api_ref"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"JavaScript API","type":"text"}],"seeAlsoSections":[{"title":"For React Native project","generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_module_bridge","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/react_usage_basics"],"anchor":"For-React-Native-project"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setPreferredServer(_:)":{"url":"\/documentation\/jivosdk\/jvsessioncontroller\/setpreferredserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setPreferredServer","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7JivoSDK15JVSessionServerO","text":"JVSessionServer","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"setPreferredServer(_:)","kind":"symbol","abstract":[{"type":"text","text":"Specifies preferred server for SDK to connect to Jivo"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setPreferredServer(_:)","role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"navigatorTitle":[{"text":"display","kind":"identifier"}],"title":"display","type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jivo\/display","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"display"},{"text":": ","kind":"text"},{"text":"JVDisplayController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Namespace for SDK displaying"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/session":{"abstract":[{"type":"text","text":"Namespace for managing user session"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"kind":"text","text":": "},{"text":"JVSessionController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionController","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/session","navigatorTitle":[{"text":"session","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jivo\/session","type":"topic","role":"symbol","title":"session"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"role":"symbol","type":"topic","title":"Jivo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","url":"\/documentation\/jivosdk\/jivo","abstract":[],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"url":"\/documentation\/jivosdk\/jivo\/notifications","title":"notifications","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"notifications"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","abstract":[{"text":"Namespace for Push Notifications","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"notifications","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","text":"JVNotificationsController","kind":"typeIdentifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setCustomData(fields:)":{"navigatorTitle":[{"text":"setCustomData:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setCustomData(fields:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCustomData"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fields"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"JVClientCustomDataField","preciseIdentifier":"s:7JivoSDK23JVClientCustomDataFielda"},{"text":"])","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Assigns custom data to user,"},{"type":"text","text":" "},{"text":"if needed for your business","type":"text"}],"url":"\/documentation\/jivosdk\/jvsessioncontroller\/setcustomdata(fields:)","kind":"symbol","title":"setCustomData(fields:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/react_module_bridge":{"abstract":[{"type":"text","text":"JavaScript Bridge"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_module_bridge","role":"article","title":"Module Bridge","url":"\/documentation\/jivosdk\/react_module_bridge","kind":"article","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setContactInfo(_:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setContactInfo(_:)","url":"\/documentation\/jivosdk\/jvsessioncontroller\/setcontactinfo(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setContactInfo"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK19JVClientContactInfoa","text":"JVClientContactInfo"},{"text":"?)","kind":"text"}],"role":"symbol","kind":"symbol","title":"setContactInfo(_:)","navigatorTitle":[{"kind":"identifier","text":"setContactInfo:"}],"abstract":[{"type":"text","text":"Assigns contact info to user,"},{"type":"text","text":" "},{"text":"to reach him easier in future","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setPermissionAsking(at:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionAsking(at:)","abstract":[{"type":"text","text":"Specifies when SDK should request access to Push Notifications"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPermissionAsking"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7JivoSDK37JVNotificationsPermissionAskingMomentO","kind":"typeIdentifier","text":"JVNotificationsPermissionAskingMoment"},{"text":")","kind":"text"}],"title":"setPermissionAsking(at:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setpermissionasking(at:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setPushToken(hex:)":{"url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setpushtoken(hex:)","title":"setPushToken(hex:)","role":"symbol","navigatorTitle":[{"text":"setPushTokenHex:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(hex:)","abstract":[{"text":"Associate the Push Token with current user using his userToken in hex-string form","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setPushToken","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hex"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"url":"\/documentation\/jivosdk\/jivo\/debugging","abstract":[{"text":"Namespace for SDK debugging","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"debugging"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugging"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController","kind":"typeIdentifier","text":"JVDebuggingController"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","title":"debugging"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/shutDown()":{"navigatorTitle":[{"kind":"identifier","text":"shutDown"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/shutDown()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shutDown"},{"text":"()","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Closes current connection, clears the local database,"},{"type":"text","text":" "},{"text":"and unsubscribes device from Push Notifications","type":"text"}],"url":"\/documentation\/jivosdk\/jvsessioncontroller\/shutdown()","kind":"symbol","title":"shutDown()"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController/setLevel(_:)":{"title":"setLevel(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setLevel","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7JivoSDK16JVDebuggingLevelO","kind":"typeIdentifier","text":"JVDebuggingLevel"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Current level of logging verbosity"}],"url":"\/documentation\/jivosdk\/jvdebuggingcontroller\/setlevel(_:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/setLevel(_:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/handleIncoming(userInfo:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"handleIncomingWithUserInfo:completionHandler:"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/handleIncoming(userInfo:completionHandler:)","abstract":[{"type":"text","text":"Processes userInfo of Push Notification"},{"text":" ","type":"text"},{"text":"For ObjC code","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handleIncoming","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"UIBackgroundFetchResult","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"handleIncoming(userInfo:completionHandler:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/handleincoming(userinfo:completionhandler:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/present(over:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/present(over:)","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/present(over:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"over"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"JVSessionHandle","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVSessionHandle"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","title":"present(over:)","navigatorTitle":[{"text":"presentOver:","kind":"identifier"}],"abstract":[{"type":"text","text":"Displays SDK modally on screen, slides it up from bottom edge (animated)"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVSessionController/setup(widgetID:clientIdentity:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVSessionController\/setup(widgetID:clientIdentity:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"widgetID"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"clientIdentity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"JVClientIdentity","preciseIdentifier":"s:7JivoSDK16JVClientIdentityO","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"JVClient","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVClient"}],"type":"topic","abstract":[{"type":"text","text":"Starts a logical session for user,"},{"type":"text","text":" "},{"text":"by either creating a new session or resuming existing one","type":"text"}],"url":"\/documentation\/jivosdk\/jvsessioncontroller\/setup(widgetid:clientidentity:)","kind":"symbol","title":"setup(widgetID:clientIdentity:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/isOnscreen":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/isOnscreen","url":"\/documentation\/jivosdk\/jvdisplaycontroller\/isonscreen","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isOnscreen","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","kind":"symbol","title":"isOnscreen","navigatorTitle":[{"text":"isOnscreen","kind":"identifier"}],"abstract":[{"type":"text","text":"Determines whether SDK is currently in UI hierarchy"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/react_pod_link":{"abstract":[{"text":"Using CocoaPods","type":"text"}],"role":"article","title":"Link to SDK","url":"\/documentation\/jivosdk\/react_pod_link","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_pod_link","type":"topic","kind":"article"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/setLocale(_:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/setLocale(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setLocale","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"},{"text":"?)","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Sets the custom locale for use instead of system one"}],"url":"\/documentation\/jivosdk\/jvdisplaycontroller\/setlocale(_:)","kind":"symbol","title":"setLocale(_:)"},"doc://org.cocoapods.JivoSDK/tutorials/JivoSDK/react_usage_basics":{"role":"project","identifier":"doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/react_usage_basics","kind":"project","url":"\/tutorials\/jivosdk\/react_usage_basics","title":"Basic usage","type":"topic","abstract":[{"type":"text","text":"Some scenarios of how to use SDK"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":[{"anchor":"For-React-Native-project","generated":true,"title":"For React Native project","identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_module_bridge","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/react_usage_basics"]}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title","value":"display"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments","op":"replace","value":[{"kind":"identifier","text":"display"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/title","op":"replace","value":"session"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1session\/fragments","value":[{"text":"session","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"value":[{"text":"Jivo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title","value":"notifications","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments","value":[{"text":"notifications","kind":"identifier"}]},{"op":"replace","value":"setCustomData:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setCustomData(fields:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setCustomData(fields:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setCustomData:","kind":"identifier"}]},{"value":"setContactInfo:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setContactInfo(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setContactInfo:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1setContactInfo(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPushToken(hex:)\/title","value":"setPushTokenHex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPushToken(hex:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPushTokenHex:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/title","value":"debugging","op":"replace"},{"value":[{"text":"debugging","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/fragments","op":"replace"},{"value":"shutDown","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1shutDown()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVSessionController~1shutDown()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"shutDown","kind":"identifier"}]},{"value":"handleIncomingWithUserInfo:completionHandler:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1handleIncoming(userInfo:completionHandler:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1handleIncoming(userInfo:completionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handleIncomingWithUserInfo:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1present(over:)\/title","value":"presentOver:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentOver:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1present(over:)\/fragments"},{"value":"isOnscreen","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1isOnscreen\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1isOnscreen\/fragments","value":[{"kind":"identifier","text":"isOnscreen"}]}]}]}