{"metadata":{"role":"article","modules":[{"name":"JivoSDK"}],"roleHeading":"Article","title":"Module Bridge"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/react_usage_basics"],"generated":true,"title":"For React Native project"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"]]},"kind":"article","abstract":[{"text":"JavaScript Bridge","type":"text"}],"variants":[{"paths":["\/documentation\/jivosdk\/react_module_bridge"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/react_module_bridge"]}],"sections":[],"primaryContentSections":[{"content":[{"text":"Import files","type":"heading","anchor":"Import-files","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Please import these items from directory "},{"type":"codeVoice","code":"[JivoSDK\/Adapters\/ReactNative]"},{"type":"text","text":":"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"jivosdk_module","type":"codeVoice"},{"type":"text","text":" folder into your Xcode target"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"JivoSDK.module.js","type":"codeVoice"},{"type":"text","text":" file into your React Native project"}]}]}]},{"type":"aside","name":"Important","style":"important","content":[{"inlineContent":[{"type":"text","text":"Please keep "},{"type":"codeVoice","code":"[jivosdk_module\/JivoSDK.module.m]"},{"text":" file up-to-date alongwith SDK updates","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_module_bridge","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK","role":"collection","url":"\/documentation\/jivosdk","type":"topic"},"doc://org.cocoapods.JivoSDK/tutorials/JivoSDK/react_usage_basics":{"type":"topic","title":"Basic usage","role":"project","kind":"project","url":"\/tutorials\/jivosdk\/react_usage_basics","abstract":[{"type":"text","text":"Some scenarios of how to use SDK"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/react_usage_basics"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/react_pod_link":{"abstract":[{"type":"text","text":"Using CocoaPods"}],"role":"article","title":"Link to SDK","kind":"article","url":"\/documentation\/jivosdk\/react_pod_link","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_pod_link"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/react_api_ref":{"type":"topic","url":"\/documentation\/jivosdk\/react_api_ref","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref","abstract":[{"type":"text","text":"JavaScript API"}],"kind":"article","role":"article","title":"API Reference"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_pod_link","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/react_api_ref","doc:\/\/org.cocoapods.JivoSDK\/tutorials\/JivoSDK\/react_usage_basics"],"title":"For React Native project"}],"path":"\/seeAlsoSections"}]}]}