{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdksessionserver\/auto"]},{"paths":["\/documentation\/jivosdk\/jivosdksessionserver\/auto"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"auto","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/auto","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer"]]},"metadata":{"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"JivoSDKSessionServerAuto"}],"platforms":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"role":"symbol","externalID":"c:@M@JivoSDK@E@JivoSDKSessionServer@JivoSDKSessionServerAuto","title":"JivoSDKSessionServer.auto"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"kind":"symbol","title":"JivoSDK","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer","url":"\/documentation\/jivosdk\/jivosdksessionserver","title":"JivoSDKSessionServer","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKSessionServer"}],"navigatorTitle":[{"text":"JivoSDKSessionServer","kind":"identifier"}],"role":"symbol","deprecated":true,"abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer/auto":{"kind":"symbol","type":"topic","title":"JivoSDKSessionServer.auto","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/auto","url":"\/documentation\/jivosdk\/jivosdksessionserver\/auto","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"auto"}],"navigatorTitle":[{"text":"JivoSDKSessionServerAuto","kind":"identifier"}],"role":"symbol","deprecated":true,"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"JivoSDKSessionServerAuto","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"JivoSDKSessionServerAuto","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"JivoSDKSessionServerAuto"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer\/title","op":"replace","value":"JivoSDKSessionServer"},{"value":[{"text":"JivoSDKSessionServer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1auto\/title","value":"JivoSDKSessionServerAuto","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1auto\/fragments","value":[{"text":"JivoSDKSessionServerAuto","kind":"identifier"}],"op":"replace"}]}]}