{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"europe"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdksessionserver\/europe"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdksessionserver\/europe"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/europe"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"roleHeading":"Case","title":"JivoSDKSessionServer.europe","navigatorTitle":[{"kind":"identifier","text":"JivoSDKSessionServerEurope"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"europe","kind":"identifier"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@JivoSDK@E@JivoSDKSessionServer@JivoSDKSessionServerEurope","modules":[{"name":"JivoSDK"}],"platforms":[]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer/europe":{"url":"\/documentation\/jivosdk\/jivosdksessionserver\/europe","navigatorTitle":[{"kind":"identifier","text":"JivoSDKSessionServerEurope"}],"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/europe","title":"JivoSDKSessionServer.europe","deprecated":true,"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"europe"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JivoSDKSessionServer","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer","role":"symbol","title":"JivoSDKSessionServer","abstract":[],"url":"\/documentation\/jivosdk\/jivosdksessionserver","kind":"symbol","navigatorTitle":[{"text":"JivoSDKSessionServer","kind":"identifier"}],"deprecated":true,"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"JivoSDKSessionServerEurope"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"JivoSDKSessionServerEurope","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"JivoSDKSessionServerEurope","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"JivoSDKSessionServerEurope","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1europe\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1europe\/fragments","value":[{"text":"JivoSDKSessionServerEurope","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer\/title","value":"JivoSDKSessionServer","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer\/fragments","value":[{"text":"JivoSDKSessionServer","kind":"identifier"}],"op":"replace"}]}]}