{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdksessionserver\/russia"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdksessionserver\/russia"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"russia"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@JivoSDK@E@JivoSDKSessionServer@JivoSDKSessionServerRussia","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"JivoSDKSessionServerRussia"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"russia"}],"platforms":[],"modules":[{"name":"JivoSDK"}],"title":"JivoSDKSessionServer.russia"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/russia"},"kind":"symbol","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer/russia":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer\/russia","type":"topic","role":"symbol","title":"JivoSDKSessionServer.russia","url":"\/documentation\/jivosdk\/jivosdksessionserver\/russia","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"russia"}],"abstract":[],"navigatorTitle":[{"text":"JivoSDKSessionServerRussia","kind":"identifier"}],"kind":"symbol","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","kind":"symbol","abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSessionServer":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKSessionServer"}],"url":"\/documentation\/jivosdk\/jivosdksessionserver","deprecated":true,"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKSessionServer"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSessionServer","role":"symbol","kind":"symbol","title":"JivoSDKSessionServer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"JivoSDKSessionServerRussia","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JivoSDKSessionServerRussia"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"JivoSDKSessionServerRussia","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1russia\/title","value":"JivoSDKSessionServerRussia"},{"op":"replace","value":[{"kind":"identifier","text":"JivoSDKSessionServerRussia"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer~1russia\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer\/title","value":"JivoSDKSessionServer"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSessionServer\/fragments","op":"replace","value":[{"text":"JivoSDKSessionServer","kind":"identifier"}]}]}]}