{"abstract":[{"type":"text","text":"Determines the presentation options for Push Notification"},{"type":"text","text":" "},{"type":"text","text":"For ObjC code"}],"metadata":{"modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"configurePresentationForNotification:proxyToHandler:resolver:"}],"title":"configurePresentation(notification:proxyTo:resolver:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configurePresentation"},{"kind":"text","text":"("},{"text":"notification","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":", ","kind":"text"},{"text":"proxyTo","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK28JVNotificationsOptionsOutputa","text":"JVNotificationsOptionsOutput"},{"text":", ","kind":"text"},{"text":"resolver","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7JivoSDK30JVNotificationsOptionsResolvera","text":"JVNotificationsOptionsResolver","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@M@JivoSDK@objc(cs)JVNotificationsController(im)configurePresentationForNotification:proxyToHandler:resolver:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/configurepresentation(notification:proxyto:resolver:)"]},{"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/configurepresentation(notification:proxyto:resolver:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/configurePresentation(notification:proxyTo:resolver:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(configurePresentationForNotification:proxyToHandler:resolver:) "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configurePresentation"},{"kind":"text","text":"("},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification"},{"text":", ","kind":"text"},{"text":"proxyTo","kind":"externalParam"},{"kind":"text","text":" "},{"text":"handler","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7JivoSDK28JVNotificationsOptionsOutputa","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsOptionsOutput","kind":"typeIdentifier","text":"JVNotificationsOptionsOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolver"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsOptionsResolver","kind":"typeIdentifier","text":"JVNotificationsOptionsResolver","preciseIdentifier":"s:7JivoSDK30JVNotificationsOptionsResolvera"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"notification","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Incoming Notification","type":"text"}]}]},{"name":"completionHandler","content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"System handler to call when processing is done","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Call this method from ","type":"text"},{"code":"userNotificationCenter(_:willPresent:withCompletionHandler:)","type":"codeVoice"}]}],"style":"important","name":"Important","type":"aside"}],"kind":"content"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsOptionsOutput":{"abstract":[{"type":"text","text":"Transfers UNNotificationPresentationOptions into system for its internal needs"}],"role":"symbol","navigatorTitle":[{"text":"JVNotificationsOptionsOutput","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsOptionsOutput","kind":"identifier"}],"title":"JVNotificationsOptionsOutput","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsOptionsOutput","url":"\/documentation\/jivosdk\/jvnotificationsoptionsoutput"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifications","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JVNotificationsController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController"}],"role":"symbol","type":"topic","title":"notifications","navigatorTitle":[{"text":"notifications","kind":"identifier"}],"abstract":[{"type":"text","text":"Namespace for Push Notifications"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jivo\/notifications","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","abstract":[{"text":"Target subsystem of Push Notification","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVNotificationsTarget","kind":"identifier"}],"navigatorTitle":[{"text":"JVNotificationsTarget","kind":"identifier"}],"title":"JVNotificationsTarget","url":"\/documentation\/jivosdk\/jvnotificationstarget","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent":{"url":"\/documentation\/jivosdk\/jvnotificationsevent","type":"topic","role":"symbol","kind":"symbol","title":"JVNotificationsEvent","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsEvent"}],"abstract":[{"type":"text","text":"Event category of notification"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsEvent","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"abstract":[],"url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"role":"symbol","title":"Jivo","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"symbol","navigatorTitle":[{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/configurePresentation(notification:proxyTo:resolver:)":{"abstract":[{"text":"Determines the presentation options for Push Notification","type":"text"},{"text":" ","type":"text"},{"text":"For ObjC code","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"configurePresentationForNotification:proxyToHandler:resolver:","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configurePresentation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"notification"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"proxyTo"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7JivoSDK28JVNotificationsOptionsOutputa","kind":"typeIdentifier","text":"JVNotificationsOptionsOutput"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"resolver"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7JivoSDK30JVNotificationsOptionsResolvera","text":"JVNotificationsOptionsResolver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"configurePresentation(notification:proxyTo:resolver:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/configurePresentation(notification:proxyTo:resolver:)","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/configurepresentation(notification:proxyto:resolver:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","isActive":true},{"type":"text","text":" namespace for Push Notifications"}],"role":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvnotificationscontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsController"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsController"}],"title":"JVNotificationsController","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsOptionsResolver":{"url":"\/documentation\/jivosdk\/jvnotificationsoptionsresolver","type":"topic","role":"symbol","kind":"symbol","title":"JVNotificationsOptionsResolver","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsOptionsResolver"}],"abstract":[{"text":"Determines UNNotificationPresentationOptions, based on event parameters","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsOptionsResolver","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsOptionsResolver"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"configurePresentationForNotification:proxyToHandler:resolver:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"configurePresentationForNotification:proxyToHandler:resolver:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"configurePresentationForNotification:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":" *) ","kind":"text"},{"text":"notification","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"proxyToHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"UNNotificationPresentationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"handler","kind":"internalParam"},{"kind":"text","text":" "},{"text":"resolver:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","text":"JVNotificationsTarget","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsEvent","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","kind":"typeIdentifier","text":"JVNotificationsEvent"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"resolver","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"notifications","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title"},{"value":[{"text":"notifications","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments"},{"value":"JVNotificationsTarget","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVNotificationsTarget"}]},{"value":"JVNotificationsEvent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/title"},{"value":[{"kind":"identifier","text":"JVNotificationsEvent"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"value":[{"text":"Jivo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"op":"replace","value":"configurePresentationForNotification:proxyToHandler:resolver:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1configurePresentation(notification:proxyTo:resolver:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"configurePresentationForNotification:proxyToHandler:resolver:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1configurePresentation(notification:proxyTo:resolver:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title","value":"JVNotificationsController"},{"value":[{"kind":"identifier","text":"JVNotificationsController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments"}]}]}