{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/delegate","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","title":"delegate","modules":[{"name":"JivoSDK"}],"externalID":"c:@M@JivoSDK@objc(cs)JVNotificationsController(py)delegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"JVNotificationsDelegate","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVNotificationsDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(delegate) "},{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVNotificationsDelegate","text":"JVNotificationsDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/delegate"]},{"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Object that handles notifications events","type":"text"}],"kind":"symbol","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","kind":"symbol","role":"collection","type":"topic","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"url":"\/documentation\/jivosdk\/jivo\/notifications","type":"topic","title":"notifications","abstract":[{"type":"text","text":"Namespace for Push Notifications"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","role":"symbol","navigatorTitle":[{"text":"notifications","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"notifications","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVNotificationsController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"url":"\/documentation\/jivosdk\/jvnotificationscontroller","type":"topic","title":"JVNotificationsController","abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","isActive":true},{"type":"text","text":" namespace for Push Notifications"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JVNotificationsController","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/delegate":{"url":"\/documentation\/jivosdk\/jvnotificationscontroller\/delegate","title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVNotificationsDelegate","text":"JVNotificationsDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/delegate","abstract":[{"text":"Object that handles notifications events","type":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","title":"Jivo","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"type":"topic","abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsDelegate":{"url":"\/documentation\/jivosdk\/jvnotificationsdelegate","title":"JVNotificationsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsDelegate","abstract":[{"type":"text","text":"Interface to handle notifications events,"},{"text":" ","type":"text"},{"type":"text","text":"relates to "},{"code":"Jivo.notifications","type":"codeVoice"},{"text":" namespace","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"JVNotificationsDelegate"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<JVNotificationsDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@JivoSDK@objc(pl)JVNotificationsDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"notifications","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments","value":[{"kind":"identifier","text":"notifications"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title","value":"JVNotificationsController"},{"value":[{"text":"JVNotificationsController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1delegate\/title","value":"delegate"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"value":"JVNotificationsDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsDelegate\/fragments","value":[{"text":"JVNotificationsDelegate","kind":"identifier"}]}]}]}