{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRemoteNotification"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBackgroundFetchResult","text":"UIBackgroundFetchResult"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"userInfo","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"userInfo of Push Notification","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"UIBackgroundFetchResult, if a notification was intended for JivoSDK;"},{"type":"text","text":" "},{"type":"text","text":"or nil, otherwise"}]}],"kind":"content"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"aside","style":"important","content":[{"inlineContent":[{"text":"Call this method from ","type":"text"},{"code":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","type":"codeVoice"}],"type":"paragraph"}],"name":"Important"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference","isActive":true},{"type":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","type":"reference","isActive":true},{"type":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/listenToWillAppear(handler:)","type":"reference","isActive":true},{"type":"text","text":" callback might be called"},{"type":"text","text":" "},{"type":"text","text":"if Push Notification is related to JivoSDK"}]}],"name":"Note"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/didReceiveRemoteNotification(userInfo:)"},"sections":[],"abstract":[{"type":"text","text":"Processes userInfo of Push Notification"},{"type":"text","text":" "},{"type":"text","text":"For Swift code"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/didreceiveremotenotification(userinfo:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"]]},"metadata":{"role":"symbol","externalID":"s:7JivoSDK25JVNotificationsControllerC28didReceiveRemoteNotification8userInfoSo23UIBackgroundFetchResultVSgSDys11AnyHashableVypG_tF","symbolKind":"method","title":"didReceiveRemoteNotification(userInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRemoteNotification"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBackgroundFetchResult","text":"UIBackgroundFetchResult"},{"kind":"text","text":"?"}],"modules":[{"name":"JivoSDK"}],"roleHeading":"Instance Method"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/didReceiveRemoteNotification(userInfo:)":{"abstract":[{"type":"text","text":"Processes userInfo of Push Notification"},{"type":"text","text":" "},{"type":"text","text":"For Swift code"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRemoteNotification"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/didReceiveRemoteNotification(userInfo:)","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/didreceiveremotenotification(userinfo:)","title":"didReceiveRemoteNotification(userInfo:)","role":"symbol","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","role":"collection","abstract":[],"url":"\/documentation\/jivosdk","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDisplayController/listenToWillAppear(handler:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDisplayController\/listenToWillAppear(handler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listenToWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/jivosdk\/jvdisplaycontroller\/listentowillappear(handler:)","kind":"symbol","role":"symbol","title":"listenToWillAppear(handler:)","abstract":[{"text":"Handler will be called before opening the SDK","type":"text"}],"navigatorTitle":[{"text":"listenToWillAppear:","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/display":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"display","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JVDisplayController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDisplayController","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"display","kind":"identifier"}],"abstract":[{"text":"Namespace for SDK displaying","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/display","url":"\/documentation\/jivosdk\/jivo\/display","title":"display","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","title":"notifications","role":"symbol","url":"\/documentation\/jivosdk\/jivo\/notifications","abstract":[{"type":"text","text":"Namespace for Push Notifications"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifications"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVNotificationsController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notifications"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"url":"\/documentation\/jivosdk\/jvnotificationscontroller","navigatorTitle":[{"text":"JVNotificationsController","kind":"identifier"}],"type":"topic","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications"},{"text":" namespace for Push Notifications","type":"text"}],"title":"JVNotificationsController","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsController","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"type":"topic","kind":"symbol","title":"Jivo","url":"\/documentation\/jivosdk\/jivo","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1listenToWillAppear(handler:)\/title","op":"replace","value":"listenToWillAppear:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDisplayController~1listenToWillAppear(handler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"listenToWillAppear:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/title","op":"replace","value":"display"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1display\/fragments","op":"replace","value":[{"text":"display","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title","op":"replace","value":"notifications"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments","op":"replace","value":[{"text":"notifications","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title","op":"replace","value":"JVNotificationsController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments","op":"replace","value":[{"text":"JVNotificationsController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JVNotificationsController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace","value":"Jivo"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]}]}]}