{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/didReceive(response:)"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(didReceiveResponse:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"text":"response","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationResponse","kind":"typeIdentifier","text":"UNNotificationResponse"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"text":" ","type":"text"},{"type":"text","text":"User’s response"}]}],"name":"response"}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"text":" ","type":"text"},{"text":"Whether the response was handled by JivoSDK","type":"text"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"Call this method from ","type":"text"},{"type":"codeVoice","code":"userNotificationCenter(_:didReceive:withCompletionHandler:)"}]}],"style":"important"}]}],"sections":[],"abstract":[{"text":"Processes the User Response","type":"text"}],"metadata":{"navigatorTitle":[{"text":"didReceiveResponse:","kind":"identifier"}],"role":"symbol","title":"didReceive(response:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"text":"UNNotificationResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"JivoSDK"}],"symbolKind":"method","externalID":"c:@M@JivoSDK@objc(cs)JVNotificationsController(im)didReceiveResponse:","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/didreceive(response:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/didreceive(response:)"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"url":"\/documentation\/jivosdk\/jivo\/notifications","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"notifications","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVNotificationsController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController"}],"navigatorTitle":[{"text":"notifications","kind":"identifier"}],"abstract":[{"type":"text","text":"Namespace for Push Notifications"}],"title":"notifications","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","title":"JivoSDK","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"abstract":[],"title":"Jivo","url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/didReceive(response:)":{"url":"\/documentation\/jivosdk\/jvnotificationscontroller\/didreceive(response:)","abstract":[{"type":"text","text":"Processes the User Response"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"didReceiveResponse:","kind":"identifier"}],"title":"didReceive(response:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceive"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationResponse","text":"UNNotificationResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/didReceive(response:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"url":"\/documentation\/jivosdk\/jvnotificationscontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVNotificationsController","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"JVNotificationsController","kind":"identifier"}],"type":"topic","abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"text":".","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","isActive":true},{"type":"text","text":" namespace for Push Notifications"}],"title":"JVNotificationsController","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"didReceiveResponse:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didReceiveResponse:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didReceiveResponse:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"type":"text","text":"User’s response"}],"type":"paragraph"}],"name":"response"}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"text":" ","type":"text"},{"type":"text","text":"Whether the response was handled by JivoSDK"}]}],"kind":"content"}},{"value":"notifications","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments","op":"replace","value":[{"text":"notifications","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"text":"Jivo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1didReceive(response:)\/title","value":"didReceiveResponse:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"didReceiveResponse:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1didReceive(response:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title","value":"JVNotificationsController"},{"value":[{"kind":"identifier","text":"JVNotificationsController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/navigatorTitle","value":[{"text":"JVNotificationsController","kind":"identifier"}]}]}]}