{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/handleuser(response:)"]},{"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/handleuser(response:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/handleUser(response:)"},"metadata":{"platforms":[],"title":"handleUser(response:)","roleHeading":"Instance Method","externalID":"c:@M@JivoSDK@objc(cs)JVNotificationsController(im)handleUserResponse:","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleUser"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationResponse","text":"UNNotificationResponse","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"text":"handleUserResponse:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"]]},"abstract":[{"type":"text","text":"Processes the User Response"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(handleUserResponse:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleUser"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"response","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"User’s response"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Whether the response was handled by JivoSDK","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"content":[{"inlineContent":[{"text":"Call this method from ","type":"text"},{"code":"userNotificationCenter(_:didReceive:withCompletionHandler:)","type":"codeVoice"}],"type":"paragraph"}],"style":"important","type":"aside","name":"Important"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/handleUser(response:)":{"type":"topic","title":"handleUser(response:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/handleUser(response:)","abstract":[{"type":"text","text":"Processes the User Response"}],"role":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/handleuser(response:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleUser"},{"text":"(","kind":"text"},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationResponse","text":"UNNotificationResponse"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"handleUserResponse:","kind":"identifier"}],"deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"role":"symbol","abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","title":"Jivo","url":"\/documentation\/jivosdk\/jivo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Jivo"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"notifications","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","kind":"typeIdentifier","text":"JVNotificationsController"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","title":"notifications","role":"symbol","url":"\/documentation\/jivosdk\/jivo\/notifications","kind":"symbol","abstract":[{"text":"Namespace for Push Notifications","type":"text"}],"type":"topic","navigatorTitle":[{"text":"notifications","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol","url":"\/documentation\/jivosdk","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVNotificationsController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","title":"JVNotificationsController","role":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscontroller","kind":"symbol","abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","type":"reference","isActive":true},{"text":" namespace for Push Notifications","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"handleUserResponse:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleUserResponse:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"handleUserResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationResponse","text":"UNNotificationResponse"},{"text":" *) ","kind":"text"},{"text":"response","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"handleUserResponse:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1handleUser(response:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1handleUser(response:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"handleUserResponse:","kind":"identifier"}]},{"value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title","value":"notifications"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments","op":"replace","value":[{"kind":"identifier","text":"notifications"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title","op":"replace","value":"JVNotificationsController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments","value":[{"text":"JVNotificationsController","kind":"identifier"}],"op":"replace"}]}]}