{"kind":"symbol","metadata":{"roleHeading":"Instance Method","externalID":"c:@M@JivoSDK@objc(cs)JVNotificationsController(im)setContentTransformerBlock:","navigatorTitle":[{"text":"setContentTransformerBlock:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setContentTransformer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"block","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"JVNotificationsEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsEvent"},{"text":") -> ","kind":"text"},{"text":"UNNotificationContent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"text":"?)","kind":"text"}],"modules":[{"name":"JivoSDK"}],"symbolKind":"method","title":"setContentTransformer(block:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"]]},"abstract":[{"text":"Handler will be called when SDK is going to present Push Notification banner","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/setcontenttransformer(block:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/setcontenttransformer(block:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(setContentTransformerBlock:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setContentTransformer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsEvent","text":"JVNotificationsEvent","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationContent","text":"UNNotificationContent"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"text":"Call the block with adjusted content (if you wish to modify the banner),","type":"text"},{"text":" ","type":"text"},{"text":"or original content (if you wish to keep things as is),","type":"text"},{"text":" ","type":"text"},{"text":"or nil (if you wish to avoid showing banner)","type":"text"}],"type":"paragraph"},{"type":"aside","style":"tip","name":"Tip","content":[{"type":"paragraph","inlineContent":[{"text":"Here you can prepare banner for displaying","type":"text"}]}]}],"kind":"content"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setContentTransformer(block:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","kind":"symbol","type":"topic","role":"collection","abstract":[],"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifications"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","kind":"typeIdentifier","text":"JVNotificationsController"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","title":"notifications","abstract":[{"type":"text","text":"Namespace for Push Notifications"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"notifications"}],"role":"symbol","url":"\/documentation\/jivosdk\/jivo\/notifications"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"url":"\/documentation\/jivosdk\/jvnotificationscontroller","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","title":"JVNotificationsController","abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","type":"reference","isActive":true},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","type":"reference","isActive":true},{"text":" namespace for Push Notifications","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsController","kind":"identifier"}],"navigatorTitle":[{"text":"JVNotificationsController","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setContentTransformer(block:)":{"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setContentTransformer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"block","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"JVNotificationsEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsEvent"},{"text":") -> ","kind":"text"},{"text":"UNNotificationContent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"text":"?)","kind":"text"}],"title":"setContentTransformer(block:)","type":"topic","navigatorTitle":[{"text":"setContentTransformerBlock:","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setcontenttransformer(block:)","abstract":[{"type":"text","text":"Handler will be called when SDK is going to present Push Notification banner"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setContentTransformer(block:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"title":"Jivo","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jivo","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent":{"navigatorTitle":[{"text":"JVNotificationsEvent","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"JVNotificationsEvent","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsEvent","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","url":"\/documentation\/jivosdk\/jvnotificationsevent"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setContentTransformerBlock:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setContentTransformerBlock:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setContentTransformerBlock:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent","kind":"typeIdentifier"},{"text":" * (^)(","kind":"text"},{"text":"JVNotificationsEvent","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsEvent","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title","value":"notifications","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments","value":[{"text":"notifications","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title","value":"JVNotificationsController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments","value":[{"text":"JVNotificationsController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/navigatorTitle","value":[{"kind":"identifier","text":"JVNotificationsController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setContentTransformer(block:)\/title","value":"setContentTransformerBlock:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setContentTransformer(block:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setContentTransformerBlock:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"kind":"identifier","text":"Jivo"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/title","value":"JVNotificationsEvent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/fragments","value":[{"kind":"identifier","text":"JVNotificationsEvent"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/navigatorTitle","value":[{"text":"JVNotificationsEvent","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}