{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(error:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Notify about userToken is unavailable","type":"text"}],"sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPushToken","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setPushTokenError:","kind":"identifier"}],"symbolKind":"method","role":"symbol","title":"setPushToken(error:)","externalID":"c:@M@JivoSDK@objc(cs)JVNotificationsController(im)setPushTokenError:","modules":[{"name":"JivoSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(setPushTokenError:) "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setPushToken","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"text":" ","type":"text"},{"type":"text","text":"An error from operating system"}]}],"name":"error"}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"name":"Important","style":"important","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Call this method from "},{"type":"codeVoice","code":"application(_:didFailToRegisterForRemoteNotificationsWithError:)"}],"type":"paragraph"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/setpushtoken(error:)"]},{"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/setpushtoken(error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"role":"symbol","title":"notifications","abstract":[{"text":"Namespace for Push Notifications","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifications","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","text":"JVNotificationsController","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"notifications"}],"url":"\/documentation\/jivosdk\/jivo\/notifications","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","type":"topic","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setPushToken(error:)":{"navigatorTitle":[{"kind":"identifier","text":"setPushTokenError:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPushToken"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setpushtoken(error:)","title":"setPushToken(error:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(error:)","abstract":[{"text":"Notify about userToken is unavailable","type":"text"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","title":"Jivo","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"type":"topic","url":"\/documentation\/jivosdk\/jivo","navigatorTitle":[{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"kind":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscontroller","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsController"}],"title":"JVNotificationsController","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications"},{"text":" namespace for Push Notifications","type":"text"}],"navigatorTitle":[{"text":"JVNotificationsController","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","type":"topic","url":"\/documentation\/jivosdk","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"setPushTokenError:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPushTokenError:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setPushTokenError:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title","value":"notifications","op":"replace"},{"value":[{"text":"notifications","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPushToken(error:)\/title","op":"replace","value":"setPushTokenError:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPushToken(error:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setPushTokenError:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo","op":"replace"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"value":"JVNotificationsController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title"},{"value":[{"text":"JVNotificationsController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments","op":"replace"}]}]}