{"sections":[],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPermissionIntro"},{"kind":"text","text":"("},{"text":"provider","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"title":"setPermissionIntro(provider:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"setPermissionIntroProvider:"}],"externalID":"c:@M@JivoSDK@objc(cs)JVNotificationsController(im)setPermissionIntroProvider:","modules":[{"name":"JivoSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionIntro(provider:)","interfaceLanguage":"swift"},"abstract":[{"text":"Handler will be called when SDK wants to access Push Notifications","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/setpermissionintro(provider:)"]},{"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/setpermissionintro(provider:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(setPermissionIntroProvider:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPermissionIntro"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"provider"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"The callback you call when it’s time"},{"type":"text","text":" "},{"text":"to present the System Request for Push Notifications","type":"text"}],"type":"paragraph"},{"name":"Tip","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You may want to present your custom UI"},{"text":" ","type":"text"},{"type":"text","text":"to inform user about accessing to Push Notifications,"},{"type":"text","text":" "},{"type":"text","text":"before SDK will trigger System Request"}]}],"style":"tip","type":"aside"}],"kind":"content"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"kind":"symbol","navigatorTitle":[{"text":"JVNotificationsController","kind":"identifier"}],"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"code":"Jivo\/notifications","type":"codeVoice"},{"type":"text","text":" namespace for Push Notifications"}],"role":"symbol","title":"JVNotificationsController","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsController"}],"url":"\/documentation\/jivosdk\/jvnotificationscontroller"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setPermissionIntro(provider:)":{"abstract":[{"type":"text","text":"Handler will be called when SDK wants to access Push Notifications"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionIntro(provider:)","navigatorTitle":[{"text":"setPermissionIntroProvider:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPermissionIntro"},{"text":"(","kind":"text"},{"text":"provider","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setpermissionintro(provider:)","type":"topic","title":"setPermissionIntro(provider:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","kind":"symbol","url":"\/documentation\/jivosdk","role":"collection","abstract":[],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"type":"topic","title":"Jivo","url":"\/documentation\/jivosdk\/jivo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"setPermissionIntroProvider:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"setPermissionIntroProvider:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setPermissionIntroProvider:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")())) "},{"kind":"internalParam","text":"provider"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"JVNotificationsController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments","op":"replace","value":[{"text":"JVNotificationsController","kind":"identifier"}]},{"op":"replace","value":[{"text":"JVNotificationsController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPermissionIntro(provider:)\/title","value":"setPermissionIntroProvider:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPermissionIntro(provider:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPermissionIntroProvider:"}],"op":"replace"},{"value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"text":"Jivo","kind":"identifier"}],"op":"replace"}]}]}