{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(setPushTokenData:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPushToken"},{"kind":"text","text":"("},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"data","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Push Token as raw data"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this method from "},{"type":"codeVoice","code":"application(_:didRegisterForRemoteNotificationsWithDeviceToken:)"}]}],"type":"aside"}]}],"abstract":[{"text":"Associate the Push Token with current user using his userToken in raw-binary form","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(data:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/setpushtoken(data:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/setpushtoken(data:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"externalID":"c:@M@JivoSDK@objc(cs)JVNotificationsController(im)setPushTokenData:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPushToken","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setPushTokenData:"}],"roleHeading":"Instance Method","modules":[{"name":"JivoSDK"}],"role":"symbol","title":"setPushToken(data:)"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"type":"topic","url":"\/documentation\/jivosdk","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"title":"Jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"role":"symbol","url":"\/documentation\/jivosdk\/jivo","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setPushToken(data:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPushToken"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"abstract":[{"text":"Associate the Push Token with current user using his userToken in raw-binary form","type":"text"}],"navigatorTitle":[{"text":"setPushTokenData:","kind":"identifier"}],"title":"setPushToken(data:)","role":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setpushtoken(data:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPushToken(data:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"url":"\/documentation\/jivosdk\/jvnotificationscontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsController"}],"type":"topic","abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"text":".","type":"text"},{"type":"codeVoice","code":"Jivo\/notifications"},{"text":" namespace for Push Notifications","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","navigatorTitle":[{"text":"JVNotificationsController","kind":"identifier"}],"title":"JVNotificationsController","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"setPushTokenData:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setPushTokenData:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setPushTokenData:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"data","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"data","content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Push Token as raw data","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo","op":"replace"},{"op":"replace","value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"text":"Jivo","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"setPushTokenData:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPushToken(data:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPushTokenData:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController~1setPushToken(data:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title","op":"replace","value":"JVNotificationsController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments","op":"replace","value":[{"text":"JVNotificationsController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JVNotificationsController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}