{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPermissionAsking"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"text":"moment","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment","text":"JVNotificationsPermissionAskingMoment","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK37JVNotificationsPermissionAskingMomentO"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The moment of requesting access to Push Notifications"}]}],"name":"moment"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionAsking(at:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/setpermissionasking(at:)"]}],"kind":"symbol","abstract":[{"type":"text","text":"Specifies when SDK should request access to Push Notifications"}],"metadata":{"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"JivoSDK"}],"title":"setPermissionAsking(at:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPermissionAsking"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7JivoSDK37JVNotificationsPermissionAskingMomentO","kind":"typeIdentifier","text":"JVNotificationsPermissionAskingMoment"},{"text":")","kind":"text"}],"externalID":"s:7JivoSDK25JVNotificationsControllerC19setPermissionAsking2atyAA0cfG6MomentO_tF"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsPermissionAskingMoment":{"kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvnotificationspermissionaskingmoment","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsPermissionAskingMoment","role":"symbol","abstract":[{"text":"Moment to request access to Push Notifications","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"JVNotificationsPermissionAskingMoment"}],"title":"JVNotificationsPermissionAskingMoment","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsPermissionAskingMoment","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"kind":"symbol","navigatorTitle":[{"text":"JVNotificationsController","kind":"identifier"}],"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"code":"Jivo\/notifications","type":"codeVoice"},{"type":"text","text":" namespace for Push Notifications"}],"role":"symbol","title":"JVNotificationsController","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVNotificationsController"}],"url":"\/documentation\/jivosdk\/jvnotificationscontroller"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/setPermissionAsking(at:)":{"url":"\/documentation\/jivosdk\/jvnotificationscontroller\/setpermissionasking(at:)","abstract":[{"text":"Specifies when SDK should request access to Push Notifications","type":"text"}],"title":"setPermissionAsking(at:)","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/setPermissionAsking(at:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setPermissionAsking","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"text":"JVNotificationsPermissionAskingMoment","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK37JVNotificationsPermissionAskingMomentO"},{"kind":"text","text":")"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","kind":"symbol","url":"\/documentation\/jivosdk","role":"collection","abstract":[],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"type":"topic","title":"Jivo","url":"\/documentation\/jivosdk\/jivo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"JVNotificationsController","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments","value":[{"text":"JVNotificationsController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/navigatorTitle","value":[{"kind":"identifier","text":"JVNotificationsController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"kind":"identifier","text":"Jivo"}]}]}]}