{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController"]]},"metadata":{"externalID":"s:7JivoSDK25JVNotificationsControllerC11willPresent12notification17preferableOptionsSo026UNNotificationPresentationI0VSgSo0J0C_AHtF","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"JivoSDK"}],"title":"willPresent(notification:preferableOptions:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willPresent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"preferableOptions"},{"kind":"text","text":": "},{"text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"method"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willPresent"},{"kind":"text","text":"("},{"text":"notification","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"preferableOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Incoming Notification","type":"text"}],"type":"paragraph"}],"name":"notification"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Preferred informing options","type":"text"}],"type":"paragraph"}],"name":"preferableOptions"}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"content":[{"inlineContent":[{"type":"text","text":"Call this method from "},{"type":"codeVoice","code":"userNotificationCenter(_:willPresent:withCompletionHandler:)"}],"type":"paragraph"}],"style":"important","name":"Important","type":"aside"}]}],"variants":[{"paths":["\/documentation\/jivosdk\/jvnotificationscontroller\/willpresent(notification:preferableoptions:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Determines the presentation options Notification"},{"type":"text","text":" "},{"text":"For Swift code","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/willPresent(notification:preferableOptions:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivo","role":"symbol","title":"Jivo","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/notifications":{"navigatorTitle":[{"text":"notifications","kind":"identifier"}],"abstract":[{"type":"text","text":"Namespace for Push Notifications"}],"title":"notifications","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifications"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVNotificationsController","text":"JVNotificationsController"}],"type":"topic","url":"\/documentation\/jivosdk\/jivo\/notifications","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController":{"kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvnotificationscontroller","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController","role":"symbol","title":"JVNotificationsController","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/notifications"},{"type":"text","text":" namespace for Push Notifications"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsController","kind":"identifier"}],"navigatorTitle":[{"text":"JVNotificationsController","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsController/willPresent(notification:preferableOptions:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsController\/willPresent(notification:preferableOptions:)","type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jvnotificationscontroller\/willpresent(notification:preferableoptions:)","role":"symbol","abstract":[{"text":"Determines the presentation options Notification","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For Swift code"}],"title":"willPresent(notification:preferableOptions:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"willPresent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":", ","kind":"text"},{"text":"preferableOptions","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/title","op":"replace","value":"notifications"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1notifications\/fragments","value":[{"kind":"identifier","text":"notifications"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/title","op":"replace","value":"JVNotificationsController"},{"op":"replace","value":[{"text":"JVNotificationsController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}