{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugging"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging","text":"JivoSDKDebugging"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdk\/debugging-c.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdk\/debugging-c.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/debugging-c.property","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"debugging"}],"role":"symbol","title":"debugging","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugging"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKDebugging","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging"}],"symbolKind":"property","externalID":"c:@M@JivoSDK@objc(cs)JivoSDK(py)debugging","modules":[{"name":"JivoSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/debugging-c.property":{"deprecated":true,"role":"symbol","title":"debugging","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugging"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKDebugging","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/debugging-c.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"debugging"}],"url":"\/documentation\/jivosdk\/jivosdk\/debugging-c.property"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"deprecated":true,"role":"symbol","title":"JivoSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDK"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JivoSDK"}],"url":"\/documentation\/jivosdk\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKDebugging":{"deprecated":true,"role":"symbol","title":"JivoSDKDebugging","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKDebugging"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JivoSDKDebugging"}],"url":"\/documentation\/jivosdk\/jivosdkdebugging"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"debugging"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"debugging"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKDebugging","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKDebugging","text":"JivoSDKDebugging"},{"kind":"text","text":" * "},{"kind":"identifier","text":"debugging"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1debugging-c.property\/title","value":"debugging"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1debugging-c.property\/fragments","value":[{"kind":"identifier","text":"debugging"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title","value":"JivoSDK"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments","value":[{"kind":"identifier","text":"JivoSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging\/title","value":"JivoSDKDebugging"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKDebugging\/fragments","value":[{"kind":"identifier","text":"JivoSDKDebugging"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}