{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession","text":"JivoSDKSession"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jivosdk\/session-c.type.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdk\/session-c.type.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/session-c.type.property","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"session"}],"role":"symbol","title":"session","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKSession","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession"}],"symbolKind":"property","externalID":"c:@M@JivoSDK@objc(cs)JivoSDK(cpy)session","modules":[{"name":"JivoSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKSession":{"deprecated":true,"role":"symbol","title":"JivoSDKSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDKSession"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JivoSDKSession"}],"url":"\/documentation\/jivosdk\/jivosdksession"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK/session-c.type.property":{"deprecated":true,"role":"symbol","title":"session","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JivoSDKSession","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK\/session-c.type.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"session"}],"url":"\/documentation\/jivosdk\/jivosdk\/session-c.type.property"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDK":{"deprecated":true,"role":"symbol","title":"JivoSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JivoSDK"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JivoSDK"}],"url":"\/documentation\/jivosdk\/jivosdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"session"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"session"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKSession","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JivoSDKSession","text":"JivoSDKSession"},{"kind":"text","text":" * "},{"kind":"identifier","text":"session"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/title","value":"JivoSDKSession"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKSession\/fragments","value":[{"kind":"identifier","text":"JivoSDKSession"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1session-c.type.property\/title","value":"session"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK~1session-c.type.property\/fragments","value":[{"kind":"identifier","text":"session"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/title","value":"JivoSDK"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDK\/fragments","value":[{"kind":"identifier","text":"JivoSDK"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}