{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"application","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"didRegisterForRemoteNotificationsWithDeviceToken","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"deviceToken","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIApplicationDelegate.application(_:didRegisterForRemoteNotificationsWithDeviceToken:)"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/jivosdk\/jvappdelegate\/application(_:didregisterforremotenotificationswithdevicetoken:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvappdelegate\/application(_:didregisterforremotenotificationswithdevicetoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[{"deprecated":true,"beta":false,"unavailable":false}],"modules":[{"name":"JivoSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"didRegisterForRemoteNotificationsWithDeviceToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"application:didRegisterForRemoteNotificationsWithDeviceToken:"}],"title":"application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","externalID":"c:@M@JivoSDK@objc(cs)JVAppDelegate(im)application:didRegisterForRemoteNotificationsWithDeviceToken:","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)":{"title":"application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","role":"symbol","kind":"symbol","url":"\/documentation\/jivosdk\/jvappdelegate\/application(_:didregisterforremotenotificationswithdevicetoken:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didRegisterForRemoteNotificationsWithDeviceToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"application:didRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}],"deprecated":true,"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate":{"title":"JVAppDelegate","type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jvappdelegate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVAppDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate","abstract":[{"text":"Feel free to use this class as parent for your own App Delegate, for easier SDK integration","type":"text"}],"navigatorTitle":[{"text":"JVAppDelegate","kind":"identifier"}],"deprecated":true,"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","title":"JivoSDK","abstract":[],"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"deprecated":true,"unavailable":false,"beta":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"application:didRegisterForRemoteNotificationsWithDeviceToken:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"application:didRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"application"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRegisterForRemoteNotificationsWithDeviceToken:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"deviceToken","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1application(_:didRegisterForRemoteNotificationsWithDeviceToken:)\/title","value":"application:didRegisterForRemoteNotificationsWithDeviceToken:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:didRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1application(_:didRegisterForRemoteNotificationsWithDeviceToken:)\/fragments"},{"op":"replace","value":"JVAppDelegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"JVAppDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"JVAppDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/navigatorTitle"}]}]}