{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","title":"bannerPresentingDelegate","externalID":"s:7JivoSDK13JVAppDelegateC016bannerPresentingD0AA0c6BannerfD0_pSgvp","symbolKind":"property","modules":[{"name":"JivoSDK"}],"platforms":[],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerPresentingDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVAppBannerPresentingDelegate","text":"JVAppBannerPresentingDelegate"},{"kind":"text","text":"?"}]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/bannerPresentingDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bannerPresentingDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate","text":"JVAppBannerPresentingDelegate","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVAppBannerPresentingDelegate"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvappdelegate\/bannerpresentingdelegate"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate","title":"JVAppDelegate","navigatorTitle":[{"kind":"identifier","text":"JVAppDelegate"}],"deprecated":true,"abstract":[{"type":"text","text":"Feel free to use this class as parent for your own App Delegate, for easier SDK integration"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVAppDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jvappdelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/bannerPresentingDelegate":{"title":"bannerPresentingDelegate","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bannerPresentingDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JVAppBannerPresentingDelegate","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVAppBannerPresentingDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic","url":"\/documentation\/jivosdk\/jvappdelegate\/bannerpresentingdelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/bannerPresentingDelegate","deprecated":true},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","kind":"symbol","url":"\/documentation\/jivosdk","role":"collection","abstract":[],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppBannerPresentingDelegate":{"abstract":[{"text":"Determines a way incoming notifications gets displayed","type":"text"}],"type":"topic","navigatorTitle":[{"text":"JVAppBannerPresentingDelegate","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvappbannerpresentingdelegate","title":"JVAppBannerPresentingDelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppBannerPresentingDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVAppBannerPresentingDelegate","kind":"identifier"}],"deprecated":true,"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"JVAppDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/fragments","value":[{"text":"JVAppDelegate","kind":"identifier"}]},{"value":[{"text":"JVAppDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/navigatorTitle"},{"value":"JVAppBannerPresentingDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/title"},{"op":"replace","value":[{"text":"JVAppBannerPresentingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppBannerPresentingDelegate\/navigatorTitle","value":[{"text":"JVAppBannerPresentingDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}