{"kind":"symbol","variants":[{"paths":["\/documentation\/jivosdk\/jvappdelegate\/jivoapp(bannerpresentation:target:event:notification:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvappdelegate\/jivoapp(bannerpresentation:target:event:notification:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"jivoAppBannerPresentation:target:event:notification:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"JivoSDK"}],"title":"jivoApp(bannerPresentation:target:event:notification:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jivoApp"},{"text":"(","kind":"text"},{"text":"bannerPresentation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"target","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JVNotificationsTarget","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsEvent","text":"JVNotificationsEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions","kind":"typeIdentifier"}],"symbolKind":"method","externalID":"c:@M@JivoSDK@objc(cs)JVAppDelegate(im)jivoAppBannerPresentation:target:event:notification:","platforms":[],"role":"symbol"},"sections":[],"abstract":[{"text":"Here you can determine UNNotificationPresentationOptions","type":"text"},{"type":"text","text":" "},{"text":"to be applied for foreground notifications","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/jivoApp(bannerPresentation:target:event:notification:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jivoApp","kind":"identifier"},{"kind":"text","text":"("},{"text":"bannerPresentation","kind":"externalParam"},{"kind":"text","text":" "},{"text":"sdk","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"target"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JVNotificationsTarget","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget"},{"kind":"text","text":", "},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsEvent","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","text":"JVNotificationsEvent"},{"kind":"text","text":", "},{"text":"notification","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Reference to JivoSDK"}]}],"name":"sdk"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A target the notification is intended for"}],"type":"paragraph"}],"name":"target"},{"name":"notification","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"An original incoming notification"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Presentation Options to be applied for notification","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","title":"JivoSDK","url":"\/documentation\/jivosdk","role":"collection","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"abstract":[],"url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"role":"symbol","title":"Jivo","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"symbol","navigatorTitle":[{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsEvent":{"url":"\/documentation\/jivosdk\/jvnotificationsevent","type":"topic","role":"symbol","kind":"symbol","title":"JVNotificationsEvent","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsEvent"}],"abstract":[{"type":"text","text":"Event category of notification"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsEvent","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/jivoApp(bannerPresentation:target:event:notification:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/jivoApp(bannerPresentation:target:event:notification:)","kind":"symbol","abstract":[{"type":"text","text":"Here you can determine UNNotificationPresentationOptions"},{"text":" ","type":"text"},{"text":"to be applied for foreground notifications","type":"text"}],"role":"symbol","type":"topic","title":"jivoApp(bannerPresentation:target:event:notification:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoApp","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerPresentation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"text":", ","kind":"text"},{"text":"target","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget","text":"JVNotificationsTarget","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVNotificationsEvent","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsEvent"},{"text":", ","kind":"text"},{"text":"notification","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"jivoAppBannerPresentation:target:event:notification:"}],"deprecated":true,"url":"\/documentation\/jivosdk\/jvappdelegate\/jivoapp(bannerpresentation:target:event:notification:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate":{"title":"JVAppDelegate","kind":"symbol","url":"\/documentation\/jivosdk\/jvappdelegate","type":"topic","role":"symbol","navigatorTitle":[{"text":"JVAppDelegate","kind":"identifier"}],"deprecated":true,"abstract":[{"type":"text","text":"Feel free to use this class as parent for your own App Delegate, for easier SDK integration"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVAppDelegate"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","abstract":[{"text":"Target subsystem of Push Notification","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JVNotificationsTarget","kind":"identifier"}],"navigatorTitle":[{"text":"JVNotificationsTarget","kind":"identifier"}],"title":"JVNotificationsTarget","url":"\/documentation\/jivosdk\/jvnotificationstarget","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"jivoAppBannerPresentation:target:event:notification:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"jivoAppBannerPresentation:target:event:notification:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"jivoAppBannerPresentation:"},{"text":"(","kind":"text"},{"text":"Jivo","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":" *) "},{"text":"sdk","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"target:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","text":"JVNotificationsTarget"},{"text":") ","kind":"text"},{"text":"target","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"event:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVNotificationsEvent","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsEvent","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsEvent"},{"text":") ","kind":"text"},{"text":"event","kind":"internalParam"},{"kind":"text","text":" "},{"text":"notification:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"notification","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"Jivo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/title","value":"JVNotificationsEvent","op":"replace"},{"value":[{"kind":"identifier","text":"JVNotificationsEvent"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsEvent\/fragments"},{"op":"replace","value":"jivoAppBannerPresentation:target:event:notification:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1jivoApp(bannerPresentation:target:event:notification:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1jivoApp(bannerPresentation:target:event:notification:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"jivoAppBannerPresentation:target:event:notification:","kind":"identifier"}]},{"value":"JVAppDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/title"},{"op":"replace","value":[{"text":"JVAppDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/fragments"},{"op":"replace","value":"JVNotificationsTarget","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/fragments","value":[{"text":"JVNotificationsTarget","kind":"identifier"}]}]}]}