{"sections":[],"metadata":{"externalID":"c:@M@JivoSDK@objc(cs)JVAppDelegate(im)jivoAppBannerPresentation:target:category:notification:","title":"jivoApp(bannerPresentation:target:category:notification:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jivoApp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerPresentation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Jivo","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVNotificationsTarget","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget"},{"kind":"text","text":", "},{"kind":"externalParam","text":"category"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVNotificationsCategory","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsCategory"},{"kind":"text","text":", "},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"}],"platforms":[{"beta":false,"deprecated":true,"unavailable":false}],"role":"symbol","modules":[{"name":"JivoSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"jivoAppBannerPresentation:target:category:notification:"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Here you can determine UNNotificationPresentationOptions"},{"type":"text","text":" "},{"type":"text","text":"to be applied for foreground notifications"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvappdelegate\/jivoapp(bannerpresentation:target:category:notification:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvappdelegate\/jivoapp(bannerpresentation:target:category:notification:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoApp","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerPresentation","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo","text":"Jivo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget","text":"JVNotificationsTarget"},{"kind":"text","text":", "},{"kind":"externalParam","text":"category"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsCategory","text":"JVNotificationsCategory"},{"kind":"text","text":", "},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"sdk","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Reference to JivoSDK"}],"type":"paragraph"}]},{"name":"target","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"A target the notification is intended for"}],"type":"paragraph"}]},{"name":"category","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"A category of incoming notification","type":"text"}]}]},{"name":"notification","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"An original incoming notification"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Presentation Options to be applied for notification"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/jivoApp(bannerPresentation:target:category:notification:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate":{"title":"JVAppDelegate","navigatorTitle":[{"text":"JVAppDelegate","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvappdelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate","abstract":[{"type":"text","text":"Feel free to use this class as parent for your own App Delegate, for easier SDK integration"}],"role":"symbol","kind":"symbol","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVAppDelegate","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","url":"\/documentation\/jivosdk","title":"JivoSDK","abstract":[],"kind":"symbol","role":"collection"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsCategory":{"url":"\/documentation\/jivosdk\/jvnotificationscategory","title":"JVNotificationsCategory","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsCategory","kind":"identifier"}],"abstract":[{"text":"Event category of notification","type":"text"}],"navigatorTitle":[{"text":"JVNotificationsCategory","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"title":"Jivo","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"url":"\/documentation\/jivosdk\/jivo","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/jivoApp(bannerPresentation:target:category:notification:)":{"navigatorTitle":[{"text":"jivoAppBannerPresentation:target:category:notification:","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Here you can determine UNNotificationPresentationOptions"},{"type":"text","text":" "},{"type":"text","text":"to be applied for foreground notifications"}],"deprecated":true,"title":"jivoApp(bannerPresentation:target:category:notification:)","url":"\/documentation\/jivosdk\/jvappdelegate\/jivoapp(bannerpresentation:target:category:notification:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/jivoApp(bannerPresentation:target:category:notification:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jivoApp","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bannerPresentation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":", ","kind":"text"},{"text":"target","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JVNotificationsTarget","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget"},{"text":", ","kind":"text"},{"text":"category","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JVNotificationsCategory","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsCategory"},{"text":", ","kind":"text"},{"text":"notification","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":") -> ","kind":"text"},{"text":"UNNotificationPresentationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVNotificationsTarget":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVNotificationsTarget"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","type":"topic","title":"JVNotificationsTarget","navigatorTitle":[{"kind":"identifier","text":"JVNotificationsTarget"}],"url":"\/documentation\/jivosdk\/jvnotificationstarget","abstract":[{"type":"text","text":"Target subsystem of Push Notification"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"deprecated":true,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"jivoAppBannerPresentation:target:category:notification:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jivoAppBannerPresentation:target:category:notification:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"UNNotificationPresentationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"text":") ","kind":"text"},{"text":"jivoAppBannerPresentation:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","text":"Jivo","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)Jivo"},{"text":" *) ","kind":"text"},{"text":"sdk","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"target:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVNotificationsTarget","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsTarget","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsTarget"},{"text":") ","kind":"text"},{"text":"target","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"category:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVNotificationsCategory","preciseIdentifier":"c:@M@JivoSDK@E@JVNotificationsCategory","text":"JVNotificationsCategory","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"category","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"notification:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"notification","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"sdk","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Reference to JivoSDK","type":"text"}]}]},{"name":"target","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"A target the notification is intended for"}],"type":"paragraph"}]},{"name":"category","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"A category of incoming notification"}]}]},{"name":"notification","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"An original incoming notification"}]}]}]},"path":"\/primaryContentSections\/1"},{"value":{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Presentation Options to be applied for notification"}]}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"JVAppDelegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JVAppDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/fragments","op":"replace"},{"value":[{"text":"JVAppDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/navigatorTitle","op":"replace"},{"value":"JVNotificationsCategory","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JVNotificationsCategory"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/fragments","op":"replace"},{"value":[{"text":"JVNotificationsCategory","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsCategory\/navigatorTitle","op":"replace"},{"value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace"},{"value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"value":[{"text":"Jivo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","op":"replace"},{"value":"jivoAppBannerPresentation:target:category:notification:","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1jivoApp(bannerPresentation:target:category:notification:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"jivoAppBannerPresentation:target:category:notification:"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1jivoApp(bannerPresentation:target:category:notification:)\/fragments","op":"replace"},{"value":"JVNotificationsTarget","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/title","op":"replace"},{"value":[{"text":"JVNotificationsTarget","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"JVNotificationsTarget"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVNotificationsTarget\/navigatorTitle","op":"replace"}]}]}