{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvappdelegate\/usernotificationcenter(_:willpresent:withcompletionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvappdelegate\/usernotificationcenter(_:willpresent:withcompletionhandler:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userNotificationCenter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"center","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willPresent","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"notification","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withCompletionHandler","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UNUserNotificationCenterDelegate.userNotificationCenter(_:willPresent:withCompletionHandler:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate"]]},"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userNotificationCenter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UNUserNotificationCenter","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"text":", ","kind":"text"},{"text":"willPresent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":", ","kind":"text"},{"text":"withCompletionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"UNNotificationPresentationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"userNotificationCenter(_:willPresent:withCompletionHandler:)","platforms":[{"deprecated":true,"unavailable":false,"beta":false}],"externalID":"c:@M@JivoSDK@objc(cs)JVAppDelegate(im)userNotificationCenter:willPresentNotification:withCompletionHandler:","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"text":"userNotificationCenter:willPresentNotification:withCompletionHandler:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/userNotificationCenter(_:willPresent:withCompletionHandler:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userNotificationCenter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UNUserNotificationCenter","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"text":", ","kind":"text"},{"text":"willPresent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":", ","kind":"text"},{"text":"withCompletionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"UNNotificationPresentationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"userNotificationCenter(_:willPresent:withCompletionHandler:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/userNotificationCenter(_:willPresent:withCompletionHandler:)","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"userNotificationCenter:willPresentNotification:withCompletionHandler:","kind":"identifier"}],"type":"topic","url":"\/documentation\/jivosdk\/jvappdelegate\/usernotificationcenter(_:willpresent:withcompletionhandler:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate":{"deprecated":true,"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate","navigatorTitle":[{"text":"JVAppDelegate","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVAppDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Feel free to use this class as parent for your own App Delegate, for easier SDK integration"}],"title":"JVAppDelegate","url":"\/documentation\/jivosdk\/jvappdelegate","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"unavailable":false,"deprecated":true,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"userNotificationCenter:willPresentNotification:withCompletionHandler:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"userNotificationCenter:willPresentNotification:withCompletionHandler:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"userNotificationCenter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"center","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"willPresentNotification:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotification","text":"UNNotification","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"notification","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1userNotificationCenter(_:willPresent:withCompletionHandler:)\/title","op":"replace","value":"userNotificationCenter:willPresentNotification:withCompletionHandler:"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1userNotificationCenter(_:willPresent:withCompletionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userNotificationCenter:willPresentNotification:withCompletionHandler:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/title","op":"replace","value":"JVAppDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVAppDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JVAppDelegate"}]}]}]}