{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvappdelegate\/usernotificationcenter(_:didreceive:withcompletionhandler:)"]},{"paths":["\/documentation\/jivosdk\/jvappdelegate\/usernotificationcenter(_:didreceive:withcompletionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"platforms":[],"navigatorTitle":[{"text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","title":"userNotificationCenter(_:didReceive:withCompletionHandler:)","externalID":"c:@M@JivoSDK@objc(cs)JVAppDelegate(im)userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userNotificationCenter"},{"text":"(","kind":"text"},{"text":"UNUserNotificationCenter","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationResponse","text":"UNNotificationResponse","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withCompletionHandler"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"modules":[{"name":"JivoSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UNUserNotificationCenterDelegate.userNotificationCenter(_:didReceive:withCompletionHandler:)"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userNotificationCenter"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"center","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"kind":"text","text":" "},{"text":"response","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate/userNotificationCenter(_:didReceive:withCompletionHandler:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"userNotificationCenter","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNUserNotificationCenter","kind":"typeIdentifier","text":"UNUserNotificationCenter"},{"kind":"text","text":", "},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": () -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"deprecated":true,"url":"\/documentation\/jivosdk\/jvappdelegate\/usernotificationcenter(_:didreceive:withcompletionhandler:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate\/userNotificationCenter(_:didReceive:withCompletionHandler:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}],"abstract":[],"title":"userNotificationCenter(_:didReceive:withCompletionHandler:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","url":"\/documentation\/jivosdk","title":"JivoSDK","type":"topic","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVAppDelegate":{"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVAppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVAppDelegate"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jvappdelegate","role":"symbol","title":"JVAppDelegate","abstract":[{"type":"text","text":"Feel free to use this class as parent for your own App Delegate, for easier SDK integration"}],"deprecated":true,"navigatorTitle":[{"text":"JVAppDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"userNotificationCenter:"},{"text":"(","kind":"text"},{"text":"UNUserNotificationCenter","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"text":" *) ","kind":"text"},{"text":"center","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveNotificationResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UNNotificationResponse","kind":"typeIdentifier","text":"UNNotificationResponse"},{"kind":"text","text":" *) "},{"text":"response","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCompletionHandler:"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")()) "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/title","value":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/fragments"},{"value":"JVAppDelegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVAppDelegate\/fragments","op":"replace","value":[{"text":"JVAppDelegate","kind":"identifier"}]}]}]}