{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"locale","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"useDefaultIcon"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"customIcon"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"titlePlaceholder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"titleColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"subtitleCaption"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"subtitleColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"outgoingColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"inputPlaceholder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"inputPrefill","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"activeMessage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"offlineMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outcomingPalette"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias","text":"JivoSDKChattingPaletteAlias","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":[],"externalID":"c:@M@JivoSDK@objc(cs)JivoSDKChattingConfig(im)initWithLocale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:","symbolKind":"init","modules":[{"name":"JivoSDK"}],"role":"symbol","title":"init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","navigatorTitle":[{"text":"initWithLocale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"locale"},{"text":": ","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"useDefaultIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"customIcon"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"titlePlaceholder"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"titleColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"? = nil, "},{"text":"subtitleCaption","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"subtitleColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"outgoingColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"? = nil, "},{"text":"inputPlaceholder","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"inputPrefill","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"activeMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"offlineMessage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"outcomingPalette"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias","kind":"typeIdentifier","text":"JivoSDKChattingPaletteAlias","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias"},{"kind":"text","text":" = .standard)"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingconfig\/init(locale:usedefaulticon:customicon:titleplaceholder:titlecolor:subtitlecaption:subtitlecolor:outgoingcolor:inputplaceholder:inputprefill:activemessage:offlinemessage:outcomingpalette:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingconfig\/init(locale:usedefaulticon:customicon:titleplaceholder:titlecolor:subtitlecaption:subtitlecolor:outgoingcolor:inputplaceholder:inputprefill:activemessage:offlinemessage:outcomingpalette:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig\/init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingConfig":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingConfig","kind":"identifier"}],"deprecated":true,"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingConfig"}],"title":"JivoSDKChattingConfig","type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattingconfig","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingConfig/init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"locale","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"useDefaultIcon"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"customIcon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"titlePlaceholder","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"titleColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"subtitleCaption"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"subtitleColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"outgoingColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inputPlaceholder"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"inputPrefill","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"activeMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"offlineMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"outcomingPalette","kind":"externalParam"},{"kind":"text","text":": "},{"text":"JivoSDKChattingPaletteAlias","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig\/init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","type":"topic","url":"\/documentation\/jivosdk\/jivosdkchattingconfig\/init(locale:usedefaulticon:customicon:titleplaceholder:titlecolor:subtitlecaption:subtitlecolor:outgoingcolor:inputplaceholder:inputprefill:activemessage:offlinemessage:outcomingpalette:)","deprecated":true,"kind":"symbol","title":"init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","role":"symbol","navigatorTitle":[{"text":"initWithLocale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias":{"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias","title":"JivoSDKChattingPaletteAlias","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"deprecated":true,"kind":"symbol","url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","type":"topic","role":"collection","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithLocale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLocale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithLocale:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSLocale","text":"NSLocale","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"locale","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"useDefaultIcon:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"useDefaultIcon","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"customIcon:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"customIcon"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titlePlaceholder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"titlePlaceholder"},{"text":" ","kind":"text"},{"text":"titleColor:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"titleColor"},{"kind":"text","text":" "},{"text":"subtitleCaption:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"subtitleCaption","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"subtitleColor:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" *) "},{"text":"subtitleColor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"outgoingColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"outgoingColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputPlaceholder:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"inputPlaceholder"},{"text":" ","kind":"text"},{"text":"inputPrefill:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"inputPrefill"},{"text":" ","kind":"text"},{"text":"activeMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"activeMessage","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"offlineMessage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"offlineMessage"},{"kind":"text","text":" "},{"text":"outcomingPalette:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias","text":"JivoSDKChattingPaletteAlias","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"outcomingPalette","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"JivoSDKChattingConfig","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig\/fragments","value":[{"text":"JivoSDKChattingConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig~1init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)\/title","value":"initWithLocale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig~1init(locale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLocale:useDefaultIcon:customIcon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias\/title","value":"JivoSDKChattingPaletteAlias","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}],"op":"replace"}]}]}