{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig"]]},"metadata":{"modules":[{"name":"JivoSDK"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"locale","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Locale","preciseIdentifier":"s:10Foundation6LocaleV"},{"text":"?, ","kind":"text"},{"text":"icon","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK0A20SDKTitleBarIconStyleO","text":"JivoSDKTitleBarIconStyle"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"titlePlaceholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"titleColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?, ","kind":"text"},{"text":"subtitleCaption","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"subtitleColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"outgoingColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?, ","kind":"text"},{"text":"inputPlaceholder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"inputPrefill","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"activeMessage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"offlineMessage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"outcomingPalette","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias","text":"JivoSDKChattingPaletteAlias","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(locale:icon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","externalID":"s:7JivoSDK0A17SDKChattingConfigC6locale4icon16titlePlaceholder0G5Color15subtitleCaption0jI008outgoingI005inputH00M7Prefill13activeMessage07offlineP016outcomingPaletteAC10Foundation6LocaleVSg_AA0A20SDKTitleBarIconStyleOSgSSSgSo7UIColorCSgAw2z4wA0acS5AliasOtcfc","roleHeading":"Initializer","platforms":[],"role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig\/init(locale:icon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"locale","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV","text":"Locale"},{"text":"? = nil, ","kind":"text"},{"text":"icon","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7JivoSDK0A20SDKTitleBarIconStyleO","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKTitleBarIconStyle","text":"JivoSDKTitleBarIconStyle"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"titlePlaceholder"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"titleColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"? = nil, "},{"text":"subtitleCaption","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"subtitleColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"? = nil, "},{"text":"outgoingColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"inputPlaceholder"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"inputPrefill","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"activeMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"offlineMessage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"outcomingPalette","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JivoSDKChattingPaletteAlias","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias","kind":"typeIdentifier"},{"text":" = .standard)","kind":"text"}],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingconfig\/init(locale:icon:titleplaceholder:titlecolor:subtitlecaption:subtitlecolor:outgoingcolor:inputplaceholder:inputprefill:activemessage:offlinemessage:outcomingpalette:)"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingConfig/init(locale:icon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig\/init(locale:icon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"locale"},{"text":": ","kind":"text"},{"text":"Locale","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation6LocaleV"},{"text":"?, ","kind":"text"},{"text":"icon","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK0A20SDKTitleBarIconStyleO","text":"JivoSDKTitleBarIconStyle"},{"text":"?, ","kind":"text"},{"text":"titlePlaceholder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"titleColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"text":"subtitleCaption","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"subtitleColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?, ","kind":"text"},{"text":"outgoingColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"inputPlaceholder"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"inputPrefill"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"activeMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"offlineMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"outcomingPalette"},{"text":": ","kind":"text"},{"text":"JivoSDKChattingPaletteAlias","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JivoSDKChattingPaletteAlias"},{"kind":"text","text":")"}],"deprecated":true,"kind":"symbol","abstract":[],"title":"init(locale:icon:titlePlaceholder:titleColor:subtitleCaption:subtitleColor:outgoingColor:inputPlaceholder:inputPrefill:activeMessage:offlineMessage:outcomingPalette:)","url":"\/documentation\/jivosdk\/jivosdkchattingconfig\/init(locale:icon:titleplaceholder:titlecolor:subtitlecaption:subtitlecolor:outgoingcolor:inputplaceholder:inputprefill:activemessage:offlinemessage:outcomingpalette:)","type":"topic","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingConfig":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingConfig","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"JivoSDKChattingConfig","kind":"identifier"}],"deprecated":true,"type":"topic","title":"JivoSDKChattingConfig","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingConfig","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdkchattingconfig"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKTitleBarIconStyle":{"kind":"symbol","type":"topic","deprecated":true,"title":"JivoSDKTitleBarIconStyle","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKTitleBarIconStyle","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKTitleBarIconStyle"}],"navigatorTitle":[{"text":"JivoSDKTitleBarIconStyle","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdktitlebariconstyle"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","url":"\/documentation\/jivosdk","title":"JivoSDK","type":"topic","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingPaletteAlias":{"abstract":[],"deprecated":true,"navigatorTitle":[{"text":"JivoSDKChattingPaletteAlias","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"JivoSDKChattingPaletteAlias","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingPaletteAlias","title":"JivoSDKChattingPaletteAlias","url":"\/documentation\/jivosdk\/jivosdkchattingpalettealias"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig\/title","value":"JivoSDKChattingConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingConfig\/fragments","value":[{"text":"JivoSDKChattingConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias\/title","op":"replace","value":"JivoSDKChattingPaletteAlias"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingPaletteAlias\/fragments","value":[{"kind":"identifier","text":"JivoSDKChattingPaletteAlias"}]}]}]}