{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/back","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"Case","title":"JivoSDKChattingCloseButton.back","role":"symbol","externalID":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton@JivoSDKChattingCloseButtonBack","modules":[{"name":"JivoSDK"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"back"}],"navigatorTitle":[{"text":"JivoSDKChattingCloseButtonBack","kind":"identifier"}],"platforms":[]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"back","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/jivosdk\/jivosdkchattingclosebutton\/back"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jivosdkchattingclosebutton\/back"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton":{"navigatorTitle":[{"text":"JivoSDKChattingCloseButton","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton","role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton","title":"JivoSDKChattingCloseButton","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JivoSDKChattingCloseButton"}],"kind":"symbol","deprecated":true,"abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton/back":{"url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton\/back","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/back","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"JivoSDKChattingCloseButtonBack","kind":"identifier"}],"kind":"symbol","title":"JivoSDKChattingCloseButton.back","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"back","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"kind":"symbol","title":"JivoSDK","url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"JivoSDKChattingCloseButtonBack"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JivoSDKChattingCloseButtonBack","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"JivoSDKChattingCloseButtonBack","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton\/title","value":"JivoSDKChattingCloseButton"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton\/fragments","value":[{"text":"JivoSDKChattingCloseButton","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton~1back\/title","value":"JivoSDKChattingCloseButtonBack"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton~1back\/fragments","value":[{"text":"JivoSDKChattingCloseButtonBack","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}