{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/dismiss","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingclosebutton\/dismiss"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingclosebutton\/dismiss"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"title":"JivoSDKChattingCloseButton.dismiss","externalID":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton@JivoSDKChattingCloseButtonDismiss","platforms":[],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingCloseButtonDismiss"}],"modules":[{"name":"JivoSDK"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"}]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"url":"\/documentation\/jivosdk","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","kind":"symbol","role":"collection","type":"topic","abstract":[]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton/dismiss":{"title":"JivoSDKChattingCloseButton.dismiss","abstract":[],"url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton\/dismiss","role":"symbol","navigatorTitle":[{"text":"JivoSDKChattingCloseButtonDismiss","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/dismiss","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"dismiss","kind":"identifier"}],"kind":"symbol","deprecated":true,"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton":{"role":"symbol","url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton","title":"JivoSDKChattingCloseButton","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JivoSDKChattingCloseButton","kind":"identifier"}],"kind":"symbol","deprecated":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton","navigatorTitle":[{"text":"JivoSDKChattingCloseButton","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"JivoSDKChattingCloseButtonDismiss"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JivoSDKChattingCloseButtonDismiss","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"JivoSDKChattingCloseButtonDismiss"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton~1dismiss\/title","value":"JivoSDKChattingCloseButtonDismiss"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton~1dismiss\/fragments","value":[{"text":"JivoSDKChattingCloseButtonDismiss","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton\/title","op":"replace","value":"JivoSDKChattingCloseButton"},{"value":[{"kind":"identifier","text":"JivoSDKChattingCloseButton"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}