{"variants":[{"paths":["\/documentation\/jivosdk\/jivosdkchattingclosebutton\/omit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jivosdkchattingclosebutton\/omit"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"roleHeading":"Case","externalID":"c:@M@JivoSDK@E@JivoSDKChattingCloseButton@JivoSDKChattingCloseButtonOmit","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"omit"}],"platforms":[],"symbolKind":"case","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"JivoSDKChattingCloseButtonOmit"}],"title":"JivoSDKChattingCloseButton.omit"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/omit","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"omit","kind":"identifier"}]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton/omit":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"omit","kind":"identifier"}],"navigatorTitle":[{"text":"JivoSDKChattingCloseButtonOmit","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton\/omit","deprecated":true,"title":"JivoSDKChattingCloseButton.omit","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton\/omit","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"type":"topic","title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JivoSDKChattingCloseButton":{"url":"\/documentation\/jivosdk\/jivosdkchattingclosebutton","type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"JivoSDKChattingCloseButton","kind":"identifier"}],"title":"JivoSDKChattingCloseButton","kind":"symbol","deprecated":true,"role":"symbol","navigatorTitle":[{"text":"JivoSDKChattingCloseButton","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JivoSDKChattingCloseButton"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"JivoSDKChattingCloseButtonOmit","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"JivoSDKChattingCloseButtonOmit","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"JivoSDKChattingCloseButtonOmit","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"JivoSDKChattingCloseButtonOmit","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton~1omit\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton~1omit\/fragments","op":"replace","value":[{"kind":"identifier","text":"JivoSDKChattingCloseButtonOmit"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton\/title","op":"replace","value":"JivoSDKChattingCloseButton"},{"value":[{"kind":"identifier","text":"JivoSDKChattingCloseButton"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JivoSDKChattingCloseButton\/fragments","op":"replace"}]}]}