{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(archiveLogsWithCompletionHandler:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"archiveLogs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingArchiveStatus","text":"JVDebuggingArchiveStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"handler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"The block that would be called when an archive is ready"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/archivelogs(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/archivelogs(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/archiveLogs(completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Performs archiving of local log entries"},{"type":"text","text":" "},{"type":"text","text":"and returns a link to the created archive"},{"type":"text","text":" "},{"type":"text","text":"via completion block with status"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"archiveLogs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"JVDebuggingArchiveStatus","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingArchiveStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"archiveLogs(completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@JivoSDK@objc(cs)JVDebuggingController(im)archiveLogsWithCompletionHandler:","modules":[{"name":"JivoSDK"}],"navigatorTitle":[{"kind":"identifier","text":"archiveLogsWithCompletionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"]]},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"role":"symbol","title":"Jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"url":"\/documentation\/jivosdk\/jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController/archiveLogs(completion:)":{"role":"symbol","title":"archiveLogs(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"archiveLogs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"JVDebuggingArchiveStatus","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingArchiveStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Performs archiving of local log entries"},{"type":"text","text":" "},{"type":"text","text":"and returns a link to the created archive"},{"type":"text","text":" "},{"type":"text","text":"via completion block with status"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/archiveLogs(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"archiveLogsWithCompletionHandler:"}],"url":"\/documentation\/jivosdk\/jvdebuggingcontroller\/archivelogs(completion:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"role":"symbol","title":"JVDebuggingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDebuggingController"}],"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging"},{"type":"text","text":" namespace for SDK debugging"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVDebuggingController"}],"url":"\/documentation\/jivosdk\/jvdebuggingcontroller"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","kind":"symbol","type":"topic","url":"\/documentation\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus":{"role":"symbol","title":"JVDebuggingArchiveStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDebuggingArchiveStatus"}],"abstract":[{"type":"text","text":"Determines how logs archiving operation was completed"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVDebuggingArchiveStatus"}],"url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"role":"symbol","title":"debugging","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugging"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVDebuggingController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController"}],"abstract":[{"type":"text","text":"Namespace for SDK debugging"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"debugging"}],"url":"\/documentation\/jivosdk\/jivo\/debugging"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"archiveLogsWithCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"archiveLogsWithCompletionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"archiveLogsWithCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSURL *, enum JVDebuggingArchiveStatus)","preciseIdentifier":"c:BFv(#*$objc(cs)NSURL#$@M@JivoSDK@E@JVDebuggingArchiveStatus)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController~1archiveLogs(completion:)\/title","value":"archiveLogsWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController~1archiveLogs(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"archiveLogsWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title","value":"JVDebuggingController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments","value":[{"kind":"identifier","text":"JVDebuggingController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus\/title","value":"JVDebuggingArchiveStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus\/fragments","value":[{"kind":"identifier","text":"JVDebuggingArchiveStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/title","value":"debugging"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/fragments","value":[{"kind":"identifier","text":"debugging"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}