{"metadata":{"externalID":"c:@M@JivoSDK@objc(cs)JVDebuggingController(im)copyLogsWithCompletionHandler:","role":"symbol","symbolKind":"method","title":"copyLogs(completion:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"copyLogs","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingArchiveStatus","text":"JVDebuggingArchiveStatus"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"copyLogsWithCompletionHandler:"}],"modules":[{"name":"JivoSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(copyLogsWithCompletionHandler:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copyLogs","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":" "},{"text":"handler","kind":"internalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingArchiveStatus","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus","text":"JVDebuggingArchiveStatus"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"handler","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The block that would be called when copying is finished"}],"type":"paragraph"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/copyLogs(completion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/copylogs(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/copylogs(completion:)"]}],"abstract":[{"text":"Performs copying of local log entries","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and returns a link to the created copy"},{"type":"text","text":" "},{"type":"text","text":"via completion block with status"}],"kind":"symbol","references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController/copyLogs(completion:)":{"type":"topic","url":"\/documentation\/jivosdk\/jvdebuggingcontroller\/copylogs(completion:)","kind":"symbol","role":"symbol","title":"copyLogs(completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"copyLogs","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingArchiveStatus","text":"JVDebuggingArchiveStatus"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"text":"Performs copying of local log entries","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and returns a link to the created copy"},{"type":"text","text":" "},{"text":"via completion block with status","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/copyLogs(completion:)","navigatorTitle":[{"kind":"identifier","text":"copyLogsWithCompletionHandler:"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"url":"\/documentation\/jivosdk\/jvdebuggingcontroller","navigatorTitle":[{"text":"JVDebuggingController","kind":"identifier"}],"kind":"symbol","type":"topic","title":"JVDebuggingController","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","role":"symbol","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","type":"reference","isActive":true},{"text":" namespace for SDK debugging","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JVDebuggingController","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","abstract":[],"kind":"symbol","url":"\/documentation\/jivosdk","type":"topic","role":"collection","title":"JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingArchiveStatus":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus","title":"JVDebuggingArchiveStatus","abstract":[{"type":"text","text":"Determines how logs archiving operation was completed"}],"url":"\/documentation\/jivosdk\/jvdebuggingarchivestatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingArchiveStatus","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDebuggingArchiveStatus"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"url":"\/documentation\/jivosdk\/jivo","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"abstract":[{"text":"Entry Point to communicate with SDK","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol","title":"Jivo","navigatorTitle":[{"text":"Jivo","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugging"},{"text":": ","kind":"text"},{"text":"JVDebuggingController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"debugging"}],"title":"debugging","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Namespace for SDK debugging"}],"url":"\/documentation\/jivosdk\/jivo\/debugging"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"copyLogsWithCompletionHandler:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"copyLogsWithCompletionHandler:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"copyLogsWithCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingArchiveStatus","text":"JVDebuggingArchiveStatus","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingArchiveStatus","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"handler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController~1copyLogs(completion:)\/title","value":"copyLogsWithCompletionHandler:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"copyLogsWithCompletionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController~1copyLogs(completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title","value":"JVDebuggingController","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"JVDebuggingController"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus\/title","value":"JVDebuggingArchiveStatus","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingArchiveStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVDebuggingArchiveStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/title","value":"debugging"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/fragments","value":[{"kind":"identifier","text":"debugging"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}