{"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@JivoSDK@objc(cs)JVDebuggingController(py)delegate","title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"modules":[{"name":"JivoSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"text":"JVDebuggingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVDebuggingDelegate"},{"kind":"text","text":")?"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"]]},"kind":"symbol","abstract":[{"type":"text","text":"Object that controls debugging process"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(delegate) ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"JVDebuggingDelegate","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingDelegate","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVDebuggingDelegate"},{"text":")? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/delegate","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/delegate"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","title":"JivoSDK","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jivo","role":"symbol","title":"Jivo","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"url":"\/documentation\/jivosdk\/jivo\/debugging","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"debugging","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JVDebuggingController","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController"}],"title":"debugging","type":"topic","navigatorTitle":[{"kind":"identifier","text":"debugging"}],"kind":"symbol","abstract":[{"text":"Namespace for SDK debugging","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController/delegate":{"kind":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"JVDebuggingDelegate","preciseIdentifier":"c:@M@JivoSDK@objc(pl)JVDebuggingDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/delegate","url":"\/documentation\/jivosdk\/jvdebuggingcontroller\/delegate","type":"topic","role":"symbol","title":"delegate","abstract":[{"type":"text","text":"Object that controls debugging process"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVDebuggingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JVDebuggingDelegate"}],"abstract":[{"text":"Interface to control debugging process,","type":"text"},{"type":"text","text":" "},{"text":"relates to ","type":"text"},{"code":"Jivo.debugging","type":"codeVoice"},{"type":"text","text":" namespace"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingDelegate","role":"symbol","url":"\/documentation\/jivosdk\/jvdebuggingdelegate","type":"topic","title":"JVDebuggingDelegate","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"url":"\/documentation\/jivosdk\/jvdebuggingcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVDebuggingController","kind":"identifier"}],"title":"JVDebuggingController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JVDebuggingController"}],"abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true},{"type":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","type":"reference","isActive":true},{"text":" namespace for SDK debugging","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"delegate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@JivoSDK@objc(pl)JVDebuggingDelegate","text":"id<JVDebuggingDelegate>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}],"op":"replace"},{"op":"replace","value":"debugging","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/title"},{"op":"replace","value":[{"kind":"identifier","text":"debugging"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/fragments"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController~1delegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController~1delegate\/fragments"},{"value":"JVDebuggingDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingDelegate\/title"},{"value":[{"text":"JVDebuggingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title","value":"JVDebuggingController"},{"op":"replace","value":[{"text":"JVDebuggingController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments"}]}]}