{"kind":"symbol","abstract":[{"type":"text","text":"Presents a sharing screen of local log entries"}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/exportLogs(within:)","interfaceLanguage":"swift"},"metadata":{"title":"exportLogs(within:)","role":"symbol","navigatorTitle":[{"text":"exportLogsWithinParent:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"JivoSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"exportLogs","kind":"identifier"},{"kind":"text","text":"("},{"text":"within","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?)","kind":"text"}],"externalID":"c:@M@JivoSDK@objc(cs)JVDebuggingController(im)exportLogsWithinParent:"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/exportlogs(within:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/exportlogs(within:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(exportLogsWithinParent:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exportLogs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"within","kind":"externalParam"},{"kind":"text","text":" "},{"text":"parent","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","abstract":[{"text":"Namespace for SDK debugging","type":"text"}],"navigatorTitle":[{"text":"debugging","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"debugging","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController","text":"JVDebuggingController"}],"url":"\/documentation\/jivosdk\/jivo\/debugging","title":"debugging","role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"type":"topic","abstract":[],"title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController/exportLogs(within:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/exportLogs(within:)","kind":"symbol","title":"exportLogs(within:)","role":"symbol","navigatorTitle":[{"text":"exportLogsWithinParent:","kind":"identifier"}],"abstract":[{"type":"text","text":"Presents a sharing screen of local log entries"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"exportLogs","kind":"identifier"},{"kind":"text","text":"("},{"text":"within","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?)"}],"url":"\/documentation\/jivosdk\/jvdebuggingcontroller\/exportlogs(within:)"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"text":".","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","isActive":true},{"text":" namespace for SDK debugging","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"JVDebuggingController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDebuggingController"}],"url":"\/documentation\/jivosdk\/jvdebuggingcontroller","title":"JVDebuggingController","role":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"kind":"symbol","navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","url":"\/documentation\/jivosdk\/jivo","abstract":[],"role":"symbol","title":"Jivo","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"exportLogsWithinParent:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"exportLogsWithinParent:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"exportLogsWithinParent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"parent","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/title","value":"debugging","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/fragments","value":[{"text":"debugging","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController~1exportLogs(within:)\/title","op":"replace","value":"exportLogsWithinParent:"},{"value":[{"text":"- ","kind":"text"},{"text":"exportLogsWithinParent:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController~1exportLogs(within:)\/fragments","op":"replace"},{"value":"JVDebuggingController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title"},{"value":[{"kind":"identifier","text":"JVDebuggingController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments"},{"value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}],"op":"replace"}]}]}