{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/exportCopy(completion:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"]]},"abstract":[{"text":"Performs copying of local log entries","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and returns a link to the created copy"},{"type":"text","text":" "},{"text":"via completion block with status","type":"text"}],"sections":[],"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"s:7JivoSDK21JVDebuggingControllerC10exportCopy10completionyyAA0C12ExportStatusO_10Foundation3URLVSgtc_tF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exportCopy"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK23JVDebuggingExportStatusO","text":"JVDebuggingExportStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"JivoSDK"}],"title":"exportCopy(completion:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"exportCopy"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":" "},{"text":"handler","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingExportStatus","text":"JVDebuggingExportStatus","preciseIdentifier":"s:7JivoSDK23JVDebuggingExportStatusO"},{"text":", ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"text":" ","type":"text"},{"type":"text","text":"The block that would be called when copying is finished"}]}],"name":"handler"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/exportcopy(completion:)"]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"title":"JVDebuggingController","type":"topic","url":"\/documentation\/jivosdk\/jvdebuggingcontroller","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDebuggingController"}],"navigatorTitle":[{"text":"JVDebuggingController","kind":"identifier"}],"abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"type":"text","text":"."},{"code":"Jivo\/debugging","type":"codeVoice"},{"text":" namespace for SDK debugging","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingExportStatus":{"title":"JVDebuggingExportStatus","abstract":[{"type":"text","text":"Determines how logs archiving operation was completed"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"JVDebuggingExportStatus","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingExportStatus","url":"\/documentation\/jivosdk\/jvdebuggingexportstatus","navigatorTitle":[{"text":"JVDebuggingExportStatus","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","url":"\/documentation\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController/exportCopy(completion:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exportCopy"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"JVDebuggingExportStatus","preciseIdentifier":"s:7JivoSDK23JVDebuggingExportStatusO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/jivosdk\/jvdebuggingcontroller\/exportcopy(completion:)","title":"exportCopy(completion:)","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/exportCopy(completion:)","abstract":[{"text":"Performs copying of local log entries","type":"text"},{"text":" ","type":"text"},{"text":"and returns a link to the created copy","type":"text"},{"type":"text","text":" "},{"type":"text","text":"via completion block with status"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"abstract":[],"title":"Jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"symbol","url":"\/documentation\/jivosdk\/jivo","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"JVDebuggingController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments","value":[{"text":"JVDebuggingController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/navigatorTitle","value":[{"text":"JVDebuggingController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace","value":"Jivo"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace","value":[{"kind":"identifier","text":"Jivo"}]},{"value":[{"text":"Jivo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle"}]}]}