{"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/exportUI(within:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Presents a sharing screen of local log entries"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/exportui(within:)"]}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"exportUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"within","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"exportUI(within:)","modules":[{"name":"JivoSDK"}],"externalID":"s:7JivoSDK21JVDebuggingControllerC8exportUI6withinySo06UIViewD0CSg_tF"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exportUI"},{"text":"(","kind":"text"},{"text":"within","kind":"externalParam"},{"kind":"text","text":" "},{"text":"parent","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController/exportUI(within:)":{"abstract":[{"text":"Presents a sharing screen of local log entries","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/exportUI(within:)","url":"\/documentation\/jivosdk\/jvdebuggingcontroller\/exportui(within:)","title":"exportUI(within:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exportUI","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"within"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","url":"\/documentation\/jivosdk","title":"JivoSDK","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","navigatorTitle":[{"text":"JVDebuggingController","kind":"identifier"}],"type":"topic","kind":"symbol","title":"JVDebuggingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVDebuggingController","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdebuggingcontroller","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging"},{"type":"text","text":" namespace for SDK debugging"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"role":"symbol","url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"title":"Jivo","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"url":"\/documentation\/jivosdk\/jivo\/debugging","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","title":"debugging","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugging"},{"kind":"text","text":": "},{"text":"JVDebuggingController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController"}],"kind":"symbol","abstract":[{"type":"text","text":"Namespace for SDK debugging"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title","op":"replace","value":"JVDebuggingController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments","value":[{"text":"JVDebuggingController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/navigatorTitle","value":[{"kind":"identifier","text":"JVDebuggingController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace","value":"Jivo"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"text":"Jivo","kind":"identifier"}],"op":"replace"},{"value":[{"text":"Jivo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle"}]}]}