{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exportArchive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"handler","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"JVDebuggingExportStatus","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingExportStatus","preciseIdentifier":"s:7JivoSDK23JVDebuggingExportStatusO"},{"text":", ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"The block that would be called when an archive is ready"}]}],"name":"handler"}]},{"kind":"mentions","mentions":["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref"]}],"variants":[{"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/exportarchive(completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Performs archiving of local log entries"},{"type":"text","text":" "},{"type":"text","text":"and returns a link to the created archive"},{"type":"text","text":" "},{"type":"text","text":"via completion block with status"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/exportArchive(completion:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"JivoSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exportArchive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:7JivoSDK23JVDebuggingExportStatusO","kind":"typeIdentifier","text":"JVDebuggingExportStatus"},{"kind":"text","text":", "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"symbolKind":"method","roleHeading":"Instance Method","title":"exportArchive(completion:)","externalID":"s:7JivoSDK21JVDebuggingControllerC13exportArchive10completionyyAA0C12ExportStatusO_10Foundation3URLVSgtc_tF"},"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","role":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jvdebuggingcontroller","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging"},{"text":" namespace for SDK debugging","type":"text"}],"navigatorTitle":[{"text":"JVDebuggingController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingController","kind":"identifier"}],"title":"JVDebuggingController","kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"abstract":[],"title":"JivoSDK","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","role":"collection","url":"\/documentation\/jivosdk","kind":"symbol","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"abstract":[{"type":"text","text":"Namespace for SDK debugging"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugging","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JVDebuggingController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController"}],"title":"debugging","url":"\/documentation\/jivosdk\/jivo\/debugging","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","navigatorTitle":[{"text":"debugging","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/flutter_api_ref":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/flutter_api_ref","kind":"article","title":"API Reference","url":"\/documentation\/jivosdk\/flutter_api_ref","abstract":[{"text":"Dart API","type":"text"}],"role":"article","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"kind":"symbol","title":"Jivo","url":"\/documentation\/jivosdk\/jivo","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Jivo"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController/exportArchive(completion:)":{"url":"\/documentation\/jivosdk\/jvdebuggingcontroller\/exportarchive(completion:)","title":"exportArchive(completion:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exportArchive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"JVDebuggingExportStatus","preciseIdentifier":"s:7JivoSDK23JVDebuggingExportStatusO"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"text":"Performs archiving of local log entries","type":"text"},{"text":" ","type":"text"},{"text":"and returns a link to the created archive","type":"text"},{"text":" ","type":"text"},{"text":"via completion block with status","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/exportArchive(completion:)","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingExportStatus":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingExportStatus","type":"topic","title":"JVDebuggingExportStatus","url":"\/documentation\/jivosdk\/jvdebuggingexportstatus","abstract":[{"type":"text","text":"Determines how logs archiving operation was completed"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDebuggingExportStatus"}],"navigatorTitle":[{"kind":"identifier","text":"JVDebuggingExportStatus"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"JVDebuggingController","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JVDebuggingController"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"JVDebuggingController"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/navigatorTitle","op":"replace"},{"value":"debugging","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/title","op":"replace"},{"value":[{"text":"debugging","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/fragments","op":"replace"},{"value":"Jivo","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","op":"replace"}]}]}