{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"]]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/init"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"JivoSDK"}],"title":"init","externalID":"c:@M@JivoSDK@objc(cs)JVDebuggingController(im)init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/init"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"title":"JivoSDK","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic","url":"\/documentation\/jivosdk"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"title":"JVDebuggingController","type":"topic","url":"\/documentation\/jivosdk\/jvdebuggingcontroller","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JVDebuggingController"}],"navigatorTitle":[{"text":"JVDebuggingController","kind":"identifier"}],"abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"type":"text","text":"."},{"code":"Jivo\/debugging","type":"codeVoice"},{"text":" namespace for SDK debugging","type":"text"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"abstract":[],"title":"Jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Jivo","kind":"identifier"}],"navigatorTitle":[{"text":"Jivo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","kind":"symbol","url":"\/documentation\/jivosdk\/jivo","type":"topic","role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController/init":{"abstract":[],"url":"\/documentation\/jivosdk\/jvdebuggingcontroller\/init","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"JVDebuggingController","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments","value":[{"kind":"identifier","text":"JVDebuggingController"}]},{"value":[{"text":"JVDebuggingController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","value":[{"kind":"identifier","text":"Jivo"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"kind":"identifier","text":"Jivo"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}