{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/level","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Current level of logging verbosity"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"]]},"metadata":{"title":"level","role":"symbol","externalID":"c:@M@JivoSDK@objc(cs)JVDebuggingController(py)level","navigatorTitle":[{"text":"level","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"JivoSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"level","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingLevel","text":"JVDebuggingLevel"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(level) "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingLevel","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel","text":"JVDebuggingLevel","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/level"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/level"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","abstract":[{"text":"Namespace for SDK debugging","type":"text"}],"url":"\/documentation\/jivosdk\/jivo\/debugging","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugging"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController","text":"JVDebuggingController"}],"title":"debugging","navigatorTitle":[{"kind":"identifier","text":"debugging"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Jivo"}],"role":"symbol","title":"Jivo","type":"topic","url":"\/documentation\/jivosdk\/jivo","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","abstract":[{"type":"text","text":"Entry Point to communicate with SDK"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController/level":{"kind":"symbol","url":"\/documentation\/jivosdk\/jvdebuggingcontroller\/level","abstract":[{"type":"text","text":"Current level of logging verbosity"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/level","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"level"},{"text":": ","kind":"text"},{"text":"JVDebuggingLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingLevel"}],"title":"level","navigatorTitle":[{"text":"level","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"kind":"symbol","url":"\/documentation\/jivosdk\/jvdebuggingcontroller","type":"topic","abstract":[{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo","isActive":true,"type":"reference"},{"type":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","isActive":true,"type":"reference"},{"type":"text","text":" namespace for SDK debugging"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"JVDebuggingController","kind":"identifier"}],"title":"JVDebuggingController","navigatorTitle":[{"text":"JVDebuggingController","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"role":"collection","title":"JivoSDK","url":"\/documentation\/jivosdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingLevel":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDebuggingLevel"}],"abstract":[{"type":"text","text":"Level of logging verbosity,"},{"type":"text","text":" "},{"type":"text","text":"relates to "},{"code":"Jivo.debugging","type":"codeVoice"},{"type":"text","text":" namespace"}],"navigatorTitle":[{"text":"JVDebuggingLevel","kind":"identifier"}],"role":"symbol","url":"\/documentation\/jivosdk\/jvdebugginglevel","title":"JVDebuggingLevel","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"level","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"level","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"JVDebuggingLevel","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel","preciseIdentifier":"c:@M@JivoSDK@E@JVDebuggingLevel"},{"text":" ","kind":"text"},{"text":"level","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"debugging","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/fragments","op":"replace","value":[{"kind":"identifier","text":"debugging"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","value":"Jivo"},{"value":[{"kind":"identifier","text":"Jivo"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController~1level\/title","value":"level","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController~1level\/fragments","op":"replace","value":[{"text":"level","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title","value":"JVDebuggingController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments","value":[{"text":"JVDebuggingController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingLevel\/title","op":"replace","value":"JVDebuggingLevel"},{"value":[{"kind":"identifier","text":"JVDebuggingLevel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingLevel\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}