{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Method","externalID":"s:7JivoSDK21JVDebuggingControllerC14listenToRecord8original8callbackyAA0c8OriginalG8BehaviorO_ySSctF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listenToRecord","kind":"identifier"},{"text":"(","kind":"text"},{"text":"original","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7JivoSDK33JVDebuggingOriginalRecordBehaviorO","text":"JVDebuggingOriginalRecordBehavior","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"entry","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"JivoSDK"}],"title":"listenToRecord(original:callback:)","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"]]},"abstract":[{"type":"text","text":"Assign a listener for each time SDK is going to log event,"},{"type":"text","text":" "},{"type":"text","text":"here you are able to replace the standard behavior with your own implementation"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listenToRecord"},{"kind":"text","text":"("},{"kind":"externalParam","text":"original"},{"kind":"text","text":" "},{"kind":"internalParam","text":"behavior"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalRecordBehavior","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK33JVDebuggingOriginalRecordBehaviorO","text":"JVDebuggingOriginalRecordBehavior"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"entry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/listentorecord(original:callback:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/listenToRecord(original:callback:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController/listenToRecord(original:callback:)":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/listenToRecord(original:callback:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listenToRecord","kind":"identifier"},{"text":"(","kind":"text"},{"text":"original","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JVDebuggingOriginalRecordBehavior","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK33JVDebuggingOriginalRecordBehaviorO"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"entry","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/jivosdk\/jvdebuggingcontroller\/listentorecord(original:callback:)","title":"listenToRecord(original:callback:)","role":"symbol","abstract":[{"text":"Assign a listener for each time SDK is going to log event,","type":"text"},{"text":" ","type":"text"},{"text":"here you are able to replace the standard behavior with your own implementation","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"debugging","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugging","kind":"identifier"},{"text":": ","kind":"text"},{"text":"JVDebuggingController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","title":"debugging","type":"topic","abstract":[{"type":"text","text":"Namespace for SDK debugging"}],"url":"\/documentation\/jivosdk\/jivo\/debugging"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"abstract":[],"title":"Jivo","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"kind":"symbol","type":"topic","url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Jivo"}],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"type":"text","text":"."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging"},{"type":"text","text":" namespace for SDK debugging"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingController","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","url":"\/documentation\/jivosdk\/jvdebuggingcontroller","type":"topic","title":"JVDebuggingController","navigatorTitle":[{"text":"JVDebuggingController","kind":"identifier"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingOriginalRecordBehavior":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JVDebuggingOriginalRecordBehavior","kind":"identifier"}],"abstract":[{"text":"SDK behavior for recording entries","type":"text"}],"title":"JVDebuggingOriginalRecordBehavior","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingOriginalRecordBehavior","url":"\/documentation\/jivosdk\/jvdebuggingoriginalrecordbehavior","navigatorTitle":[{"text":"JVDebuggingOriginalRecordBehavior","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","url":"\/documentation\/jivosdk","title":"JivoSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/title","op":"replace","value":"debugging"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo~1debugging\/fragments","op":"replace","value":[{"text":"debugging","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title","op":"replace","value":"Jivo"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title","op":"replace","value":"JVDebuggingController"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments","op":"replace","value":[{"kind":"identifier","text":"JVDebuggingController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/navigatorTitle","op":"replace","value":[{"text":"JVDebuggingController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}