{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLevel"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"level"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel","text":"JVDebuggingLevel","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK16JVDebuggingLevelO"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/setLevel(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jivosdk\/jvdebuggingcontroller\/setlevel(_:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK","doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController"]]},"metadata":{"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"JivoSDK"}],"symbolKind":"method","title":"setLevel(_:)","externalID":"s:7JivoSDK21JVDebuggingControllerC8setLevelyyAA0cF0OF","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setLevel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JVDebuggingLevel","preciseIdentifier":"s:7JivoSDK16JVDebuggingLevelO","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Current level of logging verbosity","type":"text"}],"references":{"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo":{"role":"symbol","url":"\/documentation\/jivosdk\/jivo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Jivo","kind":"identifier"}],"title":"Jivo","navigatorTitle":[{"kind":"identifier","text":"Jivo"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController/setLevel(_:)":{"title":"setLevel(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController\/setLevel(_:)","url":"\/documentation\/jivosdk\/jvdebuggingcontroller\/setlevel(_:)","type":"topic","role":"symbol","abstract":[{"text":"Current level of logging verbosity","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setLevel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JVDebuggingLevel","kind":"typeIdentifier","preciseIdentifier":"s:7JivoSDK16JVDebuggingLevelO"},{"kind":"text","text":")"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingController":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingController","navigatorTitle":[{"text":"JVDebuggingController","kind":"identifier"}],"type":"topic","kind":"symbol","title":"JVDebuggingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JVDebuggingController","kind":"identifier"}],"url":"\/documentation\/jivosdk\/jvdebuggingcontroller","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo"},{"text":".","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging"},{"type":"text","text":" namespace for SDK debugging"}],"role":"symbol"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/JVDebuggingLevel":{"identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/JVDebuggingLevel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JVDebuggingLevel"}],"role":"symbol","type":"topic","abstract":[{"text":"Level of logging verbosity,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"relates to "},{"type":"codeVoice","code":"Jivo.debugging"},{"text":" namespace","type":"text"}],"title":"JVDebuggingLevel","url":"\/documentation\/jivosdk\/jvdebugginglevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JVDebuggingLevel"}]},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK/Jivo/debugging":{"url":"\/documentation\/jivosdk\/jivo\/debugging","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK\/Jivo\/debugging","title":"debugging","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugging"},{"kind":"text","text":": "},{"text":"JVDebuggingController","kind":"typeIdentifier","preciseIdentifier":"c:@M@JivoSDK@objc(cs)JVDebuggingController"}],"kind":"symbol","abstract":[{"type":"text","text":"Namespace for SDK debugging"}],"type":"topic"},"doc://org.cocoapods.JivoSDK/documentation/JivoSDK":{"kind":"symbol","url":"\/documentation\/jivosdk","title":"JivoSDK","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.JivoSDK\/documentation\/JivoSDK"}},"variantOverrides":[{"patch":[{"value":"Jivo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/fragments","op":"replace","value":[{"text":"Jivo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1Jivo\/navigatorTitle","value":[{"kind":"identifier","text":"Jivo"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/title","value":"JVDebuggingController"},{"op":"replace","value":[{"text":"JVDebuggingController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/fragments"},{"value":[{"text":"JVDebuggingController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.JivoSDK~1documentation~1JivoSDK~1JVDebuggingController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}